Repository nhibernate/nhibernate-core, pull requests merged in 2018-06, with the labels that each got.

#1724 NH-2716 - Modify test case as suggested
  src/NHibernate.Test/Async/LazyOneToOne/LazyOneToOneTest.cs
  src/NHibernate.Test/LazyOneToOne/LazyOneToOneTest.cs
Labels: c: Tests, t: Tests

#1725 Upgrade to AsyncGenerator 0.8.2.6
  .gitignore
  Tools/packages.config
  src/AsyncGenerator.yml
  src/NHibernate.Test/Async/CacheTest/CacheFixture.cs
  src/NHibernate.Test/Async/CfgTest/ConfigurationFixture.cs
  src/NHibernate.Test/Async/Criteria/DetachedCriteriaSerializable.cs
  src/NHibernate.Test/Async/EntityModeTest/Map/Basic/DynamicClassFixture.cs
  src/NHibernate.Test/Async/Legacy/SQLLoaderTest.cs
  src/NHibernate.Test/Async/Linq/ByMethod/GroupByTests.cs
  src/NHibernate.Test/Async/Linq/ByMethod/OrderByTests.cs
  src/NHibernate.Test/Async/Linq/EagerLoadTests.cs
  src/NHibernate.Test/Async/Linq/EnumTests.cs
  src/NHibernate.Test/Async/Linq/FunctionTests.cs
  src/NHibernate.Test/Async/Linq/LinqQuerySamples.cs
  src/NHibernate.Test/Async/Linq/QueryReuseTests.cs
  src/NHibernate.Test/Async/Linq/SelectionTests.cs
  src/NHibernate.Test/Async/Linq/WhereTests.cs
  src/NHibernate.Test/Async/MultipleCollectionFetchTest/AbstractMultipleCollectionFetchFixture.cs
  src/NHibernate.Test/Async/NHSpecificTest/Dates/DateFixture.cs
  src/NHibernate.Test/Async/NHSpecificTest/Dates/DateTime2Fixture.cs
  src/NHibernate.Test/Async/NHSpecificTest/Dates/TimeAsTimeSpanFixture.cs
  src/NHibernate.Test/Async/NHSpecificTest/Dates/TimeFixture.cs
  src/NHibernate.Test/Async/NHSpecificTest/GH1547/Fixture.cs
  src/NHibernate.Test/Async/NHSpecificTest/NH1443/Fixture.cs
  src/NHibernate.Test/Async/NHSpecificTest/NH1483/Fixture.cs
  src/NHibernate.Test/Async/NHSpecificTest/NH1521/Fixture.cs
  src/NHibernate.Test/Async/NHSpecificTest/NH1601/Fixture1.cs
  src/NHibernate.Test/Async/NHSpecificTest/NH1601/Fixture2.cs
  src/NHibernate.Test/Async/NHSpecificTest/NH1679/Fixture.cs
  src/NHibernate.Test/Async/NHSpecificTest/NH1688/Fixture.cs
  src/NHibernate.Test/Async/NHSpecificTest/NH1925/Fixture.cs
  src/NHibernate.Test/Async/NHSpecificTest/NH1927/Fixture.cs
  src/NHibernate.Test/Async/NHSpecificTest/NH2288/Fixture.cs
  src/NHibernate.Test/Async/NHSpecificTest/NH2319/Fixture.cs
  src/NHibernate.Test/Async/NHSpecificTest/NH2319/MapFixture.cs
  src/NHibernate.Test/Async/NHSpecificTest/NH3436/Fixture.cs
  src/NHibernate.Test/Async/NHSpecificTest/NH369/Fixture.cs
  src/NHibernate.Test/Async/NHSpecificTest/NH372/Fixture.cs
  src/NHibernate.Test/Async/NHSpecificTest/NH3850/FixtureBase.cs
  src/NHibernate.Test/Async/NHSpecificTest/NH3850/MainFixture.cs
  src/NHibernate.Test/Async/NHSpecificTest/NH3918/FixtureByCode.cs
  src/NHibernate.Test/Async/NHSpecificTest/NH642/Fixture.cs
  src/NHibernate.Test/Async/NHSpecificTest/NH873/Fixture.cs
  src/NHibernate.Test/Async/NHSpecificTest/NH952/NH952Fixture.cs
  src/NHibernate.Test/Async/NHSpecificTest/NH965/NH965Fixture.cs
  src/NHibernate.Test/Async/Tools/hbm2ddl/SchemaUpdate/MigrationFixture.cs
  src/NHibernate.Test/Async/Tools/hbm2ddl/SchemaValidator/SchemaValidateFixture.cs
  src/NHibernate.Test/Async/TransformTests/AliasToBeanResultTransformerFixture.cs
  src/NHibernate.Test/Async/TypesTest/AbstractDateTimeTypeFixture.cs
  src/NHibernate.Test/Async/TypesTest/DateTimeOffsetTypeFixture.cs
  src/NHibernate.Test/Async/TypesTest/DateTypeTest.cs
  src/NHibernate.Test/Async/TypesTest/StringTypeWithLengthFixture.cs
Labels: c: Core, p: Trivial, t: Task

#1726 Fix serialization exception when run on .NET Core 2.1
  .travis.yml
  src/NHibernate/Transform/AliasToBeanResultTransformer.cs
Labels: c: Core, p: Minor, t: Bug

#1714 Support IEquatable<T> in the LINQ provider
  src/NHibernate.Test/Async/Linq/FunctionTests.cs
  src/NHibernate.Test/Async/NHSpecificTest/GH1712/Fixture.cs
  src/NHibernate.Test/Linq/FunctionTests.cs
  src/NHibernate.Test/NHSpecificTest/GH1712/Entity.cs
  src/NHibernate.Test/NHSpecificTest/GH1712/Fixture.cs
  src/NHibernate.Test/NHSpecificTest/GH1712/Mappings.hbm.xml
  src/NHibernate/Linq/Functions/EqualsGenerator.cs
Labels: t: Fix

#1727 Fix a null-ref exception with no-proxy one-to-one
  src/NHibernate/AdoNet/AbstractBatcher.cs
Labels: c: Core, p: Trivial, t: Bug

#1731 Query cache always missed in session having altered the entities
  src/NHibernate.Test/Async/NHSpecificTest/GH1730/Fixture.cs
  src/NHibernate.Test/NHSpecificTest/GH1730/Entity.cs
  src/NHibernate.Test/NHSpecificTest/GH1730/Fixture.cs
  src/NHibernate.Test/NHSpecificTest/GH1730/Mappings.hbm.xml
  src/NHibernate/Async/Cache/StandardQueryCache.cs
  src/NHibernate/Cache/StandardQueryCache.cs
Labels: t: Fix

#1736 Remove excessive rowIdAlias parameter in Loader
  src/NHibernate/Async/Loader/Loader.cs
  src/NHibernate/Loader/Loader.cs
Labels: c: Core, p: Trivial, t: Improvement

#1734 Loader thread safety
  src/NHibernate/Async/Loader/Loader.cs
  src/NHibernate/Loader/Loader.cs
Labels: t: Fix

#305 NH-3670 - Dynamic component should allow generic dictionary
  doc/reference/modules/basic_mapping.xml
  src/NHibernate.Test/Async/NHSpecificTest/NH1039Generic/Fixture.cs
  src/NHibernate.Test/Async/NHSpecificTest/NH1796Generic/Fixture.cs
  src/NHibernate.Test/Async/NHSpecificTest/NH2664Generic/Fixture.cs
  src/NHibernate.Test/Async/NHSpecificTest/NH3571Generic/Fixture.cs
  src/NHibernate.Test/MappingByCode/ExplicitMappingTests/DynamicComponentMappingTests.cs
  src/NHibernate.Test/MappingByCode/ExplicitMappingTests/JoinGenericDynamicComponentTests.cs
  src/NHibernate.Test/MappingByCode/MappersTests/AbstractPropertyContainerMapperTest.cs
  src/NHibernate.Test/MappingByCode/MappersTests/DynamicComponentMapperTests/ComponentPropertyOnDynamicCompoTests.cs
  src/NHibernate.Test/MappingByCode/MappersTests/DynamicComponentMapperTests/DynComponentPropertyOnDynamicCompoTests.cs
  src/NHibernate.Test/NHSpecificTest/NH1039Generic/Fixture.cs
  src/NHibernate.Test/NHSpecificTest/NH1039Generic/Mappings.hbm.xml
  src/NHibernate.Test/NHSpecificTest/NH1039Generic/Model.cs
  src/NHibernate.Test/NHSpecificTest/NH1796Generic/Entity.cs
  src/NHibernate.Test/NHSpecificTest/NH1796Generic/Fixture.cs
  src/NHibernate.Test/NHSpecificTest/NH1796Generic/Mappings.hbm.xml
  src/NHibernate.Test/NHSpecificTest/NH2664Generic/Fixture.cs
  src/NHibernate.Test/NHSpecificTest/NH2664Generic/Mappings.hbm.xml
  src/NHibernate.Test/NHSpecificTest/NH2664Generic/Product.cs
  src/NHibernate.Test/NHSpecificTest/NH3571Generic/Fixture.cs
  src/NHibernate.Test/NHSpecificTest/NH3571Generic/Mappings.hbm.xml
  src/NHibernate.Test/NHSpecificTest/NH3571Generic/Product.cs
  src/NHibernate/Linq/Visitors/VisitorUtil.cs
  src/NHibernate/Mapping/ByCode/IPlainPropertyContainerMapper.cs
  src/NHibernate/Mapping/ByCode/Impl/CustomizersImpl/JoinCustomizer.cs
  src/NHibernate/Mapping/ByCode/Impl/CustomizersImpl/PropertyContainerCustomizer.cs
  src/NHibernate/Tuple/Component/ComponentMetamodel.cs
  src/NHibernate/Tuple/Component/DynamicComponentInstantiator.cs
  src/NHibernate/Tuple/Component/DynamicMapComponentTuplizer.cs
  src/NHibernate/Tuple/DynamicMapInstantiator.cs
Labels: t: Fix

#1728 Generate a correct proxy for interfaces
  src/NHibernate.Test/StaticProxyTest/StaticProxyFactoryFixture.cs
  src/NHibernate/Proxy/NHibernateProxyBuilder.cs
Labels: c: ByteCode providers, p: Minor, t: Bug

#1737 Remove a binary breaking change introduced in #305
  src/NHibernate/Mapping/ByCode/IPlainPropertyContainerMapper.cs
Labels: c: Mapping by Code, p: Major, r: Fixed, t: Bug

#1740 NH-3543 - Add support for multi query to DB2 Driver
  src/NHibernate/Driver/DB2Driver.cs
Labels: t: Fix

#1741 Fix DbType.Binary registration in DB2Dialect
  src/NHibernate/Dialect/DB2Dialect.cs
Labels: c: DataProviders / Dialects, p: Trivial, r: Fixed, t: Bug

#1742 Add new DB2CoreDriver to use with IBM.Data.DB2.Core provider
  src/NHibernate/Driver/DB2CoreDriver.cs
  src/NHibernate/Driver/DB2Driver.cs
  src/NHibernate/Driver/DB2DriverBase.cs
Labels: c: DataProviders / Dialects, p: Minor, t: New Feature

#1743 Merge 5.1.3 into master
  appveyor.yml
  build-common/NHibernate.props
  build-common/common.xml
  releasenotes.txt
  src/NHibernate.Test/Async/NHSpecificTest/GH1730/Fixture.cs
  src/NHibernate.Test/NHSpecificTest/GH1730/Entity.cs
  src/NHibernate.Test/NHSpecificTest/GH1730/Fixture.cs
  src/NHibernate.Test/NHSpecificTest/GH1730/Mappings.hbm.xml
  src/NHibernate.Test/StaticProxyTest/StaticProxyFactoryFixture.cs
  src/NHibernate/Async/Cache/StandardQueryCache.cs
  src/NHibernate/Async/Loader/Loader.cs
  src/NHibernate/Cache/StandardQueryCache.cs
  src/NHibernate/Dialect/DB2Dialect.cs
  src/NHibernate/Loader/Loader.cs
  src/NHibernate/Proxy/NHibernateProxyBuilder.cs
  src/NHibernate/Proxy/NHibernateProxyObjectReference.cs
Labels: c: Core, p: Minor, t: Task

#1745 Remove obsoleted hibernate configuration prefix
  doc/reference/modules/toolset_guide.xml
  src/NHibernate/CacheMode.cs
Labels: c: Documentation, p: Trivial, t: Bug

#1392 Add support for query space synchronization
  src/AsyncGenerator.yml
  src/NHibernate.Test/Async/BulkManipulation/NativeSQLBulkOperationsWithCache.cs
  src/NHibernate.Test/Async/SqlTest/Query/NativeSQLQueriesFixture.cs
  src/NHibernate.Test/BulkManipulation/BulkOperationCleanupActionFixture.cs
  src/NHibernate.Test/BulkManipulation/NativeSQLBulkOperationsWithCache.cs
  src/NHibernate.Test/MappingByCode/For.cs
  src/NHibernate.Test/NHibernate.Test.csproj
  src/NHibernate.Test/SqlTest/Query/NativeSQLQueriesFixture.cs
  src/NHibernate.sln
  src/NHibernate/Action/BulkOperationCleanupAction.cs
  src/NHibernate/Async/Action/BulkOperationCleanupAction.cs
  src/NHibernate/Async/Engine/Query/NativeSQLQueryPlan.cs
  src/NHibernate/Async/Hql/Ast/ANTLR/Exec/AbstractStatementExecutor.cs
  src/NHibernate/Async/Hql/Ast/ANTLR/Exec/BasicExecutor.cs
  src/NHibernate/Async/Hql/Ast/ANTLR/Exec/MultiTableDeleteExecutor.cs
  src/NHibernate/Async/Hql/Ast/ANTLR/Exec/MultiTableUpdateExecutor.cs
  src/NHibernate/Async/ISessionFactory.cs
  src/NHibernate/Async/Impl/SessionFactoryImpl.cs
  src/NHibernate/Async/Impl/SqlQueryImpl.cs
  src/NHibernate/Engine/Query/NativeSQLQueryPlan.cs
  src/NHibernate/Hql/Ast/ANTLR/Exec/AbstractStatementExecutor.cs
  src/NHibernate/ISQLQuery.cs
  src/NHibernate/ISessionFactory.cs
  src/NHibernate/ISynchronizableQuery.cs
  src/NHibernate/Impl/AbstractQueryImpl.cs
  src/NHibernate/Impl/SessionFactoryImpl.cs
  src/NHibernate/Impl/SqlQueryImpl.cs
Labels: t: Fix

#1744 Reconnect lazy property proxy on deserialization
  src/NHibernate.Test/Async/StaticProxyTest/StaticProxyFixture.cs
  src/NHibernate.Test/StaticProxyTest/Mappings.hbm.xml
  src/NHibernate.Test/StaticProxyTest/Model.cs
  src/NHibernate.Test/StaticProxyTest/StaticProxyFixture.cs
  src/NHibernate/Async/Engine/StatefulPersistenceContext.cs
  src/NHibernate/Engine/StatefulPersistenceContext.cs
Labels: c: Core, p: Minor, t: Bug

#1748 Fix a bad setting naming about transaction scopes
  doc/reference/modules/transactions.xml
  releasenotes.txt
Labels: c: Documentation, p: Minor, t: Bug

#1747 NH-3823 - Fix extra lazy PersistentGenericSet losing pending items on initialization
  src/NHibernate.Test/Async/Extralazy/ExtraLazyFixture.cs
  src/NHibernate.Test/Async/NHSpecificTest/NH1316/Fixture.cs
  src/NHibernate.Test/Extralazy/ExtraLazyFixture.cs
  src/NHibernate/Collection/Generic/PersistentGenericSet.cs
Labels: t: Fix

#1751 Avoid completing twice the same transaction
  src/NHibernate/Transaction/AdoNetWithSystemTransactionFactory.cs
Labels: c: Core, p: Minor, t: Bug

#415 Add check to ensure that IUserCollectionType.Instantiate returns uninitialized collection
  src/NHibernate.Test/Async/NHSpecificTest/NH3772/Fixture.cs
  src/NHibernate.Test/NHSpecificTest/NH3772/CustomGenericCollection.cs
  src/NHibernate.Test/NHSpecificTest/NH3772/Entity.cs
  src/NHibernate.Test/NHSpecificTest/NH3772/Fixture.cs
  src/NHibernate/Type/CustomCollectionType.cs
Labels: c: Core, p: Trivial, t: Improvement

#1753 Fix possible InvalidCastException in ActionQueue
  src/NHibernate/Action/AbstractEntityInsertAction.cs
  src/NHibernate/Action/EntityIdentityInsertAction.cs
  src/NHibernate/Action/EntityInsertAction.cs
  src/NHibernate/Async/Action/EntityIdentityInsertAction.cs
  src/NHibernate/Async/Action/EntityInsertAction.cs
  src/NHibernate/Engine/ActionQueue.cs
Labels: c: Core, p: Trivial, r: Fixed, t: Bug

#1762 Remove duplicated and obsolete interceptor documentation
  doc/reference/modules/manipulating_data.xml
Labels: c: Documentation, p: Trivial, t: Improvement

#1761 Update mapping documentation
  doc/reference/master.xml
  doc/reference/modules/associations.xml
  doc/reference/modules/basic_mapping.xml
  doc/reference/modules/collection_mapping.xml
  doc/reference/modules/component_mapping.xml
  doc/reference/modules/example_mappings.xml
  doc/reference/modules/example_parentchild.xml
  doc/reference/modules/filters.xml
  doc/reference/modules/inheritance_mapping.xml
  doc/reference/modules/manipulating_data.xml
  doc/reference/modules/performance.xml
  doc/reference/modules/persistent_classes.xml
  src/NHibernate/Async/Id/CounterGenerator.cs
  src/NHibernate/Async/Id/IdentifierGeneratorFactory.cs
  src/NHibernate/Async/Id/SequenceIdentityGenerator.cs
  src/NHibernate/Async/Id/TableGenerator.cs
  src/NHibernate/Id/CounterGenerator.cs
  src/NHibernate/Id/IdentifierGeneratorFactory.cs
  src/NHibernate/Id/IncrementGenerator.cs
  src/NHibernate/Id/SequenceIdentityGenerator.cs
  src/NHibernate/Id/TableGenerator.cs
  src/NHibernate/Id/TableHiLoGenerator.cs
  src/NHibernate/Id/TriggerIdentityGenerator.cs
Labels: c: Documentation, p: Major, t: Improvement

#1770 Make obsolete abstract virtual
  src/NHibernate/Persister/Collection/AbstractCollectionPersister.cs
  src/NHibernate/Persister/Collection/BasicCollectionPersister.cs
  src/NHibernate/Persister/Collection/OneToManyPersister.cs
Labels: c: Core, p: Trivial, t: Improvement

#1773 Obsolete unused version related methods of SByteType
  src/NHibernate/Type/SByteType.cs
Labels: c: Core, p: Trivial, t: Task

#1764 Fix configuration schema forbidding custom bytecode provider
  src/NHibernate.Test/CfgTest/ConfigurationSchemaFixture.cs
  src/NHibernate/nhibernate-configuration.xsd
Labels: c: Core, p: Minor, t: Bug

#1767 Allow generic dictionaries for dynamic entities
  doc/reference/modules/persistent_classes.xml
  src/NHibernate.Test/Async/EntityModeTest/Map/Basic/DynamicClassFixture.cs
  src/NHibernate.Test/EntityModeTest/Map/Basic/DynamicClassFixture.cs
  src/NHibernate/Proxy/Map/MapLazyInitializer.cs
  src/NHibernate/Proxy/Map/MapProxy.cs
  src/NHibernate/Tuple/DynamicEntityInstantiator.cs
  src/NHibernate/Tuple/DynamicMapInstantiator.cs
  src/NHibernate/Tuple/Entity/DynamicMapEntityTuplizer.cs
Labels: c: Core, p: Minor, possible breaking change, t: Improvement

#1760 Support formula on one-to-many map-key
  src/NHibernate.Test/Async/NHSpecificTest/GH1760/MapKeyFormulaFixture.cs
  src/NHibernate.Test/NHSpecificTest/GH1760/Domain.cs
  src/NHibernate.Test/NHSpecificTest/GH1760/MapKeyFormulaFixture.cs
  src/NHibernate.Test/NHSpecificTest/GH1760/Mappings.hbm.xml
  src/NHibernate/Persister/Collection/OneToManyPersister.cs
Labels: c: Core, p: Minor, r: Fixed, t: Bug

#1633 Added support for batching 2nd level cache operations when loading entities and collections
  src/AsyncGenerator.yml
  src/NHibernate.Test/Async/CacheTest/BatchableCacheFixture.cs
  src/NHibernate.Test/Async/CacheTest/BatchableCacheSubclassFixture.cs
  src/NHibernate.Test/Async/CacheTest/Caches/BatchableCache.cs
  src/NHibernate.Test/CacheTest/BatchableCacheFixture.cs
  src/NHibernate.Test/CacheTest/BatchableCacheSubclassFixture.cs
  src/NHibernate.Test/CacheTest/Caches/BatchableCache.cs
  src/NHibernate.Test/CacheTest/Caches/BatchableCacheProvider.cs
  src/NHibernate.Test/CacheTest/ReadOnly.cs
  src/NHibernate.Test/CacheTest/ReadOnly.hbm.xml
  src/NHibernate.Test/CacheTest/ReadWrite.cs
  src/NHibernate.Test/CacheTest/ReadWrite.hbm.xml
  src/NHibernate/Async/Cache/AbstractCacheBatch.cs
  src/NHibernate/Async/Cache/CacheBatcher.cs
  src/NHibernate/Async/Cache/CachePutBatch.cs
  src/NHibernate/Async/Cache/IBatchableCache.cs
  src/NHibernate/Async/Cache/IBatchableCacheConcurrencyStrategy.cs
  src/NHibernate/Async/Cache/IBatchableReadOnlyCache.cs
  src/NHibernate/Async/Cache/ICacheConcurrencyStrategy.cs
  src/NHibernate/Async/Cache/NonstrictReadWriteCache.cs
  src/NHibernate/Async/Cache/ReadOnlyCache.cs
  src/NHibernate/Async/Cache/ReadWriteCache.cs
  src/NHibernate/Async/Cache/UpdateTimestampsCache.cs
  src/NHibernate/Async/Engine/BatchFetchQueue.cs
  src/NHibernate/Async/Engine/Loading/CollectionLoadContext.cs
  src/NHibernate/Async/Engine/TwoPhaseLoad.cs
  src/NHibernate/Async/Event/Default/DefaultInitializeCollectionEventListener.cs
  src/NHibernate/Async/Event/Default/DefaultLoadEventListener.cs
  src/NHibernate/Async/Loader/Loader.cs
  src/NHibernate/Cache/AbstractCacheBatch.cs
  src/NHibernate/Cache/CacheBatcher.cs
  src/NHibernate/Cache/CachePutBatch.cs
  src/NHibernate/Cache/CachePutData.cs
  src/NHibernate/Cache/IBatchableCache.cs
  src/NHibernate/Cache/IBatchableCacheConcurrencyStrategy.cs
  src/NHibernate/Cache/IBatchableReadOnlyCache.cs
  src/NHibernate/Cache/ICacheConcurrencyStrategy.cs
  src/NHibernate/Cache/NonstrictReadWriteCache.cs
  src/NHibernate/Cache/ReadOnlyCache.cs
  src/NHibernate/Cache/ReadWriteCache.cs
  src/NHibernate/Cache/UpdateTimestampsCache.cs
  src/NHibernate/Engine/BatchFetchQueue.cs
  src/NHibernate/Engine/EntityKey.cs
  src/NHibernate/Engine/Loading/CollectionLoadContext.cs
  src/NHibernate/Engine/TwoPhaseLoad.cs
  src/NHibernate/Event/Default/DefaultInitializeCollectionEventListener.cs
  src/NHibernate/Event/Default/DefaultLoadEventListener.cs
  src/NHibernate/Loader/Loader.cs
  src/NHibernate/Persister/Entity/AbstractEntityPersister.cs
  src/NHibernate/Persister/Entity/IEntityPersister.cs
Labels: c: Core, p: Major, t: New Feature

#1775 Start/Stop required db-service for TeamCity
  teamcity.build
Labels: c: Tests, p: Minor, t: Improvement

#1765 Provide cacheable representations for all NHibernate built-in types
  src/NHibernate.Test/CacheTest/TypeFixture.cs
  src/NHibernate/Async/Type/CultureInfoType.cs
  src/NHibernate/Async/Type/TypeType.cs
  src/NHibernate/Async/Type/UriType.cs
  src/NHibernate/Async/Type/XDocType.cs
  src/NHibernate/Async/Type/XmlDocType.cs
  src/NHibernate/Type/CultureInfoType.cs
  src/NHibernate/Type/TypeType.cs
  src/NHibernate/Type/UriType.cs
  src/NHibernate/Type/XDocType.cs
  src/NHibernate/Type/XmlDocType.cs
  src/NHibernate/UserTypes/IUserType.cs
Labels: c: Core, p: Minor, possible breaking change, t: Improvement
