Repository nhibernate/nhibernate-core, pull requests merged in 2018-11, with the labels that each got.

#1896 Support ICompositeUserType for ByCode Element, KeyProperty, MapKey
  src/NHibernate.Test/MappingByCode/MappersTests/ElementMapperTest.cs
  src/NHibernate.Test/MappingByCode/MappersTests/KeyPropertyMapperTest.cs
  src/NHibernate.Test/MappingByCode/MappersTests/MapKeyMapperTest.cs
  src/NHibernate/Mapping/ByCode/Impl/ElementMapper.cs
  src/NHibernate/Mapping/ByCode/Impl/KeyPropertyMapper.cs
  src/NHibernate/Mapping/ByCode/Impl/MapKeyMapper.cs
Labels: t: Fix

#1875 Improve exception message in case of duplicated column
  src/NHibernate.Test/NHSpecificTest/GH1875/Fixture.cs
  src/NHibernate/Async/Persister/Entity/AbstractEntityPersister.cs
  src/NHibernate/Persister/Entity/AbstractEntityPersister.cs
  src/NHibernate/SqlCommand/SqlInsertBuilder.cs
  src/NHibernate/SqlCommand/SqlUpdateBuilder.cs
Labels: c: Core, p: Minor, t: Improvement

#1414 Test ISession.IsDirty() should not trigger cascade saving
  src/NHibernate.Test/Async/NHSpecificTest/GH1413/FixtureByCode.cs
  src/NHibernate.Test/NHSpecificTest/GH1413/Entities.cs
  src/NHibernate.Test/NHSpecificTest/GH1413/FixtureByCode.cs
Labels: t: Tests

#1808 Support mixed formulas and columns
  doc/reference/modules/example_mappings.xml
  src/NHibernate.Test/Async/NHSpecificTest/GH1759/ColumnsAndFormulasFixture.cs
  src/NHibernate.Test/NHSpecificTest/GH1759/ColumnsAndFormulasFixture.cs
  src/NHibernate.Test/NHSpecificTest/GH1759/DateSpanType.cs
  src/NHibernate.Test/NHSpecificTest/GH1759/Domain.cs
  src/NHibernate.Test/NHSpecificTest/GH1759/Mappings.hbm.xml
  src/NHibernate.Test/NHSpecificTest/NH1007/Mappings.hbm.xml
  src/NHibernate/Cfg/MappingSchema/HbmElement.cs
  src/NHibernate/Cfg/MappingSchema/HbmManyToMany.cs
  src/NHibernate/Cfg/MappingSchema/HbmManyToOne.cs
  src/NHibernate/Cfg/MappingSchema/HbmMapKey.cs
  src/NHibernate/Cfg/MappingSchema/HbmMapKeyManyToMany.cs
  src/NHibernate/Cfg/MappingSchema/HbmProperty.cs
  src/NHibernate/Cfg/XmlHbmBinding/ValuePropertyBinder.cs
  src/NHibernate/Util/ArrayHelper.cs
Labels: c: Core, p: Minor, possible breaking change, t: Improvement

#1584 Test Parent property is not accessible in queries
  src/NHibernate.Test/Async/NHSpecificTest/GH1583/Fixture.cs
  src/NHibernate.Test/NHSpecificTest/GH1583/Fixture.cs
Labels: t: Tests

#1859 Fix filter & where fragment appended after lock hint
  src/NHibernate.Test/CollectionTest/Domain.cs
  src/NHibernate.Test/CollectionTest/Domain.hbm.xml
  src/NHibernate.Test/CollectionTest/WhereWithReadLockFixture.cs
  src/NHibernate/Persister/Collection/AbstractCollectionPersister.cs
  src/NHibernate/SqlCommand/SqlSimpleSelectBuilder.cs
Labels: c: Core, p: Minor, t: Bug

#1855 Fix NotNullUnique not taken into account for single column
  src/NHibernate.Test/Async/DialectTest/SchemaTests/NullInUnique.cs
  src/NHibernate.Test/DialectTest/SchemaTests/DialectNotSupportingNullInUnique.cs
  src/NHibernate.Test/DialectTest/SchemaTests/Entity.cs
  src/NHibernate.Test/DialectTest/SchemaTests/NullInUnique.cs
  src/NHibernate.Test/NHSpecificTest/NH3749/TestDialect.cs
  src/NHibernate/Dialect/Dialect.cs
  src/NHibernate/Mapping/Table.cs
  src/NHibernate/Mapping/UniqueKey.cs
Labels: c: Toolset, p: Trivial, t: Bug

#1440 Test case for ComposedId Entity with Lazy Property is not proxified
  src/NHibernate.Test/Async/NHSpecificTest/GH1439/Fixture.cs
  src/NHibernate.Test/NHSpecificTest/GH1439/CompositeEntity.cs
  src/NHibernate.Test/NHSpecificTest/GH1439/EntityWithComponentId.cs
  src/NHibernate.Test/NHSpecificTest/GH1439/Fixture.cs
Labels: t: Tests

#1531 Test for Merging a bidirectonal list creates unecessary UPDATE statement
  src/NHibernate.Test/Async/NHSpecificTest/GH1530/Fixture.cs
  src/NHibernate.Test/NHSpecificTest/GH1530/Fixture.cs
  src/NHibernate.Test/NHSpecificTest/GH1530/Mappings.hbm.xml
  src/NHibernate.Test/NHSpecificTest/GH1530/Model.cs
  src/NHibernate.Test/NHSpecificTest/GH1530/NonInverseMappings.hbm.xml
Labels: t: Tests

#1901 Add ability to use dynamic entities as C# dynamic
  doc/reference/modules/persistent_classes.xml
  src/NHibernate.Test/Async/EntityModeTest/Map/Basic/DynamicClassFixture.cs
  src/NHibernate.Test/EntityModeTest/Map/Basic/DynamicClassFixture.cs
  src/NHibernate/Proxy/Map/MapProxy.cs
  src/NHibernate/Tuple/DynamicEntityInstantiator.cs
Labels: c: Core, p: Minor, t: Improvement

#1812 Fix the <any/> handling without meta-values
  doc/reference/modules/basic_mapping.xml
  src/NHibernate.Test/Async/CacheTest/SerializationFixture.cs
  src/NHibernate.Test/Async/Legacy/FooBarTest.cs
  src/NHibernate.Test/CacheTest/SerializationFixture.cs
  src/NHibernate.Test/Legacy/FooBarTest.cs
  src/NHibernate.Test/NHSpecificTest/GH1774/Implicit/ImplicitMetaTypeFixture.cs
  src/NHibernate/Async/Type/ClassMetaType.cs
  src/NHibernate/Async/Type/MetaType.cs
  src/NHibernate/Hql/Ast/ANTLR/Tree/BinaryLogicOperatorNode.cs
  src/NHibernate/Mapping/Any.cs
  src/NHibernate/NHibernateUtil.cs
  src/NHibernate/Type/AnyType.cs
  src/NHibernate/Type/ClassMetaType.cs
  src/NHibernate/Type/IMetaType.cs
  src/NHibernate/Type/MetaType.cs
Labels: c: Core, p: Minor, t: Bug

#1856 Fix Guid.ToString()
  src/NHibernate.Test/Async/NHSpecificTest/NH3426/Fixture.cs
  src/NHibernate.Test/NHSpecificTest/NH3426/Entity.cs
  src/NHibernate.Test/NHSpecificTest/NH3426/Fixture.cs
  src/NHibernate.Test/NHibernate.Test.csproj
  src/NHibernate/Dialect/Dialect.cs
  src/NHibernate/Dialect/FirebirdDialect.cs
  src/NHibernate/Dialect/MySQL55Dialect.cs
  src/NHibernate/Dialect/MySQL5Dialect.cs
  src/NHibernate/Dialect/Oracle8iDialect.cs
  src/NHibernate/Dialect/PostgreSQLDialect.cs
  src/NHibernate/Dialect/SQLiteDialect.cs
  src/NHibernate/Dialect/SybaseASE15Dialect.cs
  src/NHibernate/Linq/Functions/StringGenerator.cs
Labels: t: Fix

#1900 Do not generate FK on non-generated unique constraint
  src/NHibernate.Test/DialectTest/SchemaTests/DialectNotSupportingNullInUnique.cs
  src/NHibernate.Test/DialectTest/SchemaTests/Entity.cs
  src/NHibernate/Cfg/Configuration.cs
  src/NHibernate/Mapping/ForeignKey.cs
  src/NHibernate/Mapping/Table.cs
Labels: c: Toolset, p: Minor, t: Bug

#1707 Fix NH-3150: select id generator improvements
  src/NHibernate.Test/Async/NHSpecificTest/NH3150/SelectGeneratorFixture.cs
  src/NHibernate.Test/NHSpecificTest/NH3150/Class.cs
  src/NHibernate.Test/NHSpecificTest/NH3150/Mappings.hbm.xml
  src/NHibernate.Test/NHSpecificTest/NH3150/SelectGeneratorFixture.cs
  src/NHibernate/Async/Id/IPostInsertIdentityPersister.cs
  src/NHibernate/Async/Id/Insert/AbstractSelectingDelegate.cs
  src/NHibernate/Async/Id/SelectGenerator.cs
  src/NHibernate/Async/Persister/Collection/AbstractCollectionPersister.cs
  src/NHibernate/Async/Persister/Entity/AbstractEntityPersister.cs
  src/NHibernate/Id/IPostInsertIdentityPersister.cs
  src/NHibernate/Id/Insert/AbstractSelectingDelegate.cs
  src/NHibernate/Id/SelectGenerator.cs
  src/NHibernate/Persister/Collection/AbstractCollectionPersister.cs
  src/NHibernate/Persister/Entity/AbstractEntityPersister.cs
Labels: t: Fix

#1906 Fix a test on an feature obsoleted by #1707
  src/NHibernate.Test/CollectionTest/WhereWithReadLockFixture.cs
Labels: t: Fix

#1891 Recompute hashcodes on deserialization
  src/NHibernate.Test/CacheTest/FilterKeyFixture.cs
  src/NHibernate.Test/CacheTest/QueryKeyFixture.cs
  src/NHibernate.Test/DebugSessionFactory.cs
  src/NHibernate/Cache/CacheKey.cs
  src/NHibernate/Cache/FilterKey.cs
  src/NHibernate/Cache/QueryKey.cs
  src/NHibernate/Engine/AssociationKey.cs
  src/NHibernate/Engine/CollectionKey.cs
  src/NHibernate/Engine/EntityKey.cs
  src/NHibernate/Engine/EntityUniqueKey.cs
  src/NHibernate/Engine/Query/QueryPlanCache.cs
  src/NHibernate/Impl/Printer.cs
  src/NHibernate/LockMode.cs
  src/NHibernate/Util/WeakHashtable.cs
Labels: possible breaking change, t: Fix

#1837 Have more robust log4net loading
  src/NHibernate/Logging.cs
  src/NHibernate/Logging.log4net.cs
Labels: t: Fix

#460 Fix Criteria caching filtered collections
  src/NHibernate.Test/Async/NHSpecificTest/NH3848/CriteriaTestFixture.cs
  src/NHibernate.Test/Async/NHSpecificTest/NH3848/Fixture.cs
  src/NHibernate.Test/Async/NHSpecificTest/NH3848/QueryOverTestFixture.cs
  src/NHibernate.Test/NHSpecificTest/NH3848/Company.cs
  src/NHibernate.Test/NHSpecificTest/NH3848/CriteriaTestFixture.cs
  src/NHibernate.Test/NHSpecificTest/NH3848/Customer.cs
  src/NHibernate.Test/NHSpecificTest/NH3848/Fixture.cs
  src/NHibernate.Test/NHSpecificTest/NH3848/Order.cs
  src/NHibernate.Test/NHSpecificTest/NH3848/QueryOverTestFixture.cs
  src/NHibernate/Async/Engine/Loading/CollectionLoadContext.cs
  src/NHibernate/Async/Loader/Criteria/CriteriaLoader.cs
  src/NHibernate/Async/Loader/Loader.cs
  src/NHibernate/Engine/Loading/CollectionLoadContext.cs
  src/NHibernate/Impl/CriteriaImpl.cs
  src/NHibernate/Loader/Criteria/CriteriaLoader.cs
  src/NHibernate/Loader/Criteria/CriteriaQueryTranslator.cs
  src/NHibernate/Loader/Loader.cs
Labels: c: Core, p: Major, t: Bug

#609 Fix mapping of intermediate inherited classes
  src/NHibernate.Test/NHSpecificTest/NH3992/Entities.cs
  src/NHibernate.Test/NHSpecificTest/NH3992/FixtureByCode.cs
  src/NHibernate.Test/NHSpecificTest/NH3992/Mappings.cs
  src/NHibernate/Mapping/ByCode/ModelMapper.cs
Labels: t: Fix

#287 NH-2016 - Fix joining to association twice using criteria
  src/NHibernate.Test/Async/NHSpecificTest/NH3472/Fixture.cs
  src/NHibernate.Test/NHSpecificTest/NH3472/Domain.cs
  src/NHibernate.Test/NHSpecificTest/NH3472/Fixture.cs
  src/NHibernate.Test/NHSpecificTest/NH3472/Mappings.hbm.xml
  src/NHibernate/Loader/Criteria/CriteriaJoinWalker.cs
  src/NHibernate/Loader/Criteria/CriteriaQueryTranslator.cs
  src/NHibernate/Loader/JoinWalker.cs
Labels: t: Fix

#268 Fix ICriteria/QueryOver create incorrect left join condition when table-per-hierarchy is used with filters
  src/NHibernate.Test/Async/NHSpecificTest/NH3506/Fixture.cs
  src/NHibernate.Test/NHSpecificTest/NH3506/BaseClass.cs
  src/NHibernate.Test/NHSpecificTest/NH3506/Department.cs
  src/NHibernate.Test/NHSpecificTest/NH3506/Employee.cs
  src/NHibernate.Test/NHSpecificTest/NH3506/Fixture.cs
  src/NHibernate.Test/NHSpecificTest/NH3506/Mappings.hbm.xml
  src/NHibernate/Loader/JoinWalker.cs
Labels: t: Fix

#1910 Add an overridable ADO BeginTransaction method
  src/NHibernate/Async/Transaction/AdoTransaction.cs
  src/NHibernate/Driver/DriverBase.cs
  src/NHibernate/Driver/DriverExtensions.cs
  src/NHibernate/Transaction/AdoTransaction.cs
Labels: t: Fix

#1905 Improve support of Npgsql 4
  src/NHibernate.Test/NHibernate.Test.csproj
  src/NHibernate.Test/TestDialects/PostgreSQL83TestDialect.cs
  src/NHibernate/Dialect/PostgreSQLDialect.cs
  src/NHibernate/Type/DecimalType.cs
  src/NHibernate/Type/DoubleType.cs
  src/NHibernate/Type/Int16Type.cs
  src/NHibernate/Type/Int32Type.cs
  src/NHibernate/Type/Int64Type.cs
  src/NHibernate/Type/SByteType.cs
  src/NHibernate/Type/UInt16Type.cs
  src/NHibernate/Type/UInt32Type.cs
  src/NHibernate/Type/UInt64Type.cs
Labels: c: DataProviders / Dialects, p: Minor, t: Improvement

#1916 Fix regressions introduced by Conditional and Coalesce expansion (#1880)
  src/NHibernate.Test/Async/NHSpecificTest/GH1879/ExpansionRegressionTests.cs
  src/NHibernate.Test/Async/NHSpecificTest/GH1879/FixtureByCode.cs
  src/NHibernate.Test/NHSpecificTest/GH1879/Entity.cs
  src/NHibernate.Test/NHSpecificTest/GH1879/ExpansionRegressionTests.cs
  src/NHibernate.Test/NHSpecificTest/GH1879/FixtureByCode.cs
  src/NHibernate/Linq/ReWriters/ConditionalQueryReferenceExpander.cs
Labels: t: Fix
