Repository nhibernate/nhibernate-core, pull requests merged in 2018-10, with the labels that each got.

#1823 Run tests for SQLite on .NET Core
  .travis.yml
  appveyor.yml
  src/NHibernate.Test/NHibernate.Test.csproj
  src/NHibernate.TestDatabaseSetup/TestDatabaseSetup.cs
  src/NHibernate/Dialect/SQLiteDialect.cs
Labels: c: Tests, p: Trivial, t: Task

#1864 Add an async enabled transaction synchronization
  src/NHibernate.Test/Async/NHSpecificTest/NH1082/Fixture.cs
  src/NHibernate.Test/Async/NHSpecificTest/NH1082/TransactionSynchronizationThatThrowsExceptionAtBeforeTransactionCompletion.cs
  src/NHibernate.Test/Async/TransactionTest/TransactionNotificationFixture.cs
  src/NHibernate.Test/NHSpecificTest/NH1082/Fixture.cs
  src/NHibernate.Test/NHSpecificTest/NH1082/SynchronizationThatThrowsExceptionAtBeforeTransactionCompletion.cs
  src/NHibernate.Test/NHSpecificTest/NH1082/TransactionSynchronizationThatThrowsExceptionAtBeforeTransactionCompletion.cs
  src/NHibernate.Test/TransactionTest/TransactionNotificationFixture.cs
  src/NHibernate/Async/Engine/Transaction/IsolatedWorkAfterTransaction.cs
  src/NHibernate/Async/Hql/Ast/ANTLR/Exec/AbstractStatementExecutor.cs
  src/NHibernate/Async/Transaction/AdoTransaction.cs
  src/NHibernate/Engine/Transaction/IsolatedWorkAfterTransaction.cs
  src/NHibernate/Hql/Ast/ANTLR/Exec/AbstractStatementExecutor.cs
  src/NHibernate/ITransaction.cs
  src/NHibernate/Transaction/AdoTransaction.cs
  src/NHibernate/Transaction/AfterTransactionCompletes.cs
  src/NHibernate/Transaction/ISynchronization.cs
  src/NHibernate/Transaction/ITransactionCompletionSynchronization.cs
Labels: t: Fix

#1867 Fix registration of current_date for some dialects
  src/NHibernate.Test/Async/Hql/HQLFunctions.cs
  src/NHibernate.Test/Hql/HQLFunctions.cs
  src/NHibernate/Dialect/Oracle8iDialect.cs
  src/NHibernate/Dialect/SybaseASE15Dialect.cs
  src/NHibernate/Dialect/SybaseSQLAnywhere10Dialect.cs
Labels: c: DataProviders / Dialects, p: Minor, t: Bug

#1869 Replace an O(n) lookup in LINQ query parsing by an O(1) one
  src/NHibernate.Test/Async/Hql/HQLFunctions.cs
  src/NHibernate/Linq/Functions/DefaultLinqToHqlGeneratorsRegistry.cs
Labels: c: Linq Provider, p: Minor, t: Improvement

#1870 Update build-menu options in documentation
  CONTRIBUTING.md
Labels: c: Documentation, p: Trivial, t: Bug

#1871 Fix property-ref on a component's property
  src/NHibernate.Test/Async/NHSpecificTest/GH1824/Fixture.cs
  src/NHibernate.Test/NHSpecificTest/GH1824/Bar.cs
  src/NHibernate.Test/NHSpecificTest/GH1824/Fixture.cs
  src/NHibernate.Test/NHSpecificTest/GH1824/Foo.cs
  src/NHibernate.Test/NHSpecificTest/GH1824/Mappings.hbm.xml
  src/NHibernate/Cfg/Configuration.cs
Labels: t: Fix

#1878 Fix extra-lazy collection forgetting changes
  src/NHibernate.Test/Async/Extralazy/ExtraLazyFixture.cs
  src/NHibernate.Test/Extralazy/ExtraLazyFixture.cs
  src/NHibernate/Async/Collection/IPersistentCollection.cs
  src/NHibernate/Async/Engine/Loading/CollectionLoadContext.cs
  src/NHibernate/Async/Event/Default/DefaultInitializeCollectionEventListener.cs
  src/NHibernate/Collection/AbstractPersistentCollection.cs
  src/NHibernate/Collection/Generic/PersistentGenericBag.cs
  src/NHibernate/Collection/IPersistentCollection.cs
  src/NHibernate/Engine/Loading/CollectionLoadContext.cs
  src/NHibernate/Event/Default/DefaultInitializeCollectionEventListener.cs
Labels: possible breaking change, t: Fix

#1883 Obsolete a forgotten dynamic proxy class
  src/NHibernate/Proxy/Poco/BasicLazyInitializer.cs
Labels: c: ByteCode providers, p: Trivial, t: Fix

#1885 Process classes accordingly to inheritance path in mapping by code
  src/NHibernate.Test/NHSpecificTest/NH2931/Fixture.cs
  src/NHibernate.Test/NHSpecificTest/NH2931/Mappings.cs
  src/NHibernate.Test/NHSpecificTest/NH2931/Models.cs
  src/NHibernate/Mapping/ByCode/ModelMapper.cs
Labels: c: Mapping by Code, p: Minor, t: Bug

#1872 Fix property ref handling
  src/NHibernate.Test/Async/NHSpecificTest/NH3480/Fixture.cs
  src/NHibernate.Test/Async/PropertyRef/KeyEntityPropertyRefFixture.cs
  src/NHibernate.Test/Async/PropertyRef/ManyToManyPropertyRefFixture.cs
  src/NHibernate.Test/NHSpecificTest/NH3480/Entity.cs
  src/NHibernate.Test/NHSpecificTest/NH3480/Fixture.cs
  src/NHibernate.Test/NHSpecificTest/NH3480/Mappings.hbm.xml
  src/NHibernate.Test/NHSpecificTest/Properties/Mappings.hbm.xml
  src/NHibernate.Test/PropertyRef/A.cs
  src/NHibernate.Test/PropertyRef/C.cs
  src/NHibernate.Test/PropertyRef/KeyEntityPropertyRef.hbm.xml
  src/NHibernate.Test/PropertyRef/KeyEntityPropertyRefFixture.cs
  src/NHibernate.Test/PropertyRef/ManyA.cs
  src/NHibernate.Test/PropertyRef/ManyB.cs
  src/NHibernate.Test/PropertyRef/ManyToManyPropertyRefFixture.cs
  src/NHibernate.Test/PropertyRef/ManyToManyWithPropertyRef.hbm.xml
  src/NHibernate/Async/Engine/BatchFetchQueue.cs
  src/NHibernate/Async/Engine/Collections.cs
  src/NHibernate/Async/Engine/TwoPhaseLoad.cs
  src/NHibernate/Async/Event/Default/DefaultInitializeCollectionEventListener.cs
  src/NHibernate/Async/Loader/Loader.cs
  src/NHibernate/Async/Persister/Entity/AbstractEntityPersister.cs
  src/NHibernate/Async/Persister/Entity/IUniqueKeyLoadable.cs
  src/NHibernate/Async/Type/CollectionType.cs
  src/NHibernate/Async/Type/EntityType.cs
  src/NHibernate/Cfg/XmlHbmBinding/CollectionBinder.cs
  src/NHibernate/Engine/BatchFetchQueue.cs
  src/NHibernate/Engine/EntityUniqueKey.cs
  src/NHibernate/Engine/JoinHelper.cs
  src/NHibernate/Engine/StatefulPersistenceContext.cs
  src/NHibernate/Engine/TwoPhaseLoad.cs
  src/NHibernate/Event/Default/DefaultInitializeCollectionEventListener.cs
  src/NHibernate/Loader/Collection/OneToManyJoinWalker.cs
  src/NHibernate/Loader/Loader.cs
  src/NHibernate/Persister/Collection/AbstractCollectionPersister.cs
  src/NHibernate/Persister/Collection/IQueryableCollection.cs
  src/NHibernate/Persister/Collection/OneToManyPersister.cs
  src/NHibernate/Persister/Entity/AbstractEntityPersister.cs
  src/NHibernate/Persister/Entity/IJoinable.cs
  src/NHibernate/Persister/Entity/IUniqueKeyLoadable.cs
  src/NHibernate/SqlCommand/SqlUpdateBuilder.cs
  src/NHibernate/Type/CollectionType.cs
  src/NHibernate/Type/ComponentType.cs
  src/NHibernate/Type/EntityType.cs
Labels: Regression, c: Core, p: Minor, t: Bug

#1880 GH-1879 - Allow Coalesce and Conditional logic on entity properties
  src/NHibernate.Test/Async/NHSpecificTest/GH1879/CoalesceChildThenAccessExtensionMethod.cs
  src/NHibernate.Test/Async/NHSpecificTest/GH1879/CoalesceChildThenAccessMember.cs
  src/NHibernate.Test/Async/NHSpecificTest/GH1879/CoalesceChildThenAccessMethod.cs
  src/NHibernate.Test/Async/NHSpecificTest/GH1879/CoalesceSiblingsThenAccessMember.cs
  src/NHibernate.Test/Async/NHSpecificTest/GH1879/ConditionalThenAccessMember.cs
  src/NHibernate.Test/Async/NHSpecificTest/GH1879/ConditionalThenMethodCall.cs
  src/NHibernate.Test/Async/NHSpecificTest/GH1879/FixtureByCode.cs
  src/NHibernate.Test/Async/NHSpecificTest/GH1879/NestedConditionalThenMethodCall.cs
  src/NHibernate.Test/NHSpecificTest/GH1879/CoalesceChildThenAccessExtensionMethod.cs
  src/NHibernate.Test/NHSpecificTest/GH1879/CoalesceChildThenAccessMember.cs
  src/NHibernate.Test/NHSpecificTest/GH1879/CoalesceChildThenAccessMethod.cs
  src/NHibernate.Test/NHSpecificTest/GH1879/CoalesceSiblingsThenAccessMember.cs
  src/NHibernate.Test/NHSpecificTest/GH1879/ConditionalThenAccessMember.cs
  src/NHibernate.Test/NHSpecificTest/GH1879/ConditionalThenMethodCall.cs
  src/NHibernate.Test/NHSpecificTest/GH1879/Entity.cs
  src/NHibernate.Test/NHSpecificTest/GH1879/FixtureByCode.cs
  src/NHibernate.Test/NHSpecificTest/GH1879/NestedConditionalThenMethodCall.cs
  src/NHibernate.Test/NHSpecificTest/GH1879/TestExtensions.cs
  src/NHibernate/Linq/ReWriters/ConditionalQueryReferenceExpander.cs
  src/NHibernate/Linq/ReWriters/SubQueryConditionalExpander.cs
  src/NHibernate/Linq/Visitors/MemberExpressionJoinDetector.cs
  src/NHibernate/Linq/Visitors/QueryModelVisitor.cs
  src/NHibernate/Linq/Visitors/WhereJoinDetector.cs
Labels: t: Fix

#1887 Test ref and out methods with static proxy
  src/NHibernate.Test/StaticProxyTest/StaticProxyFactoryFixture.cs
Labels: c: Tests, p: Trivial, t: Improvement

#1884 Fix attempt of static proxies to call base method for abstract classes
  src/NHibernate.Test/StaticProxyTest/StaticProxyFactoryFixture.cs
  src/NHibernate/Proxy/NHibernateProxyBuilder.cs
Labels: c: ByteCode providers, p: Minor, t: Bug

#1893 Avoid some superfluous parameter casts with Firebird
  src/NHibernate.Test/Async/DriverTest/FirebirdClientDriverFixture.cs
  src/NHibernate.Test/DriverTest/FirebirdClientDriverFixture.cs
  src/NHibernate/Driver/FirebirdClientDriver.cs
Labels: t: Fix

#1892 Allow disabling Firebird driver parameter casting
  doc/reference/modules/configuration.xml
  src/NHibernate.Test/Async/DriverTest/FirebirdClientDriverFixture.cs
  src/NHibernate.Test/DriverTest/FirebirdClientDriverFixture.cs
  src/NHibernate/Cfg/Environment.cs
  src/NHibernate/Driver/FirebirdClientDriver.cs
  src/NHibernate/nhibernate-configuration.xsd
Labels: c: DataProviders / Dialects, p: Trivial, t: New Feature

#1873 Fix many-to-many with property-ref
  src/NHibernate.Test/Async/PropertyRef/ManyToManyPropertyRefFixture.cs
  src/NHibernate.Test/PropertyRef/ManyToManyPropertyRefFixture.cs
  src/NHibernate/Persister/Collection/BasicCollectionPersister.cs
Labels: t: Fix
