Repository nhibernate/nhibernate-core, pull requests merged in 2018-09, with the labels that each got.

#1842 Remove WcfOperationSessionContext from .Net Core and .Net Standard
  src/NHibernate/Context/WcfOperationSessionContext.cs
  src/NHibernate/Impl/SessionFactoryImpl.cs
  src/NHibernate/NHibernate.csproj
Labels: c: Core, p: Minor, possible breaking change, t: Improvement

#1846 Remove dependency on System.Security.Permissions package for .NET Standard and .NET Core
  src/NHibernate/Bytecode/Lightweight/ReflectionOptimizer.cs
  src/NHibernate/Driver/OdbcDriver.cs
  src/NHibernate/Driver/OleDbDriver.cs
  src/NHibernate/NHibernate.csproj
Labels: c: Core, p: Minor, t: Improvement

#1833 Parameterize string type comparer
  doc/reference/modules/basic_mapping.xml
  src/NHibernate.Test/Async/NHSpecificTest/GH1833/Fixture.cs
  src/NHibernate.Test/Async/TypesTest/StringTypeFixture.cs
  src/NHibernate.Test/NHSpecificTest/GH1833/Entity.cs
  src/NHibernate.Test/NHSpecificTest/GH1833/Fixture.cs
  src/NHibernate.Test/NHSpecificTest/GH1833/Mappings.hbm.xml
  src/NHibernate.Test/TypesTest/StringTypeFixture.cs
  src/NHibernate/Type/AbstractStringType.cs
  src/NHibernate/Type/NullableType.cs
  src/NHibernate/Type/TypeFactory.cs
Labels: c: Core, p: Minor, possible breaking change, t: New Feature

#1452 Async After-/BeforeTransactionCompletion
  src/AsyncGenerator.yml
  src/NHibernate.Test/Async/BulkManipulation/NativeSQLBulkOperationsWithCache.cs
  src/NHibernate.Test/BulkManipulation/BulkOperationCleanupActionFixture.cs
  src/NHibernate.Test/BulkManipulation/NativeSQLBulkOperationsWithCache.cs
  src/NHibernate/Action/BulkOperationCleanupAction.cs
  src/NHibernate/Action/CollectionAction.cs
  src/NHibernate/Action/CollectionUpdateAction.cs
  src/NHibernate/Action/EntityAction.cs
  src/NHibernate/Action/IAfterTransactionCompletionProcess.cs
  src/NHibernate/Action/IAsyncExecutable.cs
  src/NHibernate/Action/IBeforeTransactionCompletionProcess.cs
  src/NHibernate/Action/IExecutable.cs
  src/NHibernate/Async/Action/BulkOperationCleanupAction.cs
  src/NHibernate/Async/Action/CollectionAction.cs
  src/NHibernate/Async/Action/CollectionUpdateAction.cs
  src/NHibernate/Async/Action/EntityAction.cs
  src/NHibernate/Async/Action/IAfterTransactionCompletionProcess.cs
  src/NHibernate/Async/Action/IBeforeTransactionCompletionProcess.cs
  src/NHibernate/Async/Engine/ActionQueue.cs
  src/NHibernate/Async/Impl/SessionImpl.cs
  src/NHibernate/Engine/ActionQueue.cs
  src/NHibernate/Hql/Ast/ANTLR/Exec/AbstractStatementExecutor.cs
Labels: c: Core, p: Major, t: Improvement

#1848 Add in ByCode support of all type mappings on Id
  src/NHibernate.Test/MappingByCode/MappersTests/IdMapperTest.cs
  src/NHibernate/Mapping/ByCode/IIdMapper.cs
  src/NHibernate/Mapping/ByCode/Impl/IdMapper.cs
Labels: c: Mapping by Code, p: Trivial, t: New Feature

#1850 Add HqlTreeBuilder.From overload that accepts HqlJoin
  src/NHibernate/Hql/Ast/HqlTreeBuilder.cs
Labels: r: Fixed, t: Fix

#1851 Add HqlTreeBuilder.From overload which accepts HqlRange and a collection of HqlJoin
  src/NHibernate/Hql/Ast/HqlTreeBuilder.cs
Labels: t: Fix

#1849 IQueryCache constraint should be an IQueryCacheFactory constraint
  src/NHibernate.Test/CfgTest/Loquacious/ConfigurationFixture.cs
  src/NHibernate.Test/CfgTest/Loquacious/LambdaConfigurationFixture.cs
  src/NHibernate/Cfg/Loquacious/CacheConfiguration.cs
  src/NHibernate/Cfg/Loquacious/ICacheConfiguration.cs
  src/NHibernate/Cfg/Loquacious/IQueryCacheConfiguration.cs
Labels: c: Core, p: Major, t: Bug

#1852 Avoid initializing proxies when ordering inserts
  src/NHibernate.Test/Async/Insertordering/AnimalModel/Fixture.cs
  src/NHibernate.Test/Insertordering/AnimalModel/Animal.cs
  src/NHibernate.Test/Insertordering/AnimalModel/Fixture.cs
  src/NHibernate.Test/Insertordering/AnimalModel/Person.cs
  src/NHibernate/Async/Action/IExecutable.cs
  src/NHibernate/Async/Engine/ActionQueue.cs
  src/NHibernate/Engine/ActionQueue.cs
Labels: t: Fix
