Repository nhibernate/nhibernate-core, pull requests merged in 2018-04, with the labels that each got.

#1622 Update cache documentation
  doc/reference/modules/nhibernate_caches.xml
Labels: c: Documentation, p: Minor, t: Task

#1630 Remove class baseType interfaces from proxified methods
  src/NHibernate.Test/Async/NHSpecificTest/GH1628/Fixture.cs
  src/NHibernate.Test/NHSpecificTest/GH1628/Entity.cs
  src/NHibernate.Test/NHSpecificTest/GH1628/Fixture.cs
  src/NHibernate.Test/NHSpecificTest/GH1628/Mappings.hbm.xml
  src/NHibernate/Proxy/DynamicProxy/ProxyFactory.cs
Labels: t: Fix

#1618 Fix NuGet push script
  ReleaseProcedure.txt
  default.build
Labels: c: Toolset, p: Trivial, t: Bug

#1644 Fix TypeLoadException in StaticProxyFactory when class has not visible interfaces
  src/NHibernate.Test/StaticProxyTest/StaticProxyFactoryFixture.cs
  src/NHibernate/Proxy/NHibernateProxyBuilder.cs
Labels: t: Fix

#1647 Fix key type mismatch in EntityUniqueKey
  src/NHibernate.Test/Async/NHSpecificTest/GH1645/Fixture.cs
  src/NHibernate.Test/NHSpecificTest/GH1645/EntityBase.cs
  src/NHibernate.Test/NHSpecificTest/GH1645/Fixture.cs
  src/NHibernate.Test/NHSpecificTest/GH1645/Mappings.hbm.xml
  src/NHibernate.Test/NHSpecificTest/GH1645/Parent.cs
  src/NHibernate.Test/NHSpecificTest/GH1645/SuperParent.cs
  src/NHibernate/Async/Type/EntityType.cs
  src/NHibernate/Engine/EntityUniqueKey.cs
  src/NHibernate/Loader/Loader.cs
  src/NHibernate/Type/EntityType.cs
Labels: t: Fix

#1649 Release 5.1.1
  ReleaseProcedure.txt
  appveyor.yml
  build-common/NHibernate.props
  build-common/common.xml
  releasenotes.txt
  src/NHibernate.sln
Labels: c: Documentation, p: Minor, t: Task

#1641 Add cross platform build for full .NET Framework
  .travis.yml
  build-common/DotNetSdkMono.props
  build-common/NHibernate.props
  psake.ps1
  src/NHibernate.Test/NHibernate.Test.csproj
Labels: c: Toolset, p: Minor, t: Improvement

#1658 Add missing cache setting
  build-common/NHibernate.props
  build-common/common.xml
  releasenotes.txt
  src/NHibernate/nhibernate-configuration.xsd
Labels: c: Core, p: Minor, t: Fix

#1659 Merge 5.0.4 into 5.1.x
  releasenotes.txt
  src/NHibernate/nhibernate-configuration.xsd
Labels: c: Core, p: Minor, t: Task

#1611 Fix IFilter.SetParameterList not supporting HashSet<T> arguments
  src/NHibernate.Test/Async/FilterTest/DynamicFilterTest.cs
  src/NHibernate.Test/FilterTest/DynamicFilterTest.cs
  src/NHibernate.Test/FilterTest/Product.cs
  src/NHibernate.Test/FilterTest/classes.hbm.xml
  src/NHibernate.Test/FilterTest/defs.hbm.xml
  src/NHibernate/Engine/Query/NativeSQLQueryPlan.cs
  src/NHibernate/Impl/FilterImpl.cs
  src/NHibernate/Loader/Loader.cs
Labels: t: Fix

#1661 Fix persistent collections' CopyTo implementations
  src/NHibernate.Test/CollectionTest/PersistentCollectionsFixture.cs
  src/NHibernate.Test/CollectionTest/PersistentGenericMapFixture.cs
  src/NHibernate/Collection/Generic/PersistentGenericBag.cs
  src/NHibernate/Collection/Generic/PersistentGenericIdentifierBag.cs
  src/NHibernate/Collection/Generic/PersistentGenericList.cs
  src/NHibernate/Collection/Generic/PersistentGenericMap.cs
  src/NHibernate/Collection/Generic/PersistentGenericSet.cs
Labels: t: Fix

#1656 Allow any `cache.*` property in NHibernate configuration
  src/NHibernate.Test/CfgTest/ConfigurationSchemaFixture.cs
  src/NHibernate/nhibernate-configuration.xsd
Labels: c: Core, p: Minor, t: Improvement

#1665 Have IFutureEnumerable.GetEnumerable executing immediatly the query
  build-common/NHibernate.props
  build-common/common.xml
  releasenotes.txt
  src/NHibernate.Test/Async/Futures/FutureQueryFixture.cs
  src/NHibernate.Test/Futures/FutureQueryFixture.cs
  src/NHibernate/Impl/DelayedEnumerator.cs
Labels: c: Core, p: Minor, t: Bug

#1668 Merge 5.0.5 into 5.1.x
  releasenotes.txt
  src/NHibernate.Test/Async/Futures/FutureQueryFixture.cs
  src/NHibernate.Test/Futures/FutureQueryFixture.cs
  src/NHibernate/Impl/DelayedEnumerator.cs
Labels: c: Core, p: Minor, t: Task
