Repository nhibernate/nhibernate-core, pull requests merged in 2018-12, with the labels that each got.

#530 NH-2285 - Support for LockMode in Linq provider
  src/NHibernate.Test/Async/Linq/QueryLock.cs
  src/NHibernate.Test/Linq/QueryLock.cs
  src/NHibernate.Test/TestDialect.cs
  src/NHibernate.Test/TestDialects/FirebirdTestDialect.cs
  src/NHibernate.Test/TestDialects/MsSql2008TestDialect.cs
  src/NHibernate.Test/TestDialects/MsSqlCe40TestDialect.cs
  src/NHibernate.Test/TestDialects/Oracle10gTestDialect.cs
  src/NHibernate.Test/TestDialects/SQLiteTestDialect.cs
  src/NHibernate.Test/TestDialects/SapSQLAnywhere17TestDialect.cs
  src/NHibernate/Linq/LinqExtensionMethods.cs
  src/NHibernate/Linq/LockExpressionNode.cs
  src/NHibernate/Linq/LockResultOperator.cs
  src/NHibernate/Linq/NhRelinqQueryParser.cs
  src/NHibernate/Linq/ReWriters/QueryReferenceExpressionFlattener.cs
  src/NHibernate/Linq/ReWriters/ResultOperatorRewriter.cs
  src/NHibernate/Linq/Visitors/QueryModelVisitor.cs
  src/NHibernate/Linq/Visitors/ResultOperatorProcessors/ProcessLock.cs
  src/NHibernate/Linq/Visitors/SubQueryFromClauseFlattener.cs
Labels: t: Fix

#1863 Release 5.2.0
  appveyor.yml
  build-common/NHibernate.props
  build-common/common.xml
  doc/reference/master.xml
  releasenotes.txt
Labels: c: Core, p: Minor, t: Task

#1918 Property-ref on many-to-one with composite id fails
  src/NHibernate.Test/Async/NHSpecificTest/GH1918/Fixture.cs
  src/NHibernate.Test/NHSpecificTest/GH1918/BiEmbIdRefEdEntity.cs
  src/NHibernate.Test/NHSpecificTest/GH1918/BiEmbIdRefIngEntity.cs
  src/NHibernate.Test/NHSpecificTest/GH1918/EmbId.cs
  src/NHibernate.Test/NHSpecificTest/GH1918/Fixture.cs
  src/NHibernate.Test/NHSpecificTest/GH1918/Mappings.hbm.xml
  src/NHibernate/Async/Persister/Entity/AbstractEntityPersister.cs
  src/NHibernate/Persister/Entity/AbstractEntityPersister.cs
Labels: Regression, c: Core, p: Minor, t: Bug

#1925 Batch fetch queue fix
  src/NHibernate.Test/Async/CacheTest/BatchableCacheFixture.cs
  src/NHibernate.Test/Async/NHSpecificTest/GH1920/Fixture.cs
  src/NHibernate.Test/CacheTest/BatchableCacheFixture.cs
  src/NHibernate.Test/NHSpecificTest/GH1920/EntityWithBatchSize.cs
  src/NHibernate.Test/NHSpecificTest/GH1920/Fixture.cs
  src/NHibernate.Test/NHSpecificTest/GH1920/Mappings.hbm.xml
  src/NHibernate/Async/Engine/BatchFetchQueue.cs
  src/NHibernate/Engine/BatchFetchQueue.cs
Labels: t: Fix

#1930 Fix alias join on join
  src/NHibernate.Test/Async/NHSpecificTest/GH1928/Fixture.cs
  src/NHibernate.Test/NHSpecificTest/GH1928/Entity.cs
  src/NHibernate.Test/NHSpecificTest/GH1928/Fixture.cs
  src/NHibernate.Test/NHSpecificTest/GH1928/Mappings.hbm.xml
  src/NHibernate/Loader/Criteria/CriteriaQueryTranslator.cs
Labels: t: Fix

#1935 Fix generation of version update statement for joined subclasses
  src/NHibernate.Test/Async/NHSpecificTest/NH3069/Fixture.cs
  src/NHibernate.Test/NHSpecificTest/NH3069/Domain.cs
  src/NHibernate.Test/NHSpecificTest/NH3069/Fixture.cs
  src/NHibernate.Test/NHSpecificTest/NH3069/Mappings.hbm.xml
  src/NHibernate/Persister/Entity/AbstractEntityPersister.cs
Labels: t: Fix

#1923 Obsolete StringHelper.Replace
  src/NHibernate/Criterion/SQLProjection.cs
  src/NHibernate/Driver/FirebirdClientDriver.cs
  src/NHibernate/Hql/Ast/ANTLR/Util/SyntheticAndFactory.cs
  src/NHibernate/Id/UUIDHexGenerator.cs
  src/NHibernate/Impl/AbstractQueryImpl.cs
  src/NHibernate/Mapping/SimpleAuxiliaryDatabaseObject.cs
  src/NHibernate/Mapping/UniqueKey.cs
  src/NHibernate/Persister/Collection/AbstractCollectionPersister.cs
  src/NHibernate/Persister/Entity/AbstractEntityPersister.cs
  src/NHibernate/Persister/Entity/AbstractPropertyMapping.cs
  src/NHibernate/SqlCommand/InFragment.cs
  src/NHibernate/SqlCommand/SelectFragment.cs
  src/NHibernate/Util/FilterHelper.cs
  src/NHibernate/Util/StringHelper.cs
Labels: c: Core, p: Minor, t: Improvement

#1931 Add session filter support for DML statement
  .editorconfig
  src/NHibernate.Test/Async/NHSpecificTest/GH1921/Fixture.cs
  src/NHibernate.Test/NHSpecificTest/GH1921/Entity.cs
  src/NHibernate.Test/NHSpecificTest/GH1921/Fixture.cs
  src/NHibernate.Test/NHSpecificTest/GH1921/Mappings.hbm.xml
  src/NHibernate.Test/TestDialect.cs
  src/NHibernate/Async/Engine/Query/NativeSQLQueryPlan.cs
  src/NHibernate/Async/Hql/Ast/ANTLR/Exec/BasicExecutor.cs
  src/NHibernate/Async/Hql/Ast/ANTLR/Exec/MultiTableDeleteExecutor.cs
  src/NHibernate/Async/Hql/Ast/ANTLR/Exec/MultiTableUpdateExecutor.cs
  src/NHibernate/Async/Loader/Loader.cs
  src/NHibernate/Engine/JoinSequence.cs
  src/NHibernate/Engine/Query/NativeSQLQueryPlan.cs
  src/NHibernate/Hql/Ast/ANTLR/Exec/BasicExecutor.cs
  src/NHibernate/Hql/Ast/ANTLR/Exec/MultiTableDeleteExecutor.cs
  src/NHibernate/Hql/Ast/ANTLR/Exec/MultiTableUpdateExecutor.cs
  src/NHibernate/Hql/Ast/ANTLR/HqlSqlWalker.cs
  src/NHibernate/Hql/Ast/ANTLR/SqlGenerator.g
  src/NHibernate/Hql/Ast/ANTLR/Util/JoinProcessor.cs
  src/NHibernate/Hql/Ast/ANTLR/Util/SyntheticAndFactory.cs
  src/NHibernate/Loader/Loader.cs
  src/NHibernate/Persister/Entity/AbstractEntityPersister.cs
  src/NHibernate/SqlCommand/InFragment.cs
  src/NHibernate/Util/FilterHelper.cs
Labels: possible breaking change, t: Fix

#1938 Cease having dynamic composite-id causing swallowed exceptions
  src/NHibernate.Test/Async/NHSpecificTest/NH3865/Fixture.cs
  src/NHibernate.Test/NHSpecificTest/NH3865/Fixture.cs
  src/NHibernate.Test/NHSpecificTest/NH3865/Mappings.hbm.xml
  src/NHibernate/Mapping/Component.cs
Labels: t: Fix

#1939 Support Future for collection filters
  src/NHibernate.Test/Async/Futures/FutureQueryFixture.cs
  src/NHibernate.Test/Async/Futures/LinqFutureFixture.cs
  src/NHibernate.Test/Futures/FutureFixture.cs
  src/NHibernate.Test/Futures/FutureQueryFixture.cs
  src/NHibernate.Test/Futures/LinqFutureFixture.cs
  src/NHibernate/Async/Impl/AbstractQueryImpl.cs
  src/NHibernate/Async/Impl/CollectionFilterImpl.cs
  src/NHibernate/Async/Impl/ExpressionQueryImpl.cs
  src/NHibernate/Impl/CollectionFilterImpl.cs
  src/NHibernate/Impl/ExpressionQueryImpl.cs
Labels: t: Fix

#1940 Allow to provide dev specific properties in NHibernate.dev.props
  .gitignore
  build-common/NHibernate.props
Labels: c: Toolset, p: Trivial, t: Task

#1943 Modified field interceptor to skip initialization of lazy properties when setting one
  src/NHibernate.Test/Async/GhostProperty/GhostPropertyFixture.cs
  src/NHibernate.Test/Async/LazyProperty/LazyPropertyFixture.cs
  src/NHibernate.Test/GhostProperty/GhostPropertyFixture.cs
  src/NHibernate.Test/LazyProperty/Book.cs
  src/NHibernate.Test/LazyProperty/LazyPropertyFixture.cs
  src/NHibernate.Test/LazyProperty/Mappings.hbm.xml
  src/NHibernate/Async/Engine/Cascade.cs
  src/NHibernate/Async/Persister/Entity/AbstractEntityPersister.cs
  src/NHibernate/Async/Persister/Entity/IEntityPersister.cs
  src/NHibernate/Engine/Cascade.cs
  src/NHibernate/Intercept/AbstractFieldInterceptor.cs
  src/NHibernate/Intercept/IFieldInterceptor.cs
  src/NHibernate/Persister/Entity/AbstractEntityPersister.cs
  src/NHibernate/Persister/Entity/IEntityPersister.cs
  src/NHibernate/Proxy/FieldInterceptorProxyBuilder.cs
  src/NHibernate/Tuple/Entity/AbstractEntityTuplizer.cs
  src/NHibernate/Tuple/Entity/IEntityTuplizer.cs
  src/NHibernate/Tuple/Entity/PocoEntityTuplizer.cs
  src/NHibernate/Util/CollectionHelper.cs
Labels: c: Core, p: Minor, possible breaking change, t: Improvement

#1754 Delay entity insert on Persist until session is flushed
  src/NHibernate.Test/Async/NHSpecificTest/GH1754/Fixture.cs
  src/NHibernate.Test/NHSpecificTest/GH1754/Entity.cs
  src/NHibernate.Test/NHSpecificTest/GH1754/Fixture.cs
  src/NHibernate.Test/NHSpecificTest/GH1754/Mappings.hbm.xml
  src/NHibernate/Action/CollectionAction.cs
  src/NHibernate/Action/CollectionRecreateAction.cs
  src/NHibernate/Action/CollectionRemoveAction.cs
  src/NHibernate/Action/CollectionUpdateAction.cs
  src/NHibernate/Action/DelayedPostInsertIdentifier.cs
  src/NHibernate/Async/Action/CollectionAction.cs
  src/NHibernate/Async/Action/CollectionRecreateAction.cs
  src/NHibernate/Async/Action/CollectionRemoveAction.cs
  src/NHibernate/Async/Action/CollectionUpdateAction.cs
  src/NHibernate/Async/Engine/CollectionEntry.cs
  src/NHibernate/Async/Event/Default/AbstractSaveEventListener.cs
  src/NHibernate/Async/Event/Default/DefaultLoadEventListener.cs
  src/NHibernate/Engine/CollectionEntry.cs
  src/NHibernate/Event/Default/AbstractSaveEventListener.cs
  src/NHibernate/Event/Default/DefaultLoadEventListener.cs
Labels: c: Core, p: Major, possible breaking change, t: Improvement

#1951 Cache Dialect when creating a session factory
  src/NHibernate/Cfg/Configuration.cs
Labels: t: Fix
