Repository nhibernate/nhibernate-core, pull requests merged in 2018-05, with the labels that each got.

#1670 Fix bitwise functions thread safety
  src/NHibernate.Test/Async/Hql/HQLFunctions.cs
  src/NHibernate.Test/Hql/HQLFunctions.cs
  src/NHibernate.Test/TestCase.cs
  src/NHibernate/Dialect/BitwiseFunctionOperation.cs
  src/NHibernate/Dialect/BitwiseNativeOperation.cs
Labels: c: DataProviders / Dialects, p: Major, t: Bug

#1679 Do not log result sets
  src/NHibernate.Test/Async/NHSpecificTest/GH1667/Fixture.cs
  src/NHibernate.Test/NHSpecificTest/GH1667/Entity.cs
  src/NHibernate.Test/NHSpecificTest/GH1667/Fixture.cs
  src/NHibernate.Test/NHSpecificTest/GH1667/Mappings.hbm.xml
  src/NHibernate/Engine/Loading/CollectionLoadContext.cs
  src/NHibernate/Engine/Loading/LoadContexts.cs
  src/NHibernate/Loader/Loader.cs
Labels: t: Fix

#1678 Back port bitwise thread safety fix in 4.1
  build-common/common.xml
  releasenotes.txt
  src/NHibernate.Test/Hql/HQLFunctions.cs
  src/NHibernate.sln.DotSettings
  src/NHibernate/Dialect/BitwiseFunctionOperation.cs
  src/NHibernate/Dialect/BitwiseNativeOperation.cs
Labels: t: Fix

#1681 #1680 Fixed Criteria Clone for Entity Join in 5.1.x
  src/NHibernate.Test/Async/Criteria/EntityJoinCriteriaTest.cs
  src/NHibernate.Test/Criteria/EntityJoinCriteriaTest.cs
  src/NHibernate/Impl/CriteriaImpl.cs
Labels: t: Fix

#1682 Add support for System.MathF methods
  src/NHibernate.Test/Linq/MathFTests.cs
  src/NHibernate/Linq/Functions/MathGenerator.cs
  src/NHibernate/Linq/Functions/RoundGenerator.cs
  src/NHibernate/Linq/Functions/TruncateGenerator.cs
Labels: c: Linq Provider, p: Trivial, r: Fixed, t: New Feature

#1677 Back port bitwise thread safety fix in 5.0
  src/NHibernate.Test/Async/Hql/HQLFunctions.cs
  src/NHibernate.Test/Hql/HQLFunctions.cs
  src/NHibernate/Dialect/BitwiseFunctionOperation.cs
  src/NHibernate/Dialect/BitwiseNativeOperation.cs
Labels: t: Fix

#1686 Release 5.0.6
  build-common/NHibernate.props
  build-common/common.xml
  releasenotes.txt
Labels: c: Documentation, p: Minor, t: Task

#1666 Handle multi-queries support in FutureBatch
  src/NHibernate.Test/Async/Futures/FallbackFixture.cs
  src/NHibernate.Test/Async/NHSpecificTest/NH3850/DateTimeOffsetFixture.cs
  src/NHibernate.Test/Async/NHSpecificTest/NH3850/FixtureBase.cs
  src/NHibernate.Test/Async/NHSpecificTest/NH3850/MainFixture.cs
  src/NHibernate.Test/Futures/FallbackFixture.cs
  src/NHibernate.Test/Futures/Mappings.hbm.xml
  src/NHibernate.Test/Futures/Person.cs
  src/NHibernate.Test/Futures/PolymorphicEntities.cs
  src/NHibernate.Test/NHSpecificTest/NH3850/DateTimeOffsetFixture.cs
  src/NHibernate.Test/NHSpecificTest/NH3850/DateTimeOffsetMappings.hbm.xml
  src/NHibernate.Test/NHSpecificTest/NH3850/Domain.cs
  src/NHibernate.Test/NHSpecificTest/NH3850/FixtureBase.cs
  src/NHibernate.Test/NHSpecificTest/NH3850/MainFixture.cs
  src/NHibernate.Test/NHSpecificTest/NH3850/Mappings.hbm.xml
  src/NHibernate/Async/Impl/FutureBatch.cs
  src/NHibernate/Async/Impl/FutureCriteriaBatch.cs
  src/NHibernate/Async/Impl/FutureQueryBatch.cs
  src/NHibernate/Impl/AbstractQueryImpl.cs
  src/NHibernate/Impl/CriteriaImpl.cs
  src/NHibernate/Impl/FutureBatch.cs
  src/NHibernate/Impl/FutureCriteriaBatch.cs
  src/NHibernate/Impl/FutureQueryBatch.cs
Labels: c: Core, p: Minor, t: Improvement

#1664 Release 5.1.2
  appveyor.yml
  build-common/NHibernate.props
  build-common/common.xml
  releasenotes.txt
Labels: c: Documentation, p: Minor, t: Task

#1691 Bitwise operator adjustments
  src/NHibernate.Test/TestCase.cs
  src/NHibernate/Dialect/Dialect.cs
  src/NHibernate/Dialect/FirebirdDialect.cs
  src/NHibernate/Dialect/Function/BitwiseFunctionOperation.cs
  src/NHibernate/Dialect/Function/BitwiseNativeOperation.cs
  src/NHibernate/Dialect/HanaDialectBase.cs
  src/NHibernate/Dialect/Oracle8iDialect.cs
  src/NHibernate/Dialect/PostgreSQLDialect.cs
  src/NHibernate/Dialect/SQLiteDialect.cs
Labels: t: Fix

#1687 Update NUnit to 3.10.1
  src/NHibernate.Test.VisualBasic/NHibernate.Test.VisualBasic.vbproj
  src/NHibernate.Test/Async/NHSpecificTest/NH2204/Fixture.cs
  src/NHibernate.Test/NHSpecificTest/NH2204/Fixture.cs
  src/NHibernate.Test/NHibernate.Test.csproj
  src/NHibernate.TestDatabaseSetup/NHibernate.TestDatabaseSetup.csproj
Labels: c: Tests, p: Trivial, t: Task

#1689 Purge more Invariant culture usages
  src/NHibernate/Dialect/Function/AnsiTrimEmulationFunction.cs
  src/NHibernate/Dialect/Function/CastFunction.cs
  src/NHibernate/Dialect/Function/ClassicAggregateFunction.cs
  src/NHibernate/Driver/NDataReader.cs
  src/NHibernate/Hql/QuerySplitter.cs
  src/NHibernate/Mapping/Column.cs
  src/NHibernate/Mapping/ManyToOne.cs
  src/NHibernate/Mapping/ReferenceDependantValue.cs
  src/NHibernate/Mapping/SimpleValue.cs
  src/NHibernate/SqlCommand/Parser/MsSqlSelectParser.cs
  src/NHibernate/SqlCommand/Parser/SqlTokenizerExtensions.cs
  src/NHibernate/SqlCommand/SqlString.cs
  src/NHibernate/SqlCommand/SubselectClauseExtractor.cs
  src/NHibernate/Type/CharBooleanType.cs
  src/NHibernate/Util/StringHelper.cs
Labels: c: Core, p: Trivial, t: Improvement

#1693 Implement SurrogateSelector
  src/NHibernate.Test/Async/CfgTest/ConfigurationSerializationTests.cs
  src/NHibernate.Test/Async/ConnectionTest/AggressiveReleaseTest.cs
  src/NHibernate.Test/Async/Criteria/CriteriaQueryTest.cs
  src/NHibernate.Test/Async/Criteria/DetachedCriteriaSerializable.cs
  src/NHibernate.Test/Async/DynamicProxyTests/InterfaceProxySerializationTests/ProxyFixture.cs
  src/NHibernate.Test/Async/Legacy/FooBarTest.cs
  src/NHibernate.Test/Async/Legacy/FumTest.cs
  src/NHibernate.Test/Async/Legacy/MasterDetailTest.cs
  src/NHibernate.Test/Async/NHSpecificTest/Dates/DateTimeOffsetFixture.cs
  src/NHibernate.Test/Async/NHSpecificTest/NH2773/Fixture.cs
  src/NHibernate.Test/Async/NHSpecificTest/NH2880/Fixture.cs
  src/NHibernate.Test/Async/NHSpecificTest/NH2898/BinaryFormatterCache.cs
  src/NHibernate.Test/Async/NHSpecificTest/NH3119/FixtureByCode.cs
  src/NHibernate.Test/Async/NHSpecificTest/NH317/Fixture.cs
  src/NHibernate.Test/Async/NHSpecificTest/NH3487/Fixture.cs
  src/NHibernate.Test/Async/NHSpecificTest/NH3731/FixtureByCode.cs
  src/NHibernate.Test/Async/ReadOnly/ReadOnlyCriteriaQueryTest.cs
  src/NHibernate.Test/Async/TransformTests/AliasToBeanResultTransformerFixture.cs
  src/NHibernate.Test/Async/TypesTest/BinaryTypeFixture.cs
  src/NHibernate.Test/CfgTest/ConfigurationSerializationTests.cs
  src/NHibernate.Test/CfgTest/MappingDocumentAggregatorTests.cs
  src/NHibernate.Test/ConnectionTest/AggressiveReleaseTest.cs
  src/NHibernate.Test/Criteria/CriteriaQueryTest.cs
  src/NHibernate.Test/Criteria/DetachedCriteriaSerializable.cs
  src/NHibernate.Test/DynamicProxyTests/InterfaceProxySerializationTests/ProxyFixture.cs
  src/NHibernate.Test/DynamicProxyTests/LazyFieldInterceptorTests.cs
  src/NHibernate.Test/Legacy/CultureInfoSerializationSurrogate.cs
  src/NHibernate.Test/Legacy/FooBarTest.cs
  src/NHibernate.Test/Legacy/FumTest.cs
  src/NHibernate.Test/Legacy/MasterDetailTest.cs
  src/NHibernate.Test/NHAssert.cs
  src/NHibernate.Test/NHSpecificTest/Dates/DateTimeOffsetFixture.cs
  src/NHibernate.Test/NHSpecificTest/NH2773/Fixture.cs
  src/NHibernate.Test/NHSpecificTest/NH2880/Fixture.cs
  src/NHibernate.Test/NHSpecificTest/NH2898/BinaryFormatterCache.cs
  src/NHibernate.Test/NHSpecificTest/NH3119/FixtureByCode.cs
  src/NHibernate.Test/NHSpecificTest/NH317/Fixture.cs
  src/NHibernate.Test/NHSpecificTest/NH3383/FixtureByCode.cs
  src/NHibernate.Test/NHSpecificTest/NH3487/Fixture.cs
  src/NHibernate.Test/NHSpecificTest/NH3731/FixtureByCode.cs
  src/NHibernate.Test/ReadOnly/ReadOnlyCriteriaQueryTest.cs
  src/NHibernate.Test/TestsContext.cs
  src/NHibernate.Test/TransformTests/AliasToBeanResultTransformerFixture.cs
  src/NHibernate.Test/TypesTest/BinaryTypeFixture.cs
  src/NHibernate.Test/UtilityTest/LinkedHashMapFixture.cs
  src/NHibernate.Test/UtilityTest/SequencedHashMapFixture.cs
  src/NHibernate/Async/Type/SerializableType.cs
  src/NHibernate/Type/SerializableType.cs
  src/NHibernate/Util/SerializationHelper.Surrogates.cs
  src/NHibernate/Util/SerializationHelper.cs
Labels: c: Core, p: Minor, t: New Feature

#1698 Document setting the logger factory programmatically
  doc/reference/modules/configuration.xml
Labels: c: Documentation, p: Trivial, t: Improvement

#1694 Implement CollectionHelper.GetHashCode that accepts IEqualityComparer<T>
  src/NHibernate.Test/NHSpecificTest/NH3956/Fixture.cs
  src/NHibernate.Test/UtilityTest/CollectionHelperFixture.cs
  src/NHibernate/Cache/FilterKey.cs
  src/NHibernate/Cache/NamedParameterComparer.cs
  src/NHibernate/Cache/QueryKey.cs
  src/NHibernate/Engine/Query/QueryPlanCache.cs
  src/NHibernate/Engine/Query/Sql/NativeSQLQuerySpecification.cs
  src/NHibernate/Mapping/Table.cs
  src/NHibernate/Util/CollectionHelper.cs
Labels: c: Core, p: Trivial, t: Improvement

#1696 Fixed CriteriaImpl.Clone for readonly query
  src/NHibernate.Test/Async/ReadOnly/ReadOnlyCriteriaQueryTest.cs
  src/NHibernate.Test/ReadOnly/ReadOnlyCriteriaQueryTest.cs
  src/NHibernate/Impl/CriteriaImpl.cs
Labels: c: Core, p: Minor, t: Bug

#1699 Add ability to load types from in-memory-only assemblies
  src/NHibernate.Test/Async/CfgTest/LoadMemoryOnlyAssembyTest.cs
  src/NHibernate.Test/CfgTest/LoadMemoryOnlyAssembyTest.cs
  src/NHibernate.Test/NHibernate.Test.csproj
  src/NHibernate/Util/ReflectHelper.cs
Labels: c: Core, p: Trivial, t: Improvement

#1700 Single place to specify TargetFrameworks
  build-common/NHibernate.props
  src/NHibernate.DomainModel/NHibernate.DomainModel.csproj
  src/NHibernate.Test.VisualBasic/NHibernate.Test.VisualBasic.vbproj
  src/NHibernate.Test/NHibernate.Test.csproj
  src/NHibernate.TestDatabaseSetup/NHibernate.TestDatabaseSetup.csproj
  src/NHibernate/NHibernate.csproj
Labels: c: Core, p: Trivial, t: Improvement

#1705 Unit test & Fix for GH1704
  src/NHibernate.Test/Async/NHSpecificTest/GH1704/Fixture.cs
  src/NHibernate.Test/NHSpecificTest/GH1704/Entity.cs
  src/NHibernate.Test/NHSpecificTest/GH1704/Fixture.cs
  src/NHibernate.Test/NHSpecificTest/GH1704/Mappings.hbm.xml
  src/NHibernate/Linq/GroupBy/GroupKeyNominator.cs
Labels: t: Fix

#1706 Entity Projection: Fixed AsEntity() for root entity
  src/NHibernate.Test/Async/Criteria/EntityProjectionsTest.cs
  src/NHibernate.Test/Criteria/EntityProjectionsTest.cs
  src/NHibernate/Criterion/ProjectionsExtensions.cs
Labels: c: QueryOver, p: Minor, r: Fixed, t: Bug

#1703 Remove dialect instantiation in AddDeserializedMapping
  src/NHibernate.Test/Async/NHSpecificTest/NH1007/Fixture.cs
  src/NHibernate.Test/Bytecode/Lightweight/BytecodeProviderFixture.cs
  src/NHibernate.Test/CfgTest/ConfigurationAddMappingEvents.cs
  src/NHibernate.Test/CfgTest/Loquacious/TypeDefinitionFixture.cs
  src/NHibernate.Test/NHSpecificTest/AliasFixture.cs
  src/NHibernate.Test/NHSpecificTest/NH1007/Fixture.cs
  src/NHibernate.Test/NHSpecificTest/NH2041/Fixture.cs
  src/NHibernate.Test/NHSpecificTest/NH2569/Fixture.cs
  src/NHibernate.Test/NHSpecificTest/NH2761/Fixture.cs
  src/NHibernate.Test/NHSpecificTest/NH3153/Fixture.cs
  src/NHibernate/Cfg/BindMappingEventArgs.cs
  src/NHibernate/Cfg/Configuration.cs
  src/NHibernate/Cfg/ConfigurationExtensions.cs
  src/NHibernate/Cfg/Mappings.cs
  src/NHibernate/Cfg/XmlHbmBinding/ClassBinder.cs
  src/NHibernate/Cfg/XmlHbmBinding/ClassCompositeIdBinder.cs
  src/NHibernate/Cfg/XmlHbmBinding/ClassIdBinder.cs
  src/NHibernate/Cfg/XmlHbmBinding/CollectionBinder.cs
  src/NHibernate/Cfg/XmlHbmBinding/JoinedSubclassBinder.cs
  src/NHibernate/Cfg/XmlHbmBinding/MappingRootBinder.cs
  src/NHibernate/Cfg/XmlHbmBinding/PropertiesBinder.cs
  src/NHibernate/Cfg/XmlHbmBinding/RootClassBinder.cs
  src/NHibernate/Cfg/XmlHbmBinding/SubclassBinder.cs
  src/NHibernate/Cfg/XmlHbmBinding/UnionSubclassBinder.cs
  src/NHibernate/Mapping/Join.cs
  src/NHibernate/Mapping/PersistentClass.cs
  src/NHibernate/SqlCommand/Alias.cs
Labels: c: Core, c: DataProviders / Dialects, p: Minor, possible breaking change, t: Improvement

#1710 Rationalize DateTimeOffset read and write
  src/NHibernate/Type/DateTimeOffSetType.cs
Labels: c: Core, p: Trivial, t: Improvement

#1612 Fix TypedValue not always using adequate comparer with SetParameterList
  src/NHibernate.Test/CacheTest/EntityWithFilters.hbm.xml
  src/NHibernate.Test/CacheTest/FilterKeyFixture.cs
  src/NHibernate.Test/CacheTest/QueryKeyFixture.cs
  src/NHibernate.Test/EngineTest/TypedValueFixture.cs
  src/NHibernate/Async/Collection/AbstractPersistentCollection.cs
  src/NHibernate/Async/Loader/Collection/CollectionLoader.cs
  src/NHibernate/Cache/FilterKey.cs
  src/NHibernate/Collection/AbstractPersistentCollection.cs
  src/NHibernate/Criterion/InExpression.cs
  src/NHibernate/Criterion/LikeExpression.cs
  src/NHibernate/Engine/TypedValue.cs
  src/NHibernate/Impl/AbstractDetachedQuery.cs
  src/NHibernate/Impl/AbstractQueryImpl.cs
  src/NHibernate/Impl/ExpressionQueryImpl.cs
  src/NHibernate/Loader/Collection/CollectionLoader.cs
  src/NHibernate/Loader/Criteria/CriteriaQueryTranslator.cs
Labels: c: Core, p: Minor, t: Bug

#1711 Fix static proxy serialization
  src/NHibernate.Test/StaticProxyTest/StaticProxyFactoryFixture.cs
  src/NHibernate/Proxy/NHibernateProxyBuilder.cs
  src/NHibernate/Proxy/NHibernateProxyObjectReference.cs
Labels: Regression, c: ByteCode providers, p: Minor
