Repository nhibernate/nhibernate-core, pull requests merged in 2018-03, with the labels that each got.

#1587 Prevent substitute garbage collection
  src/NHibernate.Test/Linq/ByMethod/WithOptionsTests.cs
Labels: c: Tests, p: Minor, r: Fixed, t: Bug

#1589 Add framework info to example web project and enable .NET Core.
  src/NHibernate.Example.Web/NHibernate.Example.Web.csproj
  src/NHibernate.Example.Web/Pages/_Layout.cshtml
Labels: p: Trivial, r: Fixed, t: Improvement, t: Task

#1533 Add query support for the static methods of System.Decimal
  src/NHibernate.Test/NHSpecificTest/GH0831/Entity.cs
  src/NHibernate.Test/NHSpecificTest/GH0831/FixtureByCode.cs
  src/NHibernate.Test/TestDialect.cs
  src/NHibernate.Test/TestDialects/FirebirdTestDialect.cs
  src/NHibernate.Test/TestDialects/MsSqlCe40TestDialect.cs
  src/NHibernate.Test/TestDialects/SQLiteTestDialect.cs
  src/NHibernate/Dialect/FirebirdDialect.cs
  src/NHibernate/Dialect/MsSql2000Dialect.cs
  src/NHibernate/Dialect/MsSqlCeDialect.cs
  src/NHibernate/Dialect/MySQLDialect.cs
  src/NHibernate/Dialect/Oracle8iDialect.cs
  src/NHibernate/Dialect/SybaseSQLAnywhere10Dialect.cs
  src/NHibernate/Linq/Functions/CompareGenerator.cs
  src/NHibernate/Linq/Functions/DecimalGenerator.cs
  src/NHibernate/Linq/Functions/DefaultLinqToHqlGeneratorsRegistry.cs
  src/NHibernate/Linq/Functions/EqualsGenerator.cs
  src/NHibernate/Linq/Functions/MathGenerator.cs
  src/NHibernate/Linq/Functions/RoundGenerator.cs
  src/NHibernate/Linq/Functions/TruncateGenerator.cs
Labels: t: Fix

#1598 Upgrade IESI to 4.0.4 for having a bumped file version.
  src/NHibernate/NHibernate.csproj
Labels: c: Core, p: Trivial, t: Task

#1595 Substitute DbType.Currency with DbType.Decimal in OracleManagedDataClientDriver and OracleDataClientDriver
  src/NHibernate.Test/Async/TypesTest/CurrencyTypeFixture.cs
  src/NHibernate.Test/TypesTest/CurrencyTypeFixture.cs
  src/NHibernate/Dialect/Oracle8iDialect.cs
  src/NHibernate/Driver/OracleDataClientDriverBase.cs
Labels: t: Fix

#1597 Add support for single-argument truncate to dialects that do not support it natively
  src/NHibernate.Test/Hql/HQLFunctions.cs
  src/NHibernate/Dialect/Function/RoundFunction.cs
  src/NHibernate/Dialect/Function/StandardSQLFunctionWithRequiredParameters.cs
  src/NHibernate/Dialect/MsSql2000Dialect.cs
  src/NHibernate/Dialect/MsSqlCeDialect.cs
  src/NHibernate/Dialect/MySQLDialect.cs
  src/NHibernate/Dialect/PostgreSQLDialect.cs
  src/NHibernate/Dialect/SybaseSQLAnywhere10Dialect.cs
Labels: c: DataProviders / Dialects, p: Minor, t: Improvement

#1603 Forgotten async generation of truncate test
  src/NHibernate.Test/Async/Hql/HQLFunctions.cs
Labels: c: Tests, p: Trivial, t: Task

#1600 Set MySqlClientBatchingBatcher as a default batcher for MySqlDataDriver
  src/NHibernate/AdoNet/MySqlClientBatchingBatcher.cs
  src/NHibernate/AdoNet/MySqlClientSqlCommandSet.cs
  src/NHibernate/Async/AdoNet/MySqlClientBatchingBatcher.cs
  src/NHibernate/Driver/MySqlDataDriver.cs
Labels: c: DataProviders / Dialects, p: Minor, t: Improvement

#1588 Add a generic batcher for insert/update/delete statements, usable with PostgreSQL and others
  src/NHibernate.Test/Ado/BatcherFixture.cs
  src/NHibernate.Test/Ado/GenericBatchingBatcherFixture.cs
  src/NHibernate.Test/Async/Ado/BatcherFixture.cs
  src/NHibernate.Test/Async/Ado/GenericBatchingBatcherFixture.cs
  src/NHibernate.Test/Async/TypesTest/AbstractDateTimeTypeFixture.cs
  src/NHibernate.Test/TypesTest/AbstractDateTimeTypeFixture.cs
  src/NHibernate/AdoNet/AbstractBatcher.cs
  src/NHibernate/AdoNet/GenericBatchingBatcher.cs
  src/NHibernate/AdoNet/GenericBatchingBatcherFactory.cs
  src/NHibernate/AdoNet/IEmbeddedBatcherFactoryProvider.cs
  src/NHibernate/Async/AdoNet/GenericBatchingBatcher.cs
  src/NHibernate/Dialect/Dialect.cs
  src/NHibernate/Dialect/MsSql2000Dialect.cs
  src/NHibernate/Driver/BasicResultSetsCommand.cs
  src/NHibernate/Driver/NpgsqlDriver.cs
  src/NHibernate/Driver/SqlClientDriver.cs
Labels: c: DataProviders / Dialects, p: Minor, t: New Feature

#1602 Preserve original snapshot mode.
  src/NHibernate.Test/Async/NHSpecificTest/NH1553/MsSQL/SnapshotIsolationUpdateConflictTest.cs
  src/NHibernate.Test/NHSpecificTest/NH1553/MsSQL/SnapshotIsolationUpdateConflictTest.cs
Labels: c: Tests, p: Trivial, t: Bug

#1596 GH1594: AsyncLocal leak in SystemTransactionContext
  src/NHibernate.Test/NHSpecificTest/GH1594/Entity.cs
  src/NHibernate.Test/NHSpecificTest/GH1594/ExecutionContextExtensions.cs
  src/NHibernate.Test/NHSpecificTest/GH1594/Fixture.cs
  src/NHibernate.Test/NHSpecificTest/GH1594/Mappings.hbm.xml
  src/NHibernate/Transaction/AdoNetWithSystemTransactionFactory.cs
Labels: t: Fix

#1520 NH-3606 - open a stateless session from a session
  src/NHibernate.Test/Async/SessionBuilder/Fixture.cs
  src/NHibernate.Test/Async/TransactionTest/TransactionFixture.cs
  src/NHibernate.Test/DebugSessionFactory.cs
  src/NHibernate.Test/SessionBuilder/Fixture.cs
  src/NHibernate.Test/TransactionTest/TransactionFixture.cs
  src/NHibernate/Async/ISession.cs
  src/NHibernate/Async/Impl/AbstractSessionImpl.cs
  src/NHibernate/Async/Impl/SessionImpl.cs
  src/NHibernate/Async/Impl/StatelessSessionImpl.cs
  src/NHibernate/Engine/ISessionImplementor.cs
  src/NHibernate/ISession.cs
  src/NHibernate/ISharedStatelessSessionBuilder.cs
  src/NHibernate/IStatelessSession.cs
  src/NHibernate/Impl/AbstractSessionImpl.cs
  src/NHibernate/Impl/ISharedSessionCreationOptions.cs
  src/NHibernate/Impl/SessionFactoryImpl.cs
  src/NHibernate/Impl/SessionImpl.cs
  src/NHibernate/Impl/StatelessSessionImpl.cs
Labels: t: Fix

#1476 Fix GetQueryCache storing two different caches.
  src/NHibernate.Test/Async/CacheTest/GetQueryCacheFixture.cs
  src/NHibernate.Test/CacheTest/GetQueryCacheFixture.cs
  src/NHibernate/Async/Impl/SessionFactoryImpl.cs
  src/NHibernate/Impl/SessionFactoryImpl.cs
Labels: Regression, c: Core, p: Minor, t: Bug

#1608 Missing Async test for GH1594
  src/NHibernate.Test/Async/NHSpecificTest/GH1594/Fixture.cs
Labels: c: Tests, p: Trivial, t: Task

#1607 Raise maximal decimal precision from 28 to 29
  src/NHibernate.Test/DriverTest/SqlClientDriverFixture.cs
  src/NHibernate/Cfg/Environment.cs
  src/NHibernate/Dialect/DB2Dialect.cs
  src/NHibernate/Dialect/Dialect.cs
  src/NHibernate/Dialect/InformixDialect.cs
  src/NHibernate/Dialect/IngresDialect.cs
  src/NHibernate/Dialect/MsSql2000Dialect.cs
  src/NHibernate/Dialect/MsSqlCeDialect.cs
  src/NHibernate/Dialect/MySQL5Dialect.cs
  src/NHibernate/Dialect/MySQLDialect.cs
  src/NHibernate/Dialect/Oracle8iDialect.cs
  src/NHibernate/Dialect/OracleLiteDialect.cs
  src/NHibernate/Dialect/PostgreSQLDialect.cs
  src/NHibernate/Dialect/SybaseASA9Dialect.cs
  src/NHibernate/Dialect/SybaseASE15Dialect.cs
  src/NHibernate/Dialect/SybaseSQLAnywhere10Dialect.cs
  src/NHibernate/nhibernate-configuration.xsd
Labels: t: Fix

#1489 SecondLevel QueryCache causes invalid cast
  src/NHibernate.Test/Async/CacheTest/QueryCacheFixture.cs
  src/NHibernate.Test/Async/NHSpecificTest/NH1612/NativeSqlCollectionLoaderFixture.cs
  src/NHibernate.Test/Async/NHSpecificTest/NH3666/Fixture.cs
  src/NHibernate.Test/CacheTest/QueryCacheFixture.cs
  src/NHibernate.Test/NHSpecificTest/NH1612/NativeSqlCollectionLoaderFixture.cs
  src/NHibernate.Test/NHSpecificTest/NH3666/Fixture.cs
  src/NHibernate/Async/Cache/StandardQueryCache.cs
  src/NHibernate/Async/Impl/MultiQueryImpl.cs
  src/NHibernate/Async/Loader/Criteria/CriteriaLoader.cs
  src/NHibernate/Async/Loader/Custom/CustomLoader.cs
  src/NHibernate/Async/Loader/Hql/QueryLoader.cs
  src/NHibernate/Async/Loader/Loader.cs
  src/NHibernate/Cache/StandardQueryCache.cs
  src/NHibernate/Hql/Ast/ANTLR/QueryTranslatorImpl.cs
  src/NHibernate/Impl/MultiQueryImpl.cs
  src/NHibernate/Loader/Criteria/CriteriaLoader.cs
  src/NHibernate/Loader/Custom/CustomLoader.cs
  src/NHibernate/Loader/Hql/QueryLoader.cs
  src/NHibernate/Loader/Loader.cs
  src/NHibernate/Transform/CacheableResultTransformer.cs
Labels: t: Fix

#1610 Move MsSql constants from driver to dialect.
  src/NHibernate.Test/DialectTest/MsSql2005DialectFixture.cs
  src/NHibernate/Dialect/MsSql2000Dialect.cs
  src/NHibernate/Dialect/MsSql2005Dialect.cs
  src/NHibernate/Driver/DB2400Driver.cs
  src/NHibernate/Driver/FirebirdClientDriver.cs
  src/NHibernate/Driver/MySqlDataDriver.cs
  src/NHibernate/Driver/NpgsqlDriver.cs
  src/NHibernate/Driver/OracleDataClientDriverBase.cs
  src/NHibernate/Driver/SQLite20Driver.cs
  src/NHibernate/Driver/SqlClientDriver.cs
  src/NHibernate/Driver/SqlServerCeDriver.cs
Labels: c: DataProviders / Dialects, p: Minor, t: Task

#1547 Double query translation
  src/NHibernate.Test/Async/NHSpecificTest/GH1547/Fixture.cs
  src/NHibernate.Test/NHSpecificTest/GH1547/Entity.cs
  src/NHibernate.Test/NHSpecificTest/GH1547/Fixture.cs
  src/NHibernate.Test/NHSpecificTest/GH1547/Mappings.hbm.xml
  src/NHibernate/Async/Impl/ExpressionQueryImpl.cs
  src/NHibernate/Impl/ExpressionQueryImpl.cs
  src/NHibernate/Linq/NhLinqExpression.cs
Labels: c: Core, c: Linq Provider, p: Minor, t: Improvement

#1525 5.1.0 release
  GitReleaseManager.yaml
  ReleaseProcedure.txt
  Tools/.gitignore
  Tools/packages.config
  build-common/NHibernate.props
  build-common/common.xml
  doc/reference/master.xml
  releasenotes.txt
Labels: c: Documentation, p: Minor, t: Task

#1619 Document "entity join" and "entity projection"
  doc/reference/modules/query_criteria.xml
  doc/reference/modules/query_queryover.xml
Labels: c: Documentation, p: Minor, t: Improvement

#1620 GH1149 one-to-one related object not loaded with stateless session
  src/NHibernate.Test/Async/NHSpecificTest/GH1149/Fixture.cs
  src/NHibernate.Test/NHSpecificTest/GH1149/Classes.cs
  src/NHibernate.Test/NHSpecificTest/GH1149/Fixture.cs
  src/NHibernate.Test/NHSpecificTest/GH1149/Mappings.hbm.xml
  src/NHibernate/Impl/StatelessSessionImpl.cs
Labels: t: Fix

#1621 Upgrade Async Generator to a version compatible with VS 15.6.3
  Tools/packages.config
Labels: c: Async, p: Major, t: Task

#1624 Add missing ids on documentation sections
  doc/reference/modules/query_sql.xml
Labels: c: Documentation, p: Trivial, t: Improvement
