Repository nhibernate/nhibernate-core, pull requests merged in 2018-07, with the labels that each got.

#1776 Make cache types serialization friendly
  src/NHibernate.Test/Async/CacheTest/SerializationFixture.cs
  src/NHibernate.Test/CacheTest/SerializationFixture.cs
  src/NHibernate/Action/CollectionUpdateAction.cs
  src/NHibernate/Action/EntityInsertAction.cs
  src/NHibernate/Action/EntityUpdateAction.cs
  src/NHibernate/Async/Action/CollectionUpdateAction.cs
  src/NHibernate/Async/Action/EntityInsertAction.cs
  src/NHibernate/Async/Action/EntityUpdateAction.cs
  src/NHibernate/Async/Cache/Entry/CacheEntry.cs
  src/NHibernate/Async/Cache/Entry/CollectionCacheEntry.cs
  src/NHibernate/Async/Cache/ReadWriteCache.cs
  src/NHibernate/Async/Engine/Loading/CollectionLoadContext.cs
  src/NHibernate/Async/Engine/TwoPhaseLoad.cs
  src/NHibernate/Async/Type/AnyType.cs
  src/NHibernate/Cache/CacheLock.cs
  src/NHibernate/Cache/CachedItem.cs
  src/NHibernate/Cache/Entry/CacheEntry.cs
  src/NHibernate/Cache/Entry/CollectionCacheEntry.cs
  src/NHibernate/Cache/Entry/StructuredCacheEntry.cs
  src/NHibernate/Cache/Entry/StructuredCollectionCacheEntry.cs
  src/NHibernate/Cache/Entry/StructuredMapCacheEntry.cs
  src/NHibernate/Cache/ReadWriteCache.cs
  src/NHibernate/Engine/Loading/CollectionLoadContext.cs
  src/NHibernate/Engine/TwoPhaseLoad.cs
  src/NHibernate/Type/AnyType.cs
Labels: c: Core, p: Minor, t: Improvement

#1755 Fix deletion of component with null property
  doc/reference/modules/component_mapping.xml
  src/NHibernate.Test/Async/NHSpecificTest/GH1170/Fixture.cs
  src/NHibernate.Test/NHSpecificTest/GH1170/Fixture.cs
  src/NHibernate.Test/NHSpecificTest/GH1170/Mappings.hbm.xml
  src/NHibernate.Test/NHSpecificTest/GH1170/Model.cs
  src/NHibernate/Async/Persister/Collection/AbstractCollectionPersister.cs
  src/NHibernate/Async/Persister/Collection/BasicCollectionPersister.cs
  src/NHibernate/Async/Persister/Collection/OneToManyPersister.cs
  src/NHibernate/Async/Type/IType.cs
  src/NHibernate/Persister/Collection/AbstractCollectionPersister.cs
  src/NHibernate/Persister/Collection/BasicCollectionPersister.cs
  src/NHibernate/Persister/Collection/OneToManyPersister.cs
  src/NHibernate/Type/IType.cs
  src/NHibernate/Util/ArrayHelper.cs
Labels: t: Fix

#1756 Fix unsaved-value for assigned identifiers
  src/NHibernate.Test/Async/Extralazy/ExtraLazyFixture.cs
  src/NHibernate.Test/Async/NHSpecificTest/GH1756/UnsavedValueNoneFixture.cs
  src/NHibernate.Test/Async/NHSpecificTest/NH1914/Fixture.cs
  src/NHibernate.Test/NHSpecificTest/GH1756/Entity.cs
  src/NHibernate.Test/NHSpecificTest/GH1756/Mappings.hbm.xml
  src/NHibernate.Test/NHSpecificTest/GH1756/UnsavedValueNoneFixture.cs
  src/NHibernate.Test/NHSpecificTest/NH1914/Fixture.cs
  src/NHibernate.Test/NHSpecificTest/NH1914/Mappings.hbm.xml
  src/NHibernate.Test/NHSpecificTest/NH1914/Model.cs
  src/NHibernate/Async/Persister/Entity/AbstractEntityPersister.cs
  src/NHibernate/Persister/Entity/AbstractEntityPersister.cs
Labels: c: Core, p: Minor, t: Bug

#1771 Obsolete unused "xml" type methods
  src/NHibernate.DomainModel/NHSpecific/NullableInt32Type.cs
  src/NHibernate.DomainModel/NHSpecific/NullableTypesType.cs
  src/NHibernate.Test/TypesTest/AbstractDateTimeTypeFixture.cs
  src/NHibernate/Async/Type/ByteType.cs
  src/NHibernate/Async/Type/EnumStringType.cs
  src/NHibernate/Async/Type/Int16Type.cs
  src/NHibernate/Async/Type/Int64Type.cs
  src/NHibernate/Async/Type/SerializableType.cs
  src/NHibernate/Async/Type/TicksType.cs
  src/NHibernate/Async/Type/TimeSpanType.cs
  src/NHibernate/Async/Type/UInt16Type.cs
  src/NHibernate/Async/Type/UInt32Type.cs
  src/NHibernate/Async/Type/UInt64Type.cs
  src/NHibernate/Type/AbstractBinaryType.cs
  src/NHibernate/Type/AbstractCharType.cs
  src/NHibernate/Type/AbstractDateTimeType.cs
  src/NHibernate/Type/AbstractEnumType.cs
  src/NHibernate/Type/AbstractStringType.cs
  src/NHibernate/Type/BooleanType.cs
  src/NHibernate/Type/ByteType.cs
  src/NHibernate/Type/CharBooleanType.cs
  src/NHibernate/Type/CultureInfoType.cs
  src/NHibernate/Type/CustomType.cs
  src/NHibernate/Type/DateTimeOffSetType.cs
  src/NHibernate/Type/DateType.cs
  src/NHibernate/Type/DecimalType.cs
  src/NHibernate/Type/DoubleType.cs
  src/NHibernate/Type/EnumCharType.cs
  src/NHibernate/Type/EnumStringType.cs
  src/NHibernate/Type/GuidType.cs
  src/NHibernate/Type/IIdentifierType.cs
  src/NHibernate/Type/IVersionType.cs
  src/NHibernate/Type/Int16Type.cs
  src/NHibernate/Type/Int32Type.cs
  src/NHibernate/Type/Int64Type.cs
  src/NHibernate/Type/NullableType.cs
  src/NHibernate/Type/PersistentEnumType.cs
  src/NHibernate/Type/PrimitiveType.cs
  src/NHibernate/Type/SByteType.cs
  src/NHibernate/Type/SerializableType.cs
  src/NHibernate/Type/SingleType.cs
  src/NHibernate/Type/TicksType.cs
  src/NHibernate/Type/TimeAsTimeSpanType.cs
  src/NHibernate/Type/TimeSpanType.cs
  src/NHibernate/Type/TimeType.cs
  src/NHibernate/Type/TimestampType.cs
  src/NHibernate/Type/TypeType.cs
  src/NHibernate/Type/UInt16Type.cs
  src/NHibernate/Type/UInt32Type.cs
  src/NHibernate/Type/UInt64Type.cs
  src/NHibernate/Type/UriType.cs
  src/NHibernate/Type/XDocType.cs
  src/NHibernate/Type/XmlDocType.cs
  src/NHibernate/UserTypes/IEnhancedUserType.cs
Labels: c: Core, p: Trivial, t: Task

#1785 Update user types documentation
  doc/reference/modules/basic_mapping.xml
  src/NHibernate/UserTypes/ICompositeUserType.cs
  src/NHibernate/UserTypes/IEnhancedUserType.cs
  src/NHibernate/UserTypes/ILoggableUserType.cs
  src/NHibernate/UserTypes/IUserType.cs
Labels: c: Documentation, p: Trivial, t: Improvement

#1786 Document future results
  doc/reference/modules/performance.xml
  doc/reference/modules/query_linq.xml
Labels: c: Documentation, p: Minor, t: New Feature

#1789 Fix shortcomings of QueryBatcher initial implementation
  src/NHibernate.Test/Async/Futures/QueryBatchFixture.cs
  src/NHibernate.Test/Futures/QueryBatchFixture.cs
  src/NHibernate/Async/Multi/IQueryBatchItem.cs
  src/NHibernate/Async/Multi/QueryBatch.cs
  src/NHibernate/Async/Multi/QueryBatchItemBase.cs
  src/NHibernate/Multi/IQueryBatchItem.cs
  src/NHibernate/Multi/QueryBatch.cs
  src/NHibernate/Multi/QueryBatchItemBase.cs
Labels: c: Core, p: Major, t: Bug

#1790 Fix SQLite/SqlCE validation failure on tables with a schema
  src/NHibernate.Test/Async/Tools/hbm2ddl/SchemaValidator/SchemaValidateTableWithSchemaFixture.cs
  src/NHibernate.Test/Tools/hbm2ddl/SchemaValidator/SchemaValidateTableWithSchemaFixture.cs
  src/NHibernate.Test/Tools/hbm2ddl/SchemaValidator/VersionWithSchema.hbm.xml
  src/NHibernate/Dialect/MsSqlCeDialect.cs
  src/NHibernate/Dialect/SQLiteDialect.cs
  src/NHibernate/Dialect/Schema/AbstractDataBaseSchema.cs
  src/NHibernate/Dialect/Schema/MsSqlCeMetaData.cs
  src/NHibernate/Dialect/Schema/SQLiteMetaData.cs
Labels: t: Fix

#1792 Obsolete HolderInstantiator
  src/NHibernate/Async/Loader/Hql/QueryLoader.cs
  src/NHibernate/Hql/HolderInstantiator.cs
  src/NHibernate/Impl/EnumerableImpl.cs
  src/NHibernate/Loader/Custom/CustomLoader.cs
  src/NHibernate/Loader/Hql/QueryLoader.cs
Labels: c: Core, p: Trivial, r: Fixed, t: Improvement

#1788 Implement multiple get and put for query cache and query batch
  Tools/packages.config
  src/AsyncGenerator.yml
  src/NHibernate.Test/Async/CacheTest/BatchableCacheFixture.cs
  src/NHibernate.Test/Async/TransformTests/AliasToBeanResultTransformerFixture.cs
  src/NHibernate.Test/CacheTest/BatchableCacheFixture.cs
  src/NHibernate/Async/Cache/CacheBatcher.cs
  src/NHibernate/Async/Cache/IQueryCache.cs
  src/NHibernate/Async/Cache/StandardQueryCache.cs
  src/NHibernate/Async/Cache/UpdateTimestampsCache.cs
  src/NHibernate/Async/Impl/MultiCriteriaImpl.cs
  src/NHibernate/Async/Impl/MultiQueryImpl.cs
  src/NHibernate/Async/Impl/MultipleQueriesCacheAssembler.cs
  src/NHibernate/Async/Loader/Loader.cs
  src/NHibernate/Async/Multi/CriteriaBatchItem.cs
  src/NHibernate/Async/Multi/IQueryBatchItem.cs
  src/NHibernate/Async/Multi/QueryBatch.cs
  src/NHibernate/Async/Multi/QueryBatchItemBase.cs
  src/NHibernate/Cache/CacheBatcher.cs
  src/NHibernate/Cache/IQueryCache.cs
  src/NHibernate/Cache/StandardQueryCache.cs
  src/NHibernate/Cache/UpdateTimestampsCache.cs
  src/NHibernate/Impl/MultiCriteriaImpl.cs
  src/NHibernate/Impl/MultiQueryImpl.cs
  src/NHibernate/Impl/MultipleQueriesCacheAssembler.cs
  src/NHibernate/Loader/Loader.cs
  src/NHibernate/Multi/CriteriaBatchItem.cs
  src/NHibernate/Multi/ICachingInformation.cs
  src/NHibernate/Multi/IQueryBatchItem.cs
  src/NHibernate/Multi/QueryBatch.cs
  src/NHibernate/Multi/QueryBatchItem.cs
  src/NHibernate/Multi/QueryBatchItemBase.cs
Labels: c: Core, p: Minor, t: Improvement

#1794 Add support for ElementAt/IList indexer for indexed collections in Linq queries
  src/NHibernate.Test/Async/NHSpecificTest/GH0819/Fixture.cs
  src/NHibernate.Test/NHSpecificTest/GH0819/Fixture.cs
  src/NHibernate.Test/NHSpecificTest/GH0819/Model.cs
  src/NHibernate/Hql/Ast/HqlTreeBuilder.cs
  src/NHibernate/Hql/Ast/HqlTreeNode.cs
  src/NHibernate/Linq/Functions/DefaultLinqToHqlGeneratorsRegistry.cs
  src/NHibernate/Linq/Functions/DictionaryGenerator.cs
  src/NHibernate/Linq/Functions/ListIndexerGenerator.cs
Labels: t: Fix

#1797 Fix NoViableAltException with boolean expression in OrderBy clause
  src/NHibernate.Test/Async/Linq/ByMethod/OrderByTests.cs
  src/NHibernate.Test/Linq/ByMethod/OrderByTests.cs
  src/NHibernate/Linq/Visitors/QueryModelVisitor.cs
Labels: t: Fix

#1800 Fix the proxy factory factory value in documentation
  doc/reference/modules/configuration.xml
Labels: c: Documentation, p: Trivial, t: Bug

#1783 Obsolete MultiQuery and MultiCriteria
  doc/reference/modules/performance.xml
  src/NHibernate.Test/Async/Criteria/Lambda/IntegrationFixture.cs
  src/NHibernate.Test/Async/NHSpecificTest/DataReaderWrapperTest/Fixture.cs
  src/NHibernate.Test/Async/NHSpecificTest/NH1253/Fixture.cs
  src/NHibernate.Test/Async/NHSpecificTest/NH1508/Fixture.cs
  src/NHibernate.Test/Async/NHSpecificTest/NH1609/Fixture.cs
  src/NHibernate.Test/Async/NHSpecificTest/NH1836/Fixture.cs
  src/NHibernate.Test/Async/NHSpecificTest/NH1869/Fixture.cs
  src/NHibernate.Test/Async/NHSpecificTest/NH2195/SQLiteMultiCriteriaTest.cs
  src/NHibernate.Test/Async/NHSpecificTest/NH2201/Fixture.cs
  src/NHibernate.Test/Async/NHSpecificTest/NH2959/Fixture.cs
  src/NHibernate.Test/Async/NHSpecificTest/SqlConverterAndMultiQuery/Fixture.cs
  src/NHibernate.Test/Async/Pagination/CustomDialectFixture.cs
  src/NHibernate.Test/Async/QueryTest/MultiCriteriaFixture.cs
  src/NHibernate.Test/Async/QueryTest/MultipleMixedQueriesFixture.cs
  src/NHibernate.Test/Async/QueryTest/MultipleQueriesFixture.cs
  src/NHibernate.Test/Async/QueryTest/QueryBatchFixture.cs
  src/NHibernate.Test/Async/Stats/StatsFixture.cs
  src/NHibernate.Test/Criteria/Lambda/IntegrationFixture.cs
  src/NHibernate.Test/NHSpecificTest/DataReaderWrapperTest/Fixture.cs
  src/NHibernate.Test/NHSpecificTest/NH1253/Fixture.cs
  src/NHibernate.Test/NHSpecificTest/NH1508/Fixture.cs
  src/NHibernate.Test/NHSpecificTest/NH1609/Fixture.cs
  src/NHibernate.Test/NHSpecificTest/NH1836/Fixture.cs
  src/NHibernate.Test/NHSpecificTest/NH1869/Fixture.cs
  src/NHibernate.Test/NHSpecificTest/NH2195/SQLiteMultiCriteriaTest.cs
  src/NHibernate.Test/NHSpecificTest/NH2201/Fixture.cs
  src/NHibernate.Test/NHSpecificTest/NH2959/Fixture.cs
  src/NHibernate.Test/NHSpecificTest/SqlConverterAndMultiQuery/Fixture.cs
  src/NHibernate.Test/Pagination/CustomDialectFixture.cs
  src/NHibernate.Test/QueryTest/MultiCriteriaFixture.cs
  src/NHibernate.Test/QueryTest/MultipleMixedQueriesFixture.cs
  src/NHibernate.Test/QueryTest/MultipleQueriesFixture.cs
  src/NHibernate.Test/QueryTest/QueryBatchFixture.cs
  src/NHibernate.Test/Stats/StatsFixture.cs
  src/NHibernate/Async/Impl/MultipleQueriesCacheAssembler.cs
  src/NHibernate/IMultiCriteria.cs
  src/NHibernate/IMultiQuery.cs
  src/NHibernate/ISession.cs
  src/NHibernate/Impl/MultiCriteriaImpl.cs
  src/NHibernate/Impl/MultiQueryImpl.cs
  src/NHibernate/Impl/MultipleQueriesCacheAssembler.cs
  src/NHibernate/Impl/SessionImpl.cs
Labels: c: Core, p: Minor, t: Task

#1796 Support CacheMode in QueryBatch
  src/NHibernate.Test/Async/Futures/QueryBatchFixture.cs
  src/NHibernate.Test/Futures/QueryBatchFixture.cs
  src/NHibernate/Async/Cache/StandardQueryCache.cs
  src/NHibernate/Async/Event/Default/DefaultDeleteEventListener.cs
  src/NHibernate/Async/Loader/Loader.cs
  src/NHibernate/Async/Multi/QueryBatchItemBase.cs
  src/NHibernate/Cache/StandardQueryCache.cs
  src/NHibernate/Engine/ISessionImplementor.cs
  src/NHibernate/Engine/QueryParameters.cs
  src/NHibernate/Event/Default/DefaultDeleteEventListener.cs
  src/NHibernate/Impl/AbstractQueryImpl.cs
  src/NHibernate/Impl/CriteriaImpl.cs
  src/NHibernate/Loader/Criteria/CriteriaQueryTranslator.cs
  src/NHibernate/Loader/Loader.cs
  src/NHibernate/Multi/QueryBatchItemBase.cs
Labels: c: Core, p: Trivial, t: New Feature

#1802 Generate stable sql objects names
  src/NHibernate.Test/MappingTest/TableFixture.cs
  src/NHibernate.Test/NHSpecificTest/NH1399/Fixture.cs
  src/NHibernate/Cfg/Configuration.cs
  src/NHibernate/Mapping/Constraint.cs
  src/NHibernate/Mapping/DenormalizedTable.cs
  src/NHibernate/Mapping/ForeignKey.cs
  src/NHibernate/Mapping/Table.cs
  src/NHibernate/Util/Hasher.cs
Labels: possible breaking change, t: Fix

#1803 Fix HQL and LINQ query by a type on <any/> with meta-types other than int
  src/NHibernate.Test/Async/NHSpecificTest/NH2328/Fixture.cs
  src/NHibernate.Test/NHSpecificTest/GH1774/Class/ClassMetaTypeFixture.cs
  src/NHibernate.Test/NHSpecificTest/GH1774/Class/Mappings.hbm.xml
  src/NHibernate.Test/NHSpecificTest/GH1774/FixtureBase.cs
  src/NHibernate.Test/NHSpecificTest/GH1774/Implicit/ImplicitMetaTypeFixture.cs
  src/NHibernate.Test/NHSpecificTest/GH1774/Implicit/Mappings.hbm.xml
  src/NHibernate.Test/NHSpecificTest/GH1774/Int32/Int32MetaTypeFixture.cs
  src/NHibernate.Test/NHSpecificTest/GH1774/Int32/Mappings.hbm.xml
  src/NHibernate.Test/NHSpecificTest/GH1774/Model.cs
  src/NHibernate.Test/NHSpecificTest/GH1774/String/Mappings.hbm.xml
  src/NHibernate.Test/NHSpecificTest/GH1774/String/StringMetaTypeFixture.cs
  src/NHibernate/Async/Type/MetaType.cs
  src/NHibernate/Hql/Ast/ANTLR/Tree/BinaryLogicOperatorNode.cs
  src/NHibernate/Type/ClassMetaType.cs
  src/NHibernate/Type/IMetaType.cs
  src/NHibernate/Type/MetaType.cs
Labels: t: Fix

#1806 Fix InvalidCastException in Linq when casting a field to Enum when type of a field is different to Enum's underlying type
  src/NHibernate.Test/Async/NHSpecificTest/GH1121/Fixture.cs
  src/NHibernate.Test/NHSpecificTest/GH1121/Entity.cs
  src/NHibernate.Test/NHSpecificTest/GH1121/Fixture.cs
  src/NHibernate.Test/NHSpecificTest/GH1121/Mappings.hbm.xml
  src/NHibernate/Linq/Visitors/SelectClauseVisitor.cs
Labels: r: Fixed, t: Fix

#1809 Update the <any /> mapping documentation
  doc/reference/modules/basic_mapping.xml
  doc/reference/modules/collection_mapping.xml
Labels: c: Documentation, p: Minor, t: Bug

#1813 Add support for String indexer property
  src/NHibernate.Test/Async/Linq/FunctionTests.cs
  src/NHibernate.Test/Linq/FunctionTests.cs
  src/NHibernate/Linq/Functions/DefaultLinqToHqlGeneratorsRegistry.cs
  src/NHibernate/Linq/Functions/StringGenerator.cs
  src/NHibernate/Util/ReflectHelper.cs
Labels: t: Fix

#1781 Clean-up IObjectsFactory usages
  src/NHibernate.Test/Bytecode/ActivatorObjectFactoryFixture.cs
  src/NHibernate.Test/ConnectionTest/CustomCurrentSessionTest.cs
  src/NHibernate.Test/ConnectionTest/MapBasedSessionContextFixture.cs
  src/NHibernate.Test/ConnectionTest/ThreadLocalCurrentSessionTest.cs
  src/NHibernate/Async/Tool/hbm2ddl/SchemaExport.cs
  src/NHibernate/Bytecode/ActivatorObjectsFactory.cs
  src/NHibernate/Bytecode/IObjectsFactory.cs
  src/NHibernate/Context/AsyncLocalSessionContext.cs
  src/NHibernate/Context/CurrentSessionContext.cs
  src/NHibernate/Context/ICurrentSessionContext.cs
  src/NHibernate/Context/MapBasedSessionContext.cs
  src/NHibernate/Context/WcfOperationSessionContext.cs
  src/NHibernate/Context/WebSessionContext.cs
  src/NHibernate/Impl/SessionFactoryImpl.cs
  src/NHibernate/Tool/hbm2ddl/SchemaExport.cs
  src/NHibernate/Transform/AliasToBeanResultTransformer.cs
  src/NHibernate/Tuple/PocoInstantiator.cs
Labels: c: Core, p: Minor, possible breaking change, t: Improvement

#1816 Remove copy-paste remnants from FieldInterceptorProxyBuilder
  src/NHibernate/Proxy/FieldInterceptorProxyBuilder.cs
  src/NHibernate/Proxy/ProxyBuilderHelper.cs
Labels: c: ByteCode providers, p: Trivial, t: Fix

#1814 Mark proxy assembly with IgnoresAccessChecksToAttribute to allow implementing non public interfaces
  src/NHibernate/Proxy/NHibernateProxyBuilder.cs
  src/NHibernate/Proxy/ProxyBuilderHelper.cs
  src/NHibernate/Util/IgnoresAccessChecksToAttribute.cs
Labels: c: ByteCode providers, p: Minor, t: Improvement

#1817 Fix SchemaValidator failing for PostgreSql sequences
  src/NHibernate.Test/Async/NHSpecificTest/GH1163/Fixture.cs
  src/NHibernate.Test/NHSpecificTest/GH1163/Account.cs
  src/NHibernate.Test/NHSpecificTest/GH1163/Fixture.cs
  src/NHibernate/Dialect/PostgreSQLDialect.cs
Labels: t: Fix
