Repository nhibernate/nhibernate-core, pull requests merged in 2019-03, with the labels that each got.

#2025 Port HQL Entity Join
  src/NHibernate.Test/Async/Hql/EntityJoinHqlTest.cs
  src/NHibernate.Test/Hql/EntityJoinHqlTest.cs
  src/NHibernate.Test/Hql/EntityJoinHqlTestEntities.cs
  src/NHibernate/Engine/JoinSequence.cs
  src/NHibernate/Hql/Ast/ANTLR/HqlSqlWalker.cs
  src/NHibernate/Hql/Ast/ANTLR/HqlSqlWalker.g
  src/NHibernate/Hql/Ast/ANTLR/SqlGenerator.cs
  src/NHibernate/Hql/Ast/ANTLR/SqlGenerator.g
  src/NHibernate/Hql/Ast/ANTLR/Tree/EntityJoinFromElement.cs
  src/NHibernate/Hql/Ast/ANTLR/Tree/EntityJoinJoinSequenceImpl.cs
  src/NHibernate/Hql/Ast/ANTLR/Tree/FromClause.cs
  src/NHibernate/Hql/Ast/ANTLR/Tree/FromElement.cs
  src/NHibernate/Hql/Ast/ANTLR/Tree/HqlSqlWalkerNode.cs
  src/NHibernate/Hql/QuerySplitter.cs
Labels: t: Fix

#2030 Release 5.2.4
  appveyor.yml
  build-common/NHibernate.props
  build-common/common.xml
  releasenotes.txt
Labels: c: Core, p: Minor, t: Task

#2024 Refactor to simplify netfx retargeting
  build-common/NHibernate.props
  default.build
  src/NHibernate.DomainModel/NHibernate.DomainModel.csproj
  src/NHibernate.Test.VisualBasic/NHibernate.Test.VisualBasic.vbproj
  src/NHibernate.Test/NHibernate.Test.csproj
  src/NHibernate.TestDatabaseSetup/NHibernate.TestDatabaseSetup.csproj
  src/NHibernate/NHibernate.csproj
Labels: c: Toolset, p: Trivial, t: Improvement

#2038 Fix a typo on the memcached distributed cache description in the docs
  doc/reference/modules/nhibernate_caches.xml
Labels: c: Documentation, p: Trivial, t: Bug

#2042 Fix missing cast when comparing a guid and string column in Sql Server
  src/NHibernate.Test/Async/NHSpecificTest/NH3426/Fixture.cs
  src/NHibernate.Test/NHSpecificTest/NH3426/Fixture.cs
  src/NHibernate/Dialect/MsSql2000Dialect.cs
  src/NHibernate/Dialect/MsSqlCeDialect.cs
Labels: t: Fix

#2032 Allow using ON instead of WITH in hql
  src/NHibernate.Test/Async/Hql/EntityJoinHqlTest.cs
  src/NHibernate.Test/Hql/EntityJoinHqlTest.cs
  src/NHibernate/Hql/Ast/ANTLR/Hql.g
  src/NHibernate/Hql/Ast/ANTLR/HqlSqlWalker.cs
Labels: c: Core, p: Minor, t: Improvement

#2046 Nullable Guid ToString does not produce correct code on some dialects
  src/NHibernate.Test/Async/NHSpecificTest/NH3426/Fixture.cs
  src/NHibernate.Test/NHSpecificTest/NH3426/Fixture.cs
  src/NHibernate/Linq/Functions/StringGenerator.cs
Labels: c: Linq Provider, p: Trivial, t: Bug

#1948 Fix SELECT N+1 for not-found=ignore
  src/NHibernate.Test/Async/NHSpecificTest/NH1001/Fixture.cs
  src/NHibernate.Test/NHSpecificTest/NH1001/Address.cs
  src/NHibernate.Test/NHSpecificTest/NH1001/Department.cs
  src/NHibernate.Test/NHSpecificTest/NH1001/Employee.cs
  src/NHibernate.Test/NHSpecificTest/NH1001/Fixture.cs
  src/NHibernate.Test/NHSpecificTest/NH1001/Mappings.hbm.xml
  src/NHibernate.Test/NHSpecificTest/NH1001/Phone.cs
  src/NHibernate/Async/Loader/Loader.cs
  src/NHibernate/Cfg/XmlHbmBinding/PropertiesBinder.cs
  src/NHibernate/Loader/Hql/QueryLoader.cs
  src/NHibernate/Loader/Loader.cs
  src/NHibernate/Loader/OuterJoinableAssociation.cs
  src/NHibernate/Mapping/ManyToOne.cs
  src/NHibernate/Mapping/OneToMany.cs
  src/NHibernate/Type/ManyToOneType.cs
  src/NHibernate/Type/TypeFactory.cs
Labels: t: Fix

#2048 Fix unexpected order by clause in a criteria with projections
  src/NHibernate.Test/Async/NHSpecificTest/NH1761/FixtureByCode.cs
  src/NHibernate.Test/NHSpecificTest/NH1761/FixtureByCode.cs
  src/NHibernate/Loader/AbstractEntityJoinWalker.cs
Labels: t: Fix

#1955 Optimize batchable cache calls for cached queries
  src/NHibernate.Test/Async/CacheTest/BatchableCacheFixture.cs
  src/NHibernate.Test/CacheTest/BatchableCacheFixture.cs
  src/NHibernate/Async/Cache/StandardQueryCache.cs
  src/NHibernate/Async/Engine/BatchFetchQueue.cs
  src/NHibernate/Async/Engine/Loading/CollectionLoadContext.cs
  src/NHibernate/Async/Event/Default/DefaultInitializeCollectionEventListener.cs
  src/NHibernate/Async/Event/Default/DefaultLoadEventListener.cs
  src/NHibernate/Async/Loader/Loader.cs
  src/NHibernate/Async/Type/CollectionType.cs
  src/NHibernate/Async/Type/ManyToOneType.cs
  src/NHibernate/Cache/StandardQueryCache.cs
  src/NHibernate/Engine/BatchFetchQueue.cs
  src/NHibernate/Engine/Loading/CollectionLoadContext.cs
  src/NHibernate/Engine/QueryCacheBatchQueue.cs
  src/NHibernate/Event/Default/DefaultInitializeCollectionEventListener.cs
  src/NHibernate/Event/Default/DefaultLoadEventListener.cs
  src/NHibernate/Loader/Loader.cs
  src/NHibernate/Type/CollectionType.cs
  src/NHibernate/Type/ManyToOneType.cs
Labels: c: Core, p: Minor, t: Improvement

#2034 Throw for DML on filter
  src/NHibernate.Test/Async/LinqBulkManipulation/Fixture.cs
  src/NHibernate.Test/LinqBulkManipulation/Fixture.cs
  src/NHibernate/Async/Linq/DefaultQueryProvider.cs
  src/NHibernate/Linq/DefaultQueryProvider.cs
Labels: t: Fix

#2063 Do missing async generation for cache batch optimization
  src/NHibernate/Async/Event/Default/DefaultInitializeCollectionEventListener.cs
  src/NHibernate/Async/Event/Default/DefaultLoadEventListener.cs
Labels: r: Fixed, t: Fix

#2062 Fix invalid DML statements for static where in mapping
  src/NHibernate.Test/Async/NHSpecificTest/GH2053/Fixture.cs
  src/NHibernate.Test/NHSpecificTest/GH2053/Entity.cs
  src/NHibernate.Test/NHSpecificTest/GH2053/Fixture.cs
  src/NHibernate.Test/NHSpecificTest/GH2053/Mappings.hbm.xml
  src/NHibernate/Persister/Collection/AbstractCollectionPersister.cs
  src/NHibernate/Persister/Entity/AbstractEntityPersister.cs
  src/NHibernate/Persister/Entity/AbstractPropertyMapping.cs
  src/NHibernate/SqlCommand/InFragment.cs
  src/NHibernate/SqlCommand/SelectFragment.cs
  src/NHibernate/SqlCommand/Template.cs
Labels: t: Fix

#2045 Fix transient detection for proxy
  src/NHibernate.Test/Async/NHSpecificTest/GH2043/Fixture.cs
  src/NHibernate.Test/NHSpecificTest/GH2043/EntityAssigned.cs
  src/NHibernate.Test/NHSpecificTest/GH2043/EntityWithAssignedBag.cs
  src/NHibernate.Test/NHSpecificTest/GH2043/EntityWithClassLookup.cs
  src/NHibernate.Test/NHSpecificTest/GH2043/EntityWithClassProxyDefinition.cs
  src/NHibernate.Test/NHSpecificTest/GH2043/EntityWithInterfaceLookup.cs
  src/NHibernate.Test/NHSpecificTest/GH2043/EntityWithInterfaceProxyDefinition.cs
  src/NHibernate.Test/NHSpecificTest/GH2043/Fixture.cs
  src/NHibernate.Test/NHSpecificTest/GH2043/IEntityProxy.cs
  src/NHibernate/Async/Engine/ForeignKeys.cs
  src/NHibernate/Engine/ForeignKeys.cs
Labels: t: Fix

#2069 Fix transient detection for proxy (#2045)
  src/NHibernate.Test/Async/NHSpecificTest/GH2043/Fixture.cs
  src/NHibernate.Test/NHSpecificTest/GH2043/EntityAssigned.cs
  src/NHibernate.Test/NHSpecificTest/GH2043/EntityWithAssignedBag.cs
  src/NHibernate.Test/NHSpecificTest/GH2043/EntityWithClassLookup.cs
  src/NHibernate.Test/NHSpecificTest/GH2043/EntityWithClassProxyDefinition.cs
  src/NHibernate.Test/NHSpecificTest/GH2043/EntityWithInterfaceLookup.cs
  src/NHibernate.Test/NHSpecificTest/GH2043/EntityWithInterfaceProxyDefinition.cs
  src/NHibernate.Test/NHSpecificTest/GH2043/Fixture.cs
  src/NHibernate.Test/NHSpecificTest/GH2043/IEntityProxy.cs
  src/NHibernate/Async/Engine/ForeignKeys.cs
  src/NHibernate/Engine/ForeignKeys.cs
Labels: t: Fix

#2068 Fix transient detection for proxy (#2045)
  src/NHibernate.Test/Async/NHSpecificTest/GH2043/Fixture.cs
  src/NHibernate.Test/NHSpecificTest/GH2043/EntityAssigned.cs
  src/NHibernate.Test/NHSpecificTest/GH2043/EntityWithAssignedBag.cs
  src/NHibernate.Test/NHSpecificTest/GH2043/EntityWithClassLookup.cs
  src/NHibernate.Test/NHSpecificTest/GH2043/EntityWithClassProxyDefinition.cs
  src/NHibernate.Test/NHSpecificTest/GH2043/EntityWithInterfaceLookup.cs
  src/NHibernate.Test/NHSpecificTest/GH2043/EntityWithInterfaceProxyDefinition.cs
  src/NHibernate.Test/NHSpecificTest/GH2043/Fixture.cs
  src/NHibernate.Test/NHSpecificTest/GH2043/IEntityProxy.cs
  src/NHibernate/Async/Engine/ForeignKeys.cs
  src/NHibernate/Engine/ForeignKeys.cs
Labels: t: Fix

#2075 Missing cast when comparing a guid and string columns in SAP SQL Anywhere
  src/NHibernate/Dialect/SapSQLAnywhere17Dialect.cs
Labels: c: DataProviders / Dialects, p: Minor, t: Bug

#2078 Avoid unnecessary join for entity comparisons in with clause
  src/NHibernate.Test/Async/Hql/EntityJoinHqlTest.cs
  src/NHibernate.Test/Hql/EntityJoinHqlTest.cs
  src/NHibernate/Hql/Ast/ANTLR/Tree/DotNode.cs
Labels: c: Core, p: Minor, r: Fixed, t: Improvement

#2039 Use generic CollectingNodeVisitor in hql parser
  src/NHibernate/Hql/Ast/ANTLR/HqlSqlWalker.cs
  src/NHibernate/Hql/Ast/ANTLR/QueryTranslatorImpl.cs
  src/NHibernate/Hql/Ast/ANTLR/Tree/AssignmentSpecification.cs
  src/NHibernate/Hql/Ast/ANTLR/Tree/FromClause.cs
  src/NHibernate/Hql/Ast/ANTLR/Tree/IdentNode.cs
  src/NHibernate/Hql/Ast/ANTLR/Tree/SelectClause.cs
  src/NHibernate/Hql/Ast/ANTLR/Util/ASTUtil.cs
  src/NHibernate/Hql/Ast/ANTLR/Util/CollectingNodeVisitor.cs
  src/NHibernate/Hql/Ast/ANTLR/Util/JoinProcessor.cs
Labels: c: Core, p: Minor, t: Improvement

#2076 Add ability to set extending entity name for subclasses in mapping by code
  src/NHibernate.Test/NHSpecificTest/GH2071/Domain.cs
  src/NHibernate.Test/NHSpecificTest/GH2071/Fixture.cs
  src/NHibernate/Mapping/ByCode/IJoinedSubclassMapper.cs
  src/NHibernate/Mapping/ByCode/ISubclassMapper.cs
  src/NHibernate/Mapping/ByCode/IUnionSubclassMapper.cs
  src/NHibernate/Mapping/ByCode/Impl/CustomizersImpl/JoinedSubclassCustomizer.cs
  src/NHibernate/Mapping/ByCode/Impl/CustomizersImpl/SubclassCustomizer.cs
  src/NHibernate/Mapping/ByCode/Impl/CustomizersImpl/UnionSubclassCustomizer.cs
  src/NHibernate/Mapping/ByCode/Impl/JoinedSubclassMapper.cs
  src/NHibernate/Mapping/ByCode/Impl/SubclassMapper.cs
  src/NHibernate/Mapping/ByCode/Impl/UnionSubclassMapper.cs
Labels: t: Fix

#476 Eliminated double Persister resolution in Loader.InstanceNotYetLoaded flow
  src/NHibernate/Async/Loader/Loader.cs
  src/NHibernate/Async/Persister/Entity/AbstractEntityPersister.cs
  src/NHibernate/Async/Persister/Entity/ILoadable.cs
  src/NHibernate/Engine/ISessionImplementor.cs
  src/NHibernate/Event/IEventSource.cs
  src/NHibernate/Impl/AbstractSessionImpl.cs
  src/NHibernate/Impl/SessionImpl.cs
  src/NHibernate/Impl/StatelessSessionImpl.cs
  src/NHibernate/Loader/Loader.cs
  src/NHibernate/Persister/Entity/AbstractEntityPersister.cs
  src/NHibernate/Persister/Entity/ILoadable.cs
Labels: t: Improvement

#2058 DB2 dialect enhancements
  src/NHibernate.Test/DialectTest/FunctionTests/SubstringSupportFixture.cs
  src/NHibernate/Dialect/DB2Dialect.cs
  src/NHibernate/Dialect/Schema/DB2MetaData.cs
  src/NHibernate/Driver/DB2DriverBase.cs
  src/NHibernate/Type/ByteType.cs
Labels: c: DataProviders / Dialects, p: Major, t: Improvement

#2080 Add ability to set custom collection type as a string in mapping by code
  src/NHibernate.Test/MappingByCode/MappersTests/IdBagMapperTest.cs
  src/NHibernate.Test/UserCollection/Parameterized/ParameterizedUserCollectionTypeByCodeFixture.cs
  src/NHibernate/Mapping/ByCode/ICollectionPropertiesMapper.cs
  src/NHibernate/Mapping/ByCode/Impl/BagMapper.cs
  src/NHibernate/Mapping/ByCode/Impl/CustomizersImpl/CollectionPropertiesCustomizer.cs
  src/NHibernate/Mapping/ByCode/Impl/IdBagMapper.cs
  src/NHibernate/Mapping/ByCode/Impl/ListMapper.cs
  src/NHibernate/Mapping/ByCode/Impl/MapMapper.cs
  src/NHibernate/Mapping/ByCode/Impl/SetMapper.cs
Labels: c: Mapping by Code, p: Minor, t: New Feature

#2070 Fix determination of interface proxies
  src/NHibernate.Test/Async/NHSpecificTest/GH2067/Fixture.cs
  src/NHibernate.Test/NHSpecificTest/GH2067/Domain.cs
  src/NHibernate.Test/NHSpecificTest/GH2067/Fixture.cs
  src/NHibernate.Test/StaticProxyTest/StaticProxyFactoryFixture.cs
  src/NHibernate/Proxy/AbstractProxyFactory.cs
  src/NHibernate/Proxy/IProxyFactory.cs
  src/NHibernate/Proxy/Map/MapProxyFactory.cs
  src/NHibernate/Proxy/NHibernateProxyFactoryInfo.cs
  src/NHibernate/Proxy/StaticProxyFactory.cs
  src/NHibernate/Tuple/Entity/DynamicMapEntityTuplizer.cs
  src/NHibernate/Tuple/Entity/PocoEntityTuplizer.cs
Labels: t: Fix

#2073 Release 5.0.7
  build-common/NHibernate.props
  build-common/common.xml
  releasenotes.txt
Labels: c: Documentation, p: Minor, t: Task

#2074 Release 5.1.5
  appveyor.yml
  build-common/NHibernate.props
  build-common/common.xml
  releasenotes.txt
Labels: c: Documentation, p: Minor, t: Task

#2084 Improve one-to-one handling in queries
  src/NHibernate.Test/Associations/OneToOneFixture.cs
  src/NHibernate.Test/Async/Associations/OneToOneFixture.cs
  src/NHibernate/Async/Param/AbstractExplicitParameterSpecification.cs
  src/NHibernate/Async/Type/IType.cs
  src/NHibernate/Async/Type/OneToOneType.cs
  src/NHibernate/Mapping/SimpleValue.cs
  src/NHibernate/Param/AbstractExplicitParameterSpecification.cs
  src/NHibernate/Persister/Entity/AbstractPropertyMapping.cs
  src/NHibernate/Type/EntityType.cs
  src/NHibernate/Type/IType.cs
  src/NHibernate/Type/OneToOneType.cs
  src/NHibernate/Type/SpecialOneToOneType.cs
Labels: c: Core, p: Major, t: Improvement

#2091 Obsolete StringHelper.Join
  src/NHibernate/Criterion/ConditionalProjection.cs
  src/NHibernate/Criterion/IdentifierProjection.cs
  src/NHibernate/Criterion/Junction.cs
  src/NHibernate/Criterion/PropertyProjection.cs
  src/NHibernate/Dialect/InformixDialect.cs
  src/NHibernate/Dialect/MsSql2000Dialect.cs
  src/NHibernate/Dialect/Oracle8iDialect.cs
  src/NHibernate/Engine/SubselectFetch.cs
  src/NHibernate/Hql/Ast/ANTLR/Exec/AbstractStatementExecutor.cs
  src/NHibernate/Hql/Ast/ANTLR/Exec/MultiTableDeleteExecutor.cs
  src/NHibernate/Hql/Ast/ANTLR/Exec/MultiTableUpdateExecutor.cs
  src/NHibernate/Hql/Ast/ANTLR/Tree/DotNode.cs
  src/NHibernate/Hql/Ast/ANTLR/Tree/FromElement.cs
  src/NHibernate/Hql/Ast/ANTLR/Tree/IdentNode.cs
  src/NHibernate/Hql/CollectionSubqueryFactory.cs
  src/NHibernate/Loader/Collection/CollectionJoinWalker.cs
  src/NHibernate/Loader/Custom/ColumnCollectionAliases.cs
  src/NHibernate/Loader/GeneratedCollectionAliases.cs
  src/NHibernate/Mapping/ForeignKey.cs
  src/NHibernate/Persister/Entity/AbstractEntityPersister.cs
  src/NHibernate/Util/StringHelper.cs
Labels: c: Core, p: Trivial, r: Fixed, t: Improvement

#2086 Release 5.2.5
  appveyor.yml
  build-common/NHibernate.props
  build-common/common.xml
  releasenotes.txt
Labels: c: Documentation, p: Minor, t: Task
