Repository nhibernate/nhibernate-core, pull requests merged in 2019-05, with the labels that each got.

#2126 Update AsyncGenerator to 0.14.0
  Tools/packages.config
  src/AsyncGenerator.yml
  src/NHibernate.Test/Async/Ado/BatcherFixture.cs
  src/NHibernate.Test/Async/CacheTest/BatchableCacheFixture.cs
  src/NHibernate.Test/Async/Component/Basic/ComponentTest.cs
  src/NHibernate.Test/Async/Criteria/CriteriaQueryTest.cs
  src/NHibernate.Test/Async/FetchLazyProperties/FetchLazyPropertiesFixture.cs
  src/NHibernate.Test/Async/Generatedkeys/Identity/IdentityGeneratedKeysTest.cs
  src/NHibernate.Test/Async/GhostProperty/GhostPropertyFixture.cs
  src/NHibernate.Test/Async/Hql/Ast/HqlFixture.cs
  src/NHibernate.Test/Async/Hql/EntityJoinHqlTest.cs
  src/NHibernate.Test/Async/Hql/HQLFunctions.cs
  src/NHibernate.Test/Async/LazyGroup/LazyGroupFixture.cs
  src/NHibernate.Test/Async/LazyProperty/LazyPropertyFixture.cs
  src/NHibernate.Test/Async/Legacy/ABCProxyTest.cs
  src/NHibernate.Test/Async/Legacy/SQLFunctionsTest.cs
  src/NHibernate.Test/Async/Legacy/SQLLoaderTest.cs
  src/NHibernate.Test/Async/Linq/BooleanMethodExtensionExample.cs
  src/NHibernate.Test/Async/Linq/ByMethod/CastTests.cs
  src/NHibernate.Test/Async/Linq/ConstantTest.cs
  src/NHibernate.Test/Async/Linq/JoinTests.cs
  src/NHibernate.Test/Async/Linq/LinqQuerySamples.cs
  src/NHibernate.Test/Async/Linq/PagingTests.cs
  src/NHibernate.Test/Async/Linq/WhereSubqueryTests.cs
  src/NHibernate.Test/Async/Linq/WhereTests.cs
  src/NHibernate.Test/Async/NHSpecificTest/CriteriaQueryOnComponentCollection/Fixture.cs
  src/NHibernate.Test/Async/NHSpecificTest/EntityWithUserTypeCanHaveLinqGenerators/Fixture.cs
  src/NHibernate.Test/Async/NHSpecificTest/GH1300/Fixture.cs
  src/NHibernate.Test/Async/NHSpecificTest/GH1920/Fixture.cs
  src/NHibernate.Test/Async/NHSpecificTest/GH1921/Fixture.cs
  src/NHibernate.Test/Async/NHSpecificTest/NH1001/Fixture.cs
  src/NHibernate.Test/Async/NHSpecificTest/NH1985/SampleTest.cs
  src/NHibernate.Test/Async/NHSpecificTest/NH2208/Filter.cs
  src/NHibernate.Test/Async/NHSpecificTest/NH2294/Fixture.cs
  src/NHibernate.Test/Async/NHSpecificTest/NH2302/Fixture.cs
  src/NHibernate.Test/Async/NHSpecificTest/NH2583/ManualTestFixture.cs
  src/NHibernate.Test/Async/NHSpecificTest/NH2693/Fixture.cs
  src/NHibernate.Test/Async/NHSpecificTest/NH2705/Test.cs
  src/NHibernate.Test/Async/NHSpecificTest/NH2721/Fixture.cs
  src/NHibernate.Test/Async/NHSpecificTest/NH2951/Fixture.cs
  src/NHibernate.Test/Async/NHSpecificTest/NH3037/FixtureByCode.cs
  src/NHibernate.Test/Async/NHSpecificTest/NH3074/Fixture.cs
  src/NHibernate.Test/Async/NHSpecificTest/NH3138/FixtureByCode.cs
  src/NHibernate.Test/Async/NHSpecificTest/NH3401/Fixture.cs
  src/NHibernate.Test/Async/NHSpecificTest/NH3850/MainFixture.cs
  src/NHibernate.Test/Async/Operations/MergeFixture.cs
  src/NHibernate.Test/Async/ReadOnly/ReadOnlyProxyTest.cs
  src/NHibernate.Test/Async/ReadOnly/ReadOnlyVersionedNodes.cs
  src/NHibernate.Test/Async/SqlTest/Query/NativeSQLQueriesFixture.cs
Labels: c: Async, p: Minor, t: Improvement

#2104 Fix exception on session refresh for removed collection item
  src/NHibernate.Test/Async/NHSpecificTest/GH1738/FixtureByCode.cs
  src/NHibernate.Test/NHSpecificTest/GH1738/Entity.cs
  src/NHibernate.Test/NHSpecificTest/GH1738/FixtureByCode.cs
  src/NHibernate/Async/Event/Default/DefaultRefreshEventListener.cs
  src/NHibernate/Event/Default/DefaultRefreshEventListener.cs
Labels: t: Fix

#2149 Fix quoting <key /> columns containing reserved words
  src/NHibernate.Test/Async/NHSpecificTest/NH2892/Fixture.cs
  src/NHibernate.Test/NHSpecificTest/NH2892/Fixture.cs
  src/NHibernate.Test/NHSpecificTest/NH2892/Mappings.hbm.xml
  src/NHibernate.Test/NHSpecificTest/NH2892/Order.cs
  src/NHibernate.Test/NHSpecificTest/NH2892/OrderLine.cs
  src/NHibernate/Async/Tool/hbm2ddl/SchemaMetadataUpdater.cs
  src/NHibernate/Tool/hbm2ddl/SchemaMetadataUpdater.cs
Labels: t: Fix

#2162 Use collection types for private members
  src/NHibernate/AdoNet/AbstractBatcher.cs
  src/NHibernate/AdoNet/HanaBatchingBatcher.cs
  src/NHibernate/AdoNet/OracleDataClientBatchingBatcher.cs
  src/NHibernate/Async/Collection/Generic/PersistentGenericSet.cs
  src/NHibernate/Cfg/Configuration.cs
  src/NHibernate/Cfg/ConfigurationSchema/EventConfiguration.cs
  src/NHibernate/Cfg/MappingSchema/HbmDatabaseObject.cs
  src/NHibernate/Cfg/MappingsQueue.cs
  src/NHibernate/Cfg/SessionFactoryConfigurationBase.cs
  src/NHibernate/Cfg/XmlHbmBinding/NamedSQLQueryBinder.cs
  src/NHibernate/Collection/Generic/PersistentGenericSet.cs
  src/NHibernate/Criterion/Junction.cs
  src/NHibernate/Criterion/ProjectionList.cs
  src/NHibernate/Driver/NDataReader.cs
  src/NHibernate/Driver/SqlStringFormatter.cs
  src/NHibernate/Engine/BatchFetchQueue.cs
  src/NHibernate/Engine/FilterDefinition.cs
  src/NHibernate/Engine/Loading/CollectionLoadContext.cs
  src/NHibernate/Engine/QueryCacheBatchQueue.cs
  src/NHibernate/Engine/StatefulPersistenceContext.cs
  src/NHibernate/Hql/Ast/ANTLR/HqlSqlWalker.cs
  src/NHibernate/Hql/Util/SessionFactoryHelper.cs
  src/NHibernate/Impl/ExpressionProcessor.cs
  src/NHibernate/Impl/ExpressionQueryImpl.cs
  src/NHibernate/Impl/FilterImpl.cs
  src/NHibernate/Impl/MultiCriteriaImpl.cs
  src/NHibernate/Impl/MultiQueryImpl.cs
  src/NHibernate/Impl/SessionFactoryImpl.cs
  src/NHibernate/Linq/ExpressionTransformers/SimplifyCompareTransformer.cs
  src/NHibernate/Linq/QuerySourceNamer.cs
  src/NHibernate/Loader/Criteria/ComponentCollectionCriteriaInfoProvider.cs
  src/NHibernate/Loader/Criteria/CriteriaJoinWalker.cs
  src/NHibernate/Loader/Criteria/CriteriaQueryTranslator.cs
  src/NHibernate/Loader/Custom/CustomLoader.cs
  src/NHibernate/Loader/Custom/Sql/SQLCustomQuery.cs
  src/NHibernate/Loader/Loader.cs
  src/NHibernate/Mapping/PersistentClass.cs
  src/NHibernate/Persister/Collection/AbstractCollectionPersister.cs
  src/NHibernate/Persister/Entity/AbstractEntityPersister.cs
  src/NHibernate/SqlCommand/SelectFragment.cs
  src/NHibernate/SqlCommand/SqlSimpleSelectBuilder.cs
  src/NHibernate/Tool/hbm2ddl/DatabaseMetadata.cs
  src/NHibernate/Transaction/AdoTransaction.cs
  src/NHibernate/Tuple/Entity/EntityMetamodel.cs
Labels: c: Core, p: Trivial, r: Fixed, t: Improvement

#2164 Do not call GC.SuppressFinalize from finalizer thread
  src/NHibernate/AdoNet/AbstractBatcher.cs
  src/NHibernate/Async/Transaction/AdoTransaction.cs
  src/NHibernate/Connection/ConnectionProvider.cs
  src/NHibernate/Impl/EnumerableImpl.cs
  src/NHibernate/Impl/SessionImpl.cs
  src/NHibernate/Impl/StatelessSessionImpl.cs
  src/NHibernate/Transaction/AdoTransaction.cs
  src/NHibernate/Util/JoinedEnumerable.cs
Labels: c: Core, p: Minor, t: Bug

#1941 Allow setting dynamic component templates from dictionary in ByCode
  src/NHibernate.Test/MappingByCode/ExplicitMappingTests/DynamicComponentMappingTests.cs
  src/NHibernate/Mapping/ByCode/IPlainPropertyContainerMapper.cs
  src/NHibernate/Mapping/ByCode/Impl/CustomizersImpl/ComponentCustomizer.cs
  src/NHibernate/Mapping/ByCode/Impl/CustomizersImpl/DynamicComponentCustomizer.cs
  src/NHibernate/Mapping/ByCode/Impl/CustomizersImpl/PropertyContainerCustomizer.cs
Labels: t: Fix

#2101 Allow columns index be shared between base and subclass properties
  src/NHibernate.Test/NHSpecificTest/GH2099/Entity.cs
  src/NHibernate.Test/NHSpecificTest/GH2099/Fixture.cs
  src/NHibernate.Test/NHSpecificTest/GH2099/Mappings.hbm.xml
  src/NHibernate/Mapping/DenormalizedTable.cs
  src/NHibernate/Mapping/Index.cs
Labels: t: Fix
