Repository nhibernate/nhibernate-core, pull requests merged in 2019-10, with the labels that each got.

#2233 Fix possible issue with async code for delayed entity inserts
  src/NHibernate/Action/DelayedPostInsertIdentifier.cs
  src/NHibernate/Action/EntityIdentityInsertAction.cs
Labels: c: Core, p: Minor, t: Bug

#2232 Use SqlStringBuilder for batching Future/QueryBatch queries
  src/NHibernate/Async/Driver/BasicResultSetsCommand.cs
  src/NHibernate/Driver/BasicResultSetsCommand.cs
  src/NHibernate/SqlCommand/SqlString.cs
  src/NHibernate/SqlCommand/SqlStringBuilder.cs
Labels: c: Core, p: Trivial, t: Improvement

#2160 Fix Order By for composite property projection in Criteria
  src/NHibernate.Test/Async/CompositeId/ClassWithCompositeIdFixture.cs
  src/NHibernate.Test/CompositeId/ClassWithCompositeIdFixture.cs
  src/NHibernate/Criterion/CriterionUtil.cs
  src/NHibernate/Criterion/IdentifierProjection.cs
  src/NHibernate/Criterion/Order.cs
Labels: t: Fix

#2245 Add sqlite.binaryguid to configuration schema
  src/NHibernate/nhibernate-configuration.xsd
Labels: c: DataProviders / Dialects, p: Trivial, r: Fixed, t: Bug

#2116 Ability to replace ConfigurationManager with a custom config provider
  src/NHibernate.Test/Async/NHSpecificTest/NH2420/Fixture.cs
  src/NHibernate.Test/CfgTest/ConfigurationSchemaFixture.cs
  src/NHibernate.Test/ConnectionStringTest/NamedConnectionStringFixture.cs
  src/NHibernate.Test/Logging/LoggerProviderTest.cs
  src/NHibernate.Test/NHSpecificTest/NH2420/Fixture.cs
  src/NHibernate.Test/TestsContext.cs
  src/NHibernate/Async/Connection/ConnectionProvider.cs
  src/NHibernate/Cfg/AppSettings.cs
  src/NHibernate/Cfg/ConfigurationProvider.cs
  src/NHibernate/Cfg/Environment.cs
  src/NHibernate/Cfg/NullConfigurationProvider.cs
  src/NHibernate/Cfg/StaticConfigurationManagerProvider.cs
  src/NHibernate/Cfg/SystemConfigurationProvider.cs
  src/NHibernate/Connection/ConnectionProvider.cs
  src/NHibernate/Logging.cs
Labels: c: Core, p: Major, t: New Feature

#2249 Improve handling of SqlCeParameter.SqlDbType
  src/NHibernate/Driver/SqlServerCeDriver.cs
Labels: c: DataProviders / Dialects, p: Trivial, t: Improvement

#2056 Optimize GetOrphans and remove wrong checks from IsNotTransientSlow
  src/NHibernate/Async/Collection/AbstractPersistentCollection.cs
  src/NHibernate/Async/Collection/Generic/PersistentGenericBag.cs
  src/NHibernate/Async/Collection/Generic/PersistentGenericIdentifierBag.cs
  src/NHibernate/Async/Collection/Generic/PersistentGenericList.cs
  src/NHibernate/Async/Collection/Generic/PersistentGenericMap.cs
  src/NHibernate/Async/Collection/Generic/PersistentGenericSet.cs
  src/NHibernate/Async/Collection/IPersistentCollection.cs
  src/NHibernate/Async/Collection/PersistentArrayHolder.cs
  src/NHibernate/Async/Engine/Cascade.cs
  src/NHibernate/Async/Engine/CollectionEntry.cs
  src/NHibernate/Async/Engine/ForeignKeys.cs
  src/NHibernate/Async/Type/IType.cs
  src/NHibernate/Collection/AbstractPersistentCollection.cs
  src/NHibernate/Collection/IPersistentCollection.cs
  src/NHibernate/Collection/PersistentArrayHolder.cs
  src/NHibernate/Engine/CollectionEntry.cs
  src/NHibernate/Engine/ForeignKeys.cs
  src/NHibernate/IdentityEqualityComparer.cs
  src/NHibernate/Type/IType.cs
Labels: c: Core, p: Minor, t: Improvement

#2246 Fix QueryOver Coalesce projection in Select
  src/NHibernate.Test/Async/Criteria/Lambda/ProjectIntegrationFixture.cs
  src/NHibernate.Test/Criteria/Lambda/ProjectIntegrationFixture.cs
  src/NHibernate.Test/Criteria/Lambda/RestrictionsFixture.cs
  src/NHibernate/Criterion/ProjectionsExtensions.cs
  src/NHibernate/Criterion/SqlFunctionProjection.cs
Labels: t: Fix

#2255 Fix a flaky test
  src/NHibernate.Test/Async/NHSpecificTest/GH1594/Fixture.cs
  src/NHibernate.Test/NHSpecificTest/GH1594/ExecutionContextExtensions.cs
  src/NHibernate.Test/NHSpecificTest/GH1594/Fixture.cs
Labels: c: Tests, p: Minor, t: Bug
