Repository nhibernate/nhibernate-core, pull requests merged in 2019-06, with the labels that each got.

#2049 Fix property-ref ignoring not-found="exception" mapping
  src/NHibernate.Test/Async/NHSpecificTest/NH1001/Fixture.cs
  src/NHibernate.Test/NHSpecificTest/NH1001/Fixture.cs
  src/NHibernate/Async/Type/EntityType.cs
  src/NHibernate/Impl/SessionFactoryImpl.cs
  src/NHibernate/ObjectNotFoundByUniqueKeyException.cs
  src/NHibernate/Proxy/IEntityNotFoundDelegate.cs
  src/NHibernate/Type/EntityType.cs
  src/NHibernate/Type/ManyToOneType.cs
  src/NHibernate/Type/OneToOneType.cs
Labels: c: Core, p: Minor, t: New Feature

#1995 Fix #1994 (many-to-many filter in hql)
  src/NHibernate.Test/Async/NHSpecificTest/GH0000/Fixture.cs
  src/NHibernate.Test/Async/NHSpecificTest/GH1994/Fixture.cs
  src/NHibernate.Test/NHSpecificTest/GH0000/Fixture.cs
  src/NHibernate.Test/NHSpecificTest/GH1994/Entity.cs
  src/NHibernate.Test/NHSpecificTest/GH1994/Fixture.cs
  src/NHibernate.Test/NHSpecificTest/GH1994/Mappings.hbm.xml
  src/NHibernate/Async/Persister/Collection/AbstractCollectionPersister.cs
  src/NHibernate/Loader/BasicLoader.cs
  src/NHibernate/Loader/Custom/ColumnCollectionAliases.cs
  src/NHibernate/Loader/GeneratedCollectionAliases.cs
  src/NHibernate/Loader/Hql/QueryLoader.cs
  src/NHibernate/Persister/Collection/AbstractCollectionPersister.cs
  src/NHibernate/Persister/Collection/ICollectionPersister.cs
Labels: t: Fix

#2157 Support projections arguments in Coalesce and other QueryOver extensions
  src/NHibernate.Test/Criteria/Lambda/Mappings.hbm.xml
  src/NHibernate.Test/Criteria/Lambda/Model.cs
  src/NHibernate.Test/Criteria/Lambda/RestrictionsFixture.cs
  src/NHibernate/Criterion/ProjectionsExtensions.cs
Labels: t: Fix

#2178 Expose Fetch method returning QueryOver
  src/NHibernate.Test/Async/Criteria/SelectModeTest/SelectModeTest.cs
  src/NHibernate.Test/Criteria/SelectModeTest/SelectModeTest.cs
  src/NHibernate/Criterion/QueryOver.cs
Labels: t: Fix

#2176 Fix generating join aliases for subcriteria
  src/NHibernate.Test/Async/NHSpecificTest/GH2175/Fixture.cs
  src/NHibernate.Test/NHSpecificTest/GH2175/Domain.cs
  src/NHibernate.Test/NHSpecificTest/GH2175/Fixture.cs
  src/NHibernate/Loader/Criteria/CriteriaJoinWalker.cs
  src/NHibernate/Loader/JoinWalker.cs
Labels: t: Fix

#2180 Upgrade AsyncGenerator to 0.8.2.11 for 5.2
  Tools/packages.config
  src/NHibernate.Test/Async/SessionBuilder/Fixture.cs
Labels: c: Toolset, p: Minor, t: Task

#2179 Fix Criteria with clause for many-to-many
  src/NHibernate.Test/Async/NHSpecificTest/GH1994/Fixture.cs
  src/NHibernate.Test/NHSpecificTest/GH1994/Fixture.cs
  src/NHibernate/Loader/JoinWalker.cs
Labels: r: Fixed, t: Fix

#2119 Obsolete interfaces for Loquacios configuration and use config classes directly
  src/NHibernate/Cfg/Configuration.cs
  src/NHibernate/Cfg/ConfigurationExtensions.cs
  src/NHibernate/Cfg/Loquacious/CacheConfiguration.cs
  src/NHibernate/Cfg/Loquacious/Configuration.cs
  src/NHibernate/Cfg/Loquacious/DbIntegrationConfiguration.cs
  src/NHibernate/Cfg/Loquacious/DbIntegrationConfigurationProperties.cs
  src/NHibernate/Cfg/Loquacious/EntityCacheConfigurationProperties.cs
  src/NHibernate/Cfg/Loquacious/FluentSessionFactoryConfiguration.cs
  src/NHibernate/Cfg/Loquacious/IBatcherConfiguration.cs
  src/NHibernate/Cfg/Loquacious/ICacheConfiguration.cs
  src/NHibernate/Cfg/Loquacious/ICollectionFactoryConfiguration.cs
  src/NHibernate/Cfg/Loquacious/ICommandsConfiguration.cs
  src/NHibernate/Cfg/Loquacious/IConnectionConfiguration.cs
  src/NHibernate/Cfg/Loquacious/IDbIntegrationConfiguration.cs
  src/NHibernate/Cfg/Loquacious/IDbIntegrationConfigurationProperties.cs
  src/NHibernate/Cfg/Loquacious/IDbSchemaIntegrationConfiguration.cs
  src/NHibernate/Cfg/Loquacious/IEntityCacheConfigurationProperties.cs
  src/NHibernate/Cfg/Loquacious/IFluentSessionFactoryConfiguration.cs
  src/NHibernate/Cfg/Loquacious/IMappingsConfiguration.cs
  src/NHibernate/Cfg/Loquacious/INamedQueryDefinitionBuilder.cs
  src/NHibernate/Cfg/Loquacious/IProxyConfiguration.cs
  src/NHibernate/Cfg/Loquacious/IQueryCacheConfiguration.cs
  src/NHibernate/Cfg/Loquacious/ITransactionConfiguration.cs
  src/NHibernate/Cfg/Loquacious/ITypeDefConfiguration.cs
  src/NHibernate/Cfg/Loquacious/MappingsConfiguration.cs
  src/NHibernate/Cfg/Loquacious/ProxyConfiguration.cs
Labels: c: Core, p: Minor, t: Improvement

#2106 Port Hibernate's support subqueries in HQL as CASE statement alternatives
  src/NHibernate.Test/Async/Hql/SubQueryTest.cs
  src/NHibernate.Test/Async/NHSpecificTest/GH1879/FixtureByCode.cs
  src/NHibernate.Test/Hql/Ast/SqlTranslationFixture.cs
  src/NHibernate.Test/Hql/SubQueryTest.cs
  src/NHibernate.Test/Hql/SubQueryTestEntities.cs
  src/NHibernate.Test/NHSpecificTest/GH1879/FixtureByCode.cs
  src/NHibernate/Hql/Ast/ANTLR/Hql.g
  src/NHibernate/Hql/Ast/ANTLR/HqlSqlWalker.g
  src/NHibernate/Linq/ReWriters/ConditionalQueryReferenceExpander.cs
  src/NHibernate/Linq/ReWriters/SubQueryConditionalExpander.cs
Labels: c: Core, p: Minor, t: New Feature

#2107 Port Hibernate's Aggregate functions for subqueries
  src/NHibernate.Test/Async/Hql/AggregateFunctionsWithSubSelectTest.cs
  src/NHibernate.Test/Hql/AggregateFunctionsWithSubSelectTest.cs
  src/NHibernate.Test/Hql/AggregateFunctionsWithSubSelectTestEntities.cs
  src/NHibernate.Test/TestDialect.cs
  src/NHibernate.Test/TestDialects/MySQL5TestDialect.cs
  src/NHibernate.Test/TestDialects/Oracle10gTestDialect.cs
  src/NHibernate.Test/TestDialects/PostgreSQL83TestDialect.cs
  src/NHibernate.Test/TestDialects/SQLiteTestDialect.cs
  src/NHibernate/Hql/Ast/ANTLR/Hql.g
  src/NHibernate/Hql/Ast/ANTLR/HqlSqlWalker.g
Labels: c: Core, p: Minor, t: New Feature

#2089 Bidirectional list fails if session only knows about child
  src/NHibernate.Test/NHSpecificTest/GH2089/Fixture.cs
  src/NHibernate.Test/NHSpecificTest/GH2089/Mappings.hbm.xml
  src/NHibernate.Test/NHSpecificTest/GH2089/Model.cs
Labels: t: Tests
