Repository nhibernate/nhibernate-core, pull requests merged in 2019-12, with the labels that each got.

#2275 Add missing options to QueryOver
  src/NHibernate.Test/Criteria/Lambda/QueryOverFixture.cs
  src/NHibernate/QueryOverExtensions.cs
Labels: t: Fix

#2285 Fix GenericBatchingBatcher to call IInterceptor.OnPrepareStatement
  src/NHibernate.Test/Ado/GenericBatchingBatcherFixture.cs
  src/NHibernate.Test/Async/Ado/GenericBatchingBatcherFixture.cs
  src/NHibernate/AdoNet/AbstractBatcher.cs
  src/NHibernate/AdoNet/GenericBatchingBatcher.cs
  src/NHibernate/Async/AdoNet/AbstractBatcher.cs
  src/NHibernate/Async/AdoNet/GenericBatchingBatcher.cs
Labels: t: Fix

#2229 Cache query plan for DML LINQ queries
  src/NHibernate.Test/Async/Linq/ConstantTest.cs
  src/NHibernate.Test/Linq/ConstantTest.cs
  src/NHibernate/Linq/NhLinqExpression.cs
Labels: t: Fix

#2288 Fix subclass filter on key columns
  src/NHibernate.Test/Async/NHSpecificTest/GH2286/Fixture.cs
  src/NHibernate.Test/NHSpecificTest/GH2286/Entities.cs
  src/NHibernate.Test/NHSpecificTest/GH2286/Fixture.cs
  src/NHibernate.Test/NHSpecificTest/GH2286/Mappings.hbm.xml
  src/NHibernate/Persister/Entity/AbstractEntityPersister.cs
Labels: t: Fix

#2216 Add a driver to support Microsoft.Data.SqlClient provider
  src/NHibernate.Test/Async/NHSpecificTest/NH2420/Fixture.cs
  src/NHibernate.Test/ExceptionsTest/MSSQLExceptionConverterExample.cs
  src/NHibernate.Test/NHSpecificTest/NH2420/Fixture.cs
  src/NHibernate.Test/NHibernate.Test.csproj
  src/NHibernate/Driver/MicrosoftDataSqlClientDriver.cs
Labels: c: DataProviders / Dialects, p: Minor, t: New Feature

#2293 Update RtMemoryCache framework dependency
  doc/reference/modules/nhibernate_caches.xml
Labels: c: Documentation, p: Trivial, t: Task

#2295 Optimize filter applying logic
  src/NHibernate/Persister/Entity/AbstractEntityPersister.cs
  src/NHibernate/Util/FilterHelper.cs
Labels: c: Core, p: Minor, t: Improvement

#2294 Add StackExchangeRedis cache provider documentation
  doc/reference/modules/nhibernate_caches.xml
Labels: c: Documentation, p: Minor, t: New Feature
