Repository nhibernate/nhibernate-core, pull requests merged in 2019-01, with the labels that each got.

#1946 Port Hibernate's BytecodeEnhancementMetadata
  src/NHibernate.Test/Async/NHSpecificTest/GH1439/Fixture.cs
  src/NHibernate.Test/NHSpecificTest/GH1439/Fixture.cs
  src/NHibernate/Async/Engine/Cascade.cs
  src/NHibernate/Async/Event/Default/DefaultMergeEventListener.cs
  src/NHibernate/Async/Persister/Entity/AbstractEntityPersister.cs
  src/NHibernate/Bytecode/IBytecodeEnhancementMetadata.cs
  src/NHibernate/Bytecode/LazyPropertiesMetadata.cs
  src/NHibernate/Bytecode/LazyPropertyDescriptor.cs
  src/NHibernate/Bytecode/NotInstrumentedException.cs
  src/NHibernate/Bytecode/UnwrapProxyPropertiesMetadata.cs
  src/NHibernate/Bytecode/UnwrapProxyPropertyDescriptor.cs
  src/NHibernate/Engine/Cascade.cs
  src/NHibernate/Engine/EntityEntry.cs
  src/NHibernate/Event/Default/AbstractSaveEventListener.cs
  src/NHibernate/Event/Default/DefaultMergeEventListener.cs
  src/NHibernate/Impl/SessionImpl.cs
  src/NHibernate/Intercept/FieldInterceptionHelper.cs
  src/NHibernate/NHibernateUtil.cs
  src/NHibernate/Persister/Entity/AbstractEntityPersister.cs
  src/NHibernate/Persister/Entity/IEntityPersister.cs
  src/NHibernate/Tuple/Entity/BytecodeEnhancementMetadataNonPocoImpl.cs
  src/NHibernate/Tuple/Entity/BytecodeEnhancementMetadataPocoImpl.cs
  src/NHibernate/Tuple/Entity/EntityMetamodel.cs
  src/NHibernate/Tuple/Entity/IEntityTuplizer.cs
  src/NHibernate/Tuple/Entity/PocoEntityTuplizer.cs
Labels: c: ByteCode providers, p: Minor, t: Improvement

#1944 Extend IAccessOptimizer to support getting/setting single property value
  src/NHibernate.Test/NHSpecificTest/NH3119/FixtureByCode.cs
  src/NHibernate.Test/PropertyTest/AccessorPerformanceFixture.cs
  src/NHibernate.Test/PropertyTest/BasicPropertyAccessorPerformanceFixture.cs
  src/NHibernate.Test/PropertyTest/FieldAccessorPerformanceFixture.cs
  src/NHibernate.Test/ReflectionOptimizerTest/LcgFixture.cs
  src/NHibernate/Bytecode/IAccessOptimizer.cs
  src/NHibernate/Bytecode/IBytecodeProvider.cs
  src/NHibernate/Bytecode/Lightweight/AccessOptimizer.cs
  src/NHibernate/Bytecode/Lightweight/BytecodeProviderImpl.cs
  src/NHibernate/Bytecode/Lightweight/Delegates.cs
  src/NHibernate/Bytecode/Lightweight/ReflectionOptimizer.cs
  src/NHibernate/Tuple/Component/PocoComponentTuplizer.cs
  src/NHibernate/Tuple/Entity/AbstractEntityTuplizer.cs
  src/NHibernate/Tuple/Entity/PocoEntityTuplizer.cs
Labels: c: ByteCode providers, p: Minor, t: Improvement

#1954 Move discovery of executedSpaces to RegisterCleanupActions
  src/NHibernate.Test/Async/SecondLevelCacheTest/InvalidationTests.cs
  src/NHibernate.Test/SecondLevelCacheTest/InvalidationTests.cs
  src/NHibernate/Async/Engine/ActionQueue.cs
  src/NHibernate/Engine/ActionQueue.cs
Labels: t: Fix

#1959 Backport Query space invalidation doesn't work for bulk actions
  appveyor.yml
  build-common/NHibernate.props
  build-common/common.xml
  releasenotes.txt
  src/NHibernate.Test/Async/SecondLevelCacheTest/InvalidationTests.cs
  src/NHibernate.Test/SecondLevelCacheTest/InvalidationTests.cs
  src/NHibernate/Async/Engine/ActionQueue.cs
  src/NHibernate/Engine/ActionQueue.cs
Labels: c: Core, p: Critical, t: Bug

#1957 Release 5.2.2
  appveyor.yml
  build-common/NHibernate.props
  build-common/common.xml
  releasenotes.txt
Labels: c: Core, p: Minor, t: Task

#1956 Fix lazy property caching
  src/NHibernate.Test/Async/LazyProperty/LazyPropertyFixture.cs
  src/NHibernate.Test/LazyProperty/LazyPropertyFixture.cs
  src/NHibernate.Test/LazyProperty/Mappings.hbm.xml
  src/NHibernate/Async/Cache/Entry/CacheEntry.cs
  src/NHibernate/Cache/Entry/CacheEntry.cs
  src/NHibernate/Cfg/XmlHbmBinding/RootClassBinder.cs
Labels: c: Core, p: Minor, t: Bug

#1961 Add missing pragma warning for FieldInterceptorProxyBuilder
  src/NHibernate/Proxy/FieldInterceptorProxyBuilder.cs
Labels: t: Fix

#1965 Fix code sample in docs, section 10.4.2
  doc/reference/modules/manipulating_data.xml
Labels: c: Documentation, p: Minor, t: Bug

#1947 Partially port Hibernate's current field interceptor mechanism
  src/NHibernate.Test/Async/GhostProperty/GhostPropertyDynamicProxyFixture.cs
  src/NHibernate.Test/Async/GhostProperty/GhostPropertyFixture.cs
  src/NHibernate.Test/Async/LazyOneToOne/LazyOneToOneTest.cs
  src/NHibernate.Test/GhostProperty/GhostPropertyDynamicProxyFixture.cs
  src/NHibernate.Test/GhostProperty/GhostPropertyFixture.cs
  src/NHibernate.Test/LazyOneToOne/LazyOneToOneTest.cs
  src/NHibernate.Test/StaticProxyTest/StaticProxyFactoryFixture.cs
  src/NHibernate/Intercept/AbstractFieldInterceptor.cs
  src/NHibernate/Intercept/DefaultDynamicLazyFieldInterceptor.cs
  src/NHibernate/Proxy/AbstractProxyFactory.cs
  src/NHibernate/Proxy/DefaultProxyFactory.cs
  src/NHibernate/Proxy/FieldInterceptorObjectReference.cs
  src/NHibernate/Proxy/IProxyFactory.cs
  src/NHibernate/Proxy/StaticProxyFactory.cs
  src/NHibernate/Tuple/Entity/PocoEntityInstantiator.cs
  src/NHibernate/Tuple/Entity/PocoEntityTuplizer.cs
  src/NHibernate/Tuple/PocoInstantiator.cs
Labels: c: ByteCode providers, p: Minor, possible breaking change, t: Improvement

#1968 Optimize StaticProxyFactory GetProxy and GetFieldInterceptionProxy methods
  src/NHibernate/Proxy/StaticProxyFactory.cs
Labels: c: ByteCode providers, p: Minor, t: Improvement

#1970 Fix session no more serializable with entities having a field interceptor
  appveyor.yml
  build-common/NHibernate.props
  build-common/common.xml
  releasenotes.txt
  src/NHibernate.Test/StaticProxyTest/Model.cs
  src/NHibernate/Proxy/FieldInterceptorObjectReference.cs
  src/NHibernate/Proxy/NHibernateProxyFactoryInfo.cs
Labels: t: Fix

#1972 Port Hibernate's EntityKey optimization
  src/NHibernate/Engine/EntityKey.cs
  src/NHibernate/Type/ManyToOneType.cs
Labels: c: Core, p: Minor, t: Improvement

#1966 Test duplicated join on some Linq queries
  src/NHibernate.Test/Async/NHSpecificTest/GH1962/Fixture.cs
  src/NHibernate.Test/NHSpecificTest/GH1962/Entity.cs
  src/NHibernate.Test/NHSpecificTest/GH1962/Fixture.cs
  src/NHibernate.Test/NHSpecificTest/GH1962/Mappings.hbm.xml
Labels: c: Linq Provider, p: Trivial, t: Tests

#1974 Optimize CriteriaQueryTranslator GetColumns and GetTypes
  src/NHibernate.Test/Async/Criteria/Lambda/SubQueryIntegrationFixture.cs
  src/NHibernate.Test/Criteria/Lambda/CriteriaGenerationBenchmarks.cs
  src/NHibernate.Test/Criteria/Lambda/SubQueryIntegrationFixture.cs
  src/NHibernate/Loader/Criteria/CriteriaQueryTranslator.cs
Labels: t: Fix

#1981 Remove AbstractLazyInitializer unused field
  src/NHibernate/Async/Proxy/AbstractLazyInitializer.cs
  src/NHibernate/Proxy/AbstractLazyInitializer.cs
Labels: c: ByteCode providers, p: Trivial, r: Fixed, t: Improvement

#1987 Allow projections in SelectGroup and CountDistinct expressions
  src/NHibernate.Test/Async/Criteria/Lambda/ProjectIntegrationFixture.cs
  src/NHibernate.Test/Criteria/Lambda/Model.cs
  src/NHibernate.Test/Criteria/Lambda/ProjectIntegrationFixture.cs
  src/NHibernate/Criterion/Lambda/QueryOverProjectionBuilder.cs
  src/NHibernate/Criterion/Projections.cs
Labels: t: Fix

#1936 Upgrade AsyncGenerator to 0.13.1
  Tools/packages.config
  src/NHibernate.Test/Async/Linq/QueryTimeoutTests.cs
  src/NHibernate.Test/Async/NHSpecificTest/GH1547/Fixture.cs
  src/NHibernate.Test/Async/NHSpecificTest/NH3848/Fixture.cs
  src/NHibernate.Test/Async/SessionBuilder/Fixture.cs
  src/NHibernate.Test/Async/SystemTransactions/DistributedSystemTransactionFixture.cs
  src/NHibernate.Test/Async/TransactionTest/TransactionNotificationFixture.cs
  src/NHibernate.sln.DotSettings
  src/NHibernate/Async/Action/CollectionAction.cs
  src/NHibernate/Async/Action/EntityIdentityInsertAction.cs
  src/NHibernate/Async/Collection/AbstractPersistentCollection.cs
  src/NHibernate/Async/Engine/ActionQueue.cs
  src/NHibernate/Async/Engine/BatchFetchQueue.cs
  src/NHibernate/Async/Event/Default/AbstractVisitor.cs
  src/NHibernate/Async/Event/Default/DefaultFlushEntityEventListener.cs
  src/NHibernate/Async/Event/Default/DefaultLoadEventListener.cs
  src/NHibernate/Async/Impl/SessionImpl.cs
  src/NHibernate/Async/Impl/StatelessSessionImpl.cs
  src/NHibernate/Async/Multi/QueryBatch.cs
  src/NHibernate/Async/Persister/Collection/AbstractCollectionPersister.cs
  src/NHibernate/Async/Type/AnyType.cs
  src/NHibernate/Async/Type/ClassMetaType.cs
Labels: c: Async, p: Trivial, t: Task

#1992 Fix System.InvalidCastException when merge collection with LazyProperty
  src/NHibernate.Test/Async/LazyProperty/LazyPropertyFixture.cs
  src/NHibernate.Test/LazyProperty/Book.cs
  src/NHibernate.Test/LazyProperty/LazyPropertyFixture.cs
  src/NHibernate.Test/LazyProperty/Mappings.hbm.xml
  src/NHibernate.Test/LazyProperty/Word.cs
  src/NHibernate/Async/Type/TypeHelper.cs
  src/NHibernate/Type/TypeHelper.cs
Labels: t: Fix

#1990 Replace <PackageLicenseUrl /> with <PackageLicenseExpression />
  build-common/NHibernate.props
Labels: t: Fix

#1922 Add support for fetching an individual lazy property with hql and linq provider
  src/NHibernate.Test/Async/FetchLazyProperties/FetchLazyPropertiesFixture.cs
  src/NHibernate.Test/FetchLazyProperties/Address.cs
  src/NHibernate.Test/FetchLazyProperties/Animal.cs
  src/NHibernate.Test/FetchLazyProperties/Cat.cs
  src/NHibernate.Test/FetchLazyProperties/Continent.cs
  src/NHibernate.Test/FetchLazyProperties/Dog.cs
  src/NHibernate.Test/FetchLazyProperties/FetchLazyPropertiesFixture.cs
  src/NHibernate.Test/FetchLazyProperties/Mappings.hbm.xml
  src/NHibernate.Test/FetchLazyProperties/Person.cs
  src/NHibernate/Async/Impl/MultiCriteriaImpl.cs
  src/NHibernate/Async/Impl/MultiQueryImpl.cs
  src/NHibernate/Async/Loader/Loader.cs
  src/NHibernate/Async/Multi/QueryBatchItemBase.cs
  src/NHibernate/Async/Persister/Entity/AbstractEntityPersister.cs
  src/NHibernate/Async/Persister/Entity/ILoadable.cs
  src/NHibernate/Bytecode/LazyPropertiesMetadata.cs
  src/NHibernate/Hql/Ast/ANTLR/Hql.g
  src/NHibernate/Hql/Ast/ANTLR/HqlSqlWalker.cs
  src/NHibernate/Hql/Ast/ANTLR/HqlSqlWalker.g
  src/NHibernate/Hql/Ast/ANTLR/Tree/FromElement.cs
  src/NHibernate/Hql/Ast/ANTLR/Tree/FromElementType.cs
  src/NHibernate/Hql/Ast/HqlTreeBuilder.cs
  src/NHibernate/Impl/MultiCriteriaImpl.cs
  src/NHibernate/Impl/MultiQueryImpl.cs
  src/NHibernate/Linq/EagerFetchingExtensionMethods.cs
  src/NHibernate/Linq/FetchLazyPropertiesExpressionNode.cs
  src/NHibernate/Linq/FetchLazyPropertiesResultOperator.cs
  src/NHibernate/Linq/IntermediateHqlTree.cs
  src/NHibernate/Linq/NhRelinqQueryParser.cs
  src/NHibernate/Linq/ReWriters/QueryReferenceExpressionFlattener.cs
  src/NHibernate/Linq/ReWriters/ResultOperatorRewriter.cs
  src/NHibernate/Linq/Visitors/QueryModelVisitor.cs
  src/NHibernate/Linq/Visitors/QuerySourceLocator.cs
  src/NHibernate/Linq/Visitors/ResultOperatorProcessors/ProcessFetch.cs
  src/NHibernate/Linq/Visitors/ResultOperatorProcessors/ProcessFetchLazyProperties.cs
  src/NHibernate/Linq/Visitors/SubQueryFromClauseFlattener.cs
  src/NHibernate/Loader/Hql/QueryLoader.cs
  src/NHibernate/Loader/Loader.cs
  src/NHibernate/Multi/QueryBatchItemBase.cs
  src/NHibernate/Persister/Entity/AbstractEntityPersister.cs
  src/NHibernate/Persister/Entity/ILoadable.cs
  src/NHibernate/Persister/Entity/IQueryable.cs
Labels: c: Core, p: Minor, t: New Feature

#1997 Fix criteria collection ordering
  src/NHibernate.Test/Async/Criteria/SelectModeTest/SelectModeTest.cs
  src/NHibernate.Test/Criteria/SelectModeTest/Entities.cs
  src/NHibernate.Test/Criteria/SelectModeTest/SelectModeTest.cs
  src/NHibernate/Loader/JoinWalker.cs
Labels: c: QueryOver, p: Minor, t: Bug
