Repository nhibernate/nhibernate-core, pull requests merged in 2019-04, with the labels that each got.

#2088 Fix cacheable CreateSQLQuery throws on query with AddJoin
  src/NHibernate.Test/Async/SqlTest/Query/NativeSQLQueriesFixture.cs
  src/NHibernate.Test/SqlTest/Query/NativeSQLQueriesFixture.cs
  src/NHibernate/Loader/Custom/CustomLoader.cs
Labels: c: Core, p: Minor, t: Bug

#2122 Update AsyncGenerator to 0.13.3
  Tools/packages.config
Labels: c: Async, p: Trivial, t: Task

#2123 Small stylistic improvement in unit test
  src/NHibernate.Test/Hql/SimpleFunctionsTest.cs
Labels: c: Tests, p: Trivial, r: Fixed, t: Improvement

#2124 Add failure messages back into unit test
  src/NHibernate.Test/Hql/SimpleFunctionsTest.cs
Labels: t: Fix

#2041 Hql entity join fixes
  src/NHibernate.Test/Async/Hql/Ast/WithClauseFixture.cs
  src/NHibernate.Test/Async/Hql/EntityJoinHqlTest.cs
  src/NHibernate.Test/Hql/Ast/WithClauseFixture.cs
  src/NHibernate.Test/Hql/EntityJoinHqlTest.cs
  src/NHibernate.Test/Hql/EntityJoinHqlTestEntities.cs
  src/NHibernate/Hql/Ast/ANTLR/HqlSqlWalker.cs
  src/NHibernate/Hql/Ast/ANTLR/SqlGenerator.g
Labels: c: Core, p: Minor, t: Improvement

#2128 Fix GetMany for ReadWriteCache
  src/NHibernate/Async/Cache/NonstrictReadWriteCache.cs
  src/NHibernate/Async/Cache/ReadOnlyCache.cs
  src/NHibernate/Async/Cache/ReadWriteCache.cs
  src/NHibernate/Async/Cache/StandardQueryCache.cs
  src/NHibernate/Cache/NonstrictReadWriteCache.cs
  src/NHibernate/Cache/ReadOnlyCache.cs
  src/NHibernate/Cache/ReadWriteCache.cs
  src/NHibernate/Cache/StandardQueryCache.cs
Labels: t: Fix

#2131 Create Stopwatch only if stats is enabled
  src/NHibernate/Async/Engine/Loading/CollectionLoadContext.cs
  src/NHibernate/Async/Engine/TwoPhaseLoad.cs
  src/NHibernate/Async/Event/Default/DefaultInitializeCollectionEventListener.cs
  src/NHibernate/Async/Event/Default/DefaultLoadEventListener.cs
  src/NHibernate/Async/Impl/MultiCriteriaImpl.cs
  src/NHibernate/Async/Impl/MultiQueryImpl.cs
  src/NHibernate/Async/Loader/Hql/QueryLoader.cs
  src/NHibernate/Async/Loader/Loader.cs
  src/NHibernate/Async/Multi/QueryBatch.cs
  src/NHibernate/Engine/Loading/CollectionLoadContext.cs
  src/NHibernate/Engine/TwoPhaseLoad.cs
  src/NHibernate/Event/Default/DefaultInitializeCollectionEventListener.cs
  src/NHibernate/Event/Default/DefaultLoadEventListener.cs
  src/NHibernate/Impl/MultiCriteriaImpl.cs
  src/NHibernate/Impl/MultiQueryImpl.cs
  src/NHibernate/Loader/Hql/QueryLoader.cs
  src/NHibernate/Loader/Loader.cs
  src/NHibernate/Multi/QueryBatch.cs
Labels: c: Core, p: Trivial, r: Fixed, t: Improvement

#2117 Replace array concatenation with hand written append
  src/NHibernate/Mapping/ByCode/Impl/ClassMapper.cs
  src/NHibernate/Mapping/ByCode/Impl/ComponentAsIdMapper.cs
  src/NHibernate/Mapping/ByCode/Impl/ComponentElementMapper.cs
  src/NHibernate/Mapping/ByCode/Impl/ComponentMapKeyMapper.cs
  src/NHibernate/Mapping/ByCode/Impl/ComponentMapper.cs
  src/NHibernate/Mapping/ByCode/Impl/ComponentNestedElementMapper.cs
  src/NHibernate/Mapping/ByCode/Impl/ComposedIdMapper.cs
  src/NHibernate/Mapping/ByCode/Impl/DynamicComponentMapper.cs
  src/NHibernate/Mapping/ByCode/Impl/JoinMapper.cs
  src/NHibernate/Mapping/ByCode/Impl/JoinedSubclassMapper.cs
  src/NHibernate/Mapping/ByCode/Impl/NaturalIdMapper.cs
  src/NHibernate/Mapping/ByCode/Impl/SubclassMapper.cs
  src/NHibernate/Mapping/ByCode/Impl/UnionSubclassMapper.cs
  src/NHibernate/Mapping/ByCode/Import.cs
  src/NHibernate/Util/ArrayHelper.cs
Labels: c: Core, p: Trivial

#2132 Add GetMany for ReadWriteCache tests
  src/NHibernate.Test/Async/CacheTest/BatchableCacheFixture.cs
  src/NHibernate.Test/CacheTest/BatchableCacheFixture.cs
Labels: c: L2 Cache, p: Trivial, r: Fixed, t: Tests

#2125 Skip logger default initialization logic when logger provided by user
  src/NHibernate/Logging.cs
Labels: c: Core, p: Trivial, t: Improvement

#2134 Fixup for NHibernate logger changes in #2125
  src/NHibernate/Logging.cs
Labels: r: Fixed, t: Fix

#2143 Use reference equality in InsertActionSorter
  src/NHibernate.Test/Async/Insertordering/AnimalModel/Fixture.cs
  src/NHibernate.Test/Insertordering/AnimalModel/Fixture.cs
  src/NHibernate.Test/Insertordering/AnimalModel/Mappings.hbm.xml
  src/NHibernate.Test/Insertordering/AnimalModel/PersonWithSivasKangals.cs
  src/NHibernate/Async/Engine/ActionQueue.cs
  src/NHibernate/Engine/ActionQueue.cs
  src/NHibernate/Util/ReferenceComparer.cs
Labels: t: Fix

#2139 Add ability to set fetch for <one-to-one> mapping in mapping by code
  src/NHibernate.Test/MappingByCode/MappersTests/OneToOneMapperTest.cs
  src/NHibernate/Mapping/ByCode/IOneToOneMapper.cs
  src/NHibernate/Mapping/ByCode/Impl/OneToOneMapper.cs
Labels: c: Mapping by Code, p: Minor, r: Fixed, t: Improvement

#2142 Fix properties mapped inside a <properties> group are empty when retrieving object
  src/NHibernate.Test/Async/NHSpecificTest/NH2714/Fixture.cs
  src/NHibernate.Test/NHSpecificTest/NH2714/Fixture.cs
  src/NHibernate.Test/NHSpecificTest/NH2714/Information.cs
  src/NHibernate.Test/NHSpecificTest/NH2714/Item.cs
  src/NHibernate.Test/NHSpecificTest/NH2714/Mappings.hbm.xml
  src/NHibernate/Type/EmbeddedComponentType.cs
Labels: t: Fix
