Repository nhibernate/nhibernate-core, pull requests merged in 2019-02, with the labels that each got.

#1988 Improve exception on user types lacking some interfaces
  src/NHibernate.Test/NHSpecificTest/GH1963/Entity.cs
  src/NHibernate.Test/NHSpecificTest/GH1963/Fixture.cs
  src/NHibernate.Test/NHSpecificTest/GH1963/Mappings.hbm.xml
  src/NHibernate.Test/NHSpecificTest/GH1963/SqlBoolean.cs
  src/NHibernate/Async/Type/CustomType.cs
  src/NHibernate/Type/CustomType.cs
Labels: c: Core, p: Trivial, t: Improvement

#2000 Fixed Equals method for transformers
  src/NHibernate.Test/NHSpecificTest/NH3957/ResultTransformerEqualityFixture.cs
  src/NHibernate/Criterion/CriteriaSpecification.cs
  src/NHibernate/Transform/AliasToEntityMapResultTransformer.cs
  src/NHibernate/Transform/CacheableResultTransformer.cs
  src/NHibernate/Transform/DistinctRootEntityResultTransformer.cs
  src/NHibernate/Transform/PassThroughResultTransformer.cs
  src/NHibernate/Transform/RootEntityResultTransformer.cs
  src/NHibernate/Transform/ToListResultTransformer.cs
  src/NHibernate/Transform/Transformers.cs
Labels: c: Core, p: Minor, t: Bug

#1999 Optimize DistinctRootEntityResultTransformer
  src/NHibernate/Linq/IntermediateHqlTree.cs
  src/NHibernate/Transform/DistinctRootEntityResultTransformer.cs
Labels: c: Core, p: Minor, t: Improvement

#463 NH-3848 - Tests and fix for HQL
  src/NHibernate.Test/Async/NHSpecificTest/NH3848/Fixture.cs
  src/NHibernate.Test/Async/NHSpecificTest/NH3848/HqlTestFixture.cs
  src/NHibernate.Test/NHSpecificTest/NH3848/Fixture.cs
  src/NHibernate.Test/NHSpecificTest/NH3848/HqlTestFixture.cs
  src/NHibernate/Async/Cache/UpdateTimestampsCache.cs
  src/NHibernate/Async/Hql/Ast/ANTLR/QueryTranslatorImpl.cs
  src/NHibernate/Cache/UpdateTimestampsCache.cs
  src/NHibernate/Hql/Ast/ANTLR/QueryTranslatorImpl.cs
  src/NHibernate/Hql/Ast/ANTLR/Tree/FromClause.cs
  src/NHibernate/Hql/Ast/ANTLR/Util/ASTUtil.cs
  src/NHibernate/Loader/Hql/QueryLoader.cs
Labels: t: Fix

#2002 Refactor DependentAlias handling logic in JoinWalker
  src/NHibernate/Loader/JoinWalker.cs
Labels: c: Core, p: Minor, t: Improvement

#2007 Dispose session in cascade tests
  src/NHibernate.Test/Async/Cascade/Circle/MultiPathCircleCascadeTest.cs
  src/NHibernate.Test/Async/Cascade/MultiPathCascadeTest.cs
  src/NHibernate.Test/Cascade/Circle/MultiPathCircleCascadeTest.cs
  src/NHibernate.Test/Cascade/MultiPathCascadeTest.cs
Labels: c: Tests, p: Minor, t: Improvement

#2006 Skip Topological sorting if not required
  src/NHibernate/Loader/JoinWalker.cs
Labels: c: Core, p: Minor, t: Improvement

#2012 Make SqlClientBatchingBatcher respect CommandTimeout seting in configuration
  src/NHibernate/AdoNet/SqlClientBatchingBatcher.cs
  src/NHibernate/Async/AdoNet/SqlClientBatchingBatcher.cs
  src/NHibernate/Driver/DriverBase.cs
  src/NHibernate/Driver/DriverExtensions.cs
Labels: t: Fix

#2016 Avoid recursive calls in BatchFetchQueue
  src/NHibernate/Async/Engine/BatchFetchQueue.cs
  src/NHibernate/Engine/BatchFetchQueue.cs
Labels: c: Core, p: Minor, t: Task

#1480 Fix cache build for honoring mapped concurrency
  src/NHibernate.Test/Async/CacheTest/BuildCacheFixture.cs
  src/NHibernate.Test/Async/CacheTest/GetQueryCacheFixture.cs
  src/NHibernate.Test/CacheTest/BuildCacheFixture.cs
  src/NHibernate.Test/CacheTest/EntitiesInSameRegion.cs
  src/NHibernate.Test/CacheTest/EntitiesInSameRegion.hbm.xml
  src/NHibernate/Async/Cache/NonstrictReadWriteCache.cs
  src/NHibernate/Async/Cache/ReadWriteCache.cs
  src/NHibernate/Async/Impl/SessionFactoryImpl.cs
  src/NHibernate/Cache/CacheExtensions.cs
  src/NHibernate/Cache/CacheFactory.cs
  src/NHibernate/Cache/ICacheConcurrencyStrategy.cs
  src/NHibernate/Cache/IQueryCache.cs
  src/NHibernate/Cache/IQueryCacheFactory.cs
  src/NHibernate/Cache/NonstrictReadWriteCache.cs
  src/NHibernate/Cache/ReadOnlyCache.cs
  src/NHibernate/Cache/ReadWriteCache.cs
  src/NHibernate/Cache/StandardQueryCache.cs
  src/NHibernate/Cache/StandardQueryCacheFactory.cs
  src/NHibernate/Cache/UpdateTimestampsCache.cs
  src/NHibernate/Cfg/Settings.cs
  src/NHibernate/Impl/SessionFactoryImpl.cs
Labels: c: Core, p: Minor, possible breaking change, t: Bug

#1952 Add support for caching fetched relations with linq query provider
  src/NHibernate.Test/Async/Linq/QueryCacheableTests.cs
  src/NHibernate.Test/Linq/QueryCacheableTests.cs
  src/NHibernate/Async/Cache/StandardQueryCache.cs
  src/NHibernate/Async/Impl/MultiCriteriaImpl.cs
  src/NHibernate/Async/Impl/MultiQueryImpl.cs
  src/NHibernate/Async/Loader/Hql/QueryLoader.cs
  src/NHibernate/Async/Loader/Loader.cs
  src/NHibernate/Async/Multi/QueryBatch.cs
  src/NHibernate/Async/Multi/QueryBatchItemBase.cs
  src/NHibernate/Async/Type/TypeHelper.cs
  src/NHibernate/Cache/QueryCacheResultBuilder.cs
  src/NHibernate/Cache/StandardQueryCache.cs
  src/NHibernate/Impl/MultiCriteriaImpl.cs
  src/NHibernate/Impl/MultiQueryImpl.cs
  src/NHibernate/Loader/Hql/QueryLoader.cs
  src/NHibernate/Loader/Loader.cs
  src/NHibernate/Multi/ICachingInformation.cs
  src/NHibernate/Multi/ICachingInformationWithFetches.cs
  src/NHibernate/Multi/QueryBatch.cs
  src/NHibernate/Multi/QueryBatchItemBase.cs
  src/NHibernate/Type/TypeHelper.cs
Labels: t: Fix

#2014 Obsolete Environment.Properties
  src/NHibernate/Cfg/Configuration.cs
  src/NHibernate/Cfg/Environment.cs
  src/NHibernate/Dialect/Dialect.cs
  src/NHibernate/Driver/DriverExtensions.cs
Labels: c: Core, p: Trivial, t: Task

#2019 Update symbol package format and add Sourcelink
  build-common/NHibernate.props
  default.build
  src/NHibernate/NHibernate.csproj
Labels: c: Toolset, p: Minor, t: Bug

#2020 Throw for DML on filter
  src/NHibernate.Test/Async/LinqBulkManipulation/Fixture.cs
  src/NHibernate.Test/LinqBulkManipulation/Fixture.cs
  src/NHibernate/Async/Linq/DefaultQueryProvider.cs
  src/NHibernate/Linq/DefaultQueryProvider.cs
Labels: c: Linq Provider, p: Major, t: Bug

#2011 Use a statically resolved dialect when building the session factory
  src/NHibernate/Cfg/Configuration.cs
Labels: c: Core, p: Trivial, t: Bug
