Repository nhibernate/nhibernate-core, pull requests merged in 2019-09, with the labels that each got.

#2199 Update Async generator to 0.8.2.12
  Tools/packages.config
Labels: c: Async, p: Minor, t: Task

#2197 Fix dependent transaction failure
  src/AsyncGenerator.yml
  src/NHibernate.Test/Async/SystemTransactions/DistributedSystemTransactionFixture.cs
  src/NHibernate.Test/Async/SystemTransactions/SystemTransactionFixture.cs
  src/NHibernate.Test/SystemTransactions/DistributedSystemTransactionFixture.cs
  src/NHibernate.Test/SystemTransactions/SystemTransactionFixture.cs
  src/NHibernate.Test/TestDialect.cs
  src/NHibernate.Test/TestDialects/PostgreSQL83TestDialect.cs
  src/NHibernate/AdoNet/ConnectionManager.cs
  src/NHibernate/Async/Transaction/AdoNetWithSystemTransactionFactory.cs
  src/NHibernate/Transaction/AdoNetWithSystemTransactionFactory.cs
Labels: t: Fix

#2200 Release 5.2.6
  appveyor.yml
  build-common/NHibernate.props
  build-common/common.xml
  releasenotes.txt
Labels: c: Documentation, p: Minor, t: Task

#2206 Fix dependent transaction failure in 5.1.x
  appveyor.yml
  build-common/NHibernate.props
  build-common/common.xml
  releasenotes.txt
  src/AsyncGenerator.yml
  src/NHibernate.Test/Async/SystemTransactions/DistributedSystemTransactionFixture.cs
  src/NHibernate.Test/Async/SystemTransactions/SystemTransactionFixture.cs
  src/NHibernate.Test/SystemTransactions/DistributedSystemTransactionFixture.cs
  src/NHibernate.Test/SystemTransactions/SystemTransactionFixture.cs
  src/NHibernate.Test/TestDialect.cs
  src/NHibernate.Test/TestDialects/PostgreSQL83TestDialect.cs
  src/NHibernate/AdoNet/ConnectionManager.cs
  src/NHibernate/Async/Transaction/AdoNetWithSystemTransactionFactory.cs
  src/NHibernate/Transaction/AdoNetWithSystemTransactionFactory.cs
Labels: t: Fix

#2207 Fix dependent transaction failure in 5.0.x
  build-common/NHibernate.props
  build-common/common.xml
  releasenotes.txt
  src/AsyncGenerator.yml
  src/NHibernate.Test/Async/SystemTransactions/DistributedSystemTransactionFixture.cs
  src/NHibernate.Test/Async/SystemTransactions/SystemTransactionFixture.cs
  src/NHibernate.Test/SystemTransactions/DistributedSystemTransactionFixture.cs
  src/NHibernate.Test/SystemTransactions/SystemTransactionFixture.cs
  src/NHibernate.Test/TestDialect.cs
  src/NHibernate.Test/TestDialects/PostgreSQL83TestDialect.cs
  src/NHibernate/AdoNet/ConnectionManager.cs
  src/NHibernate/Async/Transaction/AdoNetWithSystemTransactionFactory.cs
  src/NHibernate/Transaction/AdoNetWithSystemTransactionFactory.cs
Labels: r: Fixed, t: Fix

#2212 Fix build menu for running NUnit tests with 3.10.0
  ShowBuildMenu.bat
Labels: t: Fix

#2215 Fix ShowBuildMenu.sh
  ShowBuildMenu.sh
Labels: c: Toolset, p: Minor, t: Bug

#2213 Add a shortcut to reduce Transaction.Current reads
  src/NHibernate.Test/Async/SystemTransactions/SystemTransactionFixture.cs
  src/NHibernate.Test/SystemTransactions/SystemTransactionFixture.cs
  src/NHibernate/Async/Transaction/AdoNetWithSystemTransactionFactory.cs
  src/NHibernate/Transaction/AdoNetWithSystemTransactionFactory.cs
Labels: c: Core, p: Minor, t: Improvement

#2220 Restrict #2218 tests to only dialects that are supported
  src/NHibernate.Test/Async/NHSpecificTest/NH2951/Fixture.cs
  src/NHibernate.Test/NHSpecificTest/NH2951/Fixture.cs
Labels: t: Fix

#2219 Fix BuildTool output path
  ShowBuildMenu.bat
  ShowBuildMenu.sh
Labels: c: Toolset, p: Trivial, t: Bug, t: Fix

#2225 Avoid unnecessary locking via MethodImplOptions.Synchronized
  src/NHibernate/Stat/StatisticsImpl.cs
  src/NHibernate/Util/SimpleMRUCache.cs
  src/NHibernate/Util/SoftLimitMRUCache.cs
Labels: c: Core, p: Trivial, t: Improvement

#2226 Use DateTime.UtcNow for timestamps
  src/NHibernate/Cache/NoCacheProvider.cs
  src/NHibernate/Cache/Timestamper.cs
  src/NHibernate/Id/CounterGenerator.cs
Labels: c: Core, p: Trivial, possible breaking change, t: Improvement

#2223 Short-Circuit SessionFactoryImpl.Close() when already closed
  src/NHibernate/Async/Impl/SessionFactoryImpl.cs
  src/NHibernate/Impl/SessionFactoryImpl.cs
Labels: c: Core, p: Trivial, t: Improvement

#2210 Support LINQ GroupBy subquery
  src/NHibernate.Test/Async/Linq/NestedSelectsTests.cs
  src/NHibernate.Test/Linq/NestedSelectsTests.cs
  src/NHibernate/Linq/GroupBy/AggregatingGroupByRewriter.cs
  src/NHibernate/Linq/NestedSelects/NestedSelectRewriter.cs
  src/NHibernate/Linq/Visitors/QueryModelVisitor.cs
Labels: c: Linq Provider, p: Minor, t: Improvement

#2231 Invalid alias name used in Linq Joins
  src/NHibernate.Test/Async/Linq/ByMethod/JoinTests.cs
  src/NHibernate.Test/Linq/ByMethod/JoinTests.cs
  src/NHibernate/Linq/Visitors/QueryModelVisitor.cs
Labels: c: Linq Provider, p: Minor, r: Fixed, t: Bug

#2209 IN clause support in hql for composite keys on databases without row value constructor support
  src/NHibernate.Test/Async/CompositeId/ClassWithCompositeIdFixture.cs
  src/NHibernate.Test/CompositeId/ClassWithCompositeIdFixture.cs
  src/NHibernate/Hql/Ast/ANTLR/Tree/BinaryLogicOperatorNode.cs
  src/NHibernate/Hql/Ast/ANTLR/Tree/InLogicOperatorNode.cs
  src/NHibernate/NHibernate.csproj
Labels: c: Core, p: Minor, t: New Feature
