Repository nhibernate/nhibernate-core, pull requests merged in 2020-09, with the labels that each got.

#2480 Modification to allow Linq subqueries to have paging (OrderBy/Take)
  src/NHibernate.Test/Async/Linq/WhereSubqueryTests.cs
  src/NHibernate.Test/Linq/WhereSubqueryTests.cs
  src/NHibernate/Linq/GroupBy/PagingRewriter.cs
Labels: r: Fixed, t: Fix

#2491 Avoid unnecessary casting for Linq provider
  src/NHibernate.DomainModel/Northwind/Entities/Northwind.cs
  src/NHibernate.DomainModel/Northwind/Entities/NumericEntity.cs
  src/NHibernate.DomainModel/Northwind/Mappings/NumericEntity.hbm.xml
  src/NHibernate.Test/Async/Linq/NullComparisonTests.cs
  src/NHibernate.Test/Async/Linq/ParameterTests.cs
  src/NHibernate.Test/DbScripts/MsSql2008DialectLinqReadonlyCreateScript.sql
  src/NHibernate.Test/DbScripts/MsSql2008DialectLinqReadonlyDropScript.sql
  src/NHibernate.Test/DbScripts/MsSql2012DialectLinqReadonlyCreateScript.sql
  src/NHibernate.Test/DbScripts/MsSql2012DialectLinqReadonlyDropScript.sql
  src/NHibernate.Test/DbScripts/PostgreSQL83DialectLinqReadonlyCreateScript.sql
  src/NHibernate.Test/DbScripts/PostgreSQL83DialectLinqReadonlyDropScript.sql
  src/NHibernate.Test/Linq/LinqReadonlyTestsContext.cs
  src/NHibernate.Test/Linq/LinqTestCase.cs
  src/NHibernate.Test/Linq/NullComparisonTests.cs
  src/NHibernate.Test/Linq/ParameterTests.cs
  src/NHibernate.Test/Linq/ParameterTypeLocatorTests.cs
  src/NHibernate/Linq/ExpressionTransformers/RemoveRedundantCast.cs
  src/NHibernate/Linq/Visitors/ExpressionParameterVisitor.cs
  src/NHibernate/Linq/Visitors/HqlGeneratorExpressionVisitor.cs
  src/NHibernate/Linq/Visitors/NhPartialEvaluatingExpressionVisitor.cs
  src/NHibernate/Linq/Visitors/ParameterTypeLocator.cs
  src/NHibernate/Type/SingleType.cs
  src/NHibernate/Util/TypeExtensions.cs
Labels: t: Fix

#2519 Fix parameter caching for Linq provider
  src/NHibernate.Test/Async/Linq/ConstantTest.cs
  src/NHibernate.Test/Linq/ConstantTest.cs
  src/NHibernate/Linq/NhLinqExpression.cs
  src/NHibernate/Linq/Visitors/SelectClauseNominator.cs
  src/NHibernate/Linq/Visitors/VisitorParameters.cs
Labels: Regression, c: Linq Provider, p: Minor, t: Bug

#2461 Remove persistent collections Equals/GetHashCode overrides
  src/NHibernate/Collection/Generic/PersistentGenericList.cs
  src/NHibernate/Collection/Generic/PersistentGenericMap.cs
  src/NHibernate/Collection/Generic/PersistentGenericSet.cs
Labels: c: Core, p: Minor, possible breaking change, t: Improvement

#2487 Throw for Criteria over not mapped entity
  src/NHibernate.Test/Async/Criteria/CriteriaQueryTest.cs
  src/NHibernate.Test/Async/Events/Collections/AbstractCollectionEventFixture.cs
  src/NHibernate.Test/Async/NHSpecificTest/NH1159/Fixture.cs
  src/NHibernate.Test/Async/NHSpecificTest/NH1688/Fixture.cs
  src/NHibernate.Test/Async/TransactionTest/TransactionNotificationFixture.cs
  src/NHibernate.Test/Criteria/CriteriaQueryTest.cs
  src/NHibernate.Test/Events/Collections/AbstractCollectionEventFixture.cs
  src/NHibernate.Test/NHSpecificTest/NH1159/ContactTitle.cs
  src/NHibernate.Test/NHSpecificTest/NH1159/Fixture.cs
  src/NHibernate.Test/NHSpecificTest/NH1688/Fixture.cs
  src/NHibernate.Test/SystemTransactions/TransactionNotificationFixture.cs
  src/NHibernate.Test/TransactionTest/TransactionNotificationFixture.cs
  src/NHibernate/Async/Impl/SessionImpl.cs
  src/NHibernate/Impl/SessionImpl.cs
Labels: possible breaking change, r: Fixed, t: Fix

#2517 Fix Linq Fetch over component after fetching an association
  src/NHibernate.Test/Async/FetchLazyProperties/FetchLazyPropertiesFixture.cs
  src/NHibernate.Test/FetchLazyProperties/FetchLazyPropertiesFixture.cs
  src/NHibernate/Linq/IntermediateHqlTree.cs
  src/NHibernate/Linq/Visitors/ResultOperatorProcessors/ProcessFetch.cs
Labels: t: Fix

#2504 Throw for LINQ queries on unmapped entities
  src/NHibernate.Test/Async/Linq/FunctionTests.cs
  src/NHibernate.Test/Async/Linq/LinqQuerySamples.cs
  src/NHibernate.Test/Linq/FunctionTests.cs
  src/NHibernate.Test/Linq/LinqQuerySamples.cs
  src/NHibernate.Test/TestCase.cs
  src/NHibernate/Hql/Ast/ANTLR/AstPolymorphicProcessor.cs
  src/NHibernate/Hql/Ast/ANTLR/PolymorphicQuerySourceDetector.cs
Labels: possible breaking change, t: Fix

#2496 Reuse joins generated by Where and OrderBy methods when fetching for Linq provider
  src/NHibernate.Test/Async/Linq/EagerLoadTests.cs
  src/NHibernate.Test/Linq/EagerLoadTests.cs
  src/NHibernate/Linq/Visitors/QueryModelVisitor.cs
  src/NHibernate/Linq/Visitors/ResultOperatorProcessors/ProcessFetch.cs
Labels: r: Fixed, t: Fix

#2521 Fix wrong order by with ordered collection fetch in Criteria
  src/NHibernate.Test/Async/Criteria/CriteriaQueryTest.cs
  src/NHibernate.Test/Criteria/Animal.cs
  src/NHibernate.Test/Criteria/CriteriaQueryTest.cs
  src/NHibernate/Loader/JoinWalker.cs
Labels: t: Fix

#2513 Fix wrong inner join fetch on not lazy component key-many-to-one property in Criteria
  src/NHibernate.Test/Async/NHSpecificTest/NH3813/FixtureByCode.cs
  src/NHibernate.Test/NHSpecificTest/NH3813/Entities.cs
  src/NHibernate.Test/NHSpecificTest/NH3813/FixtureByCode.cs
  src/NHibernate/Loader/Criteria/CriteriaJoinWalker.cs
Labels: t: Fix

#2520 Fix parameter detection for Contains method for Linq provider
  src/NHibernate.DomainModel/Northwind/Entities/AnotherEntityRequired.cs
  src/NHibernate.DomainModel/Northwind/Mappings/AnotherEntityRequired.hbm.xml
  src/NHibernate.Test/Async/Linq/ParameterTests.cs
  src/NHibernate.Test/Linq/ParameterTests.cs
  src/NHibernate/Linq/Visitors/ParameterTypeLocator.cs
Labels: t: Fix

#2455 #2454 fix ConditionalProjection GetType from outer query
  src/NHibernate.Test/Async/NHSpecificTest/GH2454/FixtureByCode.cs
  src/NHibernate.Test/NHSpecificTest/GH2454/Domain.cs
  src/NHibernate.Test/NHSpecificTest/GH2454/FixtureByCode.cs
  src/NHibernate/Loader/Criteria/CriteriaQueryTranslator.cs
Labels: t: Fix

#2527 Release 5.3.3
  build-common/NHibernate.props
  releasenotes.txt
Labels: c: Core, p: Minor, t: Task

#2361 Table group joins support in hql
  src/NHibernate.Test/Async/Hql/Ast/WithClauseFixture.cs
  src/NHibernate.Test/Async/Hql/EntityJoinHqlTest.cs
  src/NHibernate.Test/Async/NHSpecificTest/NH2049/Fixture2049.cs
  src/NHibernate.Test/Async/NHSpecificTest/NH2208/Filter.cs
  src/NHibernate.Test/Hql/Ast/WithClauseFixture.cs
  src/NHibernate.Test/Hql/EntityJoinHqlTest.cs
  src/NHibernate.Test/NHSpecificTest/NH2049/Fixture2049.cs
  src/NHibernate.Test/NHSpecificTest/NH2208/Filter.cs
  src/NHibernate/Engine/JoinSequence.cs
  src/NHibernate/Hql/Ast/ANTLR/HqlSqlWalker.cs
  src/NHibernate/Hql/Ast/ANTLR/Tree/EntityJoinFromElement.cs
  src/NHibernate/Hql/Ast/ANTLR/Tree/EntityJoinJoinSequenceImpl.cs
  src/NHibernate/Hql/Ast/ANTLR/Tree/FromElement.cs
  src/NHibernate/Hql/Ast/ANTLR/Tree/FromElementType.cs
  src/NHibernate/Hql/Ast/ANTLR/Util/JoinProcessor.cs
  src/NHibernate/Persister/Entity/AbstractEntityPersister.cs
  src/NHibernate/SqlCommand/ANSIJoinFragment.cs
  src/NHibernate/SqlCommand/SqlString.cs
  src/NHibernate/SqlCommand/SqlStringHelper.cs
Labels: c: Core, p: Minor, t: New Feature

#2542 Fix parameter detection for expression arguments
  src/NHibernate.Test/Async/Linq/WhereSubqueryTests.cs
  src/NHibernate.Test/Linq/WhereSubqueryTests.cs
  src/NHibernate/Linq/Visitors/NhPartialEvaluatingExpressionVisitor.cs
Labels: t: Fix

#2550 Apply filters for entity joins in hql
  src/NHibernate.Test/Async/NHSpecificTest/GH2549/Fixture.cs
  src/NHibernate.Test/NHSpecificTest/GH2549/Fixture.cs
  src/NHibernate.Test/NHSpecificTest/GH2549/Mappings.hbm.xml
  src/NHibernate.Test/NHSpecificTest/GH2549/Model.cs
  src/NHibernate/Hql/Ast/ANTLR/Tree/EntityJoinFromElement.cs
  src/NHibernate/Hql/Ast/ANTLR/Tree/EntityJoinJoinSequenceImpl.cs
Labels: t: Fix

#2546 Enable named parameters on DB2CoreDriver
  src/NHibernate/Driver/DB2CoreDriver.cs
Labels: c: DataProviders / Dialects, p: Minor, possible breaking change, t: Improvement

#2548 Mark DB2Dialect as not supporting null columns in unique constraint
  src/NHibernate/Dialect/DB2Dialect.cs
Labels: c: DataProviders / Dialects, p: Trivial, t: Bug

#2547 Fix paging in DB2Dialect
  src/NHibernate.Test/DialectTest/DB2DialectFixture.cs
  src/NHibernate.Test/ReadOnly/TextHolder.cs
  src/NHibernate/Dialect/DB2Dialect.cs
Labels: c: DataProviders / Dialects, p: Minor, t: Bug

#2541 #2540 LINQ SELECT tests with WHERE subquery
  src/NHibernate.Test/Async/Linq/NestedSelectsTests.cs
  src/NHibernate.Test/Linq/NestedSelectsTests.cs
Labels: c: Tests

#2555 Add spaces around concat operator
  src/NHibernate/Dialect/Dialect.cs
Labels: c: DataProviders / Dialects, p: Trivial, t: Improvement

#2558 Fix caching linq query with ThenFetchMany
  src/NHibernate.Test/Async/NHSpecificTest/GH2559/FixtureByCode.cs
  src/NHibernate.Test/NHSpecificTest/GH2559/Car.cs
  src/NHibernate.Test/NHSpecificTest/GH2559/Child.cs
  src/NHibernate.Test/NHSpecificTest/GH2559/FixtureByCode.cs
  src/NHibernate.Test/NHSpecificTest/GH2559/Person.cs
  src/NHibernate.Test/NHSpecificTest/GH2559/Pet.cs
  src/NHibernate/Async/Type/CollectionType.cs
  src/NHibernate/Type/CollectionType.cs
Labels: t: Fix

#2556 Register right function for Firebird and PostgreSQL
  src/NHibernate.Test/Async/Legacy/SQLFunctionsTest.cs
  src/NHibernate.Test/Legacy/SQLFunctionsTest.cs
  src/NHibernate/Dialect/FirebirdDialect.cs
  src/NHibernate/Dialect/PostgreSQLDialect.cs
Labels: c: DataProviders / Dialects, p: Minor, t: Improvement

#2570 Update Relinq and LinFu links
  README.md
Labels: c: Documentation, p: Trivial, t: Task

#2571 Default value for CancellationToken in IQueryBatch.GetResultAsync
  src/AsyncGenerator.yml
  src/NHibernate.Test/Async/CacheTest/BatchableCacheFixture.cs
  src/NHibernate.Test/Async/Criteria/Lambda/IntegrationFixture.cs
  src/NHibernate.Test/Async/Futures/QueryBatchFixture.cs
  src/NHibernate.Test/Async/NHSpecificTest/DataReaderWrapperTest/Fixture.cs
  src/NHibernate.Test/Async/NHSpecificTest/NH1253/Fixture.cs
  src/NHibernate.Test/Async/NHSpecificTest/NH1508/Fixture.cs
  src/NHibernate.Test/Async/NHSpecificTest/NH1609/Fixture.cs
  src/NHibernate.Test/Async/NHSpecificTest/NH1836/Fixture.cs
  src/NHibernate.Test/Async/NHSpecificTest/NH1869/Fixture.cs
  src/NHibernate.Test/Async/NHSpecificTest/NH2195/SQLiteMultiCriteriaTest.cs
  src/NHibernate.Test/Async/NHSpecificTest/NH2201/Fixture.cs
  src/NHibernate.Test/Async/NHSpecificTest/NH2959/Fixture.cs
  src/NHibernate.Test/Async/NHSpecificTest/SqlConverterAndMultiQuery/Fixture.cs
  src/NHibernate.Test/Async/Pagination/CustomDialectFixture.cs
  src/NHibernate.Test/Async/QueryTest/QueryBatchFixture.cs
  src/NHibernate.Test/Async/Stats/StatsFixture.cs
  src/NHibernate/Async/Multi/IQueryBatch.cs
  src/NHibernate/Async/Multi/QueryBatch.cs
Labels: c: Async, c: Core, p: Minor, t: Improvement
