Repository nhibernate/nhibernate-core, pull requests merged in 2020-10, with the labels that each got.

#2581 Fix joining with an inherited property from another table for Linq provider
  src/NHibernate.Test/Async/Linq/ByMethod/JoinTests.cs
  src/NHibernate.Test/Linq/ByMethod/JoinTests.cs
  src/NHibernate/Linq/Visitors/QueryModelVisitor.cs
Labels: t: Fix

#2582 Remove no longer used code in QueryModelVisitor
  src/NHibernate/Linq/Clauses/NhJoinClause.cs
  src/NHibernate/Linq/Visitors/QueryModelVisitor.cs
Labels: c: Linq Provider, p: Minor, t: Task

#2501 Upgrade MySql client and remove allowed failures on CI builds
  .travis.yml
  appveyor.yml
  src/NHibernate.Test/NHibernate.Test.csproj
  src/NHibernate/Dialect/MySQLDialect.cs
Labels: c: Tests, p: Trivial, t: Task

#2545 Table group joins for subclasses in Criteria
  src/NHibernate.Test/Async/NHSpecificTest/NH2049/Fixture2049.cs
  src/NHibernate.Test/Async/NHSpecificTest/NH2208/Filter.cs
  src/NHibernate.Test/NHSpecificTest/NH2049/Fixture2049.cs
  src/NHibernate.Test/NHSpecificTest/NH2208/Filter.cs
  src/NHibernate/Engine/IJoin.cs
  src/NHibernate/Engine/JoinSequence.cs
  src/NHibernate/Engine/TableGroupJoinHelper.cs
  src/NHibernate/Loader/JoinWalker.cs
  src/NHibernate/Loader/OuterJoinableAssociation.cs
Labels: c: Core, p: Minor, t: New Feature

#2492 Replace casting with NodeType checks in Criteria ExpressionProcessor
  src/NHibernate/Impl/ExpressionProcessor.cs
Labels: c: Core, p: Trivial, t: Improvement
