Repository nhibernate/nhibernate-core, pull requests merged in 2020-07, with the labels that each got.

#2365 Add Linq parameter type detection
  src/NHibernate.DomainModel/Northwind/Entities/DynamicUser.cs
  src/NHibernate.DomainModel/Northwind/Entities/Northwind.cs
  src/NHibernate.DomainModel/Northwind/Entities/User.cs
  src/NHibernate.DomainModel/Northwind/Mappings/DynamicUser.hbm.xml
  src/NHibernate.DomainModel/Northwind/Mappings/User.hbm.xml
  src/NHibernate.Test/Async/Linq/EnumTests.cs
  src/NHibernate.Test/Async/Linq/ParameterTests.cs
  src/NHibernate.Test/Linq/ConstantTest.cs
  src/NHibernate.Test/Linq/EnumTests.cs
  src/NHibernate.Test/Linq/LinqTestCase.cs
  src/NHibernate.Test/Linq/ParameterTests.cs
  src/NHibernate.Test/Linq/ParameterTypeLocatorTests.cs
  src/NHibernate.Test/Linq/TryGetMappedTests.cs
  src/NHibernate.Test/NHSpecificTest/GH1526/Fixture.cs
  src/NHibernate/Async/Linq/DefaultQueryProvider.cs
  src/NHibernate/Driver/OdbcDriver.cs
  src/NHibernate/Driver/SqlClientDriver.cs
  src/NHibernate/Driver/SqlServerCeDriver.cs
  src/NHibernate/Hql/Ast/ANTLR/ASTQueryTranslatorFactory.cs
  src/NHibernate/Hql/Ast/ANTLR/HqlSqlWalker.cs
  src/NHibernate/Hql/Ast/ANTLR/QueryTranslatorImpl.cs
  src/NHibernate/Hql/Ast/ANTLR/Tree/BetweenOperatorNode.cs
  src/NHibernate/Hql/Ast/ANTLR/Tree/BinaryArithmeticOperatorNode.cs
  src/NHibernate/Hql/Ast/ANTLR/Tree/BinaryLogicOperatorNode.cs
  src/NHibernate/Hql/Ast/ANTLR/Tree/InLogicOperatorNode.cs
  src/NHibernate/Impl/AbstractQueryImpl.cs
  src/NHibernate/Linq/DefaultQueryProvider.cs
  src/NHibernate/Linq/Functions/BaseHqlGeneratorForMethod.cs
  src/NHibernate/Linq/Functions/GetValueOrDefaultGenerator.cs
  src/NHibernate/Linq/Functions/IHqlGeneratorForMethod.cs
  src/NHibernate/Linq/Functions/QueryableGenerator.cs
  src/NHibernate/Linq/Functions/StringGenerator.cs
  src/NHibernate/Linq/NhLinqExpression.cs
  src/NHibernate/Linq/ReWriters/AddJoinsReWriter.cs
  src/NHibernate/Linq/Visitors/ExpressionKeyVisitor.cs
  src/NHibernate/Linq/Visitors/ExpressionParameterVisitor.cs
  src/NHibernate/Linq/Visitors/HqlGeneratorExpressionVisitor.cs
  src/NHibernate/Linq/Visitors/MemberExpressionJoinDetector.cs
  src/NHibernate/Linq/Visitors/ParameterTypeLocator.cs
  src/NHibernate/Linq/Visitors/VisitorUtil.cs
  src/NHibernate/Linq/Visitors/WhereJoinDetector.cs
  src/NHibernate/Param/NamedParameter.cs
  src/NHibernate/Util/ExpressionsHelper.cs
  src/NHibernate/Util/ParameterHelper.cs
  src/NHibernate/Util/ReflectionCache.cs
Labels: c: Linq Provider, p: Minor, t: Bug

#2428 Fix NRE when having subselect and nullable value selection for Linq query provider
  src/NHibernate.Test/Async/Linq/SelectionTests.cs
  src/NHibernate.Test/Linq/SelectionTests.cs
  src/NHibernate/Linq/NestedSelects/SelectClauseRewriter.cs
Labels: t: Fix

#2429 Fix NRE in SchemaUpdate and SchemaExport Execute method for collection mappings
  src/NHibernate.Test/Tools/hbm2ddl/SchemaMetadataUpdaterTest/HeavyEntity.hbm.xml
  src/NHibernate.Test/Tools/hbm2ddl/SchemaMetadataUpdaterTest/Order.cs
  src/NHibernate.Test/Tools/hbm2ddl/SchemaMetadataUpdaterTest/OrderRow.cs
  src/NHibernate/Tool/hbm2ddl/SchemaMetadataUpdater.cs
Labels: t: Fix

#2430 Document cache.serializer setting of CoreDistributedCache
  doc/reference/modules/nhibernate_caches.xml
Labels: c: Documentation, p: Trivial, t: New Feature

#2010 Add new collection operation queue mechanism
  src/NHibernate.Test/Async/Extralazy/ExtraLazyFixture.cs
  src/NHibernate.Test/Extralazy/Company.cs
  src/NHibernate.Test/Extralazy/CreditCard.cs
  src/NHibernate.Test/Extralazy/ExtraLazyFixture.cs
  src/NHibernate.Test/Extralazy/User.cs
  src/NHibernate.Test/Extralazy/UserGroup.hbm.xml
  src/NHibernate.Test/Extralazy/UserPermission.cs
  src/NHibernate.Test/Extralazy/UserSetting.cs
  src/NHibernate/Async/Collection/AbstractPersistentCollection.cs
  src/NHibernate/Async/Collection/Generic/PersistentGenericBag.cs
  src/NHibernate/Async/Collection/Generic/PersistentGenericList.cs
  src/NHibernate/Async/Collection/Generic/PersistentGenericMap.cs
  src/NHibernate/Async/Collection/Generic/PersistentGenericSet.cs
  src/NHibernate/Collection/AbstractPersistentCollection.cs
  src/NHibernate/Collection/Generic/PersistentGenericBag.cs
  src/NHibernate/Collection/Generic/PersistentGenericList.cs
  src/NHibernate/Collection/Generic/PersistentGenericMap.cs
  src/NHibernate/Collection/Generic/PersistentGenericSet.cs
  src/NHibernate/Collection/Trackers/AbstractCollectionQueueOperationTracker.cs
  src/NHibernate/Collection/Trackers/AbstractMapQueueOperationTracker.cs
  src/NHibernate/Collection/Trackers/AbstractQueueOperationTracker.cs
  src/NHibernate/Collection/Trackers/BagQueueOperationTracker.cs
  src/NHibernate/Collection/Trackers/ClearedListQueueOperationTracker.cs
  src/NHibernate/Collection/Trackers/CollectionQueueOperationTracker.cs
  src/NHibernate/Collection/Trackers/IndexedListQueueOperationTracker.cs
  src/NHibernate/Collection/Trackers/ListQueueOperationTracker.cs
  src/NHibernate/Collection/Trackers/MapQueueOperationTracker.cs
  src/NHibernate/Collection/Trackers/NonIndexedListQueueOperationTracker.cs
  src/NHibernate/Collection/Trackers/SetQueueOperationTracker.cs
Labels: c: Core, p: Minor, t: Improvement

#2431 Document the configuration provider
  doc/reference/modules/configuration.xml
Labels: t: Fix

#2433 Improve slightly mapping documentation
  doc/reference/modules/basic_mapping.xml
  doc/reference/modules/nhibernate_mapping_attributes.xml
  doc/reference/modules/quickstart.xml
Labels: c: Documentation, p: Trivial, t: Task

#2432 Document the caches configuration providers
  doc/reference/modules/nhibernate_caches.xml
Labels: c: Documentation, p: Trivial, t: Task

#2388 Release 5.3
  build-common/NHibernate.props
  releasenotes.txt
Labels: c: Core, p: Minor, t: Task

#2436 Fix old http://nhibernate.info URIs
  HowInstall.txt
  README.md
  build-common/NHibernate.props
  doc/reference/modules/nhibernate_mapping_attributes.xml
  doc/reference/modules/preface.xml
  doc/reference/modules/toolset_guide.xml
Labels: c: Documentation, p: Trivial, t: Task

#2435 Fix iconUrl warning
  build-common/NHibernate.props
  src/NHibernate/NHibernate.csproj
Labels: c: Toolset, p: Trivial, t: Task

#2438 Fix invalid cast on nullable custom type with Linq
  src/NHibernate.Test/Async/NHSpecificTest/GH2437/Fixture.cs
  src/NHibernate.Test/NHSpecificTest/GH2437/Fixture.cs
  src/NHibernate.Test/NHSpecificTest/GH2437/SqlBoolean.cs
  src/NHibernate.Test/NHSpecificTest/GH2437/SqlNumberDate.cs
  src/NHibernate.Test/NHSpecificTest/GH2437/SqlNumberDateTime.cs
  src/NHibernate.Test/NHSpecificTest/GH2437/User.cs
  src/NHibernate.Test/NHSpecificTest/GH2437/UserMapping.cs
  src/NHibernate.Test/NHSpecificTest/GH2437/UserSession.cs
  src/NHibernate.Test/NHSpecificTest/GH2437/UserSessionMapping.cs
  src/NHibernate/Linq/Visitors/HqlGeneratorExpressionVisitor.cs
Labels: t: Fix

#2443 Fix detecting parameter types in subqueries for Linq provider
  src/NHibernate.Test/Linq/ParameterTypeLocatorTests.cs
  src/NHibernate/Util/ExpressionsHelper.cs
Labels: t: Fix

#2444 Fix InvalidCastException for Future Criteria with aliased fetches
  src/NHibernate.Test/Async/Criteria/SelectModeTest/SelectModeTest.cs
  src/NHibernate.Test/Criteria/SelectModeTest/SelectModeTest.cs
  src/NHibernate/Async/Multi/QueryBatchItemBase.cs
  src/NHibernate/Multi/QueryBatchItemBase.cs
Labels: t: Fix

#2447 Fix casting unsigned numeric types for Linq provider
  src/NHibernate.Test/Async/NHSpecificTest/GH2445/Fixture.cs
  src/NHibernate.Test/NHSpecificTest/GH2445/Fixture.cs
  src/NHibernate.Test/NHSpecificTest/GH2445/UnsignedEntity.cs
  src/NHibernate/Hql/Ast/HqlTreeNode.cs
Labels: t: Fix

#2450 Release 5.3.1
  build-common/NHibernate.props
  releasenotes.txt
Labels: c: Core, p: Minor, t: Task

#2452 Merge 5.3.1
  build-common/NHibernate.props
  releasenotes.txt
  src/NHibernate.Test/Async/Criteria/SelectModeTest/SelectModeTest.cs
  src/NHibernate.Test/Async/NHSpecificTest/GH2437/Fixture.cs
  src/NHibernate.Test/Async/NHSpecificTest/GH2445/Fixture.cs
  src/NHibernate.Test/Criteria/SelectModeTest/SelectModeTest.cs
  src/NHibernate.Test/Linq/ParameterTypeLocatorTests.cs
  src/NHibernate.Test/NHSpecificTest/GH2437/Fixture.cs
  src/NHibernate.Test/NHSpecificTest/GH2437/SqlBoolean.cs
  src/NHibernate.Test/NHSpecificTest/GH2437/SqlNumberDate.cs
  src/NHibernate.Test/NHSpecificTest/GH2437/SqlNumberDateTime.cs
  src/NHibernate.Test/NHSpecificTest/GH2437/User.cs
  src/NHibernate.Test/NHSpecificTest/GH2437/UserMapping.cs
  src/NHibernate.Test/NHSpecificTest/GH2437/UserSession.cs
  src/NHibernate.Test/NHSpecificTest/GH2437/UserSessionMapping.cs
  src/NHibernate.Test/NHSpecificTest/GH2445/Fixture.cs
  src/NHibernate.Test/NHSpecificTest/GH2445/UnsignedEntity.cs
  src/NHibernate/Async/Multi/QueryBatchItemBase.cs
  src/NHibernate/Hql/Ast/HqlTreeNode.cs
  src/NHibernate/Linq/Visitors/HqlGeneratorExpressionVisitor.cs
  src/NHibernate/Multi/QueryBatchItemBase.cs
  src/NHibernate/NHibernate.csproj
  src/NHibernate/Util/ExpressionsHelper.cs
Labels: t: Fix

#2462 Fix parameters inside evaluatable expressions for Linq provider
  src/NHibernate.Test/Async/Linq/ParameterTests.cs
  src/NHibernate.Test/Linq/ParameterTests.cs
  src/NHibernate/Linq/Visitors/NhPartialEvaluatingExpressionVisitor.cs
Labels: t: Fix

#2459 Fix detecting parameter type for Contains method for Linq provider
  src/NHibernate.Test/Async/Linq/EnumTests.cs
  src/NHibernate.Test/Linq/EnumTests.cs
  src/NHibernate.Test/Linq/ParameterTypeLocatorTests.cs
  src/NHibernate/Linq/Visitors/ParameterTypeLocator.cs
Labels: t: Fix

#2464 Fix entity join for entity with discriminator
  src/NHibernate.Test/Async/NHSpecificTest/GH2463/Fixture.cs
  src/NHibernate.Test/NHSpecificTest/GH2463/Fixture.cs
  src/NHibernate/Hql/Ast/ANTLR/HqlSqlWalker.cs
Labels: t: Fix
