Repository nhibernate/nhibernate-core, pull requests merged in 2020-02, with the labels that each got.

#2120 Prevent calling UpdateTimestampsCache if query spaces are not changed
  src/NHibernate/Async/Cache/StandardQueryCache.cs
  src/NHibernate/Async/Cache/UpdateTimestampsCache.cs
  src/NHibernate/Async/Engine/ActionQueue.cs
  src/NHibernate/Cache/StandardQueryCache.cs
  src/NHibernate/Cache/UpdateTimestampsCache.cs
  src/NHibernate/Engine/ActionQueue.cs
Labels: t: Fix

#2097 Add support for fetching an individual lazy property with Criteria
  src/NHibernate.Test/Async/Criteria/SelectModeTest/SelectModeTest.cs
  src/NHibernate.Test/Criteria/SelectModeTest/Entities.cs
  src/NHibernate.Test/Criteria/SelectModeTest/SelectModeTest.cs
  src/NHibernate/Async/Persister/Collection/AbstractCollectionPersister.cs
  src/NHibernate/Async/Persister/Entity/AbstractEntityPersister.cs
  src/NHibernate/Impl/CriteriaImpl.cs
  src/NHibernate/Loader/AbstractEntityJoinWalker.cs
  src/NHibernate/Loader/Criteria/CriteriaJoinWalker.cs
  src/NHibernate/Loader/Criteria/CriteriaLoader.cs
  src/NHibernate/Loader/Hql/QueryLoader.cs
  src/NHibernate/Loader/JoinWalker.cs
  src/NHibernate/Loader/Loader.cs
  src/NHibernate/Loader/OuterJoinableAssociation.cs
  src/NHibernate/Persister/Collection/AbstractCollectionPersister.cs
  src/NHibernate/Persister/Collection/BasicCollectionPersister.cs
  src/NHibernate/Persister/Collection/CollectionPersister.cs
  src/NHibernate/Persister/Collection/OneToManyPersister.cs
  src/NHibernate/Persister/Entity/AbstractEntityPersister.cs
  src/NHibernate/Persister/Entity/ISupportSelectModeJoinable.cs
  src/NHibernate/SelectMode.cs
  src/NHibernate/Util/StringHelper.cs
Labels: c: Core, p: Minor, t: New Feature

#2036 Reduce cast usage for aggregate functions
  src/NHibernate.DomainModel/FooComponent.cs
  src/NHibernate.DomainModel/NHSpecific/NullableInt32.cs
  src/NHibernate.DomainModel/Northwind/Entities/Address.cs
  src/NHibernate.DomainModel/Northwind/Entities/IEntity.cs
  src/NHibernate.DomainModel/Northwind/Entities/Product.cs
  src/NHibernate.DomainModel/Northwind/Entities/User.cs
  src/NHibernate.Test/Async/Linq/SelectionTests.cs
  src/NHibernate.Test/Async/NHSpecificTest/GH2029/Fixture.cs
  src/NHibernate.Test/Linq/SelectionTests.cs
  src/NHibernate.Test/Linq/TryGetMappedTests.cs
  src/NHibernate.Test/NHSpecificTest/GH2029/Fixture.cs
  src/NHibernate.Test/NHSpecificTest/GH2029/TestClass.cs
  src/NHibernate/Dialect/Dialect.cs
  src/NHibernate/Dialect/Function/CastFunction.cs
  src/NHibernate/Dialect/MySQLDialect.cs
  src/NHibernate/Dialect/TypeNames.cs
  src/NHibernate/Hql/Ast/HqlTreeNode.cs
  src/NHibernate/Linq/Functions/ListIndexerGenerator.cs
  src/NHibernate/Linq/Visitors/HqlGeneratorExpressionVisitor.cs
  src/NHibernate/Tuple/Entity/EntityMetamodel.cs
  src/NHibernate/Util/ExpressionsHelper.cs
Labels: c: Linq Provider, p: Minor, t: Improvement

#2317 Add SetFlushMode to QueryOver and Linq
  src/NHibernate.Test/Async/Linq/QueryFlushModeTests.cs
  src/NHibernate.Test/Criteria/Lambda/QueryOverFixture.cs
  src/NHibernate.Test/Linq/QueryFlushModeTests.cs
  src/NHibernate/Linq/NhQueryableOptions.cs
  src/NHibernate/QueryOverExtensions.cs
Labels: t: Fix

#1996 Enhance nullability check for "==" and "!=" operators for LINQ provider
  src/NHibernate.DomainModel/Northwind/Entities/AnotherEntityRequired.cs
  src/NHibernate.DomainModel/Northwind/Entities/User.cs
  src/NHibernate.DomainModel/Northwind/Mappings/AnotherEntityRequired.hbm.xml
  src/NHibernate.DomainModel/Northwind/Mappings/User.hbm.xml
  src/NHibernate.Test/Async/Linq/NullComparisonTests.cs
  src/NHibernate.Test/DbScripts/MsSql2008DialectLinqReadonlyCreateScript.sql
  src/NHibernate.Test/DbScripts/MsSql2012DialectLinqReadonlyCreateScript.sql
  src/NHibernate.Test/DbScripts/PostgreSQL83DialectLinqReadonlyCreateScript.sql
  src/NHibernate.Test/Linq/LinqTestCase.cs
  src/NHibernate.Test/Linq/NorthwindDbCreator.cs
  src/NHibernate.Test/Linq/NullComparisonTests.cs
  src/NHibernate/Linq/Expressions/NhAggregatedExpression.cs
  src/NHibernate/Linq/Expressions/NhCountExpression.cs
  src/NHibernate/Linq/Functions/BaseHqlGeneratorForMethod.cs
  src/NHibernate/Linq/Functions/CompareGenerator.cs
  src/NHibernate/Linq/Functions/DictionaryGenerator.cs
  src/NHibernate/Linq/Functions/EqualsGenerator.cs
  src/NHibernate/Linq/Functions/GetValueOrDefaultGenerator.cs
  src/NHibernate/Linq/Functions/IHqlGeneratorForMethod.cs
  src/NHibernate/Linq/Functions/QueryableGenerator.cs
  src/NHibernate/Linq/Functions/StringGenerator.cs
  src/NHibernate/Linq/Visitors/HqlGeneratorExpressionVisitor.cs
  src/NHibernate/Linq/Visitors/NullableExpressionDetector.cs
Labels: t: Fix
