Repository nhibernate/nhibernate-core, pull requests merged in 2020-03, with the labels that each got.

#2319 Upgrade AsyncGenerator to 0.18.1
  Tools/packages.csproj
  src/NHibernate/Async/Collection/Generic/PersistentGenericBag.cs
  src/NHibernate/Async/Collection/Generic/PersistentGenericIdentifierBag.cs
  src/NHibernate/Async/Collection/Generic/PersistentGenericList.cs
  src/NHibernate/Async/Collection/Generic/PersistentGenericMap.cs
  src/NHibernate/Async/Collection/Generic/PersistentGenericSet.cs
  src/NHibernate/Async/Collection/PersistentArrayHolder.cs
  src/NHibernate/Async/Impl/AbstractQueryImpl2.cs
  src/NHibernate/Async/Impl/CollectionFilterImpl.cs
  src/NHibernate/Async/Impl/ExpressionQueryImpl.cs
  src/NHibernate/Async/Impl/SqlQueryImpl.cs
Labels: c: Async, p: Minor, t: Bug

#2327 Add cross join support for Hql and Linq query provider
  src/NHibernate.Test/Async/FetchLazyProperties/FetchLazyPropertiesFixture.cs
  src/NHibernate.Test/Async/Hql/EntityJoinHqlTest.cs
  src/NHibernate.Test/Async/Linq/ByMethod/JoinTests.cs
  src/NHibernate.Test/Async/Linq/LinqQuerySamples.cs
  src/NHibernate.Test/FetchLazyProperties/FetchLazyPropertiesFixture.cs
  src/NHibernate.Test/Hql/EntityJoinHqlTest.cs
  src/NHibernate.Test/Linq/ByMethod/JoinTests.cs
  src/NHibernate.Test/Linq/LinqQuerySamples.cs
  src/NHibernate.Test/TestCase.cs
  src/NHibernate/AdoNet/Util/BasicFormatter.cs
  src/NHibernate/Dialect/DB2Dialect.cs
  src/NHibernate/Dialect/Dialect.cs
  src/NHibernate/Dialect/InformixDialect0940.cs
  src/NHibernate/Dialect/Oracle10gDialect.cs
  src/NHibernate/Dialect/Oracle8iDialect.cs
  src/NHibernate/Dialect/SybaseASA9Dialect.cs
  src/NHibernate/Dialect/SybaseASE15Dialect.cs
  src/NHibernate/Hql/Ast/ANTLR/Hql.g
  src/NHibernate/Hql/Ast/ANTLR/HqlSqlWalker.g
  src/NHibernate/Hql/Ast/ANTLR/Util/JoinProcessor.cs
  src/NHibernate/Hql/Ast/HqlTreeBuilder.cs
  src/NHibernate/Hql/Ast/HqlTreeNode.cs
  src/NHibernate/Linq/Clauses/NhJoinClause.cs
  src/NHibernate/Linq/ReWriters/AddJoinsReWriter.cs
  src/NHibernate/Linq/Visitors/JoinBuilder.cs
  src/NHibernate/Linq/Visitors/QueryModelVisitor.cs
  src/NHibernate/Linq/Visitors/WhereJoinDetector.cs
  src/NHibernate/SqlCommand/ANSIJoinFragment.cs
  src/NHibernate/SqlCommand/JoinFragment.cs
Labels: c: Core, c: Linq Provider, p: Major, possible breaking change, t: New Feature

#1868 Db side methods
  doc/reference/modules/configuration.xml
  src/NHibernate.Test/Async/Linq/MiscellaneousTextFixture.cs
  src/NHibernate.Test/Async/Linq/PreEvaluationTests.cs
  src/NHibernate.Test/Linq/MiscellaneousTextFixture.cs
  src/NHibernate.Test/Linq/PreEvaluationTests.cs
  src/NHibernate.Test/Linq/TryGetMappedTests.cs
  src/NHibernate.Test/TestCase.cs
  src/NHibernate/Cfg/Environment.cs
  src/NHibernate/Cfg/Settings.cs
  src/NHibernate/Cfg/SettingsFactory.cs
  src/NHibernate/Dialect/DB2Dialect.cs
  src/NHibernate/Dialect/Dialect.cs
  src/NHibernate/Dialect/FirebirdDialect.cs
  src/NHibernate/Dialect/HanaDialectBase.cs
  src/NHibernate/Dialect/InformixDialect.cs
  src/NHibernate/Dialect/MsSql2000Dialect.cs
  src/NHibernate/Dialect/MsSql2008Dialect.cs
  src/NHibernate/Dialect/MsSqlCeDialect.cs
  src/NHibernate/Dialect/MySQL55Dialect.cs
  src/NHibernate/Dialect/MySQL5Dialect.cs
  src/NHibernate/Dialect/MySQLDialect.cs
  src/NHibernate/Dialect/Oracle10gDialect.cs
  src/NHibernate/Dialect/Oracle8iDialect.cs
  src/NHibernate/Dialect/Oracle9iDialect.cs
  src/NHibernate/Dialect/PostgreSQL81Dialect.cs
  src/NHibernate/Dialect/PostgreSQLDialect.cs
  src/NHibernate/Dialect/SQLiteDialect.cs
  src/NHibernate/Dialect/SybaseASA9Dialect.cs
  src/NHibernate/Dialect/SybaseASE15Dialect.cs
  src/NHibernate/Dialect/SybaseSQLAnywhere10Dialect.cs
  src/NHibernate/Dialect/SybaseSQLAnywhere12Dialect.cs
  src/NHibernate/Linq/Functions/DateTimeNowHqlGenerator.cs
  src/NHibernate/Linq/Functions/DefaultLinqToHqlGeneratorsRegistry.cs
  src/NHibernate/Linq/Functions/IAllowPreEvaluationHqlGenerator.cs
  src/NHibernate/Linq/Functions/IHqlGeneratorForMethod.cs
  src/NHibernate/Linq/Functions/IHqlGeneratorForProperty.cs
  src/NHibernate/Linq/Functions/NewGuidHqlGenerator.cs
  src/NHibernate/Linq/Functions/RandomHqlGenerator.cs
  src/NHibernate/Linq/NhLinqExpression.cs
  src/NHibernate/Linq/NhRelinqQueryParser.cs
  src/NHibernate/Linq/Visitors/MemberExpressionJoinDetector.cs
  src/NHibernate/Linq/Visitors/NhPartialEvaluatingExpressionVisitor.cs
  src/NHibernate/Linq/Visitors/NullableExpressionDetector.cs
  src/NHibernate/Linq/Visitors/SelectClauseNominator.cs
  src/NHibernate/Linq/Visitors/WhereJoinDetector.cs
  src/NHibernate/NHibernateUtil.cs
  src/NHibernate/Type/DateType.cs
  src/NHibernate/Type/LocalDateType.cs
  src/NHibernate/Util/ReflectHelper.cs
  src/NHibernate/nhibernate-configuration.xsd
Labels: t: Fix

#2337 Fix some NRE in work isolation and connection handling
  src/NHibernate/Async/Transaction/AdoNetTransactionFactory.cs
  src/NHibernate/Connection/ConnectionProvider.cs
  src/NHibernate/Transaction/AdoNetTransactionFactory.cs
Labels: t: Fix

#2321 Support setting parameters with a dynamic object
  src/NHibernate.Test/Async/Legacy/SQLFunctionsTest.cs
  src/NHibernate.Test/Async/Legacy/SQLLoaderTest.cs
  src/NHibernate.Test/Legacy/SQLFunctionsTest.cs
  src/NHibernate.Test/Legacy/SQLLoaderTest.cs
  src/NHibernate/Impl/AbstractQueryImpl.cs
Labels: t: Fix

#2323 Fix Linq Fetch/FetchMany after SelectMany method
  src/NHibernate.Test/Async/Linq/EagerLoadTests.cs
  src/NHibernate.Test/Linq/EagerLoadTests.cs
  src/NHibernate/Linq/Visitors/ResultOperatorProcessors/ProcessFetch.cs
Labels: t: Fix

#1627 Refactored session List<T> method for Criteria
  src/NHibernate.Test/Async/Criteria/DetachedCriteriaSerializable.cs
  src/NHibernate.Test/Criteria/DetachedCriteriaSerializable.cs
  src/NHibernate/Async/Impl/AbstractSessionImpl.cs
  src/NHibernate/Async/Impl/CriteriaImpl.cs
  src/NHibernate/Async/Impl/SessionImpl.cs
  src/NHibernate/Async/Impl/StatelessSessionImpl.cs
  src/NHibernate/Async/Loader/Criteria/CriteriaLoader.cs
  src/NHibernate/Impl/AbstractSessionImpl.cs
  src/NHibernate/Impl/CriteriaImpl.cs
  src/NHibernate/Impl/SessionImpl.cs
  src/NHibernate/Impl/StatelessSessionImpl.cs
  src/NHibernate/Loader/Criteria/CriteriaLoader.cs
  src/NHibernate/Util/EnumerableExtensions.cs
Labels: c: Core, p: Minor, t: Improvement

#2238 Call generic query.List from Linq queries
  src/NHibernate.Test/Linq/ByMethod/WithOptionsTests.cs
  src/NHibernate/Async/Linq/DefaultQueryProvider.cs
  src/NHibernate/Linq/DefaultQueryProvider.cs
  src/NHibernate/Linq/LinqExtensionMethods.cs
  src/NHibernate/Linq/NhQueryable.cs
Labels: c: Linq Provider, p: Minor, t: Improvement

#452 Fix custom sql loader with composite id
  src/AsyncGenerator.yml
  src/NHibernate.Test/Async/NHSpecificTest/NH3079/Fixture.cs
  src/NHibernate.Test/NHSpecificTest/NH3079/Employer.cs
  src/NHibernate.Test/NHSpecificTest/NH3079/EmployerCpId.cs
  src/NHibernate.Test/NHSpecificTest/NH3079/Employment.cs
  src/NHibernate.Test/NHSpecificTest/NH3079/EmploymentCpId.cs
  src/NHibernate.Test/NHSpecificTest/NH3079/Fixture.cs
  src/NHibernate.Test/NHSpecificTest/NH3079/Mappings.hbm.xml
  src/NHibernate.Test/NHSpecificTest/NH3079/Person.cs
  src/NHibernate.Test/NHSpecificTest/NH3079/PersonCpId.cs
  src/NHibernate.Test/NHSpecificTest/NH3079/PersonNoComponent.cs
  src/NHibernate/Async/Impl/SqlQueryImpl.cs
  src/NHibernate/Impl/AbstractQueryImpl.cs
  src/NHibernate/Impl/SqlQueryImpl.cs
Labels: t: Fix, to review

#2081 Force join for comparisons in hql when not null entity key can represent null entity
  src/NHibernate.Test/Async/Hql/EntityJoinHqlTest.cs
  src/NHibernate.Test/Hql/EntityJoinHqlTest.cs
  src/NHibernate.Test/Hql/EntityJoinHqlTestEntities.cs
  src/NHibernate/Hql/Ast/ANTLR/Tree/DotNode.cs
  src/NHibernate/Hql/Ast/ANTLR/Tree/FromElement.cs
Labels: r: Fixed, t: Fix
