Repository nhibernate/nhibernate-core, pull requests merged in 2020-01, with the labels that each got.

#2299 Proper query plan caching for DML LINQ queries
  src/NHibernate.Test/Async/Linq/ConstantTest.cs
  src/NHibernate.Test/Linq/ConstantTest.cs
  src/NHibernate/Linq/DmlExpressionRewriter.cs
  src/NHibernate/Linq/NhLinqExpression.cs
  src/NHibernate/Linq/Visitors/QueryModelVisitor.cs
Labels: c: Linq Provider, p: Major, t: Bug

#2302 Backport sqlite.binaryguid to configuration schema
  src/NHibernate/nhibernate-configuration.xsd
Labels: c: DataProviders / Dialects, p: Trivial, r: Fixed, t: Bug

#2304 Add logging for QueryBatch similar to Loader.DoQuery
  src/NHibernate/Async/Multi/QueryBatchItemBase.cs
  src/NHibernate/Multi/QueryBatchItemBase.cs
Labels: t: Fix

#2300 Do not cache ExpandedQueryExpression query plan if it's based on not cacheable query expression
  src/NHibernate.Test/Async/Linq/ConstantTest.cs
  src/NHibernate.Test/Linq/ConstantTest.cs
  src/NHibernate/Engine/Query/QueryPlanCache.cs
  src/NHibernate/IQueryExpression.cs
  src/NHibernate/Impl/ExpressionQueryImpl.cs
  src/NHibernate/Linq/NhLinqExpression.cs
Labels: t: Fix

#2303 Release 5.2.7
  appveyor.yml
  build-common/NHibernate.props
  build-common/common.xml
  releasenotes.txt
Labels: c: Documentation, p: Minor, t: Task

#2305 Backport Dml Linq Update Produce Wrong Sql
  appveyor.yml
  build-common/NHibernate.props
  build-common/common.xml
  releasenotes.txt
  src/NHibernate.Test/Async/Linq/ConstantTest.cs
  src/NHibernate.Test/Linq/ConstantTest.cs
  src/NHibernate/Engine/Query/QueryPlanCache.cs
  src/NHibernate/IQueryExpression.cs
  src/NHibernate/Impl/ExpressionQueryImpl.cs
  src/NHibernate/Linq/NhLinqExpression.cs
Labels: t: Fix
