Repository nhibernate/nhibernate-core, pull requests merged in 2020-04, with the labels that each got.

#2344 Fix a missing async regeneration in #2081
  src/NHibernate.Test/Async/Hql/EntityJoinHqlTest.cs
Labels: t: Fix

#2082 Use entities prepared by Loader in hql select projections
  src/NHibernate.Test/Async/NHSpecificTest/GH2064/OneToOneSelectProjectionFixture.cs
  src/NHibernate.Test/NHSpecificTest/GH2064/OneToOneEntity.cs
  src/NHibernate.Test/NHSpecificTest/GH2064/OneToOneSelectProjectionFixture.cs
  src/NHibernate.Test/NHSpecificTest/GH2064/ParentEntity.cs
  src/NHibernate/Async/Loader/Hql/QueryLoader.cs
  src/NHibernate/Hql/Ast/ANTLR/Tree/ConstructorNode.cs
  src/NHibernate/Hql/Ast/ANTLR/Tree/SelectClause.cs
  src/NHibernate/Loader/Hql/QueryLoader.cs
Labels: c: Core, p: Trivial, t: Improvement

#2090 Add support for caching fetched relations with Criteria
  src/NHibernate.DomainModel/Northwind/Entities/Northwind.cs
  src/NHibernate.DomainModel/Northwind/Entities/NorthwindQueryOver.cs
  src/NHibernate.Test/Async/Criteria/ReadonlyTests/QueryOverCacheableTests.cs
  src/NHibernate.Test/Async/Linq/QueryCacheableTests.cs
  src/NHibernate.Test/Criteria/ReadonlyTests/CriteriaNorthwindReadonlyTestCase.cs
  src/NHibernate.Test/Criteria/ReadonlyTests/QueryOverCacheableTests.cs
  src/NHibernate.Test/Criteria/ReadonlyTests/ReadonlyFixtureSetUp.cs
  src/NHibernate.Test/Linq/QueryCacheableTests.cs
  src/NHibernate/Async/Loader/Loader.cs
  src/NHibernate/Cache/QueryCacheResultBuilder.cs
  src/NHibernate/Hql/Ast/ANTLR/Tree/SelectClause.cs
  src/NHibernate/Loader/Criteria/CriteriaLoader.cs
  src/NHibernate/Loader/Custom/CustomLoader.cs
  src/NHibernate/Loader/Hql/QueryLoader.cs
  src/NHibernate/Loader/Loader.cs
  src/NHibernate/Loader/OuterJoinLoader.cs
  src/NHibernate/Transform/CacheableResultTransformer.cs
  src/NHibernate/Util/ArrayHelper.cs
  src/NHibernate/Util/EnumerableExtensions.cs
Labels: c: Core, p: Minor, t: New Feature

#2147 Improve async locking
  src/AsyncGenerator.yml
  src/NHibernate.Test/Async/UtilityTest/AsyncReaderWriterLockFixture.cs
  src/NHibernate.Test/NHibernate.Test.csproj
  src/NHibernate.Test/UtilityTest/AsyncReaderWriterLockFixture.cs
  src/NHibernate/Async/Cache/ReadWriteCache.cs
  src/NHibernate/Async/Cache/UpdateTimestampsCache.cs
  src/NHibernate/Async/Id/Enhanced/OptimizerFactory.cs
  src/NHibernate/Async/Id/Enhanced/TableGenerator.cs
  src/NHibernate/Async/Id/IncrementGenerator.cs
  src/NHibernate/Async/Id/SequenceHiLoGenerator.cs
  src/NHibernate/Async/Id/TableGenerator.cs
  src/NHibernate/Async/Id/TableHiLoGenerator.cs
  src/NHibernate/Cache/ReadWriteCache.cs
  src/NHibernate/Cache/UpdateTimestampsCache.cs
  src/NHibernate/Id/Enhanced/OptimizerFactory.cs
  src/NHibernate/Id/Enhanced/TableGenerator.cs
  src/NHibernate/Id/IncrementGenerator.cs
  src/NHibernate/Id/SequenceHiLoGenerator.cs
  src/NHibernate/Id/TableGenerator.cs
  src/NHibernate/Id/TableHiLoGenerator.cs
  src/NHibernate/Util/AsyncLock.cs
  src/NHibernate/Util/AsyncReaderWriterLock.cs
Labels: c: Async, c: Core, p: Major, t: Bug

#2235 Configure log4net from embedded resource log4net.xml in tests
  src/NHibernate.Test/App.config
  src/NHibernate.Test/Hql/Ast/ParsingFixture.cs
  src/NHibernate.Test/Log4netConfiguration.cs
  src/NHibernate.Test/NHSpecificTest/NH1587/Fixture.cs
  src/NHibernate.Test/NHibernate.Test.csproj
  src/NHibernate.Test/TestCase.cs
  src/NHibernate.Test/TestsContext.cs
  src/NHibernate.Test/TypesTest/TypeFactoryFixture.cs
  src/NHibernate.Test/log4net.xml
Labels: c: Tests, p: Minor, t: Improvement

#2156 Support basic arithmetic operations (+, -, *, /) in QueryOver
  src/NHibernate.Test/Async/Criteria/Lambda/IntegrationFixture.cs
  src/NHibernate.Test/Criteria/Lambda/IntegrationFixture.cs
  src/NHibernate/Criterion/ConstantProjection.cs
  src/NHibernate/Impl/ExpressionProcessor.cs
Labels: c: QueryOver, p: Minor, t: New Feature

#2346 Fix SQLite typing
  src/NHibernate/Dialect/SQLiteDialect.cs
  src/NHibernate/Type/TimeAsTimeSpanType.cs
Labels: c: DataProviders / Dialects, p: Minor, possible breaking change, t: Bug

#2322 Add support for OData group by queries
  src/NHibernate.Test/Async/Linq/ByMethod/GroupByTests.cs
  src/NHibernate.Test/Async/Linq/ODataTests.cs
  src/NHibernate.Test/Linq/ByMethod/GroupByTests.cs
  src/NHibernate.Test/Linq/ODataTests.cs
  src/NHibernate.Test/NHibernate.Test.csproj
  src/NHibernate/Linq/GroupBy/GroupBySelectClauseRewriter.cs
  src/NHibernate/Linq/GroupBy/GroupKeyNominator.cs
  src/NHibernate/Linq/GroupResultOperatorExtensions.cs
  src/NHibernate/Linq/Visitors/PagingRewriterSelectClauseVisitor.cs
  src/NHibernate/Linq/Visitors/TransparentIdentifierRemovingExpressionVisitor.cs
Labels: t: Fix

#2351 Get rid of JoinedEnumerable<T> and SingletonEnumerable<T>
  src/NHibernate.Test/UtilityTest/JoinedEnumerableGenericFixture.cs
  src/NHibernate.Test/UtilityTest/SingletonEnumerableFixture.cs
  src/NHibernate/Mapping/Component.cs
  src/NHibernate/Mapping/DenormalizedTable.cs
  src/NHibernate/Mapping/PersistentClass.cs
  src/NHibernate/Mapping/RootClass.cs
  src/NHibernate/Mapping/SingleTableSubclass.cs
  src/NHibernate/Mapping/Subclass.cs
  src/NHibernate/Util/JoinedEnumerable.cs
  src/NHibernate/Util/SingletonEnumerable.cs
Labels: c: Core, p: Trivial, t: Task

#2353 Update Microsoft.SourceLink.GitHub to 1.0.0
  src/NHibernate/NHibernate.csproj
Labels: c: Toolset, p: Trivial, t: Task

#2348 Use static ReferenceComparer for reference comparisons
  src/NHibernate/Collection/AbstractPersistentCollection.cs
  src/NHibernate/IdentityEqualityComparer.cs
  src/NHibernate/Proxy/Poco/BasicLazyInitializer.cs
  src/NHibernate/Transform/DistinctRootEntityResultTransformer.cs
  src/NHibernate/Util/IdentityMap.cs
Labels: c: Core, p: Trivial, t: Task

#2349 Add support for Oracle binary floating point types
  src/NHibernate.Test/Async/Linq/ByMethod/AverageTests.cs
  src/NHibernate.Test/DriverTest/OracleClientDriverFixture.cs
  src/NHibernate.Test/Linq/ByMethod/AverageTests.cs
  src/NHibernate/Cfg/Environment.cs
  src/NHibernate/Dialect/Oracle10gDialect.cs
  src/NHibernate/Dialect/Oracle8iDialect.cs
  src/NHibernate/Driver/OracleClientDriver.cs
  src/NHibernate/Driver/OracleDataClientDriverBase.cs
  src/NHibernate/nhibernate-configuration.xsd
Labels: c: DataProviders / Dialects, p: Minor, t: New Feature

#2354 Do not require Mono to build on not Windows
  .travis.yml
  build-common/DotNetSdkMono.props
  build-common/NHibernate.props
Labels: c: Toolset, p: Trivial, t: Task

#2352 Improve performance of ReflectHelper.GetMethod/Definition
  src/NHibernate/Linq/ExpressionTransformers/SimplifyCompareTransformer.cs
  src/NHibernate/Linq/Functions/CompareGenerator.cs
  src/NHibernate/Linq/Functions/ConvertGenerator.cs
  src/NHibernate/Linq/Functions/DecimalGenerator.cs
  src/NHibernate/Linq/Functions/EqualsGenerator.cs
  src/NHibernate/Linq/Functions/ListIndexerGenerator.cs
  src/NHibernate/Linq/Functions/MathGenerator.cs
  src/NHibernate/Linq/Functions/NewGuidHqlGenerator.cs
  src/NHibernate/Linq/Functions/QueryableGenerator.cs
  src/NHibernate/Linq/Functions/RoundGenerator.cs
  src/NHibernate/Linq/Functions/TruncateGenerator.cs
  src/NHibernate/Linq/LinqExtensionMethods.cs
  src/NHibernate/Linq/NestedSelects/NestedSelectRewriter.cs
  src/NHibernate/Linq/NhRelinqQueryParser.cs
  src/NHibernate/Linq/Visitors/ExpressionParameterVisitor.cs
  src/NHibernate/Linq/Visitors/SelectClauseVisitor.cs
  src/NHibernate/Util/ReflectHelper.cs
  src/NHibernate/Util/ReflectionCache.cs
Labels: c: Core, p: Minor, t: Improvement

#2158 Proper support for IN clause for composite values in Criteria
  src/NHibernate.Test/Async/CompositeId/ClassWithCompositeIdFixture.cs
  src/NHibernate.Test/CompositeId/ClassWithCompositeIdFixture.cs
  src/NHibernate/Criterion/InExpression.cs
  src/NHibernate/SqlCommand/SqlString.cs
  src/NHibernate/SqlCommand/SqlStringHelper.cs
Labels: c: Core, p: Minor, t: Bug

#2316 Add multiple arguments support for ISQLFunction
  src/NHibernate/Criterion/SqlFunctionProjection.cs
  src/NHibernate/Dialect/DB2Dialect.cs
  src/NHibernate/Dialect/Dialect.cs
  src/NHibernate/Dialect/FirebirdDialect.cs
  src/NHibernate/Dialect/Function/AnsiSubstringFunction.cs
  src/NHibernate/Dialect/Function/AnsiTrimEmulationFunction.cs
  src/NHibernate/Dialect/Function/AvgQueryFunctionInfo.cs
  src/NHibernate/Dialect/Function/BitwiseFunctionOperation.cs
  src/NHibernate/Dialect/Function/BitwiseNativeOperation.cs
  src/NHibernate/Dialect/Function/CastFunction.cs
  src/NHibernate/Dialect/Function/CharIndexFunction.cs
  src/NHibernate/Dialect/Function/ClassicAggregateFunction.cs
  src/NHibernate/Dialect/Function/ClassicAvgFunction.cs
  src/NHibernate/Dialect/Function/ClassicCountFunction.cs
  src/NHibernate/Dialect/Function/CountQueryFunctionInfo.cs
  src/NHibernate/Dialect/Function/ISQLFunction.cs
  src/NHibernate/Dialect/Function/ISQLFunctionExtended.cs
  src/NHibernate/Dialect/Function/IifSQLFunction.cs
  src/NHibernate/Dialect/Function/IifSafeSQLFunction.cs
  src/NHibernate/Dialect/Function/ModulusFunction.cs
  src/NHibernate/Dialect/Function/ModulusFunctionTemplate.cs
  src/NHibernate/Dialect/Function/ModulusFunctionTypeDetector.cs
  src/NHibernate/Dialect/Function/NoArgSQLFunction.cs
  src/NHibernate/Dialect/Function/NvlFunction.cs
  src/NHibernate/Dialect/Function/PositionSubstringFunction.cs
  src/NHibernate/Dialect/Function/SQLFunctionTemplate.cs
  src/NHibernate/Dialect/Function/StandardSQLFunction.cs
  src/NHibernate/Dialect/Function/SumQueryFunctionInfo.cs
  src/NHibernate/Dialect/Function/VarArgsSQLFunction.cs
  src/NHibernate/Dialect/HanaDialectBase.cs
  src/NHibernate/Dialect/MsSql2000Dialect.cs
  src/NHibernate/Dialect/MsSql2012Dialect.cs
  src/NHibernate/Dialect/MsSqlCeDialect.cs
  src/NHibernate/Dialect/MySQLDialect.cs
  src/NHibernate/Dialect/Oracle8iDialect.cs
  src/NHibernate/Dialect/OracleLiteDialect.cs
  src/NHibernate/Dialect/PostgreSQLDialect.cs
  src/NHibernate/Dialect/SQLiteDialect.cs
  src/NHibernate/Dialect/SybaseASE15Dialect.cs
  src/NHibernate/Dialect/SybaseSQLAnywhere10Dialect.cs
  src/NHibernate/Hql/Ast/ANTLR/SessionFactoryHelperExtensions.cs
  src/NHibernate/Hql/Ast/ANTLR/Tree/AggregateNode.cs
  src/NHibernate/Hql/Ast/ANTLR/Tree/CountNode.cs
  src/NHibernate/Hql/Ast/ANTLR/Tree/IdentNode.cs
  src/NHibernate/Hql/Ast/ANTLR/Tree/MethodNode.cs
Labels: c: Core, c: DataProviders / Dialects, p: Minor, t: Improvement

#2356 Obsolete IdentitySet class
  src/NHibernate.Test/UtilityTest/IdentitySetFixture.cs
  src/NHibernate/Async/Engine/Query/HQLQueryPlan.cs
  src/NHibernate/Async/Event/Default/DefaultDeleteEventListener.cs
  src/NHibernate/Async/Hql/Ast/ANTLR/QueryTranslatorImpl.cs
  src/NHibernate/Engine/Query/HQLQueryPlan.cs
  src/NHibernate/Event/Default/DefaultDeleteEventListener.cs
  src/NHibernate/Hql/Ast/ANTLR/QueryTranslatorImpl.cs
  src/NHibernate/Util/IdentitySet.cs
Labels: c: Core, p: Minor, t: Task

#2248 Remove most RemoveAsAliasesFromSql usages
  src/NHibernate.Test/Async/CompositeId/ClassWithCompositeIdFixture.cs
  src/NHibernate.Test/CompositeId/ClassWithCompositeIdFixture.cs
  src/NHibernate/Criterion/AggregateProjection.cs
  src/NHibernate/Criterion/AvgProjection.cs
  src/NHibernate/Criterion/BetweenExpression.cs
  src/NHibernate/Criterion/CastProjection.cs
  src/NHibernate/Criterion/ConditionalProjection.cs
  src/NHibernate/Criterion/CountProjection.cs
  src/NHibernate/Criterion/CriterionUtil.cs
  src/NHibernate/Criterion/GroupedProjection.cs
  src/NHibernate/Criterion/IdentifierEqExpression.cs
  src/NHibernate/Criterion/InsensitiveLikeExpression.cs
  src/NHibernate/Criterion/LikeExpression.cs
  src/NHibernate/Criterion/NotNullExpression.cs
  src/NHibernate/Criterion/NullExpression.cs
  src/NHibernate/Criterion/Order.cs
  src/NHibernate/Criterion/PropertyExpression.cs
  src/NHibernate/Criterion/SimpleExpression.cs
  src/NHibernate/Criterion/SqlFunctionProjection.cs
  src/NHibernate/SqlCommand/SqlStringHelper.cs
Labels: c: Core, p: Minor, t: Improvement

#2324 Update IIsEntityDecider to use ExpressionsHelper.TryGetMappedType
  src/NHibernate.DomainModel/Northwind/Entities/Animal.cs
  src/NHibernate.Test/Async/Linq/SelectionTests.cs
  src/NHibernate.Test/Linq/SelectionTests.cs
  src/NHibernate/Linq/ReWriters/AddJoinsReWriter.cs
  src/NHibernate/Linq/Visitors/MemberExpressionJoinDetector.cs
  src/NHibernate/Linq/Visitors/SelectClauseNominator.cs
  src/NHibernate/Linq/Visitors/WhereJoinDetector.cs
Labels: c: Linq Provider, p: Minor, t: Bug

#2360 Add OData test for single property $expand
  src/NHibernate.Test/Async/Linq/ODataTests.cs
  src/NHibernate.Test/Linq/ODataTests.cs
Labels: c: Linq Provider, p: Minor, t: Tests

#2363 Upgrade AsyncGenerator to 0.18.2
  Tools/packages.csproj
  src/NHibernate.Test/Async/Futures/FutureCriteriaFixture.cs
  src/NHibernate.Test/Async/Linq/MiscellaneousTextFixture.cs
  src/NHibernate.Test/Async/Linq/QueryLock.cs
  src/NHibernate.Test/Async/NHSpecificTest/NH2322/PostUpdateEventListener.cs
  src/NHibernate.Test/Async/NHSpecificTest/NH2500/Fixture.cs
  src/NHibernate.Test/Async/NHSpecificTest/NH2898/BinaryFormatterCache.cs
  src/NHibernate.Test/Async/NHSpecificTest/NH3848/CriteriaTestFixture.cs
  src/NHibernate.Test/Async/NHSpecificTest/NH3848/HqlTestFixture.cs
  src/NHibernate.Test/Async/NHSpecificTest/NH3848/QueryOverTestFixture.cs
  src/NHibernate.Test/Async/NHSpecificTest/NH3918/FixtureByCode.cs
  src/NHibernate.Test/Async/ProjectionFixtures/Fixture.cs
  src/NHibernate/Async/AdoNet/HanaBatchingBatcher.cs
  src/NHibernate/Async/AdoNet/OracleDataClientBatchingBatcher.cs
  src/NHibernate/Async/Cache/ICacheConcurrencyStrategy.cs
  src/NHibernate/Async/Cache/IQueryCache.cs
  src/NHibernate/Async/Cache/UpdateTimestampsCache.cs
  src/NHibernate/Async/Dialect/Lock/UpdateLockingStrategy.cs
  src/NHibernate/Async/Engine/Collections.cs
  src/NHibernate/Async/Impl/SessionFactoryImpl.cs
  src/NHibernate/Async/Loader/Loader.cs
  src/NHibernate/Async/Persister/Entity/AbstractEntityPersister.cs
  src/NHibernate/Async/Persister/Entity/ILoadable.cs
  src/NHibernate/Async/Tool/hbm2ddl/SchemaMetadataUpdater.cs
  src/NHibernate/Async/Transaction/AdoNetTransactionFactory.cs
Labels: c: Toolset, p: Trivial, r: Fixed, t: Task
