Repository nhibernate/nhibernate-core, pull requests merged in 2020-06, with the labels that each got.

#2386 Fix OData string comparisons (lt, gt, ge, le)
  src/NHibernate.Test/Async/Linq/ODataTests.cs
  src/NHibernate.Test/Async/Linq/WhereTests.cs
  src/NHibernate.Test/Linq/ODataTests.cs
  src/NHibernate.Test/Linq/WhereTests.cs
  src/NHibernate/Linq/Functions/BaseHqlGeneratorForMethod.cs
  src/NHibernate/Linq/Functions/CompareGenerator.cs
  src/NHibernate/Linq/Functions/StringGenerator.cs
Labels: t: Fix

#2405 Fix QueryKey Equals method
  src/NHibernate/Cache/QueryKey.cs
Labels: t: Fix

#2399 Optimize PersistentGenericBag.EqualsSnapshot
  src/NHibernate.Test/Async/GenericTest/BagGeneric/BagGenericFixture.cs
  src/NHibernate.Test/GenericTest/BagGeneric/BagGenericFixture.cs
  src/NHibernate/Collection/Generic/PersistentGenericBag.cs
Labels: c: Core, p: Minor, t: Improvement

#2401 Optimize JoinWalker.WhereString method
  src/NHibernate/Loader/JoinWalker.cs
Labels: c: Core, p: Minor, t: Improvement

#2406 Make Render method virtual for Cast function
  src/NHibernate/Dialect/Function/CastFunction.cs
  src/NHibernate/Dialect/Function/TransparentCastFunction.cs
  src/NHibernate/Dialect/SQLiteDialect.cs
Labels: t: Fix

#2409 SessionFactoryImpl - throw AggregateHibernateException when schema update fails
  doc/reference/modules/configuration.xml
  src/NHibernate.Test/Async/Tools/hbm2ddl/SchemaUpdate/MigrationFixture.cs
  src/NHibernate.Test/CfgTest/Loquacious/ConfigurationFixture.cs
  src/NHibernate.Test/CfgTest/Loquacious/LambdaConfigurationFixture.cs
  src/NHibernate.Test/Tools/hbm2ddl/SchemaUpdate/3_Person.hbm.xml
  src/NHibernate.Test/Tools/hbm2ddl/SchemaUpdate/MigrationFixture.cs
  src/NHibernate/Cfg/Environment.cs
  src/NHibernate/Cfg/Loquacious/DbIntegrationConfiguration.cs
  src/NHibernate/Cfg/Loquacious/DbIntegrationConfigurationProperties.cs
  src/NHibernate/Cfg/Settings.cs
  src/NHibernate/Cfg/SettingsFactory.cs
  src/NHibernate/Impl/SessionFactoryImpl.cs
  src/NHibernate/nhibernate-configuration.xsd
Labels: t: Fix

#2417 Fix SQL formatter failures
  src/NHibernate.Test/UtilityTest/SqlStatementLoggerFixture.cs
  src/NHibernate/AdoNet/Util/BasicFormatter.cs
  src/NHibernate/AdoNet/Util/DdlFormatter.cs
  src/NHibernate/AdoNet/Util/SqlStatementLogger.cs
Labels: t: Fix

#2411 Add an option to register a custom pre-transformer for a Linq query
  doc/reference/modules/configuration.xml
  src/NHibernate.Test/Async/Linq/CustomExpressionTransformerRegistrarTests.cs
  src/NHibernate.Test/Linq/CustomExpressionTransformerRegistrarTests.cs
  src/NHibernate.Test/TestCase.cs
  src/NHibernate/Cfg/Environment.cs
  src/NHibernate/Cfg/Loquacious/DbIntegrationConfigurationProperties.cs
  src/NHibernate/Cfg/Settings.cs
  src/NHibernate/Cfg/SettingsFactory.cs
  src/NHibernate/Linq/NhRelinqQueryParser.cs
  src/NHibernate/Linq/Visitors/IExpressionTransformerRegistrar.cs
  src/NHibernate/Linq/Visitors/PreTransformationParameters.cs
  src/NHibernate/nhibernate-configuration.xsd
Labels: c: Linq Provider, p: Minor, t: New Feature

#2422 Fix an inversion of meaning
  doc/reference/modules/best_practices.xml
Labels: t: Fix
