Repository nhibernate/nhibernate-core, pull requests merged in 2020-11, with the labels that each got.

#2587 Release 5.3.4
  build-common/NHibernate.props
  releasenotes.txt
Labels: c: Documentation, p: Minor, t: Task

#2593 Merge 5.3.4
  releasenotes.txt
  src/NHibernate.Test/Async/Linq/ByMethod/JoinTests.cs
  src/NHibernate.Test/Async/Linq/WhereSubqueryTests.cs
  src/NHibernate.Test/Async/NHSpecificTest/GH2549/Fixture.cs
  src/NHibernate.Test/Async/NHSpecificTest/GH2559/FixtureByCode.cs
  src/NHibernate.Test/Linq/ByMethod/JoinTests.cs
  src/NHibernate.Test/Linq/WhereSubqueryTests.cs
  src/NHibernate.Test/NHSpecificTest/GH2549/Fixture.cs
  src/NHibernate.Test/NHSpecificTest/GH2549/Mappings.hbm.xml
  src/NHibernate.Test/NHSpecificTest/GH2549/Model.cs
  src/NHibernate.Test/NHSpecificTest/GH2559/Car.cs
  src/NHibernate.Test/NHSpecificTest/GH2559/Child.cs
  src/NHibernate.Test/NHSpecificTest/GH2559/FixtureByCode.cs
  src/NHibernate.Test/NHSpecificTest/GH2559/Person.cs
  src/NHibernate.Test/NHSpecificTest/GH2559/Pet.cs
  src/NHibernate/Async/Type/CollectionType.cs
  src/NHibernate/Hql/Ast/ANTLR/Tree/EntityJoinFromElement.cs
  src/NHibernate/Hql/Ast/ANTLR/Tree/EntityJoinJoinSequenceImpl.cs
  src/NHibernate/Linq/Visitors/NhPartialEvaluatingExpressionVisitor.cs
  src/NHibernate/Type/CollectionType.cs
Labels: p: Minor, t: Task

#2595 Fix invalid alias inside Dml subquery
  src/NHibernate.Test/Async/Hql/Ast/BulkManipulation.cs
  src/NHibernate.Test/Async/LinqBulkManipulation/Fixture.cs
  src/NHibernate.Test/Hql/Ast/BulkManipulation.cs
  src/NHibernate.Test/LinqBulkManipulation/Fixture.cs
  src/NHibernate.Test/TestDialect.cs
  src/NHibernate.Test/TestDialects/MySQL5TestDialect.cs
  src/NHibernate/Hql/Ast/ANTLR/HqlSqlWalker.cs
  src/NHibernate/Hql/Ast/ANTLR/Tree/FromElement.cs
  src/NHibernate/Hql/Ast/ANTLR/Tree/FromElementType.cs
Labels: t: Fix

#2600 Fix missing subclass discriminator in ON clause for entity joins
  src/NHibernate.Test/Async/NHSpecificTest/GH2463/Fixture.cs
  src/NHibernate.Test/NHSpecificTest/GH2463/Fixture.cs
  src/NHibernate/Engine/JoinSequence.cs
  src/NHibernate/Hql/Ast/ANTLR/Tree/EntityJoinFromElement.cs
  src/NHibernate/Loader/JoinWalker.cs
  src/NHibernate/Loader/OuterJoinableAssociation.cs
Labels: t: Fix

#2606 Release 5.3.5
  build-common/NHibernate.props
  releasenotes.txt
Labels: c: Documentation, p: Minor, t: Task

#2607 Merge 5.3.5
  releasenotes.txt
  src/NHibernate.Test/Async/NHSpecificTest/GH2463/Fixture.cs
  src/NHibernate.Test/NHSpecificTest/GH2463/Fixture.cs
  src/NHibernate/Engine/JoinSequence.cs
  src/NHibernate/Hql/Ast/ANTLR/Tree/EntityJoinFromElement.cs
  src/NHibernate/Loader/JoinWalker.cs
  src/NHibernate/Loader/OuterJoinableAssociation.cs
Labels: c: Core, p: Minor, t: Task

#2605 Upgrade AsyncGenerator to 0.19.1
  .config/dotnet-tools.json
  ShowBuildMenu.sh
  Tools/packages.csproj
  build-common/common.xml
  default.build
Labels: c: Toolset, p: Minor, t: Task
