Repository nhibernate/nhibernate-core, pull requests merged in 2020-05, with the labels that each got.

#2066 Tests for proxy interface handling
  src/NHibernate.Test/Async/StaticProxyTest/InterfaceHandling/Fixture.cs
  src/NHibernate.Test/StaticProxyTest/InterfaceHandling/BaseInterfaces.cs
  src/NHibernate.Test/StaticProxyTest/InterfaceHandling/Entities.cs
  src/NHibernate.Test/StaticProxyTest/InterfaceHandling/Fixture.cs
  src/NHibernate.Test/StaticProxyTest/InterfaceHandling/SubclassEntities.cs
Labels: c: Tests

#2254 Add dev build version suffix
  .gitignore
  ReleaseProcedure.txt
  appveyor.yml
  build-common/NHibernate.props
  build-common/common.xml
  default.build
  doc/NHibernate.shfbproj.template
  doc/reference/master.template.xml
  doc/reference/reference.build
Labels: c: Toolset, p: Minor, t: Improvement

#2335 Minimize Linq query parameters
  src/NHibernate.Test/Async/Linq/ParameterTests.cs
  src/NHibernate.Test/Linq/ConstantTest.cs
  src/NHibernate.Test/Linq/ParameterTests.cs
  src/NHibernate.Test/Linq/TryGetMappedTests.cs
  src/NHibernate/Linq/ExpressionTransformers/RemoveCharToIntConversion.cs
  src/NHibernate/Linq/NhLinqDmlExpression.cs
  src/NHibernate/Linq/NhLinqExpression.cs
  src/NHibernate/Linq/NhRelinqQueryParser.cs
  src/NHibernate/Linq/Visitors/ExpressionParameterVisitor.cs
  src/NHibernate/Linq/Visitors/NhPartialEvaluatingExpressionVisitor.cs
  src/NHibernate/Linq/Visitors/PreTransformationParameters.cs
  src/NHibernate/Linq/Visitors/PreTransformationResult.cs
  src/NHibernate/Linq/Visitors/ResultOperatorProcessors/ProcessContains.cs
  src/NHibernate/Util/ExpressionsHelper.cs
Labels: possible breaking change, t: Fix

#2347 Support fetching individual lazy properties for Criteria EntityProjection
  src/NHibernate.Test/Async/Criteria/EntityProjectionsTest.cs
  src/NHibernate.Test/Criteria/EntityProjectionsEntities.cs
  src/NHibernate.Test/Criteria/EntityProjectionsTest.cs
  src/NHibernate/Criterion/EntityProjection.cs
  src/NHibernate/Loader/AbstractEntityJoinWalker.cs
  src/NHibernate/Loader/OuterJoinableAssociation.cs
  src/NHibernate/Persister/Entity/IQueryable.cs
  src/NHibernate/SelectMode.cs
Labels: c: Core, p: Minor, t: New Feature

#2359 Rename ISQLFunctionExtended.FunctionName to Name
  src/NHibernate/Dialect/FirebirdDialect.cs
  src/NHibernate/Dialect/Function/AnsiSubstringFunction.cs
  src/NHibernate/Dialect/Function/AnsiTrimEmulationFunction.cs
  src/NHibernate/Dialect/Function/BitwiseFunctionOperation.cs
  src/NHibernate/Dialect/Function/BitwiseNativeOperation.cs
  src/NHibernate/Dialect/Function/CastFunction.cs
  src/NHibernate/Dialect/Function/CharIndexFunction.cs
  src/NHibernate/Dialect/Function/ClassicAggregateFunction.cs
  src/NHibernate/Dialect/Function/ISQLFunctionExtended.cs
  src/NHibernate/Dialect/Function/NoArgSQLFunction.cs
  src/NHibernate/Dialect/Function/NvlFunction.cs
  src/NHibernate/Dialect/Function/PositionSubstringFunction.cs
  src/NHibernate/Dialect/Function/SQLFunctionTemplate.cs
  src/NHibernate/Dialect/Function/StandardSQLFunction.cs
  src/NHibernate/Dialect/Function/VarArgsSQLFunction.cs
  src/NHibernate/Dialect/HanaDialectBase.cs
  src/NHibernate/Dialect/Oracle8iDialect.cs
  src/NHibernate/Dialect/PostgreSQLDialect.cs
  src/NHibernate/Hql/Ast/ANTLR/Tree/AggregateNode.cs
Labels: t: Fix

#2368 Replace SafetyEnumerable<T> with OfType<T> where applicable
  src/NHibernate.Test/UtilityTest/SafetyEnumerableFixture.cs
  src/NHibernate/Async/Engine/Query/HQLQueryPlan.cs
  src/NHibernate/Cfg/XmlHbmBinding/RootClassBinder.cs
  src/NHibernate/Engine/Query/HQLQueryPlan.cs
  src/NHibernate/Mapping/Constraint.cs
  src/NHibernate/Mapping/IdentifierCollection.cs
  src/NHibernate/Mapping/IndexedCollection.cs
  src/NHibernate/Mapping/Join.cs
  src/NHibernate/Mapping/ManyToOne.cs
  src/NHibernate/Mapping/OneToOne.cs
  src/NHibernate/Mapping/PersistentClass.cs
  src/NHibernate/Mapping/SimpleValue.cs
  src/NHibernate/Persister/Entity/JoinedSubclassEntityPersister.cs
  src/NHibernate/SqlCommand/SqlInsertBuilder.cs
  src/NHibernate/SqlCommand/SqlUpdateBuilder.cs
  src/NHibernate/Util/EnumerableExtensions.cs
  src/NHibernate/Util/SafetyEnumerable.cs
Labels: c: Core, p: Trivial, r: Fixed, t: Task

#2376 Add MyGet gallery link to readme
  README.md
Labels: c: Documentation, p: Trivial, t: Task

#2350 Optimize LINQ batch item processing for queries with overridden result type
  src/NHibernate/Async/Multi/LinqBatchItem.cs
  src/NHibernate/Multi/LinqBatchItem.cs
  src/NHibernate/Multi/LinqBatchReflectHelper.cs
Labels: c: Linq Provider, p: Minor, t: Improvement

#2377 Use dotnet to push packages to nuget
  Tools/.gitignore
  build-common/common.xml
  default.build
Labels: c: Toolset, p: Trivial, t: Task

#2328 Add left join support for Linq query provider
  src/NHibernate.Test/Async/Linq/ByMethod/JoinTests.cs
  src/NHibernate.Test/Async/Linq/LinqQuerySamples.cs
  src/NHibernate.Test/Linq/ByMethod/JoinTests.cs
  src/NHibernate.Test/Linq/LinqQuerySamples.cs
  src/NHibernate/Linq/Clauses/NhOuterJoinClause.cs
  src/NHibernate/Linq/GroupJoin/GroupJoinAggregateDetectionVisitor.cs
  src/NHibernate/Linq/GroupJoin/NonAggregatingGroupJoinRewriter.cs
  src/NHibernate/Linq/INhQueryModelVisitor.cs
  src/NHibernate/Linq/LinqExtensionMethods.cs
  src/NHibernate/Linq/QuerySourceNamer.cs
  src/NHibernate/Linq/ReWriters/AddJoinsReWriter.cs
  src/NHibernate/Linq/Visitors/QueryModelVisitor.cs
  src/NHibernate/Linq/Visitors/QuerySourceIdentifier.cs
  src/NHibernate/Util/ReflectHelper.cs
  src/NHibernate/Util/ReflectionCache.cs
Labels: c: Linq Provider, p: Minor, t: New Feature

#2385 Fix detecting entities of left join by IEntityDecider
  src/NHibernate/Util/ExpressionsHelper.cs
Labels: t: Fix

#2384 Tests to verify NH-2329 is obsolete
  src/NHibernate.Test/Async/Legacy/FooBarTest.cs
  src/NHibernate.Test/Legacy/FooBarTest.cs
Labels: c: Tests, p: Minor, t: Tests

#2382 Refactor debug logging in AbstractBatcher
  src/NHibernate/AdoNet/AbstractBatcher.cs
  src/NHibernate/Async/AdoNet/AbstractBatcher.cs
Labels: c: Core, p: Trivial, t: Task

#2387 Fix OData filtering by a base class member
  src/NHibernate.Test/Async/Linq/ODataTests.cs
  src/NHibernate.Test/Linq/ODataTests.cs
  src/NHibernate/Linq/NhLinqExpression.cs
  src/NHibernate/Linq/Visitors/TransparentIdentifierRemovingExpressionVisitor.cs
Labels: t: Fix

#2397 Update GitReleaseManager
  ReleaseProcedure.txt
  Tools/packages.csproj
Labels: c: Toolset, p: Trivial, t: Task

#2378 Add missing ISession.Get(entityName, id, lockMode)
  src/NHibernate.Test/Async/NHSpecificTest/NH1275/Fixture.cs
  src/NHibernate.Test/NHSpecificTest/NH1275/Fixture.cs
  src/NHibernate/Async/ISession.cs
  src/NHibernate/Async/IStatelessSession.cs
  src/NHibernate/Async/Impl/SessionImpl.cs
  src/NHibernate/Async/Impl/StatelessSessionImpl.cs
  src/NHibernate/ISession.cs
  src/NHibernate/IStatelessSession.cs
  src/NHibernate/Impl/SessionImpl.cs
  src/NHibernate/Impl/StatelessSessionImpl.cs
Labels: t: Fix

#2392 Add locate support for SQLite
  src/NHibernate.Test/Async/Hql/HQLFunctions.cs
  src/NHibernate.Test/Async/Linq/FunctionTests.cs
  src/NHibernate.Test/Hql/HQLFunctions.cs
  src/NHibernate.Test/Linq/FunctionTests.cs
  src/NHibernate.Test/TestCase.cs
  src/NHibernate.Test/TestDialect.cs
  src/NHibernate.Test/TestDialects/SQLiteTestDialect.cs
  src/NHibernate/Dialect/SQLiteDialect.cs
Labels: c: DataProviders / Dialects, p: Minor, t: New Feature

#2383 Support for criteria aliases in SqlProjection and SQLCriterion
  src/NHibernate.Test/Async/Criteria/CriteriaQueryTest.cs
  src/NHibernate.Test/Criteria/CriteriaQueryTest.cs
  src/NHibernate/Criterion/ICriteriaQuery.cs
  src/NHibernate/Criterion/SQLCriterion.cs
  src/NHibernate/Criterion/SQLProjection.cs
  src/NHibernate/Loader/Criteria/CriteriaQueryTranslator.cs
Labels: t: Fix

#2394 Optimize PersistentGenericSet snapshot
  src/NHibernate.Test/NHibernate.Test.csproj
  src/NHibernate.Test/UtilityTest/SetSnapShotFixture.cs
  src/NHibernate/Async/Collection/Generic/PersistentGenericSet.cs
  src/NHibernate/Collection/Generic/PersistentGenericSet.cs
  src/NHibernate/Collection/Generic/SetHelpers/ISetSnapshot.cs
  src/NHibernate/Collection/Generic/SetHelpers/SetSnapShot.cs
Labels: c: Core, p: Minor, t: Improvement

#2402 Fix Oracle binary floating point setting
  src/NHibernate.Test/Async/Linq/ByMethod/AverageTests.cs
  src/NHibernate.Test/Linq/ByMethod/AverageTests.cs
  src/NHibernate/Dialect/Oracle10gDialect.cs
Labels: t: Fix
