Repository nhibernate/nhibernate-core, pull requests merged in 2020-08, with the labels that each got.

#2469 Fix NRE in AsyncReaderWriterLock.ReadLock method
  src/NHibernate/Util/AsyncReaderWriterLock.cs
Labels: t: Fix

#2467 Fix parameter detection related to sequence selectors for Linq provider
  src/NHibernate.Test/Async/Linq/ParameterTests.cs
  src/NHibernate.Test/Async/NHSpecificTest/GH2465/Fixture.cs
  src/NHibernate.Test/Linq/ParameterTests.cs
  src/NHibernate.Test/NHSpecificTest/GH2465/Entity.cs
  src/NHibernate.Test/NHSpecificTest/GH2465/Fixture.cs
  src/NHibernate.Test/NHSpecificTest/GH2465/Mappings.hbm.xml
  src/NHibernate/Linq/Visitors/ParameterTypeLocator.cs
Labels: t: Fix

#2472 Release 5.3.2
  build-common/NHibernate.props
  releasenotes.txt
Labels: c: Core, p: Minor, t: Task

#2474 Fetch all lazy properties when entity is already loaded fails
  src/NHibernate.Test/Async/FetchLazyProperties/FetchLazyPropertiesFixture.cs
  src/NHibernate.Test/FetchLazyProperties/FetchLazyPropertiesFixture.cs
  src/NHibernate/Async/Persister/Entity/AbstractEntityPersister.cs
  src/NHibernate/Persister/Entity/AbstractEntityPersister.cs
Labels: Regression, c: Core, p: Minor, t: Bug

#2482 Add missing possible breaking changes for #2010
  releasenotes.txt
Labels: c: Documentation, p: Trivial, t: Task

#2484 Entity Joins are not polymorphic in hql
  src/NHibernate.Test/Async/Linq/ByMethod/JoinTests.cs
  src/NHibernate.Test/Linq/ByMethod/JoinTests.cs
  src/NHibernate/Engine/JoinSequence.cs
  src/NHibernate/Hql/Ast/ANTLR/Tree/EntityJoinJoinSequenceImpl.cs
Labels: Regression, c: Core, p: Minor, t: Bug

#2486 Add Projections.Select in Criteria
  src/NHibernate/Criterion/Lambda/QueryOverProjectionBuilder.cs
  src/NHibernate/Criterion/Projections.cs
  src/NHibernate/Criterion/QueryOver.cs
Labels: c: Core, p: Minor, t: New Feature

#2489 Improve CriteriaAssertFixture
  src/NHibernate.Test/Criteria/Lambda/CriteriaAssertFixture.cs
Labels: c: Tests, p: Minor, t: Tests

#2481 Fix lazy set when adding a transient element with overridden Equals method
  src/NHibernate.Test/Async/Extralazy/ExtraLazyFixture.cs
  src/NHibernate.Test/Extralazy/ExtraLazyFixture.cs
  src/NHibernate.Test/Extralazy/User.cs
  src/NHibernate.Test/Extralazy/UserFollower.cs
  src/NHibernate.Test/Extralazy/UserGroup.hbm.xml
  src/NHibernate/Async/Collection/AbstractPersistentCollection.cs
  src/NHibernate/Collection/AbstractPersistentCollection.cs
  src/NHibernate/Collection/Generic/PersistentGenericSet.cs
  src/NHibernate/Tuple/Entity/EntityMetamodel.cs
Labels: t: Fix

#2485 Throw entity not mapped exception for entity join in hql if possible
  src/NHibernate/Hql/Ast/ANTLR/HqlSqlWalker.cs
Labels: Regression, c: Core, p: Minor, t: Bug

#2488 Fix parameter detection for Equals and CompareTo methods for Linq provider
  src/NHibernate.Test/Async/NHSpecificTest/GH2437/Fixture.cs
  src/NHibernate.Test/Linq/ParameterTypeLocatorTests.cs
  src/NHibernate.Test/NHSpecificTest/GH2437/Fixture.cs
  src/NHibernate/Linq/Functions/EqualsGenerator.cs
  src/NHibernate/Linq/Visitors/ParameterTypeLocator.cs
Labels: Regression, c: Linq Provider, p: Minor, t: Bug

#2502 Support count distinct on function in hql
  src/NHibernate.Test/Async/Hql/Ast/HqlFixture.cs
  src/NHibernate.Test/Async/Linq/ByMethod/CountTests.cs
  src/NHibernate.Test/Hql/Ast/HqlFixture.cs
  src/NHibernate.Test/Linq/ByMethod/CountTests.cs
  src/NHibernate/Hql/Ast/ANTLR/Hql.g
Labels: t: Fix

#2503 Flatten AsQueryableResultOperator
  src/NHibernate.Test/Async/Linq/WhereSubqueryTests.cs
  src/NHibernate.Test/Linq/WhereSubqueryTests.cs
  src/NHibernate/Linq/Visitors/SubQueryFromClauseFlattener.cs
Labels: t: Fix
