Repository nhibernate/nhibernate-core, pull requests merged in 2021-01, with the labels that each got.

#2645 Allow specifying the size of the query plan cache
  src/NHibernate.Test/Async/NHSpecificTest/NH3050/FixtureByCode.cs
  src/NHibernate.Test/CfgTest/SettingsFactoryFixture.cs
  src/NHibernate.Test/NHSpecificTest/NH3050/FixtureByCode.cs
  src/NHibernate/Cfg/Environment.cs
  src/NHibernate/Cfg/Settings.cs
  src/NHibernate/Cfg/SettingsFactory.cs
  src/NHibernate/Engine/Query/QueryPlanCache.cs
  src/NHibernate/Impl/SessionFactoryImpl.cs
  src/NHibernate/nhibernate-configuration.xsd
Labels: c: Core, p: Minor, t: New Feature

#2618 Fix limits in polymorphic queries
  src/NHibernate.Test/Async/NHSpecificTest/GH2614/Fixture.cs
  src/NHibernate.Test/NHSpecificTest/GH2614/BaseClass.cs
  src/NHibernate.Test/NHSpecificTest/GH2614/ConcreteClass1.cs
  src/NHibernate.Test/NHSpecificTest/GH2614/ConcreteClass2.cs
  src/NHibernate.Test/NHSpecificTest/GH2614/Fixture.cs
  src/NHibernate.Test/NHSpecificTest/GH2614/Mappings.hbm.xml
  src/NHibernate/Async/Engine/Query/HQLQueryPlan.cs
  src/NHibernate/Engine/Query/HQLQueryPlan.cs
Labels: r: Fixed, t: Fix

#2651 Fix enum detection when using OfType for Linq provider
  src/NHibernate.DomainModel/Northwind/Entities/Animal.cs
  src/NHibernate.DomainModel/Northwind/Mappings/Animal.hbm.xml
  src/NHibernate.Test/Linq/ParameterTypeLocatorTests.cs
  src/NHibernate/Util/ExpressionsHelper.cs
Labels: t: Fix

#2609 Fix #2608 - persisting a one-to-one with delayed insert fails
  src/NHibernate.Test/Async/NHSpecificTest/GH2608/Fixture.cs
  src/NHibernate.Test/Async/Operations/MergeFixture.cs
  src/NHibernate.Test/NHSpecificTest/GH2608/Fixture.cs
  src/NHibernate.Test/NHSpecificTest/GH2608/Mappings.hbm.xml
  src/NHibernate.Test/NHSpecificTest/GH2608/Person.cs
  src/NHibernate.Test/NHSpecificTest/GH2608/PersonalDetails.cs
  src/NHibernate.Test/Operations/MergeFixture.cs
  src/NHibernate.Test/Operations/OneToOne.hbm.xml
  src/NHibernate/Action/DelayedPostInsertIdentifier.cs
  src/NHibernate/Action/EntityInsertAction.cs
  src/NHibernate/Async/Action/EntityInsertAction.cs
  src/NHibernate/Async/Engine/StatefulPersistenceContext.cs
  src/NHibernate/Async/Event/Default/AbstractSaveEventListener.cs
  src/NHibernate/Engine/StatefulPersistenceContext.cs
  src/NHibernate/Event/Default/AbstractSaveEventListener.cs
Labels: t: Fix

#2652 Fix dynamic delete for one-to-one association
  src/NHibernate.Test/Async/NHSpecificTest/GH2631/Fixture.cs
  src/NHibernate.Test/NHSpecificTest/GH2631/Address.cs
  src/NHibernate.Test/NHSpecificTest/GH2631/Fixture.cs
  src/NHibernate.Test/NHSpecificTest/GH2631/Mappings.hbm.xml
  src/NHibernate.Test/NHSpecificTest/GH2631/Person.cs
  src/NHibernate/Async/Persister/Entity/AbstractEntityPersister.cs
  src/NHibernate/Persister/Entity/AbstractEntityPersister.cs
Labels: t: Fix

#2653 Fix Any on composite id in Select
  src/NHibernate.Test/Async/CompositeId/CompositeIdFixture.cs
  src/NHibernate.Test/CompositeId/CompositeIdFixture.cs
  src/NHibernate/Hql/Ast/ANTLR/HqlSqlWalker.cs
Labels: t: Fix
