Repository nhibernate/nhibernate-core, pull requests merged in 2021-07, with the labels that each got.

#2841 Fix possible test failure for SqlServer 2019
  src/NHibernate.Test/Async/NHSpecificTest/GH1300/Fixture.cs
  src/NHibernate.Test/NHSpecificTest/GH1300/Fixture.cs
Labels: c: Tests, p: Minor, t: Bug

#2835 Fix ExecuteWorkInIsolation ignores MultiTenancy configuration
  src/NHibernate.Test/Async/MultiTenancy/DatabaseStrategyNoDbSpecificFixture.cs
  src/NHibernate.Test/Async/MultiTenancy/TenantIsolatatedWork.cs
  src/NHibernate.Test/MultiTenancy/DatabaseStrategyNoDbSpecificFixture.cs
  src/NHibernate.Test/MultiTenancy/TenantIsolatatedWork.cs
  src/NHibernate/AdoNet/ConnectionManager.cs
  src/NHibernate/Async/AdoNet/ConnectionManager.cs
  src/NHibernate/Async/Transaction/AdoNetTransactionFactory.cs
  src/NHibernate/Transaction/AdoNetTransactionFactory.cs
Labels: c: Core, p: Minor, t: Bug

#2837 Release 5.3.9
  build-common/NHibernate.props
  releasenotes.txt
Labels: c: Documentation, p: Minor, t: Task

#2844 Merge 5.3.9
  .github/workflows/NetCoreTests.yml
  .travis.yml
  releasenotes.txt
  src/NHibernate.Test/Async/Hql/EntityJoinHqlTest.cs
  src/NHibernate.Test/Async/Linq/ByMethod/JoinTests.cs
  src/NHibernate.Test/Async/Linq/CustomExtensionsExample.cs
  src/NHibernate.Test/Async/Linq/LinqQuerySamples.cs
  src/NHibernate.Test/Async/Linq/OperatorTests.cs
  src/NHibernate.Test/Async/Linq/ParameterTests.cs
  src/NHibernate.Test/Async/MultiTenancy/DatabaseStrategyNoDbSpecificFixture.cs
  src/NHibernate.Test/Async/MultiTenancy/TenantIsolatatedWork.cs
  src/NHibernate.Test/Async/NHSpecificTest/GH1300/Fixture.cs
  src/NHibernate.Test/Hql/EntityJoinHqlTest.cs
  src/NHibernate.Test/Linq/ByMethod/JoinTests.cs
  src/NHibernate.Test/Linq/CustomExtensionsExample.cs
  src/NHibernate.Test/Linq/LinqQuerySamples.cs
  src/NHibernate.Test/Linq/OperatorTests.cs
  src/NHibernate.Test/Linq/ParameterTests.cs
  src/NHibernate.Test/MultiTenancy/DatabaseStrategyNoDbSpecificFixture.cs
  src/NHibernate.Test/MultiTenancy/TenantIsolatatedWork.cs
  src/NHibernate.Test/NHSpecificTest/GH1300/Fixture.cs
  src/NHibernate.Test/TestCase.cs
  src/NHibernate.Test/UtilityTest/SetSnapShotFixture.cs
  src/NHibernate/AdoNet/ConnectionManager.cs
  src/NHibernate/Async/AdoNet/ConnectionManager.cs
  src/NHibernate/Async/Transaction/AdoNetTransactionFactory.cs
  src/NHibernate/Collection/Generic/SetHelpers/SetSnapShot.cs
  src/NHibernate/Dialect/Dialect.cs
  src/NHibernate/Dialect/SQLiteDialect.cs
  src/NHibernate/Hql/Ast/ANTLR/HqlSqlWalker.cs
  src/NHibernate/Hql/Ast/ANTLR/Tree/DotNode.cs
  src/NHibernate/Impl/SessionFactoryImpl.cs
  src/NHibernate/Impl/SessionImpl.cs
  src/NHibernate/Impl/StatelessSessionImpl.cs
  src/NHibernate/Linq/Visitors/HqlGeneratorExpressionVisitor.cs
  src/NHibernate/Linq/Visitors/ParameterTypeLocator.cs
  src/NHibernate/Transaction/AdoNetTransactionFactory.cs
Labels: t: Fix

#2859 Fix possible ERROR log when parsing join in hql
  src/NHibernate.Test/Associations/OneToOneFixture.cs
  src/NHibernate.Test/Async/Associations/OneToOneFixture.cs
  src/NHibernate.Test/Async/Hql/EntityJoinHqlTest.cs
  src/NHibernate.Test/Hql/EntityJoinHqlTest.cs
  src/NHibernate.Test/Hql/EntityJoinHqlTestEntities.cs
  src/NHibernate/Hql/Ast/ANTLR/HqlSqlWalker.cs
  src/NHibernate/Hql/Ast/ANTLR/Tree/DotNode.cs
Labels: t: Fix

#2848 Add Oracle to Git Hub Actions
  .github/workflows/NetCoreTests.yml
  psake.ps1
  src/NHibernate.Test/Async/NHSpecificTest/NH1171/Fixture.cs
  src/NHibernate.Test/Async/NHSpecificTest/NH1693/Fixture.cs
  src/NHibernate.Test/Async/Tools/hbm2ddl/SchemaMetadataUpdaterTest/SchemaMetadataUpdaterFixture.cs
  src/NHibernate.Test/NHSpecificTest/NH1171/Fixture.cs
  src/NHibernate.Test/NHSpecificTest/NH1693/Fixture.cs
  src/NHibernate.Test/NHibernate.Test.csproj
  src/NHibernate.Test/Tools/hbm2ddl/SchemaMetadataUpdaterTest/SchemaMetadataUpdaterFixture.cs
Labels: c: Tests, p: Minor, t: Tests

#2851 Cache Dialect in tests
  src/NHibernate.Test/TestCase.cs
Labels: c: Tests, p: Lowest, r: Fixed, t: Task
