Repository nhibernate/nhibernate-core, pull requests merged in 2021-02, with the labels that each got.

#2657 Fix NRE with merge and ignore not-found
  src/NHibernate.Test/Async/NHSpecificTest/GH2627/Fixture.cs
  src/NHibernate.Test/NHSpecificTest/GH2627/Child.cs
  src/NHibernate.Test/NHSpecificTest/GH2627/Entity.cs
  src/NHibernate.Test/NHSpecificTest/GH2627/Fixture.cs
  src/NHibernate.Test/NHSpecificTest/GH2627/Mappings.hbm.xml
  src/NHibernate/Async/Type/ManyToOneType.cs
  src/NHibernate/Type/ManyToOneType.cs
Labels: t: Fix

#2643 Add special case for constants contained within Convert nodes (#2642)
  src/NHibernate.Test/Async/Linq/ParameterTests.cs
  src/NHibernate.Test/Linq/ParameterTests.cs
  src/NHibernate/Linq/Visitors/ExpressionParameterVisitor.cs
Labels: t: Fix

#2668 Upgrade log4net
  src/NHibernate.Test/NHibernate.Test.csproj
Labels: r: Fixed, t: Fix

#2669 Fix wrong column selection when using OfType in a Linq query
  src/NHibernate.Test/Async/NHSpecificTest/GH2626/Fixture.cs
  src/NHibernate.Test/NHSpecificTest/GH2626/Entity.cs
  src/NHibernate.Test/NHSpecificTest/GH2626/Fixture.cs
  src/NHibernate.Test/NHSpecificTest/GH2626/Mappings.hbm.xml
  src/NHibernate/Util/ExpressionsHelper.cs
Labels: t: Fix

#2664 Fix subquery "Item with Same Key has already been added” exception for Linq provider
  src/NHibernate.DomainModel/Northwind/Entities/Order.cs
  src/NHibernate.DomainModel/Northwind/Mappings/Order.hbm.xml
  src/NHibernate.Test/Async/Linq/WhereTests.cs
  src/NHibernate.Test/Linq/WhereTests.cs
  src/NHibernate/Linq/Visitors/HqlGeneratorExpressionVisitor.cs
Labels: t: Fix

#2656 Make sure dbcommand is disposed
  src/NHibernate/AdoNet/GenericBatchingBatcher.cs
  src/NHibernate/Async/AdoNet/GenericBatchingBatcher.cs
Labels: c: DataProviders / Dialects, p: Minor, t: Improvement

#2675 Fix collection lazy loading with composite keys on subclass columns
  src/NHibernate.Test/Async/NHSpecificTest/NH2174/Fixture.cs
  src/NHibernate.Test/NHSpecificTest/NH2174/Entity.cs
  src/NHibernate.Test/NHSpecificTest/NH2174/Fixture.cs
  src/NHibernate.Test/NHSpecificTest/NH2174/Mappings.hbm.xml
  src/NHibernate/Loader/Collection/CollectionJoinWalker.cs
  src/NHibernate/Loader/JoinWalker.cs
Labels: c: Core, p: Minor, t: Bug

#2678 Fix missing ConfigureAwait(false) in FutureEnumerable
  src/NHibernate/Async/Multi/QueryBatchExtensions.cs
  src/NHibernate/Multi/QueryBatchExtensions.cs
Labels: t: Fix

#2674 Fix Queryable.Contains method for Linq provider
  src/NHibernate.Test/Async/Linq/MethodCallTests.cs
  src/NHibernate.Test/Async/NHSpecificTest/NH3850/MainFixture.cs
  src/NHibernate.Test/Linq/MethodCallTests.cs
  src/NHibernate.Test/NHSpecificTest/NH3850/MainFixture.cs
  src/NHibernate/Linq/Visitors/ResultOperatorProcessors/ProcessAny.cs
  src/NHibernate/Linq/Visitors/ResultOperatorProcessors/ProcessContains.cs
Labels: t: Fix

#2680 Fix join on subclass columns
  src/NHibernate.Test/Async/NHSpecificTest/NH1747/Fixture.cs
  src/NHibernate.Test/Async/NHSpecificTest/NH2174/Fixture.cs
  src/NHibernate.Test/NHSpecificTest/NH1747/Fixture.cs
  src/NHibernate.Test/NHSpecificTest/NH2174/Fixture.cs
  src/NHibernate/Engine/IJoin.cs
  src/NHibernate/Engine/JoinHelper.cs
  src/NHibernate/Engine/JoinSequence.cs
  src/NHibernate/Engine/TableGroupJoinHelper.cs
  src/NHibernate/Loader/JoinWalker.cs
  src/NHibernate/Loader/OuterJoinableAssociation.cs
  src/NHibernate/Persister/Entity/AbstractEntityPersister.cs
Labels: t: Fix

#2676 Release 5.3.6
  build-common/NHibernate.props
  releasenotes.txt
Labels: c: Documentation, p: Minor, t: Task

#2691 Fix NoViableAltException in delete query
  src/NHibernate.Test/Async/Hql/EntityJoinHqlTest.cs
  src/NHibernate.Test/Hql/EntityJoinHqlTest.cs
  src/NHibernate.Test/Hql/EntityJoinHqlTestEntities.cs
  src/NHibernate/Hql/Ast/ANTLR/Tree/DotNode.cs
Labels: t: Fix
