Repository nhibernate/nhibernate-core, pull requests merged in 2021-03, with the labels that each got.

#2695 Fix parameter detection when using GroupBy method for Linq provider
  src/NHibernate.Test/Async/Linq/ByMethod/GroupByHavingTests.cs
  src/NHibernate.Test/Async/Linq/ByMethod/GroupByTests.cs
  src/NHibernate.Test/Linq/ByMethod/GroupByHavingTests.cs
  src/NHibernate.Test/Linq/ByMethod/GroupByTests.cs
  src/NHibernate/Linq/ExpressionExtensions.cs
  src/NHibernate/Linq/Visitors/ParameterTypeLocator.cs
  src/NHibernate/Util/ExpressionsHelper.cs
Labels: t: Fix

#2703 Fix LINQ projection of nullable enum with list
  src/NHibernate.Test/Async/Linq/EnumTests.cs
  src/NHibernate.Test/Linq/EnumTests.cs
  src/NHibernate/Linq/NestedSelects/SelectClauseRewriter.cs
Labels: t: Fix

#2705 Propagate ExpectedType to CaseNode in hql
  src/NHibernate.Test/Async/NHSpecificTest/GH2704/FixtureByCode.cs
  src/NHibernate.Test/NHSpecificTest/GH2704/Entity.cs
  src/NHibernate.Test/NHSpecificTest/GH2704/FixtureByCode.cs
  src/NHibernate.Test/NHSpecificTest/GH2704/StringBoolToBoolUserType.cs
  src/NHibernate/Hql/Ast/ANTLR/Tree/CaseNode.cs
Labels: t: Fix

#2576 Fix caching of OneToOneType from second level cache.
  src/NHibernate.Test/Async/NHSpecificTest/GH2552/Fixture.cs
  src/NHibernate.Test/Async/OneToOneType/Fixture.cs
  src/NHibernate.Test/NHSpecificTest/GH2552/Details.cs
  src/NHibernate.Test/NHSpecificTest/GH2552/Fixture.cs
  src/NHibernate.Test/NHSpecificTest/GH2552/Mappings.hbm.xml
  src/NHibernate.Test/NHSpecificTest/GH2552/Person.cs
  src/NHibernate.Test/OneToOneType/Details.cs
  src/NHibernate.Test/OneToOneType/Fixture.cs
  src/NHibernate.Test/OneToOneType/Mappings.hbm.xml
  src/NHibernate.Test/OneToOneType/Owner.cs
  src/NHibernate/Async/Type/OneToOneType.cs
  src/NHibernate/Type/OneToOneType.cs
Labels: t: Fix

#2701 Release 5.3.7
  build-common/NHibernate.props
  releasenotes.txt
Labels: c: Documentation, p: Minor, t: Task

#2706 Set the rolledBack flag when disposing active transactions
  src/NHibernate/Async/Transaction/AdoTransaction.cs
  src/NHibernate/Transaction/AdoTransaction.cs
Labels: c: Core, p: Lowest, t: Improvement

#2713 Skip transparent cast for unknown ident types in hql conditional expression
  src/NHibernate.Test/Async/NHSpecificTest/GH2707/FixtureByCode.cs
  src/NHibernate.Test/NHSpecificTest/GH2707/Entity.cs
  src/NHibernate.Test/NHSpecificTest/GH2707/FixtureByCode.cs
  src/NHibernate/Linq/Visitors/HqlGeneratorExpressionVisitor.cs
Labels: t: Fix

#2712 Fix concurrency issue for update/delete commands when using filters
  src/NHibernate.Test/Async/NHSpecificTest/GH2710/Fixture.cs
  src/NHibernate.Test/NHSpecificTest/GH2710/Entity.cs
  src/NHibernate.Test/NHSpecificTest/GH2710/Fixture.cs
  src/NHibernate.Test/NHSpecificTest/GH2710/Mappings.hbm.xml
  src/NHibernate/Async/Hql/Ast/ANTLR/Exec/BasicExecutor.cs
  src/NHibernate/Async/Hql/Ast/ANTLR/Exec/MultiTableDeleteExecutor.cs
  src/NHibernate/Hql/Ast/ANTLR/Exec/BasicExecutor.cs
  src/NHibernate/Hql/Ast/ANTLR/Exec/MultiTableDeleteExecutor.cs
Labels: t: Fix

#2711 Fix MappedAs when called on an UnaryExpression
  src/NHibernate.Test/Async/Linq/ByMethod/MappedAsTests.cs
  src/NHibernate.Test/Linq/ByMethod/MappedAsTests.cs
  src/NHibernate/Linq/Visitors/ExpressionParameterVisitor.cs
  src/NHibernate/Linq/Visitors/ParameterTypeLocator.cs
Labels: t: Fix
