Repository nhibernate/nhibernate-core, pull requests merged in 2021-08, with the labels that each got.

#2882 Fix ArgumentNullException when provider is unable to open a connection
  src/NHibernate/Async/Tool/hbm2ddl/SchemaExport.cs
  src/NHibernate/Tool/hbm2ddl/SchemaExport.cs
  teamcity.build
Labels: c: SchemaUpdate, p: Lowest, t: Bug

#2875 Keep guessed parameter type in hql
  src/NHibernate.Test/Async/Linq/LinqQuerySamples.cs
  src/NHibernate.Test/Linq/LinqQuerySamples.cs
  src/NHibernate/Hql/Ast/ANTLR/HqlSqlWalker.cs
  src/NHibernate/Hql/Ast/ANTLR/Tree/ParameterNode.cs
  src/NHibernate/Hql/Ast/ANTLR/Tree/SelectClause.cs
  src/NHibernate/Linq/Visitors/ParameterTypeLocator.cs
  src/NHibernate/Param/NamedParameter.cs
Labels: t: Fix

#2879 Fix casting to unmapped interface in LINQ
  src/NHibernate.DomainModel/Northwind/Entities/Animal.cs
  src/NHibernate.Test/Async/NHSpecificTest/GH2858/FixtureByCode.cs
  src/NHibernate.Test/Linq/ParameterTypeLocatorTests.cs
  src/NHibernate.Test/Linq/TryGetMappedTests.cs
  src/NHibernate.Test/NHSpecificTest/GH2858/Entity.cs
  src/NHibernate.Test/NHSpecificTest/GH2858/FixtureByCode.cs
  src/NHibernate/Util/ExpressionsHelper.cs
Labels: t: Fix

#2888 Do not leave AdoTransaction in an inconsistent state
  src/NHibernate/Async/Transaction/AdoTransaction.cs
  src/NHibernate/Transaction/AdoTransaction.cs
Labels: t: Fix

#2877 Fix property type retrieval for Composite User Type in LINQ
  src/NHibernate.Test/Async/NHSpecificTest/GH2856/Fixture.cs
  src/NHibernate.Test/NHSpecificTest/GH2856/Entity.cs
  src/NHibernate.Test/NHSpecificTest/GH2856/Fixture.cs
  src/NHibernate.Test/NHSpecificTest/GH2856/Mappings.hbm.xml
  src/NHibernate.Test/NHSpecificTest/GH2856/PhoneNumber.cs
  src/NHibernate.Test/NHSpecificTest/GH2856/PhoneNumberUserType.cs
  src/NHibernate/Util/ExpressionsHelper.cs
Labels: t: Fix

#2885 Do not serialize unnecessary members in SessionFactory
  src/NHibernate/Impl/SessionFactoryImpl.cs
Labels: t: Bug, r: Fixed, p: Lowest, c: Core

#2889 Fix nullable entity comparison with null
  src/NHibernate.Test/Async/Hql/EntityJoinHqlTest.cs
  src/NHibernate.Test/Hql/EntityJoinHqlTest.cs
  src/NHibernate/Hql/Ast/ANTLR/HqlSqlWalker.cs
  src/NHibernate/Hql/Ast/ANTLR/HqlSqlWalker.g
  src/NHibernate/Hql/Ast/ANTLR/Tree/DotNode.cs
Labels: t: Fix

#2891 Fix nullable entity comparison with null and implicit/cross joins
  src/NHibernate.Test/Async/Hql/EntityJoinHqlTest.cs
  src/NHibernate.Test/Hql/EntityJoinHqlTest.cs
  src/NHibernate/Hql/Ast/ANTLR/SqlGenerator.cs
Labels: t: Bug, c: Core, p: Minor
