Repository nhibernate/nhibernate-core, pull requests merged in 2021-05, with the labels that each got.

#2756 Update dependencies
  src/NHibernate.Test.VisualBasic/NHibernate.Test.VisualBasic.vbproj
  src/NHibernate.Test/NHibernate.Test.csproj
  src/NHibernate.TestDatabaseSetup/NHibernate.TestDatabaseSetup.csproj
  src/NHibernate/NHibernate.csproj
Labels: c: Core, p: Minor, t: Task

#2752 Change cascade style for DefaultDirtyCheckEventListener to persist to avoid flushing the session
  src/NHibernate.Test/Async/NHSpecificTest/GH1413/FixtureByCode.cs
  src/NHibernate.Test/NHSpecificTest/GH1413/FixtureByCode.cs
  src/NHibernate/Async/Event/Default/DefaultDirtyCheckEventListener.cs
  src/NHibernate/Event/Default/DefaultDirtyCheckEventListener.cs
Labels: c: Core, p: Minor, r: Fixed, t: Improvement

#2757 Allow using ForeignGenerator with StatelessSession
  src/NHibernate.Test/Async/OneToOneType/Fixture.cs
  src/NHibernate.Test/OneToOneType/Fixture.cs
  src/NHibernate/Async/Id/ForeignGenerator.cs
  src/NHibernate/Id/ForeignGenerator.cs
Labels: t: Fix

#2758 Fix AmbiguousMatchException in ClearPool with FirebirdClient 6.6.0 and above
  src/NHibernate.Test/NHibernate.Test.csproj
  src/NHibernate/Driver/FirebirdClientDriver.cs
Labels: c: DataProviders / Dialects, p: Lowest, r: Fixed, t: Bug

#2759 Enable dependabot
  .github/dependabot.yml
Labels: c: Toolset, p: Lowest, t: Task

#2743 Implement support of SqlCheck in mapping by code
  src/NHibernate.Test/MappingByCode/MappersTests/JoinMapperTests.cs
  src/NHibernate/Mapping/ByCode/ICollectionSqlsWithCheckMapper.cs
  src/NHibernate/Mapping/ByCode/IEntitySqlsWithCheckMapper.cs
  src/NHibernate/Mapping/ByCode/Impl/BagMapper.cs
  src/NHibernate/Mapping/ByCode/Impl/ClassMapper.cs
  src/NHibernate/Mapping/ByCode/Impl/CustomizersImpl/ClassCustomizer.cs
  src/NHibernate/Mapping/ByCode/Impl/CustomizersImpl/CollectionPropertiesCustomizer.cs
  src/NHibernate/Mapping/ByCode/Impl/CustomizersImpl/JoinCustomizer.cs
  src/NHibernate/Mapping/ByCode/Impl/CustomizersImpl/JoinedSubclassCustomizer.cs
  src/NHibernate/Mapping/ByCode/Impl/CustomizersImpl/SubclassCustomizer.cs
  src/NHibernate/Mapping/ByCode/Impl/CustomizersImpl/UnionSubclassCustomizer.cs
  src/NHibernate/Mapping/ByCode/Impl/IdBagMapper.cs
  src/NHibernate/Mapping/ByCode/Impl/JoinMapper.cs
  src/NHibernate/Mapping/ByCode/Impl/JoinedSubclassMapper.cs
  src/NHibernate/Mapping/ByCode/Impl/ListMapper.cs
  src/NHibernate/Mapping/ByCode/Impl/MapMapper.cs
  src/NHibernate/Mapping/ByCode/Impl/SetMapper.cs
  src/NHibernate/Mapping/ByCode/Impl/SubclassMapper.cs
  src/NHibernate/Mapping/ByCode/Impl/UnionSubclassMapper.cs
  src/NHibernate/Mapping/ByCode/SqlCheck.cs
Labels: r: Fixed, t: Fix

#2755 Fix stateless batcher
  src/AsyncGenerator.yml
  src/NHibernate.Test/Async/NHSpecificTest/GH2750/FixtureByCode.cs
  src/NHibernate.Test/NHSpecificTest/GH2750/Entity.cs
  src/NHibernate.Test/NHSpecificTest/GH2750/FixtureByCode.cs
  src/NHibernate/Async/IStatelessSession.cs
  src/NHibernate/Async/Impl/StatelessSessionImpl.cs
  src/NHibernate/IStatelessSession.cs
  src/NHibernate/Impl/StatelessSessionImpl.cs
Labels: r: Fixed, t: Fix
