Repository nhibernate/nhibernate-core, pull requests merged in 2021-04, with the labels that each got.

#2720 Fix deserialization for same type proxy association
  src/NHibernate.Test/Async/NHSpecificTest/GH2673/Fixture.cs
  src/NHibernate.Test/Async/NHSpecificTest/GH2707/FixtureByCode.cs
  src/NHibernate.Test/NHSpecificTest/GH2673/Entity.cs
  src/NHibernate.Test/NHSpecificTest/GH2673/Fixture.cs
  src/NHibernate/Proxy/NHibernateProxyFactoryInfo.cs
  src/NHibernate/Proxy/NHibernateProxyObjectReference.cs
Labels: t: Fix

#2721 Release 5.3.8
  build-common/NHibernate.props
  releasenotes.txt
Labels: c: Documentation, p: Minor, t: Task

#2742 Remove locks from UpdateTimestampsCache
  src/NHibernate/Async/Cache/UpdateTimestampsCache.cs
  src/NHibernate/Cache/UpdateTimestampsCache.cs
Labels: c: L2 Cache, p: Minor, possible breaking change, t: Improvement
