Repository nhibernate/nhibernate-core, pull requests merged in 2021-06, with the labels that each got.

#2808 Update Travis CI to use Ubuntu Xenial on 5.3.x
  .travis.yml
Labels: c: Toolset, p: Lowest, t: Task

#2794 Fix possible ArgumentNullException when provider is unable to open a connection
  src/NHibernate/Tool/hbm2ddl/SchemaExport.cs
Labels: c: SchemaUpdate, p: Lowest, t: Bug

#2806 Fix SetSnapShot for duplicate items
  src/NHibernate.Test/UtilityTest/SetSnapShotFixture.cs
  src/NHibernate/Collection/Generic/SetHelpers/SetSnapShot.cs
Labels: r: Fixed, t: Fix

#2809 Fix nullable entity projection in hql
  src/NHibernate.Test/Async/Hql/EntityJoinHqlTest.cs
  src/NHibernate.Test/Hql/EntityJoinHqlTest.cs
  src/NHibernate/Hql/Ast/ANTLR/Tree/DotNode.cs
Labels: t: Fix

#2811 Remove session finializer
  src/NHibernate/Impl/SessionImpl.cs
  src/NHibernate/Impl/StatelessSessionImpl.cs
Labels: Regression, c: Core, p: Minor, t: Bug

#2810 Fix join on interface in Linq/hql
  src/NHibernate.Test/Async/Linq/ByMethod/JoinTests.cs
  src/NHibernate.Test/Linq/ByMethod/JoinTests.cs
  src/NHibernate/Hql/Ast/ANTLR/HqlSqlWalker.cs
  src/NHibernate/Impl/SessionFactoryImpl.cs
  src/NHibernate/Linq/Visitors/QueryModelVisitor.cs
Labels: t: Fix

#2793 Fix parameter detection for custom hql method generators
  src/NHibernate.Test/Async/Linq/CustomExtensionsExample.cs
  src/NHibernate.Test/Linq/CustomExtensionsExample.cs
  src/NHibernate/Linq/Visitors/ParameterTypeLocator.cs
Labels: t: Fix

#2827 Fix BadImageFormatException in dynamic proxies for abstract classes and interfaces
  src/NHibernate/Proxy/DynamicProxy/DefaultMethodEmitter.cs
Labels: c: ByteCode providers, p: Lowest, t: Bug

#2816 Add Projections.Conditional for CASE expressions with multiple conditions
  src/NHibernate.Test/Async/Criteria/ConditionalProjectionTest.cs
  src/NHibernate.Test/Criteria/ConditionalProjectionTest.cs
  src/NHibernate/Criterion/ConditionalProjection.cs
  src/NHibernate/Criterion/ConditionalProjectionCase.cs
  src/NHibernate/Criterion/Projections.cs
Labels: t: Fix

#2807 Fix decimal equality comparison for Sqlite
  src/NHibernate.Test/Async/Linq/OperatorTests.cs
  src/NHibernate.Test/Async/Linq/ParameterTests.cs
  src/NHibernate.Test/Linq/OperatorTests.cs
  src/NHibernate.Test/Linq/ParameterTests.cs
  src/NHibernate.Test/TestCase.cs
  src/NHibernate/Dialect/Dialect.cs
  src/NHibernate/Dialect/SQLiteDialect.cs
  src/NHibernate/Linq/Visitors/HqlGeneratorExpressionVisitor.cs
Labels: t: Fix

#2832 Change access modifiers on AliasToBeanResultTransformer
  src/NHibernate/Transform/AliasToBeanResultTransformer.cs
Labels: t: Fix

#2836 Fix Linq failure on null parameter value
  src/NHibernate.Test/Async/Linq/LinqQuerySamples.cs
  src/NHibernate.Test/Linq/LinqQuerySamples.cs
  src/NHibernate/Linq/Visitors/ParameterTypeLocator.cs
Labels: t: Fix
