Repository nhibernate/nhibernate-core, pull requests merged in 2022-03, with the labels that each got.

#3028 Add OracleSuppressDecimalInvalidCastException setting
  doc/reference/modules/configuration.xml
  src/NHibernate.Test/Async/NHSpecificTest/GH2641/Fixture.cs
  src/NHibernate.Test/NHSpecificTest/GH2641/Entity.cs
  src/NHibernate.Test/NHSpecificTest/GH2641/Fixture.cs
  src/NHibernate/AdoNet/DbCommandWrapper.cs
  src/NHibernate/AdoNet/HanaBatchingBatcher.cs
  src/NHibernate/AdoNet/MySqlClientBatchingBatcher.cs
  src/NHibernate/AdoNet/OracleDataClientBatchingBatcher.cs
  src/NHibernate/AdoNet/SqlClientBatchingBatcher.cs
  src/NHibernate/Async/AdoNet/DbCommandWrapper.cs
  src/NHibernate/Async/AdoNet/HanaBatchingBatcher.cs
  src/NHibernate/Async/AdoNet/MySqlClientBatchingBatcher.cs
  src/NHibernate/Async/AdoNet/OracleDataClientBatchingBatcher.cs
  src/NHibernate/Async/Driver/OracleDataClientDriverBase.cs
  src/NHibernate/Cfg/Environment.cs
  src/NHibernate/Driver/DriverBase.cs
  src/NHibernate/Driver/DriverExtensions.cs
  src/NHibernate/Driver/OracleDataClientDriverBase.cs
  src/NHibernate/nhibernate-configuration.xsd
Labels: t: Fix

#3027 Avoid allocations on lock in SyncCacheLock
  src/NHibernate/Cache/SyncCacheLock.cs
Labels: t: Improvement, p: Lowest, c: L2 Cache

#3024 Enable test accessing Component's Parent property in LINQ
  src/NHibernate.Test/Async/NHSpecificTest/GH1583/Fixture.cs
  src/NHibernate.Test/NHSpecificTest/GH1583/Fixture.cs
Labels: c: Tests, p: Minor, t: Tests

#2744 Set which entities classes should never be cached, even indirectly
  doc/reference/modules/configuration.xml
  doc/reference/modules/performance.xml
  src/NHibernate.Test/App.config
  src/NHibernate.Test/Async/SecondLevelCacheTest/NeverCachedEntityTests.cs
  src/NHibernate.Test/CfgTest/EntityCacheUsageParserFixture.cs
  src/NHibernate.Test/DebugSessionFactory.cs
  src/NHibernate.Test/SecondLevelCacheTest/Item.hbm.xml
  src/NHibernate.Test/SecondLevelCacheTest/NeverCachedEntityTests.cs
  src/NHibernate.Test/SecondLevelCacheTest/NeverItem.cs
  src/NHibernate/Action/BulkOperationCleanupAction.cs
  src/NHibernate/Action/CollectionAction.cs
  src/NHibernate/Action/EntityAction.cs
  src/NHibernate/Action/ICacheableExecutable.cs
  src/NHibernate/Async/Action/BulkOperationCleanupAction.cs
  src/NHibernate/Async/Action/CollectionAction.cs
  src/NHibernate/Async/Action/EntityAction.cs
  src/NHibernate/Async/Hql/Ast/ANTLR/QueryTranslatorImpl.cs
  src/NHibernate/Async/Loader/Custom/CustomLoader.cs
  src/NHibernate/Async/Loader/Loader.cs
  src/NHibernate/Async/Persister/Collection/AbstractCollectionPersister.cs
  src/NHibernate/Async/Persister/Entity/AbstractEntityPersister.cs
  src/NHibernate/Cache/CacheFactory.cs
  src/NHibernate/Cfg/EntityCacheUsage.cs
  src/NHibernate/Cfg/Environment.cs
  src/NHibernate/Cfg/MappingSchema/Hbm.generated.cs
  src/NHibernate/Cfg/MappingSchema/HbmExtensions.cs
  src/NHibernate/Cfg/Settings.cs
  src/NHibernate/Cfg/SettingsFactory.cs
  src/NHibernate/Engine/ActionQueue.cs
  src/NHibernate/Engine/ISessionFactoryImplementor.cs
  src/NHibernate/Hql/Ast/ANTLR/HqlSqlWalker.cs
  src/NHibernate/Hql/Ast/ANTLR/QueryTranslatorImpl.cs
  src/NHibernate/Hql/Ast/ANTLR/Tree/DotNode.cs
  src/NHibernate/Hql/Ast/ANTLR/Tree/EntityJoinFromElement.cs
  src/NHibernate/Hql/Ast/ANTLR/Tree/FromElementFactory.cs
  src/NHibernate/Hql/Ast/ANTLR/Tree/IdentNode.cs
  src/NHibernate/Hql/Ast/ANTLR/Tree/MethodNode.cs
  src/NHibernate/Impl/SessionFactoryImpl.cs
  src/NHibernate/Loader/Criteria/ComponentCollectionCriteriaInfoProvider.cs
  src/NHibernate/Loader/Criteria/CriteriaLoader.cs
  src/NHibernate/Loader/Criteria/CriteriaQueryTranslator.cs
  src/NHibernate/Loader/Criteria/EntityCriteriaInfoProvider.cs
  src/NHibernate/Loader/Criteria/IExtendedCriteriaInfoProvider.cs
  src/NHibernate/Loader/Criteria/ScalarCollectionCriteriaInfoProvider.cs
  src/NHibernate/Loader/Custom/CustomLoader.cs
  src/NHibernate/Loader/Hql/QueryLoader.cs
  src/NHibernate/Loader/Loader.cs
  src/NHibernate/Mapping/ByCode/CacheUsage.cs
  src/NHibernate/Persister/Collection/AbstractCollectionPersister.cs
  src/NHibernate/Persister/Collection/ICollectionPersister.cs
  src/NHibernate/Persister/Entity/AbstractEntityPersister.cs
  src/NHibernate/Persister/Entity/IEntityPersister.cs
  src/NHibernate/Persister/IPersister.cs
  src/NHibernate/nhibernate-configuration.xsd
  src/NHibernate/nhibernate-mapping.xsd
Labels: t: New Feature, p: Minor, c: L2 Cache

#3034 Proxy creation fail for class with explicit generic interface
  src/NHibernate.Test/Async/StaticProxyTest/InterfaceHandling/Fixture.cs
  src/NHibernate.Test/StaticProxyTest/InterfaceHandling/Entities.cs
  src/NHibernate.Test/StaticProxyTest/InterfaceHandling/Fixture.cs
  src/NHibernate/Proxy/ProxyBuilderHelper.cs
Labels: t: Fix
