Repository nhibernate/nhibernate-core, pull requests merged in 2022-10, with the labels that each got.

#3172 Skip caching for auto discovery type queries with result transformer
  src/NHibernate.Test/Async/SqlTest/Query/NativeSQLQueriesFixture.cs
  src/NHibernate.Test/SqlTest/Query/NativeSQLQueriesFixture.cs
  src/NHibernate/Loader/Loader.cs
Labels: t: Fix

#3183 Release 5.3.14
  build-common/NHibernate.props
  releasenotes.txt
Labels: p: Minor, c: Documentation, t: Task

#2242 Test case for NH-3972 - SQL error when selecting a column of a subclass when sibling classes have a column of the same name
  src/NHibernate.Test/Async/NHSpecificTest/NH3972/Fixture.cs
  src/NHibernate.Test/NHSpecificTest/NH3972/Change.cs
  src/NHibernate.Test/NHSpecificTest/NH3972/DataChangeState.cs
  src/NHibernate.Test/NHSpecificTest/NH3972/DataIncidentState.cs
  src/NHibernate.Test/NHSpecificTest/NH3972/DataProblemState.cs
  src/NHibernate.Test/NHSpecificTest/NH3972/DataRecord.cs
  src/NHibernate.Test/NHSpecificTest/NH3972/DataRequestForChangeState.cs
  src/NHibernate.Test/NHSpecificTest/NH3972/DataState.cs
  src/NHibernate.Test/NHSpecificTest/NH3972/Entity.cs
  src/NHibernate.Test/NHSpecificTest/NH3972/Fixture.cs
  src/NHibernate.Test/NHSpecificTest/NH3972/Incident.cs
  src/NHibernate.Test/NHSpecificTest/NH3972/Mappings.hbm.xml
  src/NHibernate.Test/NHSpecificTest/NH3972/Problem.cs
  src/NHibernate.Test/NHSpecificTest/NH3972/RequestForChange.cs
Labels: c: Tests, p: Minor, t: Tests

#3188 No way of detecting if AutoFlush performed in added AutoFlushEventListener
  src/NHibernate.Test/Async/NHSpecificTest/NH3583/AutoFlushFixture.cs
  src/NHibernate.Test/NHSpecificTest/NH3583/AutoFlushFixture.cs
  src/NHibernate/Async/Event/Default/DefaultAutoFlushEventListener.cs
  src/NHibernate/Event/Default/DefaultAutoFlushEventListener.cs
Labels: t: Bug, c: Core, p: Minor

#3184 Support caching queries with autodiscovered types
  src/NHibernate.Test/Async/CacheTest/JsonSerializerCacheFixture.cs
  src/NHibernate.Test/Async/QueryTest/MultiCriteriaFixture.cs
  src/NHibernate.Test/Async/QueryTest/MultipleMixedQueriesFixture.cs
  src/NHibernate.Test/Async/QueryTest/MultipleQueriesFixture.cs
  src/NHibernate.Test/Async/SqlTest/Query/NativeSQLQueriesFixture.cs
  src/NHibernate.Test/CacheTest/JsonSerializerCacheFixture.cs
  src/NHibernate.Test/NHibernate.Test.csproj
  src/NHibernate.Test/QueryTest/MultiCriteriaFixture.cs
  src/NHibernate.Test/QueryTest/MultipleMixedQueriesFixture.cs
  src/NHibernate.Test/QueryTest/MultipleQueriesFixture.cs
  src/NHibernate.Test/SqlTest/Query/NativeSQLQueriesFixture.cs
  src/NHibernate/Async/Cache/StandardQueryCache.cs
  src/NHibernate/Cache/StandardQueryCache.cs
  src/NHibernate/Loader/Loader.cs
  src/NHibernate/Transform/CacheableResultTransformer.cs
Labels: r: Fixed, t: Improvement, p: Minor, c: L2 Cache

#3189 Support proxies of classes with init properties
  .config/dotnet-tools.json
  src/NHibernate.Test/StaticProxyTest/IsExternalInit.cs
  src/NHibernate.Test/StaticProxyTest/StaticProxyFactoryFixture.cs
  src/NHibernate/Proxy/ProxyBuilderHelper.cs
Labels: t: Bug, r: Fixed, p: Minor, c: ByteCode providers

#2622 Fix enums used as parameter for string columns
  src/NHibernate.Test/NHSpecificTest/GH2621Enum/Fixture.cs
  src/NHibernate.Test/NHSpecificTest/GH2621Enum/Mappings.hbm.xml
  src/NHibernate.Test/NHSpecificTest/GH2621Enum/Model.cs
  src/NHibernate/Type/AbstractStringType.cs
Labels: r: Fixed, t: Fix
