Repository nhibernate/nhibernate-core, pull requests merged in 2022-01, with the labels that each got.

#2965 Fix possible issue with logging for Linq Readonly tests
  src/NHibernate.Test/Linq/LinqReadonlyTestsContext.cs
  src/NHibernate.Test/TestsContext.cs
  src/NHibernate.Test/TestsContextBase.cs
Labels: t: Bug, p: Lowest, c: Tests

#2964 Fix parameter detection when using custom hql functions
  src/NHibernate.Test/Async/Linq/CustomExtensionsExample.cs
  src/NHibernate.Test/Linq/CustomExtensionsExample.cs
  src/NHibernate.Test/TestDialect.cs
  src/NHibernate/Hql/Ast/ANTLR/HqlSqlWalker.cs
  src/NHibernate/Hql/Ast/ANTLR/QueryTranslatorImpl.cs
  src/NHibernate/Linq/Visitors/ParameterTypeLocator.cs
Labels: t: Fix

#2968 Fix QueryStatistics.ExecutionAvgTime calculation
  src/NHibernate.Test/Async/Stats/StatsFixture.cs
  src/NHibernate.Test/Stats/StatsFixture.cs
  src/NHibernate/Stat/QueryStatistics.cs
Labels: t: Bug, r: Fixed, p: Lowest, c: Core

#2984 Bump AsyncGenerator to 0.18.3 for 5.3 branch with fix for .net 6
  Tools/packages.csproj
Labels: r: Fixed, p: Lowest, c: Toolset, t: Task

#2979 Restore OData tests under .net 6
  src/NHibernate.Test/Async/Linq/ODataTests.cs
  src/NHibernate.Test/NHibernate.Test.csproj
Labels: r: Fixed, c: Tests, t: Fix

#2943 Fix caching SQL queries with enabled auto discovery type
  src/NHibernate.Test/Async/SqlTest/Query/NativeSQLQueriesFixture.cs
  src/NHibernate.Test/SqlTest/Query/NativeSQLQueriesFixture.cs
  src/NHibernate.Test/TestCase.cs
  src/NHibernate/Transform/CacheableResultTransformer.cs
Labels: t: Fix

#2992 Fix schema validator for Npgsql 5
  src/NHibernate.Test/NHibernate.Test.csproj
  src/NHibernate/Dialect/Schema/PostgreSQLMetadata.cs
Labels: t: Fix
