Repository nhibernate/nhibernate-core, pull requests merged in 2022-08, with the labels that each got.

#3080 Replace Dependabot with Renovate
  .github/dependabot.yml
  .github/renovate.json
Labels: c: Toolset, p: Minor, t: Task

#3091 Use GitReleaseManager dotnet tool
  .config/dotnet-tools.json
  ReleaseProcedure.txt
  Tools/packages.csproj
Labels: t: Improvement, p: Lowest, c: Toolset

#3087 Add support for nested non aggregating group by operators
  src/NHibernate.Test/Async/Linq/ByMethod/GroupByTests.cs
  src/NHibernate.Test/Linq/ByMethod/GroupByTests.cs
  src/NHibernate/Linq/GroupBy/NonAggregatingGroupByRewriter.cs
  src/NHibernate/Linq/ResultOperators/NonAggregatingGroupBy.cs
  src/NHibernate/Linq/Visitors/ResultOperatorProcessors/ProcessNonAggregatingGroupBy.cs
Labels: t: Fix

#2959 Support Dynamic BatchFetchStyle
  src/NHibernate.Test/Async/CacheTest/BatchableCacheFixture.cs
  src/NHibernate.Test/Async/CacheTest/BatchableCacheSubclassFixture.cs
  src/NHibernate.Test/Async/NHSpecificTest/NH3142/ChildrenTest.cs
  src/NHibernate.Test/Async/NHSpecificTest/NH3530/BatchFetchStyleFixture.cs
  src/NHibernate.Test/CacheTest/BatchableCacheFixture.cs
  src/NHibernate.Test/CacheTest/BatchableCacheSubclassFixture.cs
  src/NHibernate.Test/NHSpecificTest/NH3142/ChildrenTest.cs
  src/NHibernate.Test/NHSpecificTest/NH3530/BatchFetchStyleFixture.cs
  src/NHibernate.Test/NHSpecificTest/NH3530/Entities.cs
  src/NHibernate.Test/NHSpecificTest/NH3530/EntityMappings.cs
  src/NHibernate/Async/Loader/Collection/AbstractBatchingCollectionInitializer.cs
  src/NHibernate/Async/Loader/Collection/BatchingCollectionInitializer.cs
  src/NHibernate/Async/Loader/Collection/DynamicBatchingCollectionInitializer.cs
  src/NHibernate/Async/Loader/Entity/AbstractBatchingEntityLoader.cs
  src/NHibernate/Async/Loader/Entity/AbstractEntityLoader.cs
  src/NHibernate/Async/Loader/Entity/BatchingEntityLoader.cs
  src/NHibernate/Async/Loader/Entity/DynamicBatchingEntityLoader.cs
  src/NHibernate/Async/Loader/Entity/DynamicEntityLoader.cs
  src/NHibernate/Async/Loader/Loader.cs
  src/NHibernate/Cfg/Environment.cs
  src/NHibernate/Cfg/Settings.cs
  src/NHibernate/Cfg/SettingsFactory.cs
  src/NHibernate/Criterion/InExpression.cs
  src/NHibernate/Loader/BatchFetchStyle.cs
  src/NHibernate/Loader/Collection/AbstractBatchingCollectionInitializer.cs
  src/NHibernate/Loader/Collection/BatchingCollectionInitializer.cs
  src/NHibernate/Loader/Collection/BatchingCollectionInitializerBuilder.cs
  src/NHibernate/Loader/Collection/CollectionLoader.cs
  src/NHibernate/Loader/Collection/DynamicBatchingCollectionInitializer.cs
  src/NHibernate/Loader/Collection/DynamicBatchingCollectionInitializerBuilder.cs
  src/NHibernate/Loader/Collection/DynamicBatchingCollectionLoader.cs
  src/NHibernate/Loader/Collection/LegacyBatchingCollectionInitializerBuilder.cs
  src/NHibernate/Loader/DynamicBatchingHelper.cs
  src/NHibernate/Loader/Entity/AbstractBatchingEntityLoader.cs
  src/NHibernate/Loader/Entity/AbstractEntityLoader.cs
  src/NHibernate/Loader/Entity/BatchingEntityLoader.cs
  src/NHibernate/Loader/Entity/BatchingEntityLoaderBuilder.cs
  src/NHibernate/Loader/Entity/DynamicBatchingEntityLoader.cs
  src/NHibernate/Loader/Entity/DynamicBatchingEntityLoaderBuilder.cs
  src/NHibernate/Loader/Entity/DynamicEntityLoader.cs
  src/NHibernate/Loader/Entity/LegacyBatchingEntityLoaderBuilder.cs
  src/NHibernate/Loader/JoinWalker.cs
  src/NHibernate/Loader/Loader.cs
  src/NHibernate/Persister/Collection/BasicCollectionPersister.cs
  src/NHibernate/Persister/Collection/OneToManyPersister.cs
  src/NHibernate/Persister/Entity/AbstractEntityPersister.cs
  src/NHibernate/SqlCommand/SqlString.cs
  src/NHibernate/nhibernate-configuration.xsd
Labels: t: New Feature, c: Core, p: Minor

#3109 Fix table group join issue with subclasses
  src/NHibernate.Test/Async/Linq/ByMethod/JoinTests.cs
  src/NHibernate.Test/Linq/ByMethod/JoinTests.cs
  src/NHibernate/Engine/TableGroupJoinHelper.cs
Labels: t: Bug, c: Core, p: Minor

#3110 Fix inner join issue when referenced in Where clause in LINQ
  src/NHibernate.Test/Async/Linq/ByMethod/JoinTests.cs
  src/NHibernate.Test/Linq/ByMethod/JoinTests.cs
  src/NHibernate/Linq/GroupJoin/GroupJoinAggregateDetectionVisitor.cs
Labels: t: Bug, c: Linq Provider, p: Minor

#3116 Simplify SqlGenerator.FromFragmentSeparator
  src/NHibernate/Hql/Ast/ANTLR/SqlGenerator.cs
Labels: r: Fixed, t: Improvement, p: Lowest, c: Core

#3125 Fix adding package info to NuGet package
  build-common/NHibernate.props
Labels: r: Fixed, t: Fix

#3120 Guards against use of a disposed session factory
  src/NHibernate.Test/Async/SessionBuilder/Fixture.cs
  src/NHibernate.Test/SessionBuilder/Fixture.cs
  src/NHibernate/Async/Impl/SessionFactoryImpl.cs
  src/NHibernate/Impl/SessionFactoryImpl.cs
Labels: t: Improvement, p: Lowest, c: Core, t: Fix

#3133 Automatically generate async code on pull request
  .github/workflows/GenerateAsyncCode.yml
Labels: r: Fixed, t: Improvement, p: Lowest, c: Toolset

#3126 Fix MappingByCode discriminator string type throws
  src/NHibernate.Test/Async/NHSpecificTest/GH2717/DiscriminatorStringTypeByCodeFixture.cs
  src/NHibernate.Test/NHSpecificTest/GH2717/DiscriminatorStringTypeByCodeFixture.cs
  src/NHibernate.Test/NHSpecificTest/GH2717/Entity.cs
  src/NHibernate/Mapping/ByCode/Impl/DiscriminatorMapper.cs
Labels: t: Fix

#2723 Avoid double param type guessing and better NULL parameter handling in LINQ
  src/NHibernate.Test/Async/NHSpecificTest/NH3565/FixtureByCode.cs
  src/NHibernate.Test/NHSpecificTest/NH3565/Entity.cs
  src/NHibernate.Test/NHSpecificTest/NH3565/FixtureByCode.cs
  src/NHibernate/Async/IQuery.cs
  src/NHibernate/IQuery.cs
  src/NHibernate/Impl/AbstractQueryImpl.cs
  src/NHibernate/Linq/DefaultQueryProvider.cs
Labels: r: Fixed, t: Improvement, c: Linq Provider, p: Minor

#3050 Add .NET Standard 2.1 target
  build-common/NHibernate.props
  default.build
  psake.ps1
  src/NHibernate/Collection/Generic/SetHelpers/SetSnapShot.cs
  src/NHibernate/Driver/DriverBase.cs
  src/NHibernate/Driver/ReflectionBasedDriver.cs
  src/NHibernate/Linq/Functions/MathGenerator.cs
  src/NHibernate/Linq/Functions/RoundGenerator.cs
  src/NHibernate/Linq/Functions/StringGenerator.cs
  src/NHibernate/Linq/Functions/TruncateGenerator.cs
  src/NHibernate/Linq/Visitors/ExpressionKeyVisitor.cs
  src/NHibernate/Linq/Visitors/ExpressionParameterVisitor.cs
  src/NHibernate/Linq/Visitors/HqlGeneratorExpressionVisitor.cs
  src/NHibernate/Linq/Visitors/ParameterTypeLocator.cs
  src/NHibernate/NHibernate.csproj
  src/NHibernate/Proxy/FieldInterceptorProxyBuilder.cs
  src/NHibernate/Proxy/NHibernateProxyBuilder.cs
  src/NHibernate/Util/ExpressionsHelper.cs
Labels: r: Fixed, t: Improvement, p: Lowest, c: Core

#3137 Fix gh3113
  src/NHibernate.Test/Async/NHSpecificTest/GH3113/FixtureByCode.cs
  src/NHibernate.Test/NHSpecificTest/GH3113/Entity.cs
  src/NHibernate.Test/NHSpecificTest/GH3113/FixtureByCode.cs
  src/NHibernate/Hql/Ast/ANTLR/Util/JoinProcessor.cs
Labels: t: Fix

#3140 Fix SelectMode.ChildFetch for many-to-many
  src/NHibernate.Test/Async/NHSpecificTest/GH3134/ManyToManyChildFetchByCodeFixture.cs
  src/NHibernate.Test/NHSpecificTest/GH3134/A.cs
  src/NHibernate.Test/NHSpecificTest/GH3134/AMap.cs
  src/NHibernate.Test/NHSpecificTest/GH3134/B.cs
  src/NHibernate.Test/NHSpecificTest/GH3134/BMap.cs
  src/NHibernate.Test/NHSpecificTest/GH3134/ManyToManyChildFetchByCodeFixture.cs
  src/NHibernate/Loader/OuterJoinableAssociation.cs
Labels: t: Fix

#3144 Fix named parameter leaking to query cache
  src/NHibernate.Test/NHSpecificTest/GH3030/ByCodeFixture.cs
  src/NHibernate/Engine/Query/QueryExpressionPlan.cs
  src/NHibernate/Engine/Query/QueryPlanCache.cs
  src/NHibernate/Hql/Ast/ANTLR/ASTQueryTranslatorFactory.cs
  src/NHibernate/Hql/Ast/ANTLR/HqlSqlWalker.cs
  src/NHibernate/Hql/Ast/ANTLR/QueryTranslatorImpl.cs
  src/NHibernate/Linq/NhLinqExpression.cs
  src/NHibernate/Linq/NhLinqExpressionCache.cs
Labels: t: Fix

#3146 Run tests against Oracle XE 21c
  .github/workflows/NetCoreTests.yml
  lib/teamcity/oracle/oracle_installation.txt
Labels: p: Lowest, c: Tests, t: Task
