Repository nhibernate/nhibernate-core, pull requests merged in 2022-09, with the labels that each got.

#3145 Release 5.3.13
  build-common/NHibernate.props
  releasenotes.txt
Labels: p: Minor, c: Documentation, t: Task

#3147 Add `datetimex` keyword to SapSQLAnywhere17Dialect
  src/NHibernate/Dialect/SapSQLAnywhere17Dialect.cs
Labels: r: Fixed, p: Lowest, c: DataProviders / Dialects, t: Task

#3127 Register IType CLR types as aliases
  src/NHibernate.Test/Async/NHSpecificTest/GH3127/FixtureByCode.cs
  src/NHibernate.Test/NHSpecificTest/GH3127/Entity.cs
  src/NHibernate.Test/NHSpecificTest/GH3127/FixtureByCode.cs
  src/NHibernate.Test/TypesTest/TimestampTypeFixture.cs
  src/NHibernate/Type/TypeFactory.cs
  src/NHibernate/Util/EnumerableExtensions.cs
Labels: r: Fixed, t: Improvement, c: Mapping by Code, p: Minor

#2718 Fix loop detection for associations with fetch="join" mapping
  src/NHibernate.Test/Async/Immutable/EntityWithMutableCollection/AbstractEntityWithOneToManyTest.cs
  src/NHibernate.Test/Async/NHSpecificTest/GH2201/CircularReferenceFetchDepth0Fixture.cs
  src/NHibernate.Test/Async/NHSpecificTest/GH2201/CircularReferenceFetchDepthFixture.cs
  src/NHibernate.Test/Async/NHSpecificTest/GH2201/CircularReferenceFetchFixture.cs
  src/NHibernate.Test/Async/NHSpecificTest/GH2201/DetectFetchLoopsFalseFixture.cs
  src/NHibernate.Test/Immutable/EntityWithMutableCollection/AbstractEntityWithOneToManyTest.cs
  src/NHibernate.Test/NHSpecificTest/GH2201/BaseFetchFixture.cs
  src/NHibernate.Test/NHSpecificTest/GH2201/CircularReferenceFetchDepth0Fixture.cs
  src/NHibernate.Test/NHSpecificTest/GH2201/CircularReferenceFetchDepthFixture.cs
  src/NHibernate.Test/NHSpecificTest/GH2201/CircularReferenceFetchFixture.cs
  src/NHibernate.Test/NHSpecificTest/GH2201/Detail.cs
  src/NHibernate.Test/NHSpecificTest/GH2201/DetectFetchLoopsFalseFixture.cs
  src/NHibernate.Test/NHSpecificTest/GH2201/Entity.cs
  src/NHibernate.Test/NHSpecificTest/GH2201/Mappings.hbm.xml
  src/NHibernate.Test/NHSpecificTest/GH2201/Order.cs
  src/NHibernate.Test/NHSpecificTest/GH2201/Person.cs
  src/NHibernate/Cfg/Environment.cs
  src/NHibernate/Cfg/Settings.cs
  src/NHibernate/Cfg/SettingsFactory.cs
  src/NHibernate/Loader/AbstractEntityJoinWalker.cs
  src/NHibernate/Loader/Criteria/CriteriaJoinWalker.cs
  src/NHibernate/Loader/JoinWalker.cs
  src/NHibernate/nhibernate-configuration.xsd
Labels: t: Fix

#3014 Fix optional join optimistic lock handling
  src/NHibernate.Test/Async/NHSpecificTest/GH1235/OptionalJoinFixture.cs
  src/NHibernate.Test/NHSpecificTest/GH1235/Entity.cs
  src/NHibernate.Test/NHSpecificTest/GH1235/OptionalJoinFixture.cs
  src/NHibernate/Async/Persister/Entity/AbstractEntityPersister.cs
  src/NHibernate/Persister/Entity/AbstractEntityPersister.cs
Labels: r: Fixed, t: Fix

#3154 Fix query dynamic component on unmapped interface
  src/NHibernate.Test/Async/NHSpecificTest/NH2664Generic/Fixture.cs
  src/NHibernate.Test/Async/NHSpecificTest/NH3571Generic/Fixture.cs
  src/NHibernate.Test/NHSpecificTest/NH2664Generic/Fixture.cs
  src/NHibernate.Test/NHSpecificTest/NH2664Generic/IProduct.cs
  src/NHibernate.Test/NHSpecificTest/NH2664Generic/Product.cs
  src/NHibernate.Test/NHSpecificTest/NH3571Generic/Fixture.cs
  src/NHibernate.Test/NHSpecificTest/NH3571Generic/IProduct.cs
  src/NHibernate.Test/NHSpecificTest/NH3571Generic/Product.cs
  src/NHibernate/Linq/Visitors/ExpressionParameterVisitor.cs
  src/NHibernate/Linq/Visitors/VisitorUtil.cs
Labels: r: Fixed, t: Fix

#3157 Compile lambda for null access expressions
  src/NHibernate.Test/Criteria/Lambda/ExpressionProcessorFindValueFixture.cs
  src/NHibernate/Impl/ExpressionProcessor.cs
Labels: t: Fix

#3161 Tell NuGet about the readme file
  src/NHibernate/NHibernate.csproj
Labels: p: Lowest, c: Documentation, t: Task

#3074 Added support for the CancelQuery() method in IStatelessSession
  src/NHibernate.Test/Async/Stateless/StatelessSessionCancelQueryFixture.cs
  src/NHibernate.Test/Stateless/StatelessSessionCancelQueryFixture.cs
  src/NHibernate.Test/TestDialect.cs
  src/NHibernate.Test/TestDialects/MsSql2008TestDialect.cs
  src/NHibernate.Test/TestDialects/Oracle10gTestDialect.cs
  src/NHibernate/AdoNet/AbstractBatcher.cs
  src/NHibernate/Async/AdoNet/AbstractBatcher.cs
  src/NHibernate/IStatelessSession.cs
Labels: t: Fix

#3171 Fix fetching lazy component with formula
  build-common/NHibernate.props
  src/NHibernate.Test/Async/NHSpecificTest/GH3164/FixtureByCode.cs
  src/NHibernate.Test/NHSpecificTest/GH3164/ContentItem.cs
  src/NHibernate.Test/NHSpecificTest/GH3164/ContentItemMapping.cs
  src/NHibernate.Test/NHSpecificTest/GH3164/FixtureByCode.cs
  src/NHibernate.Test/NHSpecificTest/GH3164/Head.cs
  src/NHibernate.Test/NHSpecificTest/GH3164/HeadMapping.cs
  src/NHibernate.Test/NHSpecificTest/GH3164/IHead.cs
  src/NHibernate/Persister/Entity/AbstractEntityPersister.cs
Labels: t: Fix
