Repository nhibernate/nhibernate-core, pull requests merged in 2023-04, with the labels that each got.

#3238 Linq: add enum HasFlag method support
  src/NHibernate.Test/Async/NHSpecificTest/GH0829/Fixture.cs
  src/NHibernate.Test/NHSpecificTest/GH0829/Fixture.cs
  src/NHibernate.Test/NHSpecificTest/GH0829/Mappings.hbm.xml
  src/NHibernate.Test/NHSpecificTest/GH0829/Model.cs
  src/NHibernate.Test/NHSpecificTest/GH0829/TestEnum.cs
  src/NHibernate/Linq/ExpressionTransformers/RemoveRedundantCast.cs
  src/NHibernate/Linq/Functions/DefaultLinqToHqlGeneratorsRegistry.cs
  src/NHibernate/Linq/Functions/HasFlagGenerator.cs
Labels: r: Fixed, t: Fix

#3274 Improve LINQ Contains subquery parameter detection
  src/NHibernate.Test/Async/Linq/WhereTests.cs
  src/NHibernate.Test/Linq/WhereTests.cs
  src/NHibernate/Linq/Visitors/ParameterTypeLocator.cs
Labels: t: Bug, c: Linq Provider, p: Minor

#3275 Migrate dev packages to Cloudsmith
  README.md
Labels: c: Toolset, p: Minor, t: Task

#3276 Release 5.3.16
  build-common/NHibernate.props
  releasenotes.txt
Labels: p: Minor, c: Documentation, t: Task

#3264 Fix collection filter on subclass columns
  src/NHibernate.Test/Async/SubclassFilterTest/JoinedSubclassFilterTest.cs
  src/NHibernate.Test/SubclassFilterTest/JoinedSubclassFilterTest.cs
  src/NHibernate/Persister/Collection/AbstractCollectionPersister.cs
  src/NHibernate/Persister/Entity/AbstractEntityPersister.cs
Labels: t: Bug, r: Fixed, c: Core, p: Minor

#3233 Make object destructors not proxiable
  src/NHibernate.Test/NHSpecificTest/ProxyValidator/ShouldBeProxiableTests.cs
  src/NHibernate/Proxy/DefaultDynamicProxyMethodCheckerExtensions.cs
  src/NHibernate/Util/ReflectionCache.cs
Labels: r: Fixed, t: Fix

#3277 Release 5.4.2
  build-common/NHibernate.props
  releasenotes.txt
Labels: p: Minor, c: Documentation, t: Task

#3284 Update NHibernate.Caches to v5.9.0
  .github/renovate.json
  src/NHibernate.Test/NHibernate.Test.csproj
Labels: r: Fixed, c: Tests, p: Minor, t: Task
