Repository nhibernate/nhibernate-core, pull requests merged in 2023-06, with the labels that each got.

#3310 Move persist tracking context out of the loop in AbstractFlushingEventListener
  src/NHibernate/Async/Event/Default/AbstractFlushingEventListener.cs
  src/NHibernate/Event/Default/AbstractFlushingEventListener.cs
Labels: t: Fix

#3312 Fix referencing nullable entity in correlated subquery
  src/NHibernate.Test/Async/NHSpecificTest/GH3306NullableEntityCorrelatedSubquery/Fixture.cs
  src/NHibernate.Test/NHSpecificTest/GH3306NullableEntityCorrelatedSubquery/Fixture.cs
  src/NHibernate.Test/NHSpecificTest/GH3306NullableEntityCorrelatedSubquery/Mappings.hbm.xml
  src/NHibernate.Test/NHSpecificTest/GH3306NullableEntityCorrelatedSubquery/Model.cs
  src/NHibernate/Hql/Ast/ANTLR/Tree/DotNode.cs
Labels: t: Fix

#3313 Fix LINQ cross join with InformixDialect
  src/NHibernate/Dialect/InformixDialect.cs
  src/NHibernate/Dialect/InformixDialect0940.cs
Labels: t: Fix

#3314 Fix NRE with reused fetch and collection join
  src/NHibernate.Test/Async/NHSpecificTest/GH3288/FetchAndCollectionJoinFixture.cs
  src/NHibernate.Test/NHSpecificTest/GH3288/Entity.cs
  src/NHibernate.Test/NHSpecificTest/GH3288/FetchAndCollectionJoinFixture.cs
  src/NHibernate.Test/NHSpecificTest/GH3288/Mappings.hbm.xml
  src/NHibernate/Hql/Ast/ANTLR/HqlSqlWalker.cs
Labels: t: Fix

#3315 Release 5.3.17
  build-common/NHibernate.props
  releasenotes.txt
Labels: p: Minor, c: Documentation, t: Task

#3318 Merge 5.3.17 in 5.4.x
  releasenotes.txt
  src/NHibernate.Test/Async/NHSpecificTest/GH3306NullableEntityCorrelatedSubquery/Fixture.cs
  src/NHibernate.Test/NHSpecificTest/GH3306NullableEntityCorrelatedSubquery/Fixture.cs
  src/NHibernate.Test/NHSpecificTest/GH3306NullableEntityCorrelatedSubquery/Mappings.hbm.xml
  src/NHibernate.Test/NHSpecificTest/GH3306NullableEntityCorrelatedSubquery/Model.cs
  src/NHibernate.Test/UtilityTest/SetSnapShotFixture.cs
  src/NHibernate/Collection/Generic/SetHelpers/SetSnapShot.cs
  src/NHibernate/Dialect/InformixDialect.cs
  src/NHibernate/Dialect/InformixDialect0940.cs
  src/NHibernate/Hql/Ast/ANTLR/Tree/DotNode.cs
Labels: r: Fixed, c: Core, p: Minor, t: Task

#3316 Fix many-to-many fetch issue
  src/NHibernate.Test/Async/NHSpecificTest/GH3290/Fixture.cs
  src/NHibernate.Test/NHSpecificTest/GH3288/Entity.cs
  src/NHibernate.Test/NHSpecificTest/GH3288/Mappings.hbm.xml
  src/NHibernate.Test/NHSpecificTest/GH3290/Entity.cs
  src/NHibernate.Test/NHSpecificTest/GH3290/Fixture.cs
  src/NHibernate/Loader/JoinWalker.cs
Labels: t: Fix

#3321 Fix components list lazy loading with not lazy associations
  src/NHibernate.Test/Async/NHSpecificTest/GH3317/FixtureByCode.cs
  src/NHibernate.Test/NHSpecificTest/GH3317/Entity.cs
  src/NHibernate.Test/NHSpecificTest/GH3317/FixtureByCode.cs
  src/NHibernate/Loader/JoinWalker.cs
Labels: t: Fix

#3343 Fix FetchLazyProperties updates modified properties
  src/NHibernate.Test/Async/FetchLazyProperties/FetchLazyPropertiesFixture.cs
  src/NHibernate.Test/FetchLazyProperties/FetchLazyPropertiesFixture.cs
  src/NHibernate/Async/Loader/Loader.cs
  src/NHibernate/Loader/Loader.cs
Labels: t: Fix
