Repository nhibernate/nhibernate-core, pull requests merged in 2023-07, with the labels that each got.

#3340 SqlString.Trim should return the same instance for not modified string
  src/NHibernate.Test/SqlCommandTest/SqlStringFixture.cs
  src/NHibernate/SqlCommand/SqlString.cs
Labels: t: Improvement, p: Lowest, c: Core

#3345 Fix lazy property handling with field accessors
  src/NHibernate.Test/Async/LazyProperty/LazyPropertyFixture.cs
  src/NHibernate.Test/LazyProperty/Book.cs
  src/NHibernate.Test/LazyProperty/LazyPropertyFixture.cs
  src/NHibernate.Test/LazyProperty/Mappings.hbm.xml
  src/NHibernate/Tuple/Entity/PocoEntityTuplizer.cs
Labels: t: Fix

#3341 Apply fromFragment processing only when required in ProcessDynamicFilterParameters
  src/NHibernate/Hql/Ast/ANTLR/Util/JoinProcessor.cs
Labels: t: Improvement, p: Lowest, c: Core

#3346 Release 5.3.18
  build-common/NHibernate.props
  releasenotes.txt
Labels: p: Minor, c: Documentation, t: Task

#3348 Merge 5.3.18 into 5.4.x
  releasenotes.txt
  src/NHibernate.Test/Async/FetchLazyProperties/FetchLazyPropertiesFixture.cs
  src/NHibernate.Test/Async/LazyProperty/LazyPropertyFixture.cs
  src/NHibernate.Test/FetchLazyProperties/FetchLazyPropertiesFixture.cs
  src/NHibernate.Test/LazyProperty/Book.cs
  src/NHibernate.Test/LazyProperty/LazyPropertyFixture.cs
  src/NHibernate.Test/LazyProperty/Mappings.hbm.xml
  src/NHibernate/Async/Loader/Loader.cs
  src/NHibernate/Loader/Loader.cs
  src/NHibernate/Tuple/Entity/PocoEntityTuplizer.cs
Labels: c: Core, p: Minor, t: Task

#3349 Release 5.4.3
  build-common/NHibernate.props
  releasenotes.txt
Labels: p: Minor, c: Documentation, t: Task

#3351 Merge 5.4.3 in master
  .github/renovate.json
  releasenotes.txt
  src/NHibernate.Test.VisualBasic/NHibernate.Test.VisualBasic.vbproj
  src/NHibernate.Test/Async/FetchLazyProperties/FetchLazyPropertiesFixture.cs
  src/NHibernate.Test/Async/LazyProperty/LazyPropertyFixture.cs
  src/NHibernate.Test/Async/NHSpecificTest/GH3288/FetchAndCollectionJoinFixture.cs
  src/NHibernate.Test/Async/NHSpecificTest/GH3289/FixtureByCode.cs
  src/NHibernate.Test/Async/NHSpecificTest/GH3290/Fixture.cs
  src/NHibernate.Test/Async/NHSpecificTest/GH3291/Fixture.cs
  src/NHibernate.Test/Async/NHSpecificTest/GH3306NullableEntityCorrelatedSubquery/Fixture.cs
  src/NHibernate.Test/Async/NHSpecificTest/GH3317/FixtureByCode.cs
  src/NHibernate.Test/FetchLazyProperties/FetchLazyPropertiesFixture.cs
  src/NHibernate.Test/LazyProperty/Book.cs
  src/NHibernate.Test/LazyProperty/LazyPropertyFixture.cs
  src/NHibernate.Test/LazyProperty/Mappings.hbm.xml
  src/NHibernate.Test/NHSpecificTest/GH3288/Entity.cs
  src/NHibernate.Test/NHSpecificTest/GH3288/FetchAndCollectionJoinFixture.cs
  src/NHibernate.Test/NHSpecificTest/GH3288/Mappings.hbm.xml
  src/NHibernate.Test/NHSpecificTest/GH3289/FixtureByCode.cs
  src/NHibernate.Test/NHSpecificTest/GH3289/Models.cs
  src/NHibernate.Test/NHSpecificTest/GH3290/Entity.cs
  src/NHibernate.Test/NHSpecificTest/GH3290/Fixture.cs
  src/NHibernate.Test/NHSpecificTest/GH3291/Fixture.cs
  src/NHibernate.Test/NHSpecificTest/GH3291/Mappings.hbm.xml
  src/NHibernate.Test/NHSpecificTest/GH3291/Person.cs
  src/NHibernate.Test/NHSpecificTest/GH3306NullableEntityCorrelatedSubquery/Fixture.cs
  src/NHibernate.Test/NHSpecificTest/GH3306NullableEntityCorrelatedSubquery/Mappings.hbm.xml
  src/NHibernate.Test/NHSpecificTest/GH3306NullableEntityCorrelatedSubquery/Model.cs
  src/NHibernate.Test/NHSpecificTest/GH3317/Entity.cs
  src/NHibernate.Test/NHSpecificTest/GH3317/FixtureByCode.cs
  src/NHibernate.Test/NHibernate.Test.csproj
  src/NHibernate.Test/StaticProxyTest/StaticProxyFactoryFixture.cs
  src/NHibernate.Test/UtilityTest/SetSnapShotFixture.cs
  src/NHibernate.TestDatabaseSetup/NHibernate.TestDatabaseSetup.csproj
  src/NHibernate.TestDatabaseSetup/TestDatabaseSetup.cs
  src/NHibernate/Async/Event/Default/AbstractFlushingEventListener.cs
  src/NHibernate/Async/Loader/Loader.cs
  src/NHibernate/Collection/Generic/SetHelpers/SetSnapShot.cs
  src/NHibernate/Dialect/InformixDialect.cs
  src/NHibernate/Dialect/InformixDialect0940.cs
  src/NHibernate/Driver/NpgsqlDriver.cs
  src/NHibernate/Event/Default/AbstractFlushingEventListener.cs
  src/NHibernate/Hql/Ast/ANTLR/HqlSqlWalker.cs
  src/NHibernate/Hql/Ast/ANTLR/Tree/DotNode.cs
  src/NHibernate/Linq/Visitors/ResultOperatorProcessors/ProcessFetch.cs
  src/NHibernate/Loader/JoinWalker.cs
  src/NHibernate/Loader/Loader.cs
  src/NHibernate/Proxy/ProxyBuilderHelper.cs
  src/NHibernate/Tuple/Entity/PocoEntityTuplizer.cs
Labels: c: Core, p: Minor, t: Task

#3347 Fix getting of initialized proxies for no-proxy associations outside of session scope
  src/NHibernate.Test/Async/GhostProperty/GhostPropertyFixture.cs
  src/NHibernate.Test/GhostProperty/GhostPropertyFixture.cs
  src/NHibernate.Test/GhostProperty/Mappings.hbm.xml
  src/NHibernate.Test/GhostProperty/Order.cs
  src/NHibernate/Intercept/AbstractFieldInterceptor.cs
Labels: t: Fix

#3236 Add MySQL8Dialect and MySQL8InnoDBDialect
  src/NHibernate/Dialect/MySQL8Dialect.cs
  src/NHibernate/Dialect/MySQL8InnoDBDialect.cs
Labels: r: Fixed, c: DataProviders / Dialects, p: Minor, t: Task

#3357 Fix fetching properties from unmapped base class
  src/NHibernate.Test/Async/NHSpecificTest/GH3352/FetchFromNotMappedBaseClassFixture.cs
  src/NHibernate.Test/NHSpecificTest/GH3352/Entity.cs
  src/NHibernate.Test/NHSpecificTest/GH3352/FetchFromNotMappedBaseClassFixture.cs
  src/NHibernate/Linq/Visitors/ResultOperatorProcessors/ProcessFetch.cs
Labels: t: Fix

#3360 Incorrect parameter length for char types in MicrosoftDataSqlClientDriver
  .github/workflows/NetCoreTests.yml
  appveyor.yml
  psake.ps1
  src/NHibernate.TestDatabaseSetup/TestDatabaseSetup.cs
  src/NHibernate/Driver/MicrosoftDataSqlClientDriver.cs
  src/NHibernate/Driver/SqlClientDriver.cs
  teamcity.build
Labels: t: Bug, r: Fixed, p: Lowest, c: DataProviders / Dialects

#3326 Fixes cascading orphan delete on versioned entity
  src/NHibernate.Test/Async/Immutable/EntityWithMutableCollection/AbstractEntityWithManyToManyTest.cs
  src/NHibernate.Test/Async/NHSpecificTest/GH3325/Fixture.cs
  src/NHibernate.Test/Async/ReadOnly/ReadOnlyVersionedNodes.cs
  src/NHibernate.Test/Immutable/EntityWithMutableCollection/AbstractEntityWithManyToManyTest.cs
  src/NHibernate.Test/NHSpecificTest/GH3325/Entity.cs
  src/NHibernate.Test/NHSpecificTest/GH3325/Fixture.cs
  src/NHibernate.Test/NHSpecificTest/GH3325/Mappings.hbm.xml
  src/NHibernate.Test/ReadOnly/ReadOnlyVersionedNodes.cs
  src/NHibernate/Async/Event/Default/AbstractSaveEventListener.cs
  src/NHibernate/Event/Default/AbstractSaveEventListener.cs
Labels: r: Fixed, t: Fix

#3365 Call BeforeAssemble on persistent collections' InitializeFromCache to allow batched cache fetching
  src/NHibernate.Test/Async/CacheTest/BatchableCacheFixture.cs
  src/NHibernate.Test/CacheTest/BatchableCacheFixture.cs
  src/NHibernate/Async/Collection/Generic/PersistentGenericBag.cs
  src/NHibernate/Async/Collection/Generic/PersistentGenericIdentifierBag.cs
  src/NHibernate/Async/Collection/Generic/PersistentGenericList.cs
  src/NHibernate/Async/Collection/Generic/PersistentGenericMap.cs
  src/NHibernate/Async/Collection/Generic/PersistentGenericSet.cs
  src/NHibernate/Async/Collection/PersistentArrayHolder.cs
  src/NHibernate/Collection/Generic/PersistentGenericBag.cs
  src/NHibernate/Collection/Generic/PersistentGenericIdentifierBag.cs
  src/NHibernate/Collection/Generic/PersistentGenericList.cs
  src/NHibernate/Collection/Generic/PersistentGenericMap.cs
  src/NHibernate/Collection/Generic/PersistentGenericSet.cs
  src/NHibernate/Collection/PersistentArrayHolder.cs
Labels: t: Fix

#3367 Update readme with actual dev build information for 5.4
  README.md
Labels: p: Lowest, c: Documentation, t: Task

#3368 Allow internal entity classes/interfaces in .NET Standard 2.0 for field interceptor
  src/NHibernate/Proxy/FieldInterceptorProxyBuilder.cs
Labels: r: Fixed, t: Improvement, p: Minor, c: ByteCode providers

#3328 Fix AND/OR negation logic in hql
  src/NHibernate.Test/Async/NHSpecificTest/GH3327/Fixture.cs
  src/NHibernate.Test/NHSpecificTest/GH3327/Entity.cs
  src/NHibernate.Test/NHSpecificTest/GH3327/Fixture.cs
  src/NHibernate.Test/NHSpecificTest/GH3327/Mappings.hbm.xml
  src/NHibernate/Hql/Ast/ANTLR/HqlParser.cs
Labels: t: Fix

#3373 Refactor sequential select related members in AbstractEntityPersister
  src/NHibernate/Persister/Entity/AbstractEntityPersister.cs
  src/NHibernate/Persister/Entity/SingleTableEntityPersister.cs
Labels: t: Improvement, c: Core, p: Minor

#3374 Simplify aggregateDistinctAll rule in Hql.g
  src/NHibernate/Hql/Ast/ANTLR/Hql.g
Labels: r: Fixed, t: Improvement, p: Lowest, c: Core

#3379 Remove NHibernate.Example.Web project
  .github/renovate.json
  src/NHibernate.Everything.sln
  src/NHibernate.Example.Web/Infrastructure/AppSessionFactory.cs
  src/NHibernate.Example.Web/Infrastructure/NHibernateToMicrosoftLogger.cs
  src/NHibernate.Example.Web/Infrastructure/NHibernateToMicrosoftLoggerFactory.cs
  src/NHibernate.Example.Web/Models/Item.cs
  src/NHibernate.Example.Web/Models/ItemMap.cs
  src/NHibernate.Example.Web/NHibernate.Example.Web.csproj
  src/NHibernate.Example.Web/Pages/Error.cshtml
  src/NHibernate.Example.Web/Pages/Error.cshtml.cs
  src/NHibernate.Example.Web/Pages/Index.cshtml
  src/NHibernate.Example.Web/Pages/Index.cshtml.cs
  src/NHibernate.Example.Web/Pages/InsertItem.cshtml
  src/NHibernate.Example.Web/Pages/InsertItem.cshtml.cs
  src/NHibernate.Example.Web/Pages/Schema.cshtml
  src/NHibernate.Example.Web/Pages/Schema.cshtml.cs
  src/NHibernate.Example.Web/Pages/ViewData.cshtml
  src/NHibernate.Example.Web/Pages/ViewData.cshtml.cs
  src/NHibernate.Example.Web/Pages/_Layout.cshtml
  src/NHibernate.Example.Web/Pages/_ViewImports.cshtml
  src/NHibernate.Example.Web/Pages/_ViewStart.cshtml
  src/NHibernate.Example.Web/Program.cs
  src/NHibernate.Example.Web/Properties/launchSettings.json
  src/NHibernate.Example.Web/Startup.cs
  src/NHibernate.Example.Web/appsettings.Development.json
  src/NHibernate.Example.Web/appsettings.json
Labels: p: Lowest, c: Documentation, t: Task

#3377 Move HqlToken.PossibleId to HqlParser.IsPossibleId method and remove castings
  src/NHibernate/Hql/Ast/ANTLR/HqlParser.cs
  src/NHibernate/Hql/Ast/ANTLR/HqlToken.cs
Labels: t: Improvement, p: Lowest, c: Core

#3384 Improve path rule handling with reserved words in Hql.g
  src/NHibernate.Test/Hql/Parser/HqlParserFixture.cs
  src/NHibernate.Test/Hql/Parser/WarningAsErrorReporter.cs
  src/NHibernate.Test/NHibernate.Test.csproj
  src/NHibernate/Hql/Ast/ANTLR/Hql.g
  src/NHibernate/Hql/Ast/ANTLR/HqlParser.cs
Labels: t: Improvement, c: Core, p: Minor

#3386 Release 5.4.4
  build-common/NHibernate.props
  releasenotes.txt
Labels: p: Minor, c: Documentation, t: Task

#3387 Merge 5.4.4 into master
  releasenotes.txt
  src/NHibernate.Test/Async/CacheTest/BatchableCacheFixture.cs
  src/NHibernate.Test/Async/LazyProperty/LazyPropertyFixture.cs
  src/NHibernate.Test/Async/NHSpecificTest/GH3352/FetchFromNotMappedBaseClassFixture.cs
  src/NHibernate.Test/CacheTest/BatchableCacheFixture.cs
  src/NHibernate.Test/LazyProperty/Book.cs
  src/NHibernate.Test/LazyProperty/LazyPropertyFixture.cs
  src/NHibernate.Test/NHSpecificTest/GH3352/Entity.cs
  src/NHibernate.Test/NHSpecificTest/GH3352/FetchFromNotMappedBaseClassFixture.cs
  src/NHibernate/Async/Collection/Generic/PersistentGenericBag.cs
  src/NHibernate/Async/Collection/Generic/PersistentGenericIdentifierBag.cs
  src/NHibernate/Async/Collection/Generic/PersistentGenericList.cs
  src/NHibernate/Async/Collection/Generic/PersistentGenericMap.cs
  src/NHibernate/Async/Collection/Generic/PersistentGenericSet.cs
  src/NHibernate/Async/Collection/PersistentArrayHolder.cs
  src/NHibernate/Collection/Generic/PersistentGenericBag.cs
  src/NHibernate/Collection/Generic/PersistentGenericIdentifierBag.cs
  src/NHibernate/Collection/Generic/PersistentGenericList.cs
  src/NHibernate/Collection/Generic/PersistentGenericMap.cs
  src/NHibernate/Collection/Generic/PersistentGenericSet.cs
  src/NHibernate/Collection/PersistentArrayHolder.cs
  src/NHibernate/Linq/Visitors/ResultOperatorProcessors/ProcessFetch.cs
  src/NHibernate/Proxy/FieldInterceptorProxyBuilder.cs
Labels: c: Core, p: Minor, t: Task
