Repository nhibernate/nhibernate-core, pull requests merged in 2023-01, with the labels that each got.

#3217 Fix Count Distinct on path with hql reserved words
  src/NHibernate.Test/Async/NHSpecificTest/GH3215/FixtureByCode.cs
  src/NHibernate.Test/NHSpecificTest/GH3215/Entity.cs
  src/NHibernate.Test/NHSpecificTest/GH3215/FixtureByCode.cs
  src/NHibernate/Hql/Ast/ANTLR/Hql.g
Labels: t: Fix

#3187 Fix mixing implied implicit and left joins in hql for v5.3
  build-common/NHibernate.props
  src/NHibernate.Test/Async/Hql/EntityJoinHqlTest.cs
  src/NHibernate.Test/Hql/EntityJoinHqlTest.cs
  src/NHibernate/Hql/Ast/ANTLR/Tree/FromElement.cs
Labels: t: Bug, p: Lowest, c: Core

#3222 Automatically generate async code on pull requests for 5.3
  .github/workflows/GenerateAsyncCode.yml
  Tools/.gitignore
Labels: p: Minor, t: Task, c: Async

#3220 Fix Contains subquery with parameter
  src/NHibernate.Test/Async/NHSpecificTest/GH3218/ContainsParameterFixture.cs
  src/NHibernate.Test/NHSpecificTest/GH3218/ContainsParameterFixture.cs
  src/NHibernate.Test/NHSpecificTest/GH3218/Entity.cs
  src/NHibernate/Linq/Visitors/ResultOperatorProcessors/ProcessContains.cs
Labels: t: Fix

#3216 Enable one-to-one optimistic lock handling in mapping
  doc/reference/modules/basic_mapping.xml
  src/NHibernate.Test/Async/NHSpecificTest/GH3204/OneToOneOptimisticLockFixture.cs
  src/NHibernate.Test/NHSpecificTest/GH3204/Entity.cs
  src/NHibernate.Test/NHSpecificTest/GH3204/OneToOneOptimisticLockFixture.cs
  src/NHibernate/Cfg/MappingSchema/Hbm.generated.cs
  src/NHibernate/Cfg/MappingSchema/HbmOneToOne.cs
  src/NHibernate/Mapping/ByCode/Impl/OneToOneMapper.cs
  src/NHibernate/nhibernate-mapping.xsd
Labels: t: Bug, c: Core, p: Minor, Regression

#3209 Allow custom query loader
  src/NHibernate.Test/Async/QueryTranslator/CustomQueryLoaderFixture.cs
  src/NHibernate.Test/BulkManipulation/BaseFixture.cs
  src/NHibernate.Test/Hql/Ast/BaseFixture.cs
  src/NHibernate.Test/NHSpecificTest/NH2031/HqlModFuctionForMsSqlTest.cs
  src/NHibernate.Test/QueryTranslator/CustomQueryLoader.cs
  src/NHibernate.Test/QueryTranslator/CustomQueryLoaderFactory.cs
  src/NHibernate.Test/QueryTranslator/CustomQueryLoaderFixture.cs
  src/NHibernate.Test/QueryTranslator/CustomQueryTranslatorFactory.cs
  src/NHibernate/Async/Hql/Ast/ANTLR/QueryTranslatorImpl.cs
  src/NHibernate/Async/Hql/IQueryTranslator.cs
  src/NHibernate/Async/Impl/MultiQueryImpl.cs
  src/NHibernate/Async/Loader/Hql/IQueryLoader.cs
  src/NHibernate/Async/Loader/Hql/QueryLoader.cs
  src/NHibernate/Async/Loader/ILoader.cs
  src/NHibernate/Async/Loader/Loader.cs
  src/NHibernate/Async/Multi/CriteriaBatchItem.cs
  src/NHibernate/Async/Multi/QueryBatchItemBase.cs
  src/NHibernate/Cache/CachePutData.cs
  src/NHibernate/Cache/QueryCacheResultBuilder.cs
  src/NHibernate/Engine/Query/QueryPlanCache.cs
  src/NHibernate/Hql/Ast/ANTLR/ASTQueryTranslatorFactory.cs
  src/NHibernate/Hql/Ast/ANTLR/QueryTranslatorImpl.cs
  src/NHibernate/Hql/IQueryTranslator.cs
  src/NHibernate/Impl/MultiQueryImpl.cs
  src/NHibernate/Linq/DefaultQueryProvider.cs
  src/NHibernate/Linq/ILinqQueryExpression.cs
  src/NHibernate/Linq/NhLinqExpression.cs
  src/NHibernate/Linq/NhLinqExpressionCache.cs
  src/NHibernate/Loader/Criteria/CriteriaLoader.cs
  src/NHibernate/Loader/Custom/CustomLoader.cs
  src/NHibernate/Loader/Hql/IQueryLoader.cs
  src/NHibernate/Loader/Hql/IQueryLoaderFactory.cs
  src/NHibernate/Loader/Hql/QueryLoader.cs
  src/NHibernate/Loader/Hql/QueryLoaderFactory.cs
  src/NHibernate/Loader/ILoader.cs
  src/NHibernate/Loader/Loader.cs
  src/NHibernate/Multi/CriteriaBatchItem.cs
  src/NHibernate/Multi/QueryBatchItem.cs
  src/NHibernate/Multi/QueryBatchItemBase.cs
  src/NHibernate/Persister/IPersister.cs
Labels: t: Improvement, c: Core, p: Minor

#3225 Release 5.3.15
  build-common/NHibernate.props
  releasenotes.txt
Labels: p: Minor, c: Documentation, t: Task
