Repository nhibernate/nhibernate-core, pull requests merged in 2023-08, with the labels that each got.

#3390 Enable Not node handling in HqlParser.NegateNode
  src/NHibernate.Test/Async/NHSpecificTest/GH3327/Fixture.cs
  src/NHibernate.Test/NHSpecificTest/GH3327/Fixture.cs
  src/NHibernate/Hql/Ast/ANTLR/HqlParser.cs
Labels: t: Improvement, p: Lowest, c: Core

#3391 Clean up Linq Joiner class removing no longer needed AddJoinMethod property
  src/NHibernate/Linq/Visitors/JoinBuilder.cs
Labels: r: Fixed, t: Fix

#3392 Partial fix fetching lazy property after Select in Linq
  src/NHibernate.Test/Async/FetchLazyProperties/FetchLazyPropertiesFixture.cs
  src/NHibernate.Test/FetchLazyProperties/FetchLazyPropertiesFixture.cs
  src/NHibernate/Linq/IntermediateHqlTree.cs
  src/NHibernate/Linq/Visitors/ResultOperatorProcessors/ProcessFetch.cs
Labels: t: Bug, c: Linq Provider, p: Minor

#3394 Get rid of select queries for each ManyToMany not found ignored element in hql
  src/NHibernate.Test/Async/NHSpecificTest/NH750/ManyToManyNotFoundIgnoreFixture.cs
  src/NHibernate.Test/NHSpecificTest/NH750/ManyToManyNotFoundIgnoreFixture.cs
  src/NHibernate/Engine/TableGroupJoinHelper.cs
  src/NHibernate/Hql/Ast/ANTLR/Tree/FromElementFactory.cs
Labels: t: Improvement, c: Core, p: Minor

#3395 Remove ConstantConverter
  src/NHibernate/Hql/Ast/ANTLR/QueryTranslatorImpl.cs
  src/NHibernate/Hql/Ast/ANTLR/Tree/DotNode.cs
  src/NHibernate/Hql/Ast/ANTLR/Tree/JavaConstantNode.cs
  src/NHibernate/Hql/Ast/ANTLR/Util/LiteralProcessor.cs
  src/NHibernate/Util/ReflectHelper.cs
Labels: t: Improvement, c: Core, p: Minor

#3396 Get rid of select queries for each ManyToMany not found ignored element in Criteria and lazy loading
  src/NHibernate.Test/Async/NHSpecificTest/NH750/ManyToManyFixture.cs
  src/NHibernate.Test/Async/NHSpecificTest/NH750/ManyToManyNotFoundIgnoreFixture.cs
  src/NHibernate.Test/Async/NHSpecificTest/NH750/ManyToManyThrowsForNotFoundFixture.cs
  src/NHibernate.Test/NHSpecificTest/NH750/Device.cs
  src/NHibernate.Test/NHSpecificTest/NH750/Drive.cs
  src/NHibernate.Test/NHSpecificTest/NH750/ManyToManyFixture.cs
  src/NHibernate.Test/NHSpecificTest/NH750/ManyToManyNotFoundIgnoreFixture.cs
  src/NHibernate.Test/NHSpecificTest/NH750/ManyToManyThrowsForNotFoundFixture.cs
  src/NHibernate.Test/NHSpecificTest/NH750/Mappings.hbm.xml
  src/NHibernate/Loader/JoinWalker.cs
Labels: t: Improvement, p: Minor, c: Criteria

#3399 Wrap mapping usages in StaticDialectMappingWrapper in Configuration class
  src/NHibernate/Cfg/Configuration.cs
Labels: t: Fix

#3404 Fix NamedSQLQuery ignores query-param type
  src/NHibernate.Test/Async/NHSpecificTest/GH3311SqlQueryParam/SqlQueryParamTypeFixture.cs
  src/NHibernate.Test/NHSpecificTest/GH3311SqlQueryParam/Entity.cs
  src/NHibernate.Test/NHSpecificTest/GH3311SqlQueryParam/Mappings.hbm.xml
  src/NHibernate.Test/NHSpecificTest/GH3311SqlQueryParam/SqlQueryParamTypeFixture.cs
  src/NHibernate/Cfg/XmlHbmBinding/NamedSQLQueryBinder.cs
  src/NHibernate/Engine/Query/QueryPlanCache.cs
  src/NHibernate/Impl/AbstractSessionImpl.cs
Labels: t: Fix

#3405 Release 5.3.19
  build-common/NHibernate.props
  releasenotes.txt
Labels: p: Minor, c: Documentation, t: Task

#3408 Release 5.4.5
  build-common/NHibernate.props
  releasenotes.txt
Labels: p: Minor, c: Documentation, t: Task

#3409 Merge 5.4.5 in master
  releasenotes.txt
  src/NHibernate/Cfg/Configuration.cs
Labels: c: Core, p: Minor, t: Task

#3406 Fix orphan removal for detached one-to-one
  src/NHibernate.Test/Async/NHSpecificTest/GH3403OneToOne/Fixture.cs
  src/NHibernate.Test/NHSpecificTest/GH3403OneToOne/Entity.cs
  src/NHibernate.Test/NHSpecificTest/GH3403OneToOne/Fixture.cs
  src/NHibernate.Test/NHSpecificTest/GH3403OneToOne/Mappings.hbm.xml
  src/NHibernate/Async/Engine/Cascade.cs
  src/NHibernate/Engine/Cascade.cs
Labels: t: Bug, c: Core, p: Minor

#3398 Do not store mapping field in Configuration
  src/NHibernate.Test/DialectTest/MsSql2008DialectFixture.cs
  src/NHibernate/Cfg/Configuration.cs
Labels: t: Improvement, c: Core, p: Minor

#3410 Remove redundant collection BeforeAssemble call from query cache
  src/NHibernate.Test/Async/CacheTest/BatchableCacheFixture.cs
  src/NHibernate.Test/CacheTest/BatchableCacheFixture.cs
  src/NHibernate/Async/Collection/Generic/PersistentGenericBag.cs
  src/NHibernate/Async/Collection/Generic/PersistentGenericIdentifierBag.cs
  src/NHibernate/Async/Collection/Generic/PersistentGenericList.cs
  src/NHibernate/Async/Collection/Generic/PersistentGenericMap.cs
  src/NHibernate/Async/Collection/Generic/PersistentGenericSet.cs
  src/NHibernate/Async/Collection/PersistentArrayHolder.cs
  src/NHibernate/Collection/Generic/PersistentGenericBag.cs
  src/NHibernate/Collection/Generic/PersistentGenericIdentifierBag.cs
  src/NHibernate/Collection/Generic/PersistentGenericList.cs
  src/NHibernate/Collection/Generic/PersistentGenericMap.cs
  src/NHibernate/Collection/Generic/PersistentGenericSet.cs
  src/NHibernate/Collection/PersistentArrayHolder.cs
Labels: t: Improvement, p: Minor, c: L2 Cache

#3411 Remove ISessionFactoryImplementor parameter from TableGroupJoinHelper
  src/NHibernate/Engine/JoinSequence.cs
  src/NHibernate/Engine/TableGroupJoinHelper.cs
  src/NHibernate/Loader/JoinWalker.cs
Labels: r: Fixed, t: Improvement, p: Lowest, t: Task

#3412 Revive hql ParsingFixture
  src/NHibernate.Test/Hql/Ast/ParsingFixture.cs
  src/NHibernate.Test/Hql/Ast/TestQueries.xml
  src/NHibernate.Test/Hql/Ast/TestQueriesWithResults.xml
  src/NHibernate.Test/NHibernate.Test.csproj
Labels: c: Core, p: Minor, t: Tests

#3413 Downgrade dependency System.Data.SQLite.Core 1.0.118 -> 1.0.117
  src/NHibernate.Test/NHibernate.Test.csproj
Labels: t: Bug, c: Tests, p: Minor

#3414 Reenable use of SelectClauseVisitor for subqueries
  src/NHibernate.Test/Async/Linq/WhereTests.cs
  src/NHibernate.Test/Linq/WhereTests.cs
  src/NHibernate/Linq/Visitors/QueryModelVisitor.cs
  src/NHibernate/Linq/Visitors/SelectClauseNominator.cs
  src/NHibernate/Linq/Visitors/SelectClauseVisitor.cs
Labels: t: Bug, c: Linq Provider, p: Minor, Regression

#3420 Merge 5.4.6 in master
  releasenotes.txt
  src/NHibernate.Test/Async/Linq/WhereTests.cs
  src/NHibernate.Test/Linq/WhereTests.cs
  src/NHibernate/Linq/Visitors/QueryModelVisitor.cs
  src/NHibernate/Linq/Visitors/SelectClauseNominator.cs
  src/NHibernate/Linq/Visitors/SelectClauseVisitor.cs
Labels: c: Core, p: Minor, t: Task
