Repository nhibernate/nhibernate-core, pull requests merged in 2023-05, with the labels that each got.

#3299 Fix invalid handling of null DateTime parameters in Npgsql 6+
  src/NHibernate.Test/Async/NHSpecificTest/GH3291/Fixture.cs
  src/NHibernate.Test/NHSpecificTest/GH3291/Fixture.cs
  src/NHibernate.Test/NHSpecificTest/GH3291/Mappings.hbm.xml
  src/NHibernate.Test/NHSpecificTest/GH3291/Person.cs
  src/NHibernate.TestDatabaseSetup/TestDatabaseSetup.cs
  src/NHibernate/Driver/NpgsqlDriver.cs
Labels: t: Fix

#3298 Fix building proxies for classess with static interface members
  src/NHibernate.Test/StaticProxyTest/StaticProxyFactoryFixture.cs
  src/NHibernate/Proxy/ProxyBuilderHelper.cs
Labels: r: Fixed, t: Fix

#3301 Npgsql 6: set parameter DbType to DateTime2 when value is not Utc DateTime
  src/NHibernate/Driver/NpgsqlDriver.cs
Labels: t: Fix

#3300 Backport handling of null DateTime parameters in Npgsql 6+
  src/NHibernate.Test/Async/NHSpecificTest/GH3291/Fixture.cs
  src/NHibernate.Test/NHSpecificTest/GH3291/Fixture.cs
  src/NHibernate.Test/NHSpecificTest/GH3291/Mappings.hbm.xml
  src/NHibernate.Test/NHSpecificTest/GH3291/Person.cs
  src/NHibernate.TestDatabaseSetup/TestDatabaseSetup.cs
  src/NHibernate/Driver/NpgsqlDriver.cs
Labels: c: DataProviders / Dialects, p: Minor, t: Task

#3302 Upgrade NUnit3TestAdapter to fix "Unknown framework version 7.0"
  .github/renovate.json
  src/NHibernate.Test.VisualBasic/NHibernate.Test.VisualBasic.vbproj
  src/NHibernate.Test/NHibernate.Test.csproj
  src/NHibernate.TestDatabaseSetup/NHibernate.TestDatabaseSetup.csproj
Labels: c: Tests, p: Minor, t: Task

#3242 Linq: add enum Equals and object Equals support
  src/NHibernate.Test/Async/Linq/FunctionTests.cs
  src/NHibernate.Test/Linq/FunctionTests.cs
  src/NHibernate/Linq/Functions/DefaultLinqToHqlGeneratorsRegistry.cs
  src/NHibernate/Linq/Functions/EqualsGenerator.cs
Labels: r: Fixed, t: New Feature, c: Linq Provider, p: Minor

#3304 Fix SetSnapShot CopyTo variance failure
  src/NHibernate.Test/UtilityTest/SetSnapShotFixture.cs
  src/NHibernate/Collection/Generic/SetHelpers/SetSnapShot.cs
Labels: t: Bug, p: Lowest, c: Core
