Repository nhibernate/nhibernate-core, pull requests merged in 2024-07, with the labels that each got.

#3547 Handle SQL injection vulnerabilities within ObjectToSQLString
  doc/reference/modules/configuration.xml
  src/NHibernate.Config.Templates/SapSQLAnywhere.cfg.xml
  src/NHibernate.Test/Async/NHSpecificTest/GH3516/FixtureByCode.cs
  src/NHibernate.Test/NHSpecificTest/GH3516/Entity.cs
  src/NHibernate.Test/NHSpecificTest/GH3516/FixtureByCode.cs
  src/NHibernate.Test/NHSpecificTest/GH3516/Hierarchy.cs
  src/NHibernate.Test/SqlCommandTest/SqlInsertBuilderFixture.cs
  src/NHibernate.Test/TestDialect.cs
  src/NHibernate.Test/TestDialects/Oracle10gTestDialect.cs
  src/NHibernate.Test/TestDialects/SapSQLAnywhere17TestDialect.cs
  src/NHibernate/Async/Type/ByteType.cs
  src/NHibernate/Async/Type/Int16Type.cs
  src/NHibernate/Async/Type/Int32Type.cs
  src/NHibernate/Async/Type/Int64Type.cs
  src/NHibernate/Async/Type/TicksType.cs
  src/NHibernate/Async/Type/TimeAsTimeSpanType.cs
  src/NHibernate/Async/Type/TimeSpanType.cs
  src/NHibernate/Async/Type/UInt16Type.cs
  src/NHibernate/Async/Type/UInt32Type.cs
  src/NHibernate/Async/Type/UInt64Type.cs
  src/NHibernate/Cfg/Environment.cs
  src/NHibernate/Dialect/DB2Dialect.cs
  src/NHibernate/Dialect/Dialect.cs
  src/NHibernate/Dialect/IngresDialect.cs
  src/NHibernate/Dialect/MsSql2000Dialect.cs
  src/NHibernate/Dialect/MySQLDialect.cs
  src/NHibernate/Dialect/Oracle8iDialect.cs
  src/NHibernate/Dialect/SybaseASA9Dialect.cs
  src/NHibernate/Dialect/SybaseSQLAnywhere10Dialect.cs
  src/NHibernate/Type/AbstractCharType.cs
  src/NHibernate/Type/AbstractDateTimeType.cs
  src/NHibernate/Type/AbstractStringType.cs
  src/NHibernate/Type/ByteType.cs
  src/NHibernate/Type/CharBooleanType.cs
  src/NHibernate/Type/DateTimeOffSetType.cs
  src/NHibernate/Type/DateType.cs
  src/NHibernate/Type/DecimalType.cs
  src/NHibernate/Type/DoubleType.cs
  src/NHibernate/Type/EnumCharType.cs
  src/NHibernate/Type/GuidType.cs
  src/NHibernate/Type/Int16Type.cs
  src/NHibernate/Type/Int32Type.cs
  src/NHibernate/Type/Int64Type.cs
  src/NHibernate/Type/SByteType.cs
  src/NHibernate/Type/SingleType.cs
  src/NHibernate/Type/TicksType.cs
  src/NHibernate/Type/TimeAsTimeSpanType.cs
  src/NHibernate/Type/TimeSpanType.cs
  src/NHibernate/Type/TimeType.cs
  src/NHibernate/Type/UInt16Type.cs
  src/NHibernate/Type/UInt32Type.cs
  src/NHibernate/Type/UInt64Type.cs
  src/NHibernate/Type/UriType.cs
  src/NHibernate/nhibernate-configuration.xsd
Labels: t: Bug, c: Core, p: Minor

#3574 Remove usage of NHIBERNATE_BOT_TOKEN
  .github/workflows/GenerateAsyncCode.yml
Labels: p: Minor, t: Task, c: Async

#3576 Release 5.4.9
  build-common/NHibernate.props
  releasenotes.txt
Labels: p: Minor, c: Documentation, t: Task

#3578 Release 5.5.2
  build-common/NHibernate.props
  releasenotes.txt
Labels: p: Minor, c: Documentation, t: Task

#3590 Remove Microsoft.SourceLink.GitHub
  src/NHibernate/NHibernate.csproj
Labels: c: Core, p: Minor, t: Task
