Repository nhibernate/nhibernate-core, pull requests merged in 2024-04, with the labels that each got.

#3519 Fix reference errors in XML comments
  src/NHibernate/Criterion/MatchMode.cs
  src/NHibernate/Linq/Visitors/PreTransformationParameters.cs
  src/NHibernate/Linq/Visitors/PreTransformationResult.cs
  src/NHibernate/Multi/LinqBatchItem.cs
Labels: t: Bug, p: Lowest, c: Documentation

#3518 Add workaround for Rider to see the Antlr3 generated files at design time
  .editorconfig
  src/NHibernate/NHibernate.csproj
Labels: t: Bug, r: Fixed, p: Lowest, c: Documentation

#3522 Fix NUnit2050 warnings
  .editorconfig
  src/NHibernate.Test/Async/Criteria/Lambda/IntegrationFixture.cs
  src/NHibernate.Test/Async/Criteria/ProjectionsTest.cs
  src/NHibernate.Test/Async/Criteria/SelectModeTest/SelectModeTest.cs
  src/NHibernate.Test/Async/Extralazy/ExtraLazyFixture.cs
  src/NHibernate.Test/Async/Hql/Ast/BulkManipulation.cs
  src/NHibernate.Test/Async/IdGen/NativeGuid/NativeGuidGeneratorFixture.cs
  src/NHibernate.Test/Async/Linq/FunctionTests.cs
  src/NHibernate.Test/Async/NHSpecificTest/NH1253/Fixture.cs
  src/NHibernate.Test/Async/NHSpecificTest/NH1612/NativeSqlCollectionLoaderFixture.cs
  src/NHibernate.Test/Async/NHSpecificTest/NH2195/SQLiteMultiCriteriaTest.cs
  src/NHibernate.Test/Async/NHSpecificTest/NH3023/DeadlockConnectionPoolIssueTest.cs
  src/NHibernate.Test/Async/NHSpecificTest/NH3952/Fixture.cs
  src/NHibernate.Test/Async/NHSpecificTest/NH940/NH940Fixture.cs
  src/NHibernate.Test/Async/NHSpecificTest/SqlConverterAndMultiQuery/Fixture.cs
  src/NHibernate.Test/Async/SystemTransactions/DistributedSystemTransactionFixture.cs
  src/NHibernate.Test/Async/SystemTransactions/SystemTransactionFixture.cs
  src/NHibernate.Test/Async/Tools/hbm2ddl/SchemaValidator/SchemaValidateTableWithSchemaFixture.cs
  src/NHibernate.Test/ConnectionTest/AsyncLocalSessionContextFixture.cs
  src/NHibernate.Test/ConnectionTest/ThreadStaticSessionContextFixture.cs
  src/NHibernate.Test/Criteria/Lambda/IntegrationFixture.cs
  src/NHibernate.Test/Criteria/ProjectionsTest.cs
  src/NHibernate.Test/Criteria/SelectModeTest/SelectModeTest.cs
  src/NHibernate.Test/DialectTest/MsSql2005DialectFixture.cs
  src/NHibernate.Test/DialectTest/MsSql2012DialectFixture.cs
  src/NHibernate.Test/DriverTest/OracleDataClientDriverFixture.cs
  src/NHibernate.Test/Extralazy/ExtraLazyFixture.cs
  src/NHibernate.Test/Futures/FutureFixture.cs
  src/NHibernate.Test/Hql/Ast/BulkManipulation.cs
  src/NHibernate.Test/IdGen/NativeGuid/NativeGuidGeneratorFixture.cs
  src/NHibernate.Test/Linq/FunctionTests.cs
  src/NHibernate.Test/MappingTest/NonReflectiveBinderFixture.cs
  src/NHibernate.Test/NHAssert.cs
  src/NHibernate.Test/NHSpecificTest/NH1253/Fixture.cs
  src/NHibernate.Test/NHSpecificTest/NH1612/NativeSqlCollectionLoaderFixture.cs
  src/NHibernate.Test/NHSpecificTest/NH2195/SQLiteMultiCriteriaTest.cs
  src/NHibernate.Test/NHSpecificTest/NH3023/DeadlockConnectionPoolIssueTest.cs
  src/NHibernate.Test/NHSpecificTest/NH3850/MainFixture.cs
  src/NHibernate.Test/NHSpecificTest/NH3952/Fixture.cs
  src/NHibernate.Test/NHSpecificTest/NH940/NH940Fixture.cs
  src/NHibernate.Test/NHSpecificTest/SqlConverterAndMultiQuery/Fixture.cs
  src/NHibernate.Test/ProxyTest/PeVerifier.cs
  src/NHibernate.Test/SqlCommandTest/SqlTokenizerFixture.cs
  src/NHibernate.Test/SystemTransactions/DistributedSystemTransactionFixture.cs
  src/NHibernate.Test/SystemTransactions/SystemTransactionFixture.cs
  src/NHibernate.Test/Tools/hbm2ddl/SchemaValidator/SchemaValidateTableWithSchemaFixture.cs
  src/NHibernate.Test/TypesTest/SerializableTypesFixture.cs
  src/NHibernate.Test/TypesTest/TypeFactoryFixture.cs
Labels: r: Fixed, c: Tests, p: Minor, t: Task

#3524 Fix setting ScaleDefined in SqlType
  src/NHibernate/SqlTypes/SqlType.cs
Labels: t: Bug, r: Fixed, p: Lowest, c: DataProviders / Dialects

#3532 Remove mentions of Prevalence cache from documentation
  doc/reference/modules/nhibernate_caches.xml
  doc/reference/modules/performance.xml
Labels: p: Minor, c: Documentation, t: Task

#3533 Update Iesi.Collections to 4.1.1
  src/NHibernate/NHibernate.csproj
Labels: c: Core, p: Minor, t: Task

#3535 Fix wrong log message in LoadContexts
  src/NHibernate/Engine/Loading/LoadContexts.cs
Labels: t: Fix
