Repository nhibernate/nhibernate-core, pull requests merged in 2024-05, with the labels that each got.

#3538 Treat all non-virtual methods of System.Object as not proxiable
  build-common/NHibernate.props
  src/NHibernate.Test/NHSpecificTest/ProxyValidator/Fixture.cs
  src/NHibernate.Test/NHSpecificTest/ProxyValidator/ShouldBeProxiableTests.cs
  src/NHibernate/Proxy/DefaultDynamicProxyMethodCheckerExtensions.cs
  src/NHibernate/Proxy/DynProxyTypeValidator.cs
Labels: r: Fixed, t: Fix

#3543 Obsolete JoinedEnumerable
  src/NHibernate.Test/Async/Legacy/FooBarTest.cs
  src/NHibernate.Test/Legacy/FooBarTest.cs
  src/NHibernate.Test/UtilityTest/JoinedEnumerableFixture.cs
  src/NHibernate/Async/Engine/Query/HQLQueryPlan.cs
  src/NHibernate/Engine/Query/HQLQueryPlan.cs
  src/NHibernate/IQueryOver.cs
  src/NHibernate/Util/JoinedEnumerable.cs
Labels: c: Core, p: Minor, t: Task

#3542 Add a security policy
  SECURITY.md
Labels: p: Minor, c: Documentation, t: Task

#3517 Obsolete literal AddColumn
  src/NHibernate.Test/SqlCommandTest/SqlInsertBuilderFixture.cs
  src/NHibernate.Test/SqlCommandTest/SqlUpdateBuilderFixture.cs
  src/NHibernate/SqlCommand/SqlInsertBuilder.cs
  src/NHibernate/SqlCommand/SqlUpdateBuilder.cs
Labels: c: Core, p: Minor, t: Task

#3545 Upgrade Npgsql to a non vulnerable version
  src/NHibernate.Test/ExceptionsTest/PostgresExceptionConverterExample.cs
  src/NHibernate.Test/NHibernate.Test.csproj
Labels: c: Tests, p: Minor, t: Task

#3546 Fix incorrect import in DynamicClassFixture
  src/NHibernate.Test/Async/EntityModeTest/Map/Basic/DynamicClassFixture.cs
  src/NHibernate.Test/EntityModeTest/Map/Basic/DynamicClassFixture.cs
Labels: t: Bug, p: Lowest, c: Tests

#3544 Upgrade vulnerable test dependencies
  build-common/NHibernate.props
  src/NHibernate.Test/NHibernate.Test.csproj
Labels: c: Core, p: Minor, t: Task

#3549 Obsolete NullableType.Get by column name
  src/NHibernate.DomainModel/NHSpecific/NullableTypesType.cs
  src/NHibernate.Test/Async/TypesTest/BooleanTypeFixture.cs
  src/NHibernate.Test/Async/TypesTest/GuidTypeFixture.cs
  src/NHibernate.Test/TypesTest/BooleanTypeFixture.cs
  src/NHibernate.Test/TypesTest/CharBooleanTypeFixture.cs
  src/NHibernate.Test/TypesTest/GuidTypeFixture.cs
  src/NHibernate/Type/AbstractBinaryType.cs
  src/NHibernate/Type/AbstractCharType.cs
  src/NHibernate/Type/AbstractDateTimeType.cs
  src/NHibernate/Type/AbstractStringType.cs
  src/NHibernate/Type/BooleanType.cs
  src/NHibernate/Type/ByteType.cs
  src/NHibernate/Type/CharBooleanType.cs
  src/NHibernate/Type/CultureInfoType.cs
  src/NHibernate/Type/DateTimeOffSetType.cs
  src/NHibernate/Type/DecimalType.cs
  src/NHibernate/Type/DoubleType.cs
  src/NHibernate/Type/EnumCharType.cs
  src/NHibernate/Type/EnumStringType.cs
  src/NHibernate/Type/GuidType.cs
  src/NHibernate/Type/Int16Type.cs
  src/NHibernate/Type/Int32Type.cs
  src/NHibernate/Type/Int64Type.cs
  src/NHibernate/Type/NullableType.cs
  src/NHibernate/Type/PersistentEnumType.cs
  src/NHibernate/Type/SByteType.cs
  src/NHibernate/Type/SerializableType.cs
  src/NHibernate/Type/SingleType.cs
  src/NHibernate/Type/TimeAsTimeSpanType.cs
  src/NHibernate/Type/TimeSpanType.cs
  src/NHibernate/Type/TimeType.cs
  src/NHibernate/Type/TypeType.cs
  src/NHibernate/Type/UInt16Type.cs
  src/NHibernate/Type/UInt32Type.cs
  src/NHibernate/Type/UInt64Type.cs
  src/NHibernate/Type/UriType.cs
  src/NHibernate/Type/XDocType.cs
  src/NHibernate/Type/XmlDocType.cs
Labels: c: Core, p: Minor, t: Task

#3553 Obsolete ForeignKeys.IsNotTransientSlow
  src/NHibernate/Async/Engine/ForeignKeys.cs
  src/NHibernate/Engine/ForeignKeys.cs
Labels: r: Fixed, p: Lowest, c: Core, t: Task
