Repository nhibernate/nhibernate-core, pull requests merged in 2024-02, with the labels that each got.

#3475 Adjust the doc about flush on commit
  doc/reference/modules/manipulating_data.xml
Labels: t: Improvement, p: Lowest, c: Documentation

#3476 Do not append from element when already in from
  src/NHibernate.Test/Async/NHSpecificTest/GH3465/Fixture.cs
  src/NHibernate.Test/NHSpecificTest/GH3465/Entities.cs
  src/NHibernate.Test/NHSpecificTest/GH3465/Fixture.cs
  src/NHibernate.Test/NHSpecificTest/GH3465/Mappings.hbm.xml
  src/NHibernate/Hql/Ast/ANTLR/Tree/FromElement.cs
Labels: t: Fix

#3480 Fix null reference exception when running tests with Npgsql 8
  src/NHibernate.Test/ExceptionsTest/PostgresExceptionConverterExample.cs
Labels: t: Bug, c: Tests, p: Minor

#3482 Fix Clear forgetting the non lazy collections
  src/NHibernate.Test/Async/NHSpecificTest/GH3424/Fixture.cs
  src/NHibernate.Test/NHSpecificTest/GH3424/Entities.cs
  src/NHibernate.Test/NHSpecificTest/GH3424/Fixture.cs
  src/NHibernate.Test/NHSpecificTest/GH3424/Mappings.hbm.xml
  src/NHibernate/Engine/StatefulPersistenceContext.cs
Labels: r: Fixed, t: Fix

#3481 Support an arbitrary length for CultureInfoType
  doc/reference/modules/basic_mapping.xml
  src/NHibernate.Test/Async/TypesTest/AbstractDateTimeTypeFixture.cs
  src/NHibernate.Test/Async/TypesTest/CultureInfoTypeFixture.cs
  src/NHibernate.Test/Async/TypesTest/DateTimeOffsetTypeFixture.cs
  src/NHibernate.Test/Async/TypesTest/DecimalTypeFixture.cs
  src/NHibernate.Test/Async/TypesTest/EnumStringTypeFixture.cs
  src/NHibernate.Test/Async/TypesTest/GenericEnumStringTypeFixture.cs
  src/NHibernate.Test/Async/TypesTest/StringTypeFixture.cs
  src/NHibernate.Test/Async/TypesTest/TimeAsTimeSpanTypeFixture.cs
  src/NHibernate.Test/TypesTest/AbstractDateTimeTypeFixture.cs
  src/NHibernate.Test/TypesTest/CultureInfoClass.cs
  src/NHibernate.Test/TypesTest/CultureInfoClass.hbm.xml
  src/NHibernate.Test/TypesTest/CultureInfoTypeFixture.cs
  src/NHibernate.Test/TypesTest/DateTimeOffsetTypeFixture.cs
  src/NHibernate.Test/TypesTest/DecimalTypeFixture.cs
  src/NHibernate.Test/TypesTest/EnumStringTypeFixture.cs
  src/NHibernate.Test/TypesTest/GenericEnumStringTypeFixture.cs
  src/NHibernate.Test/TypesTest/StringTypeFixture.cs
  src/NHibernate.Test/TypesTest/TimeAsTimeSpanTypeFixture.cs
  src/NHibernate.Test/TypesTest/TypeFixtureBase.cs
  src/NHibernate/Type/CultureInfoType.cs
  src/NHibernate/Type/TypeFactory.cs
Labels: r: Fixed, t: Fix

#3309 Test Case for Invalid SQL with property-ref on property using a formula
  src/NHibernate.Test/Async/NHSpecificTest/GH1313/Fixture.cs
  src/NHibernate.Test/NHSpecificTest/GH1313/Account.cs
  src/NHibernate.Test/NHSpecificTest/GH1313/Fixture.cs
  src/NHibernate.Test/NHSpecificTest/GH1313/HoldClose.cs
  src/NHibernate.Test/NHSpecificTest/GH1313/Mappings.hbm.xml
Labels: r: Fixed, c: Tests, p: Minor, t: Task

#3485 Fix implied commits for Oracle and MySQL
  src/NHibernate.Test/Async/NHSpecificTest/GH3474/Fixture.cs
  src/NHibernate.Test/NHSpecificTest/GH3474/Entities.cs
  src/NHibernate.Test/NHSpecificTest/GH3474/Fixture.cs
  src/NHibernate.Test/NHSpecificTest/GH3474/Mappings.hbm.xml
  src/NHibernate/Async/Hql/Ast/ANTLR/Exec/AbstractStatementExecutor.cs
  src/NHibernate/Dialect/Dialect.cs
  src/NHibernate/Dialect/MySQLDialect.cs
  src/NHibernate/Dialect/Oracle8iDialect.cs
  src/NHibernate/Hql/Ast/ANTLR/Exec/AbstractStatementExecutor.cs
Labels: r: Fixed, t: Fix

#3484 Modernize the test case example
  src/NHibernate.Test/Async/NHSpecificTest/GH0000/Fixture.cs
  src/NHibernate.Test/Async/NHSpecificTest/GH0000/FixtureByCode.cs
  src/NHibernate.Test/NHSpecificTest/GH0000/Fixture.cs
  src/NHibernate.Test/NHSpecificTest/GH0000/FixtureByCode.cs
Labels: r: Fixed, p: Lowest, c: Tests, t: Task

#3488 Fix a failing test for SQL Server CE
  src/NHibernate.Test/Async/NHSpecificTest/GH3474/Fixture.cs
  src/NHibernate.Test/NHSpecificTest/GH3474/Fixture.cs
Labels: t: Fix

#3487 Allocation free iterators for LinkedHashMap
  src/NHibernate.Test/Async/UtilityTest/LinkHashMapFixture.cs
  src/NHibernate.Test/NHibernate.Test.csproj
  src/NHibernate.Test/UtilityTest/LinkHashMapFixture.cs
  src/NHibernate.Test/UtilityTest/LinkedHashMapFixture.cs
  src/NHibernate/Async/Engine/BatchFetchQueue.cs
  src/NHibernate/Cfg/XmlHbmBinding/NamedQueryBinder.cs
  src/NHibernate/Engine/BatchFetchQueue.cs
  src/NHibernate/Mapping/Table.cs
  src/NHibernate/SqlCommand/CaseFragment.cs
  src/NHibernate/SqlCommand/SqlInsertBuilder.cs
  src/NHibernate/SqlCommand/SqlUpdateBuilder.cs
  src/NHibernate/Util/CollectionHelper.cs
  src/NHibernate/Util/LinkHashMap.cs
  src/NHibernate/Util/LinkedHashMap.cs
Labels: t: Fix
