Repository nhibernate/nhibernate-core, pull requests merged in 2025-03, with the labels that each got.

#3663 Make StringHelper.GenerateSuffix internal
  src/NHibernate.Test/Async/NHSpecificTest/NH2898/BinaryFormatterCache.cs
  src/NHibernate/Util/StringHelper.cs
Labels: r: Fixed, t: Fix

#3649 Improve some sparse arrays
  src/NHibernate/Loader/Loader.cs
  src/NHibernate/Mapping/Constraint.cs
  src/NHibernate/Mapping/ForeignKey.cs
  src/NHibernate/Mapping/Index.cs
  src/NHibernate/Mapping/SimpleValue.cs
  src/NHibernate/Mapping/Table.cs
  src/NHibernate/SqlCommand/SqlString.cs
Labels: r: Fixed, t: Improvement, p: Lowest, c: Core

#3610 Eliminate memory allocations in GuidCombGenerator under .NET 8+
  src/NHibernate.Test/IdGen/GuidComb/GuidCombFixture.cs
  src/NHibernate/Async/Id/GuidCombGenerator.cs
  src/NHibernate/Id/GuidCombGenerator.cs
Labels: t: Improvement, p: Lowest, c: Core
