Repository nhibernate/nhibernate-core, pull requests merged in 2025-08, with the labels that each got.

#3682 InternalsVisibleTo NHibernate.Test
  build-common/NHibernate.props
  src/NHibernate.DomainModel/NHibernate.DomainModel.csproj
  src/NHibernate.Test/ExceptionsTest/OracleClientExceptionConverterExample.cs
  src/NHibernate.Test/NHibernate.Test.csproj
  src/NHibernate/NHibernate.csproj
Labels: r: Fixed, t: Improvement, p: Lowest, c: Toolset

#3685 Fix filtering sub-queries on property-ref
  src/NHibernate.Test/Async/NHSpecificTest/GH3609/Fixture.cs
  src/NHibernate.Test/NHSpecificTest/GH3609/Entities.cs
  src/NHibernate.Test/NHSpecificTest/GH3609/Fixture.cs
  src/NHibernate.Test/NHSpecificTest/GH3609/Mappings.hbm.xml
  src/NHibernate/Hql/Ast/ANTLR/Tree/DotNode.cs
Labels: t: Fix

#3688 Release 5.4.10
  build-common/NHibernate.props
  releasenotes.txt
Labels: p: Minor, c: Documentation, t: Task

#3691 Merge 5.4.10 into 5.5.x
  releasenotes.txt
  src/NHibernate.Test/Async/NHSpecificTest/GH3609/Fixture.cs
  src/NHibernate.Test/NHSpecificTest/GH3607/FixtureByCode.cs
  src/NHibernate.Test/NHSpecificTest/GH3607/LineItem.cs
  src/NHibernate.Test/NHSpecificTest/GH3607/LineItemData.cs
  src/NHibernate.Test/NHSpecificTest/GH3607/LineItemDataMapping.cs
  src/NHibernate.Test/NHSpecificTest/GH3607/LineItemMapping.cs
  src/NHibernate.Test/NHSpecificTest/GH3607/Order.cs
  src/NHibernate.Test/NHSpecificTest/GH3607/OrderMapping.cs
  src/NHibernate.Test/NHSpecificTest/GH3609/Entities.cs
  src/NHibernate.Test/NHSpecificTest/GH3609/Fixture.cs
  src/NHibernate.Test/NHSpecificTest/GH3609/Mappings.hbm.xml
  src/NHibernate/Cfg/MappingSchema/HbmOneToOne.cs
  src/NHibernate/Hql/Ast/ANTLR/Tree/DotNode.cs
Labels: c: Core, p: Minor, t: Task

#3689 Update Microsoft.Data.SqlClient to v5
  .github/workflows/NetCoreTests.yml
  appveyor.yml
  src/NHibernate.Test/NHibernate.Test.csproj
  teamcity.build
Labels: p: Lowest, c: Tests, t: Task, dependencies

#3528 Fix Linq .Second bug for PostgreSQL et al.
  src/NHibernate.Test/Async/Linq/DateTimeTests.cs
  src/NHibernate.Test/Linq/DateTimeTests.cs
  src/NHibernate.Test/TestDialect.cs
  src/NHibernate/Dialect/FirebirdDialect.cs
  src/NHibernate/Dialect/Function/SQLFunctionRegistry.cs
  src/NHibernate/Dialect/Oracle8iDialect.cs
  src/NHibernate/Dialect/PostgreSQLDialect.cs
  src/NHibernate/Linq/Functions/DateTimePropertiesHqlGenerator.cs
Labels: r: Fixed, t: Fix

#3461 Support for DbBatch
  .editorconfig
  src/NHibernate.Test/Ado/BatcherFixture.cs
  src/NHibernate.Test/Async/Ado/BatcherFixture.cs
  src/NHibernate.Test/NHibernate.Test.csproj
  src/NHibernate.sln
  src/NHibernate/Action/BulkOperationCleanupAction.cs
  src/NHibernate/AdoNet/ConnectionManager.cs
  src/NHibernate/AdoNet/DbBatchBatcher.cs
  src/NHibernate/AdoNet/DbBatchBatcherFactory.cs
  src/NHibernate/Async/ITransaction.cs
  src/NHibernate/Driver/DbProviderFactoryDriveConnectionCommandProvider.cs
  src/NHibernate/Driver/DriverBase.cs
  src/NHibernate/Driver/IDriveConnectionCommandProvider.cs
  src/NHibernate/Driver/IDriver.cs
  src/NHibernate/Driver/ReflectionBasedDriver.cs
  src/NHibernate/Driver/ReflectionDriveConnectionCommandProvider.cs
  src/NHibernate/ITransaction.cs
  src/NHibernate/Transaction/AdoTransaction.cs
Labels: t: New Feature, c: Core, p: Minor
